### ISSUE TITLE
intermittent nvmf target_disconnect.sh failure

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#1043]
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/49296/archive/nvmf_autotest/build.log

nvme_ctrlr.c:1068:spdk_nvme_ctrlr_reset: *NOTICE*: resetting controller
nvme_rdma.c: 392:nvme_rdma_process_event: *ERROR*: Expected RDMA_CM_EVENT_ESTABLISHED but received RDMA_CM_EVENT_REJECTED (8) from CM event channel (status = 10)
nvme_rdma.c: 769:nvme_rdma_connect: *ERROR*: RDMA connect error
nvme_rdma.c: 999:nvme_rdma_qpair_connect: *ERROR*: Unable to connect the rqpair
nvme_ctrlr.c:1089:spdk_nvme_ctrlr_reset: *ERROR*: Controller reinitialization failed.
nvme_ctrlr.c: 673:nvme_ctrlr_fail: *ERROR*: ctrlr 10.102.17.184 in failed state.
Unable to reset the controller.
nvme_ctrlr.c:1068:spdk_nvme_ctrlr_reset: *NOTICE*: resetting controller
nvme_rdma.c: 392:nvme_rdma_process_event: *ERROR*: Expected RDMA_CM_EVENT_ESTABLISHED but received RDMA_CM_EVENT_REJECTED (8) from CM event channel (status = 10)
nvme_rdma.c: 769:nvme_rdma_connect: *ERROR*: RDMA connect error
nvme_rdma.c: 999:nvme_rdma_qpair_connect: *ERROR*: Unable to connect the rqpair
nvme_ctrlr.c:1089:spdk_nvme_ctrlr_reset: *ERROR*: Controller reinitialization failed.
nvme_ctrlr.c: 673:nvme_ctrlr_fail: *ERROR*: ctrlr 10.102.17.184 in failed state.
Unable to reset the controller.
Controller cannot be recovered. Exiting.
Initializing NVMe Controllers
Attaching to NVMe over Fabrics controller at 10.102.17.184:4420: nqn.2016-06.io.spdk:cnode1
Attached to NVMe over Fabrics controller at 10.102.17.184:4420: nqn.2016-06.io.spdk:cnode1
Associating RDMA (addr:10.102.17.184 subnqn:nqn.2016-06.io.spdk:cnode1) with lcore 3
Associating RDMA (addr:10.102.17.184 subnqn:nqn.2016-06.io.spdk:cnode1) with lcore 2
Associating RDMA (addr:10.102.17.184 subnqn:nqn.2016-06.io.spdk:cnode1) with lcore 1
Associating RDMA (addr:10.102.17.184 subnqn:nqn.2016-06.io.spdk:cnode1) with lcore 0
Initialization complete. Launching workers.
Starting thread on core 3
Starting thread on core 2
Starting thread on core 1
Starting thread on core 0
  17:35:52	# trap - ERR
  17:35:52	# print_backtrace
  17:35:53	# [[ ehxBE =~ e ]]
  17:35:53	# xtrace_disable
  17:35:53	# PREV_BASH_OPTS=ehxBE
  17:35:53	# set +x
========== Backtrace start: ==========

in test/nvmf/host/target_disconnect.sh:45 -> main()
     ...
   40  	kill -9 $nvmfpid
   41  	
   42  	sleep 2
   43  	disconnect_init $NVMF_FIRST_TARGET_IP
   44  	
=> 45  	wait $reconnectpid
   46  	sync
   47  	
   48  	if [ -n "$NVMF_SECOND_TARGET_IP" ]; then
   49  		timing_enter failover_test
   50  	
     ...

========== Backtrace end ==========
  17:35:53	# xtrace_enable
  17:35:53	# return 0
 17:35:53	# process_shm --id 0
 17:35:53	# type=--id
 17:35:53	# id=0
 17:35:53	# '[' --id = --pid ']'
 17:35:53	# '[' --id = --id ']'
 17:35:53	# id=0
  17:35:53	# find /dev/shm -name '*.0' -printf '%f\n'
 17:35:53	# shm_files='nvmf_trace.0
event_perf_trace.0'
 17:35:53	# [[ -z nvmf_trace.0
event_perf_trace.0 ]]
 17:35:53	# for n in $shm_files
 1

**Comment by spdkci** [comment]
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49296.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49325.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49249.html

**Comment by Seth5141** [comment]
On all of these failures, the common difference is the status code returned when we fail to reconnect the ctrlr. It's 10 which correcponds with 10. This is an unexpected return value since the target has just been killed so it can't have any stale connection information. Based on the fact that these are all on Soft-RoCE NICs, I am leaning towards some weird state thing in that driver.

For reference:

passing build
~~~
nvme_rdma.c: 392:nvme_rdma_process_event: *ERROR*: Expected RDMA_CM_EVENT_ESTABLISHED but received RDMA_CM_EVENT_REJECTED (8) from CM event channel (status = 8)
nvme_rdma.c: 769:nvme_rdma_connect: *ERROR*: RDMA connect error
nvme_rdma.c: 999:nvme_rdma_qpair_connect: *ERROR*: Unable to connect the rqpair
nvme_ctrlr.c:1089:spdk_nvme_ctrlr_reset: *ERROR*: Controller reinitialization failed.
nvme_ctrlr.c: 673:nvme_ctrlr_fail: *ERROR*: ctrlr 10.102.17.183 in failed state.
Unable to reset the controller.
~~~

failing build
~~~
nvme_rdma.c: 392:nvme_rdma_process_event: *ERROR*: Expected RDMA_CM_EVENT_ESTABLISHED but received RDMA_CM_EVENT_REJECTED (8) from CM event channel (status = 10)
nvme_rdma.c: 769:nvme_rdma_connect: *ERROR*: RDMA connect error
nvme_rdma.c: 999:nvme_rdma_qpair_connect: *ERROR*: Unable to connect the rqpair
nvme_ctrlr.c:1089:spdk_nvme_ctrlr_reset: *ERROR*: Controller reinitialization failed.
nvme_ctrlr.c: 673:nvme_ctrlr_fail: *ERROR*: ctrlr 10.102.17.184 in failed state.
Unable to reset the controller.
~~~

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49383.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49430.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49497.html

**Comment by jimharris** [comment]
Bug scrub: @Seth5141 is going to modify this test script so that it doesn't fail the test if this issue happens when running on rxe.  We'd still like to keep running tests with rxe (soft-roce) since it's nice for developers who want to get familiar with the code without having an RDMA NIC.

**Comment by Seth5141** [comment]
Patch to disable this tet on RXE: https://review.gerrithub.io/c/spdk/spdk/+/474279. I figure disabling the test and not exiting the scripts if it fails are functionally the same since we aren't going to go back and look at the logs from passing tests.

**Comment by Seth5141** [comment]
Closing this since the change has been merged.
