### ISSUE TITLE
vpp_autotest: print with illegal characters in log

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#1062]
There are some illegal characters in autotest-per-patch/vpp_autotest , such as 鈥榑鈥� and â€˜_â€™
They come from the third part tool: vpp.
```
/usr/local/src/vpp-19.04/build-root/install-vpp_debug-native/vpp/include/vppinfra/cpu.h:118:1: note: in expansion of macro 鈥榑鈥�
 _ (sse3,     1, ecx, 0)   \
 ^
/usr/local/src/vpp-19.04/build-root/install-vpp_debug-native/vpp/include/vppinfra/cpu.h:203:1: note: in expansion of macro 鈥榝oreach_x86_64_flags鈥�
 foreach_x86_64_flags
 ^~~~~~~~~~~~~~~~~~~~
/usr/local/src/vpp-19.04/build-root/install-vpp_debug-native/vpp/include/vppinfra/cpu.h: In function 鈥榗lib_cpu_supports_sse3鈥�:
/usr/local/src/vpp-19.04/build-root/install-vpp_debug-native/vpp/include/vppinfra/cpu.h:196:1: warning: old-style function definition [-Wold-style-definition]
/usr/local/src/vpp-19.04/build-root/install-vpp_debug-native/vpp/include/vppinfra/cpu.h:118:1: note: in expansion of macro â€˜_â€™
 _ (sse3,     1, ecx, 0)   \
 ^
/usr/local/src/vpp-19.04/build-root/install-vpp_debug-native/vpp/include/vppinfra/cpu.h:203:1: note: in expansion of macro â€˜foreach_x86_64_flagsâ€™
 foreach_x86_64_flags
 ^~~~~~~~~~~~~~~~~~~~
/usr/local/src/vpp-19.04/build-root/install-vpp_debug-native/vpp/include/vppinfra/cpu.h: In function â€˜clib_cpu_supports_sse3â€™:
/usr/local/src/vpp-19.04/build-root/install-vpp_debug-native/vpp/include/vppinfra/cpu.h:196:1: warning: old-style function definition [-Wold-style-definition]
```

## Expected Behavior
print without illegal characters

## Current Behavior
print with illegal characters

## Possible Solution
Please check source code: /usr/local/src/vpp, fix illegal characters

## Steps to Reproduce
1. open any one SPDK CI Jenkins log of autotest-per-patch
2. open vpp_autotest #10350
3. open build.log
4. search "vpp/include/vppinfra/cpu.h", "include/vlib/global_funcs.h" and "vpp/include/vlib/threads.h"

## Context (Environment including OS version, SPDK version, etc.)
commit cabbe1b1792b7e0d7671f76f5fbdb9ce307179e8

**Comment by jimharris** [comment]
I think some of these "illegal" characters are a localized problem on your system.  At least I don't see the Chinese characters when viewing these on my system.

I do see the â€˜_â€ weirdness though.  But I think it's because VPP literally makes a #define for _.

#define _(flag, func, reg, bit)

The function that gets defined uses () instead of (void) which at least on some of the CI systems seems to be causing the build warning.

But this is all in VPP code.  I really don't think we should keep this open in SPDK.  It's only a build warning and fixing this in upstream VPP isn't critical in my opinion.

I'm going to close this, but if anyone feel differently, please respond and we can discuss in next bug scrub.
