### ISSUE TITLE
Spdk can start with old config with aio bdev but not with json config

### ISSUE THREAD

**Issue by pawelkax** [spdk/spdk#1196]
Spdk cannot run with json config with aio bdev.

## Expected Behavior
Spdk can run successfully.

## Current Behavior
Spdk exits with error code:
json_config.c: 191:rpc_client_poller: *ERROR*: error response: {"code":-32601,"message":"Method not found"}}
app.c: 712:spdk_app_stop: *WARNING*: spdk_app_stop'd on non-zero

## Steps to Reproduce
1. Define bdev_aio.json with:
```
{
  "subsystems": [
    {
      "subsystem": "bdev",
      "config": [
        {
          "params": {
            "name": "AIO0",
            "block_size": 2048,
            "filename": "/tmp/aiofile"
          },
          "method": "bdev_aio_create"
        }
      ]
    }
  ]
}
```
2. Run app/spdk_tgt/spdk_tgt --json bdev_aio.json

**Comment by tomzawadzki** [comment]
[Bug scrub] This issue occurs on FreeBSD where AIO is not available. The expected behavior is one in json config. Since ini configs works by picking up certain parts of the configure, meanwhile json process all of the configuration.

Ini config files will get removed in the near future, so there is no need to fix this behavior.
