### ISSUE TITLE
SSL_ERROR_SYSCALL in connection to review.spdk.io:443 

### ISSUE THREAD

**Issue by darsto** [spdk/spdk#1284]
```
[nvme-phy-autotest] $ /usr/bin/env bash /tmp/jenkins1228380188633858290.sh
MANUAL, will clone
Cloning into '/var/jenkins/workspace/nvme-phy-autotest/spdk'...
fatal: unable to access 'https://review.spdk.io/spdk/spdk/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to review.spdk.io:443 
./copy_or_clone.sh: line 26: cd: spdk: No such file or directory
git version 2.21.1
fatal: not in a git directory
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @darsto. log: https://ci.spdk.io/public_build/autotest-per-patch_6478.html

**Comment by tomzawadzki** [comment]
@karlatec I think there is already a retrigger feature for instances where there is obvious Jenkins error (java exceptions etc..). Since copy_or_clone.sh is outside of SPDK repository and is unaffected by patch under test.
Let's maybe add such retrigger to other steps that are strictly CI/infrastructure related - such as running copy_or_clone.sh.

**Comment by karlatec** [comment]
I added a retry rule looking for a very simple expression: `./copy_or_clone: line \d+ `
Should fire anytime this script fail.

If we dont see another update in this issue then let's close it

**Comment by tomzawadzki** [comment]
Thanks @karlatec !
