### ISSUE TITLE
[spdkcli_tcp] "timeout while waiting for process to start listening..." on FreeBSD

### ISSUE THREAD

**Issue by Maciej-Szwed** [spdk/spdk#1330]
spdkcli_tcp test fails on FreeBSD with message: timeout while waiting for process to start listening...

Example log:
https://10.102.17.111:8080/job/freebsd-autotest/9139/artifact/build.log

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_9171.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_9176.html

**Comment by tomzawadzki** [comment]
The issue was caused by missing `socat` on particular FreeBSD machine at the time.
`test/spdkcli/tcp.sh: line 65: socat: command not found` 

I believe the machines were updated to with this since. No new reports were posted as well.
@karlatec Can you confirm that action was taken to make sure socat was installed on all FreeBSD machines ?

**Comment by karlatec** [comment]
I'm 99.999% sure that it was.  
@wawryk can confirm so we can be 100% sure;)

**Comment by tomzawadzki** [comment]
Well I'm good with this level of confirmation ;)
