### ISSUE TITLE
[unitest-nightly] compilation error in autopackage.sh

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1357]
## Current Behavior

Compilation failure:

```
/usr/bin/ld.bfd: /tmp/reduce_ut.NYsugc.ltrans1.ltrans.o: in function `destroy_unload_cpl':
<artificial>:(.text+0x5bcd): undefined reference to `__wrap_unlink'
collect2: error: ld returned 1 exit status
make[5]: *** [/var/jenkins/workspace/unittest-nightly-autotest/spdk/mk/spdk.unittest.mk:71: reduce_ut] Error 1
make[4]: *** [/var/jenkins/workspace/unittest-nightly-autotest/spdk/mk/spdk.subdirs.mk:44: reduce.c] Error 2
make[3]: *** [/var/jenkins/workspace/unittest-nightly-autotest/spdk/mk/spdk.subdirs.mk:44: reduce] Error 2
make[3]: *** Waiting for unfinished jobs...
```

https://ci.spdk.io/public_build/autotest-nightly_371.html

## Steps to Reproduce

1. Run SPDK ./autorun .sh with current unit-test config:
```
SPDK_RUN_VALGRIND=1
SPDK_RUN_FUNCTIONAL_TEST=0
SPDK_TEST_AUTOBUILD=1
SPDK_TEST_UNITTEST=1
SPDK_TEST_BLOCKDEV=1
SPDK_TEST_PMDK=1
SPDK_TEST_ISAL=1
SPDK_TEST_REDUCE=1
SPDK_TEST_CRYPTO=1
SPDK_TEST_FTL=1
SPDK_TEST_OCF=1
SPDK_TEST_RAID5=1
SPDK_TEST_RBD=1
SPDK_RUN_ASAN=1
SPDK_RUN_UBSAN=1

RUN_NIGHTLY=1
```
2. autopackage.sh fails on:
```
$ ./configure --enable-debug --enable-werror --enable-log-bt --with-rdma --with-fio=/usr/src/fio --with-iscsi-initiator --with-pmdk --with-reduce --with-rbd --with-crypto --with-ocf --enable-ubsan --enable-asan --enable-coverage --with-raid5 --disable-debug --enable-lto
Using default SPDK env in /var/jenkins/workspace/unittest-nightly-autotest/spdk/lib/env_dpdk
Using default DPDK in /var/jenkins/workspace/unittest-nightly-autotest/spdk/dpdk/build
RDMA_OPTION_ID_ACK_TIMEOUT is not supported
Configuring ISA-L (logfile: /var/jenkins/workspace/unittest-nightly-autotest/spdk/isa-l/spdk-isal.log)...done.
Creating mk/config.mk...done.
Creating mk/cc.flags.mk...done.
Type 'make' to build.
 13:45:50	$ make -j12

[...]

/usr/bin/ld.bfd: /tmp/reduce_ut.NYsugc.ltrans1.ltrans.o: in function `destroy_unload_cpl':
<artificial>:(.text+0x5bcd): undefined reference to `__wrap_unlink'
collect2: error: ld returned 1 exit status
make[5]: *** [/var/jenkins/workspace/unittest-nightly-autotest/spdk/mk/spdk.unittest.mk:71: reduce_ut] Error 1
make[4]: *** [/var/jenkins/workspace/unittest-nightly-autotest/spdk/mk/spdk.subdirs.mk:44: reduce.c] Error 2
make[3]: *** [/var/jenkins/workspace/unittest-nightly-autotest/spdk/mk/spdk.subdirs.mk:44: reduce] Error 2
make[3]: *** Waiting for unfinished jobs....
```

## Context (Environment including OS version, SPDK version, etc.)

SPDK 22a1acce9 
Fedora 30 5.4.21 
KVM Virtual Machine

**Comment by jimharris** [comment]
Commit 4f7f0f0986 is the culprit here.  It added the config params when doing the configure in autopackage.sh.  Before this point, the reduce unit tests were never built with LTO.  autopackage.sh is only run as a nightly test, and I'm guessing this patch never ran through the test pool with nightly enabled before getting merged.

It's not entirely clear how we should fix the reduce unit tests.  It needs to override unlink(), but in a non-generic way - meaning we can't just add the definition to the the ut_mock library.  LTO apparently is more picky about the order on the link line - lib/reduce depends on unlink, yet is listed after the object file that defines the wrapper.

I think we have to revert 4f7f0f0986 for now, until this can get worked out.  @Seth5141 - could you submit a revert patch?  I may have some time later this week to work out the reduce/unlink issue, but think we should get the nightly test unblocked ASAP.

Thanks,

-Jim

**Comment by jimharris** [comment]
@Seth5141 - never mind on the revert patch.  I think this patch fixes the problem.

https://review.spdk.io/gerrit/c/spdk/spdk/+/1948

**Comment by tomzawadzki** [comment]
Patch https://review.spdk.io/gerrit/c/spdk/spdk/+/2055 has been merged to mitigate LTO and unit tests conflicting.

Still proper resolution like one proposed by @jimharris would be great to have.

**Comment by jimharris** [comment]
I updated https://review.spdk.io/gerrit/c/spdk/spdk/+/1948 which should fix the reduce unit test issue.  I am reverting the changes from Gerrit 2055 in that patch too, since the workaround should no longer be needed after 1948 is merged.

**Comment by jimharris** [comment]
Patch was merged.
