### ISSUE TITLE
can't attach again after detaching controller

### ISSUE THREAD

**Issue by jlefley** [spdk/spdk#138]
I'm updating some code we developed against SPDK v16.08 to use the latest release of SPDK (v17.03) and I notice that after the application has attached to a controller via ```spdk_nvme_probe()``` and then detached via ```spdk_nvme_detach()```, a subsequent attempt to reattach by calling ```spdk_nvme_probe()``` results in the probe callback not getting called.

Essentially, it seems like that once a controller has been attached, it is still not enumerated on later attempts, despite having called ```spdk_nvme_detach()``` between attachments. Is this expected behavior? Before upgrading to v17.03, our code could successfully attach again after having attached and detached a particular controller. I know there have been some changes to the attach mechanism but the existence of ```spdk_nvme_detach()``` leads me to think that it should be possible to attach, detach, and then attach again.

This is reproducible by adding a second call to ```spdk_nvme_probe()``` near the bottom of ```main()``` in ```identify.c``` so it reads:

```
static void
attach_cb(void *cb_ctx, const struct spdk_nvme_transport_id *trid,
          struct spdk_nvme_ctrlr *ctrlr, const struct spdk_nvme_ctrlr_opts *opts)
{
        print_controller(ctrlr, trid);
        spdk_nvme_detach(ctrlr);
}

int main(int argc, char **argv)
{
        int                             rc;
        struct spdk_env_opts            opts;

        spdk_env_opts_init(&opts);
        opts.name = "identify";
        opts.core_mask = "0x1";
        spdk_env_init(&opts);

        rc = parse_args(argc, argv);
        if (rc != 0) {
                return rc;
        }

        rc = 0;
        if (spdk_nvme_probe(&g_trid, NULL, probe_cb, attach_cb, NULL) != 0) {
                fprintf(stderr, "spdk_nvme_probe() failed\n");
                rc = 1;
        }
        if (spdk_nvme_probe(&g_trid, NULL, probe_cb, attach_cb, NULL) != 0) {
                fprintf(stderr, "spdk_nvme_probe() failed\n");
                rc = 1;
        }

        return rc;
}
```

When run with this modification, the program only prints the controller information one time and during the second call to ```spdk_nvme_probe()```, the EAL log output (```EAL: PCI device 0000:8c:00.0 on NUMA socket 1...```) does not appear for the controller previously attached/detached as it did during the first call to ```spdk_nvme_probe()```.

**Comment by benlwalker** [comment]
We're very much aware of this issue and have had a number of long discussions about what to do. In short, there is a bug in DPDK that we're trying our best to work around. There is no complete work around, so we have to make some trade offs. We did change the behavior in 17.03 to make different trade offs than in 16.08 in response to other issues filed, but now your use case is broken. The reality is that we need to fix DPDK, and we've already submitted patches to do so, but they haven't landed yet.

DPDK wasn't designed originally to support unbinding and rebinding drivers, and it definitely wasn't designed for hotplug. It's of course a framework for writing NIC drivers where those use cases are not common. Now, there isn't any reason why DPDK can't handle all of these storage use cases and that team is supportive of our patches. The big issue remaining is that there isn't an API to unbind the device from its driver that doesn't also treat it as if it was hot removed.

The best way to work around this is to pass a specific spdk_transport_id (with traddr filled out with a PCI address) to spdk_nvme_probe instead of the generic "any nvme device" one used in the identify example the second time you call it. If you do that,  you'll hit a workaround path we added that will go try to re-add the device to DPDK. We can't do the workaround on the wildcard version of spdk_nvme_probe because we'd have to open every device in /sys/bus/pci and that takes way too long.

Hopefully this is fully resolved in the next DPDK release.

**Comment by jlefley** [comment]
Thanks for the info. Is there a way to access the list of the attached controllers through SPDK or is that information only available during the first probe/attach? I think this thread discusses a similar topic: https://lists.01.org/pipermail/spdk/2016-February/000011.html

**Comment by benlwalker** [comment]
There isn't a way to iterate the list of attached controllers today. All of our examples save their own list in the attach callback. We could consider adding an API to iterate the list though - we definitely have the list within the driver.

**Comment by jlefley** [comment]
I think such an extension to the API would be useful. I'll maintain this list in the application for now.

**Comment by dverkamp-intel** [comment]
I think the original issue reported here has been fixed (our DPDK PCI integration has been updated to allow re-attaching to controllers that have been detached), so I'm going to close this issue.
