### ISSUE TITLE
Should spdk "thread context" be in the public API - spdk_thread_init_ext(), spdk_thread_get_ctx() et al?

### ISSUE THREAD

**Issue by nufosmatic** [spdk/spdk#1545]
Should spdk "context" APIs be public - spdk_thread_init(), spdk_thread_get_ctx() et al? It looks like the "thread context" is reserved for supporting the "reactor" paradigm and is not generally usable after calling spdk_app_start().

## Expected Behavior

Define my own context using spdk_thread_init_ext(). The context seemed handy for avoiding evil global variables or noisy arguments in thread messages.

## Current Behavior

spdk_thread_init_ext() after calling spdk_app_start() will fail in asserts() on thread op functions.

## Possible Solution

Take these out of the public API. Or qualify their use against the "app" subsystem.

## Steps to Reproduce

Code spdk_thread_init_ext() after spdk_app_start() - will fail in the asserts.

## Context (Environment including OS version, SPDK version, etc.)

CentOS 7.5 SPDK 20.04.1

**Comment by benlwalker** [comment]
SPDK is built in layers so that you can pick and choose which components to use. The application framework - the spdk_app_* calls are the very highest layer. If you use SPDK's app framework, it does almost everything for you to get all of the threads and reactors set up. For applications that require additional control, they can target lower level APIs like the thread library. If you elect to use the thread API, you must forego using the application framework and implement it's functionality yourself.
