### ISSUE TITLE
[FAQ] review.spdk.org password generating issue need help

### ISSUE THREAD

**Issue by gwnet** [spdk/spdk#1553]
I try to download SPDK patch, I use the same password of my github account. but failed to get the code.

Password for 'https://gwnet@review.spdk.io': 
remote: Unauthorized
fatal: Authentication failed for 'https://review.spdk.io/gerrit/a/spdk/spdk/'
intel@wcp116:~/wayne/warraid5/spdk$ git fetch "https://gwnet@review.spdk.io/gerrit/a/spdk/spdk" refs/changes/03/3203/7 && git checkout -b change-3203-7 FETCH_HEAD
Password for 'https://gwnet@review.spdk.io': 
remote: Unauthorized
fatal: Authentication failed for 'https://review.spdk.io/gerrit/a/spdk/spdk/'
intel@wcp116:~/wayne/warraid5/spdk$ 

then I tried to reset the password at review.spdk.org. it give me 500 error as below.

![image](https://user-images.githubusercontent.com/7543276/90231912-6fa32680-de4e-11ea-983f-0eb91f971fbf.png)

can anyone help me?

## Steps to Reproduce

1.
2.
3.
4.

**Comment by peluse** [comment]
@Seth5141 might be able to help

**Comment by Seth5141** [comment]
This issue was resolved over slack this morning. I'm just going to summarize the main points for anyone coming across this later.

1. The http password created by gerrit for use with cloning and pushing using the http API is not the same thing as your GitHub password used to log in using OAUTH.
2. In order to generate an https password you have to first configure your e-mail address in the gerrit settings tab. Only then will the generate password button work properly.

Thanks for the question @gwnet,

Seth
