### ISSUE TITLE
Virtual address obtained by spdk_pci_device_map_bar causes segmentation fault

### ISSUE THREAD

**Issue by aohzju** [spdk/spdk#1631]
I reported this issue some time ago in the community: https://lists.01.org/hyperkitty/list/spdk@lists.01.org/message/PKDUDNMZIW7ILNPO2WRWGDQJFKZXZ4JD/

I'd like to report it as bug here.

My NVMe device has MSI-X table at offset 0x2000 in BAR 0. I'd like to access that area from the host. So I used the function spdk_pci_device_map_bar to get the virtual address of BAR 0, then add the offset 0x2000:
`...
spdk_pci_device_map_bar(dev, 0, &virBarAddr, &phys, &size);
addrToWrite = virBarAddr + 0x2000; 
spdk_mmio_write_8(addrToWrite, data);`

The program causes segmentation fault on executing spdk_mmio_write_8 above. 

But it's ok to use the above virBarAddr to access NVMe registers, which are at offset 0. So to me, it is like spdk_pci_device_map_bar doesn't map the whole BAR space? 

Though I've got an walkaround as stated in https://lists.01.org/hyperkitty/list/spdk@lists.01.org/message/PKDUDNMZIW7ILNPO2WRWGDQJFKZXZ4JD/, it'll be more convenient if spdk_pci_device_map_bar works for the whole requested BAR space.

**Comment by jimharris** [comment]
Hi,

What does size show after the spdk_pci_device_map_bar call?  And are you using uio or vfio?

**Comment by aohzju** [comment]
The size is correct (64K). I'm using vfio. It has no problem with uio.

**Comment by jimharris** [comment]
Hi @aohzju,

This behavior is dictated by the vfio-pci kernel driver itself.  vfio provides hooks to allow applications to register interrupt vectors.  So when PCI bars are mapped, it excludes the MSI-X table so that the application cannot interfere with the interrupt configuration.

I'm going to close this issue since it's not something SPDK can fix or modify.

-Jim
