### ISSUE TITLE
value for psdt field in nvme command for nvmf

### ISSUE THREAD

**Issue by eyuval** [spdk/spdk#165]
I analyzed a trace of running the examples/nvme/perf/perf tool  and realized that the psdt has value 2 instead of 1. I checked in the nvme standard and saw that the value prescribed for nvme over fabrics is 1.
I checked in the code and saw indeed spdk alwas sets psdt to SPDK_NVME_PSDT_SGL_MPTR_SGL.  So I think this is in contradition to what the standard prescribes.

**Comment by dverkamp-intel** [comment]
You are right - the spec requires that Fabrics implementations send 01b (SPDK_NVME_PSDT_SGL_MPTR_CONTIG).  The Linux kernel NVMe-oF target seems to accept both 01b and 10b, and conceptually they are equivalent, since NVMe-oF only supports extended LBA metadata (MPTR is not used).  However, we should definitely send the correct value as defined by the spec.

Please review this fix: https://review.gerrithub.io/#/c/362239/

Thanks for the report!

**Comment by peluse** [comment]
eyuval , did you get a chance to try this yet?  It's been merged

**Comment by dverkamp-intel** [comment]
Closing this as fixed - please reopen if you find any problems.
