### ISSUE TITLE
SPDK fails to connect to NVMf target with large NN value in controller identify structure

### ISSUE THREAD

**Issue by EugeneKochetov** [spdk/spdk#1664]
If NVMf target reports huge (but still valid) value in cdata.nn, SPDK NVMe initiator fails to connect with memory allocation error. Kernel nvme driver works well with such targets.
According to NVMe spec:

> Number of Namespaces (NN): This field indicates the maximum value of a valid NSID for the NVM subsystem. If the MNAN field is cleared to 0h, then this field also indicates the maximum number of namespaces supported by the NVM subsystem.

SPDK NVMe initiator tries to allocate array of namespaces of cdata.nn length. But it doesn't have to. Actual number of active namespaces can be small and is discovered with IDENTIFY_ACTIVE_NS command. There is no sense to waste memory for inactive namespaces.

## Expected Behavior

SPDK NVMe initiator shall connect successfully and run traffic to targets reporting huge cdata.nn.

## Current Behavior

SPDK fails to connect with memory allocation error:

```
$ sudo ./install/bin/spdk_nvme_identify -r 'trtype:rdma adrfam:ipv4 traddr:1.1.1.1 trsvcid:4420 subnqn:nqn.2016-06.io.spdk:cnode1'
[2020-10-28 23:38:37.242763] Starting SPDK v21.01-pre git sha1 a474889bc / DPDK 20.08.0 initialization...
[2020-10-28 23:38:37.242903] [ DPDK EAL parameters: [2020-10-28 23:38:37.242935] identify [2020-10-28 23:38:37.242960] --no-shconf [2020-10-28 23:38:37.242985] -c 0x1 [2020-10-28 23:38:37.243008] -n 1 [2020-10-28 23:38:37.243031] -m 0 [2020-10-28 23:38:37.243053] --no-pci [2020-10-28 23:38:37.243076] --log-level=lib.eal:6 [2020-10-28 23:38:37.243099] --log-level=lib.cryptodev:5 [2020-10-28 23:38:37.243122] --log-level=user1:6 [2020-10-28 23:38:37.243145] --iova-mode=pa [2020-10-28 23:38:37.243169] --base-virtaddr=0x200000000000 [2020-10-28 23:38:37.243196] --match-allocations [2020-10-28 23:38:37.243219] --file-prefix=spdk_pid120923 [2020-10-28 23:38:37.243243] ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No legacy callbacks, legacy socket not created
EAL: eal_memalloc_alloc_seg_bulk(): couldn't find suitable memseg_list
EAL: eal_memalloc_alloc_seg_bulk(): couldn't find suitable memseg_list
[2020-10-28 23:38:37.301405] nvme.c: 702:nvme_ctrlr_poll_internal: *ERROR*: Failed to initialize SSD: 1.1.1.1
[2020-10-28 23:38:37.319034] nvme_ctrlr.c: 924:nvme_ctrlr_fail: *ERROR*: ctrlr 1.1.1.1 in failed state.
[2020-10-28 23:38:37.319108] nvme_ctrlr.c: 952:nvme_ctrlr_shutdown_async: *ERROR*: ctrlr 1.1.1.1 get_cc() failed
spdk_nvme_connect() failed

```

## Possible Solution

Redesign namespace handling in NVMe initiator to allocate memory only for active namespaces.
Currently namespace ID is used as index on array to retrieve namespace object. And this is extremely fast. If we store only active namespaces, we have to implement search for namespace based on its ID. And this search may have negative performance impact. For relatively small number of active namespaces performance penalty will be very small. For large number of active namespaces we need to think about good search algorithm. Luckily, we already have a sorted array of active namespace IDs and it can be reused for search. Or, we can introduce hashmap.

## Steps to Reproduce

There are no publicly available targets that can report huge cdata.nn. To reproduce the issue SPDK target can be patched:

```
diff --git a/lib/nvmf/ctrlr.c b/lib/nvmf/ctrlr.c
index f50b6f986..a24cd9ae3 100644
--- a/lib/nvmf/ctrlr.c
+++ b/lib/nvmf/ctrlr.c
@@ -2097,7 +2097,7 @@ spdk_nvmf_ctrlr_identify_ctrlr(struct spdk_nvmf_ctrlr *ctrlr, struct spdk_nvme_c
                cdata->sqes.max = 6;
                cdata->cqes.min = 4;
                cdata->cqes.max = 4;
-               cdata->nn = subsystem->max_nsid;
+               cdata->nn = 0xFFFFEFFF;
                cdata->vwc.present = 1;
                cdata->vwc.flush_broadcast = SPDK_NVME_FLUSH_BROADCAST_NOT_SUPPORTED;

```

1. Build and run patched SPDK NVMf target
2. Create subsystem with one namespace and listener. Transport type should not matter.
3. Connect to this subsystem with SPDK NVMe initiator, e.g. spdk_nvme_perf or spdk_nvme_identify
4. Check the initiator logs for memory allocation failure

## Context (Environment including OS version, SPDK version, etc.)

SPDK version: current master, commit hash a474889bc.

**Comment by jimharris** [comment]
Hi @EugeneKochetov,

The plain array is really nice but you're right it doesn't work with such a large nn value.

Note that we have two arrays that will need to be modified - spdk_nvme_ctrlr::ns and spdk_nvme_ctrlr::nsdata.  Maybe spdk_nvme_ctrlr::nsdata_zns too, we made it an array of pointers to save some space, but even an array of 0xFFFFFFFF pointers is way too much memory.

A few things I noticed while looking into the code further:

1) The arrays protected us against race conditions - such as one thread accessing the array while another was modifying it; for example, we do access the ns array in the IO path for getting md information in spdk_nvme_ctrlr_cmd_io_raw_with_md.  So we will probably need to protect the new namespace lists/hashmap/whatever with the ctrlr_lock

2) We have spdk_nvme_ctrlr_get_ns() that is used in almost all places, but there are some places where we access ctrlr->ns directly rather than using this helper function - it might be helpful as we make changes here to consolidate access to the ctrlr->ns array by changing those places to use the spdk_nvme_ctrlr_get_ns() function

3) Once we make changes for the ns array, it might make sense to just put the nsdata and nsdata_zns directly in spdk_nvme_ns rather than keeping the separate arrays.

Is this something that you or @AlekseyMarchuk want to tackle?

-Jim

**Comment by EugeneKochetov** [comment]
Hi @jimharris 

Thanks for the input.

I've started working on it. I have a version that works in basic use case. Basically, I just needed to switch to dynamic array and apply point 2 from your message.
Now, I'm working on support for runtime namespace add/remove/update. And it is much more challenging. Mostly because of the point 1 you noted. I'd like to avoid locks on IO path but don't know how to do it yet.

**Comment by jimharris** [comment]
Oh of course.  I was only thinking of accessing the array - but users of the nvme driver will keep a reference to the spdk_nvme_ns structure and use it later in the I/O path.

We must avoid locks in the I/O path.  One option would be to keep a reference count on the spdk_nvme_ns which is incremented when user calls spdk_nvme_ctrlr_get_ns().  Then we add a new API spdk_nvme_ctrlr_put_ns() to release the reference.

But that would effectively break all existing users since now they need to add spdk_nvme_ctrlr_put_ns() calls or risk accessing freed memory if this race condition occurs.

Based on what you've done so far, how hard would it be to do something like:

1) keep current static array but also add support for dynamic array
2) add ctrlr option for user to opt in to dynamic array
3) set a max value for static array; if ctrlr option set to use static array, and NN is bigger than max value, fail the attach with error message indicating dynamic array option must be set
4) add spdk_nvme_ctrlr_put_ns() routine and start doing ref counting in all cases, even if static array was chosen
5) on detach, check the ref counts - if they are not zero, print an error message but still do the detach - then this is a hint to users that they need to add spdk_nvme_ctrlr_put_ns() calls into their code

**Comment by EugeneKochetov** [comment]
I was also thinking about reference counting and "put" function.
I'm just in the beginning of implementation. So far, I have a prototype with dynamic array and several unit tests to verify it in basic scenario. But it doesn't handle runtime add/remove of namespaces yet. I think, it should not be a problem to keep existing static array for backward compatibility.

Another idea to think about. Pointer to spdk_nvme_ns returned by spdk_nvme_ctrlr_get_ns() function is opaque. So, it does not really have to be a pointer. It can be a NS ID, for example. In this case it is always valid. Functions that receive spdk_nvme_ns will convert it to NS ID and search for NS struct. Not sure about performance impact. Maybe it is possible to find something more optimal than NS ID.

**Comment by jimharris** [comment]
I think the conversion from nsid to ns struct would add too much overhead to the I/O path.  And I think there would still be a race between one thread that is searching for the ns struct and another that is removing the ns struct because the namespace went away.

**Comment by changpe1** [comment]
@EugeneKochetov Do you still work on dynamic NS patch? If not, may I close this issue? Thanks.

**Comment by EugeneKochetov** [comment]
Hi @changpe1. Yes, I'm still on it. It's not moving as fast as I'd like. I plan to push it till the next release.

**Comment by EugeneKochetov** [comment]
Hi @jimharris,

I have pushed for review a patch series for this issue: https://review.spdk.io/gerrit/c/spdk/spdk/+/6510

- It starts with a few preparation refactoring patches.
- Then dynamic allocation is added to nvme driver. Static allocation is kept. At this stage, once NS is allocated, it is not released till controller destruction. Even if it becomes inactive.
- Then I add dynamic allocation to bdev_nvme layer. Here, I fully replace static allocation since there is no impact on APIs and IO path.
- The last patch adds reference counting and "put_ns" function. At this stage inactive namespaces are released when reference counter reaches zero.

**Comment by jimharris** [comment]
Thanks @EugeneKochetov.  I've added it to my review queue.

**Comment by EugeneKochetov** [comment]
@jimharris, I see that CI fails now on multi-process tests. Controller sharing is something new to me. I will check how to rework the solution. Looks like, current approach with "ns_ops" structure and function pointers will not work for shared controllers. The only thing that comes to my mind at the moment is to replace "ns_ops" in controller with "dynamic_ns" flag and replace calls via "ns_ops" with something like:

```
int nvme_ctrlr_construct_namespaces(...)
{
    if (ctrlr->dynamic_ns) {
       nvme_ctrlr_construct_namespaces_dynamic(...);
    } else {
       nvme_ctrlr_construct_namespaces_static(...);
    }
}
```

Please, let me know If you have other thoughts about this issue.

**Comment by jimharris** [comment]
I think your suggestion is probably best.  The alternative is to put the function pointer table in the per-process controller structure (spdk_nvme_ctrlr_process) but I think your method is simpler.

**Comment by shuhei-matsumoto** [comment]
Hi @EugeneKochetov @jimharris 

Thanks for your work. My concern is how we can keep fast access to nvme_bdev_ns in I/O paths when we support multipath in the NVMe bdev module.

In the NVMe bdev module, you have replaced the array, nvme_bdev_ctrlr->namespaces array by the linked list nvme_bdev_ctrlr->ns_list. I'm wondering if we still need the array for performance perspective as you keep it in NVMe driver.

From here, I talk about the case when we support multipath in NVMe bdev module.

Each nvme_bdev has a single pointer to nvme_bdev_ns now. So there is no performance impact. However, when we support multipath, an nvme_bdev will have multiple nvme_bdev_ns and such allocation will be changed (added or removed) dynamically.

We can change nvme_bdev to have the pointer to linked list. However, it is not simple and we cannot use the nvme_bdev->ns_list in I/O paths, because we need to guard nvme_bdev->ns_list by mutex. So we were thinking to introduce subsystem layer and replace nvme_bdev->nvme_ns by nvme_bdev->nsid. All namespaces will be accessed via nsid -> subsystem -> ctrlr -> namespace.

On the other hand, in I/O paths, each I/O needs two pointers, a pointer to spdk_nvme_ns and a pointer to spdk_nvme_qpair.
Each I/O can be submitted to NVMe driver if it verifies ANA state of the spdk_nvme_ns is accessible and the spdk_nvme_qpair is actively connected. So my idea was that
  nsid = nvme_io->nvme_bdev->nsid;
  get the first ctrlr from nvme_io_channel.
  check if the qpair of the ctrlr is active.
  check if the namespace of the ctrlr is accessible.
  submit I/O to the ctrlr and the namespace.
  iterate until these are found.

The multipath configuration may be asymmetric, i.e., it's possible that namespace 1 can be accessed via ctrlr 0 but cannot be accessed via ctrlr1. So this iteration will be necessary.

If we want to reduce the overhead each nvme_io_channel can have a cache per namespace and per qpair. However, we still need not linked list but array to get the cache entry from nsid.

So I think not only NVMe driver but also NVMe bdev module needs static array by default anyway.

Different from you, no complete patches are not ready yet but I wish my concern makes sense to you. Any feedback is appreciated.

**Comment by shuhei-matsumoto** [comment]
Hi @EugeneKochetov @jimharris 

Please ignore my concern for now. Multipath is new and does not need to be backward compatible too. So I will try putting multipath on your idea. That will be interesting.

**Comment by shuhei-matsumoto** [comment]
Hi @EugeneKochetov @jimharris and all,

I might find a solution to satisfy both sparse namespaces and multipath.

nvme_bdev_io needs pointers to spdk_nvme_ns and spdk_nvme_qpair to submit it to NVMe driver.

When we support multipath, a nvme_bdev_subsystem has multiple nvme_bdev_ctrlr and a nvme_bdev has multiple nvme_bdev_ns.

We register both nvme_bdev_subsystem and nvme_bdev as I/O devices by spdk_io_device_register().
The callback to nvme_bdev_subsystem creates and holds qpairs per nvme_bdev_ctrlr.
The callback to nvme_bdev holds references per nvme_bdev_ns.

The getter function to nvme_io_channel calls both the callback to nvme_bdev_subsystem and nvme_bdev_ns.

Hence nvme_io_channel has multiple qpairs and nvme_bdev_ns.
Each nvme_bdev_ns can be associated with a qpair.

nvme_io_channel has cache to nvme_bdev_ns and qpair.

So the key structures are

```
struct nvme_ctrlr_channel {
  struct spdk_nvme_qpair *qpair;
  STAILQ_ENTRY(nvme_ctrlr_channel) stailq;
};

struct nvme_subsystem_channel {
  STAILQ_HEAD(, nvme_ctrlr_channel) ctrlr_chs;
};

struct nvme_ns_head {
  struct nvme_bdev_ns *nvme_ns;
  STAILQ_ENTRY(nvme_ns_head) stailq;
};

struct nvme_bdev_channel {
  STAILQ_HEAD(, nvme_ns_head) ns_heads;
};

struct nvme_io_channel {
  struct nvme_subsystem_channel *subsys_ch;
  struct nvme_bdev_channel *ctrlr_ch;
};
```

I will try figuring out this idea clearly by patches.
Please let me know if you find any issue or have any question.

-Shuhei

-Shuhei

**Comment by EugeneKochetov** [comment]
Hi @shuhei-matsumoto 

Thanks for looking into this conflict.
Do you have patches in gerrit to look at which introduce the subsystem layer for multipath? I'd like to build deeper understanding of the changes and maybe will have some ideas too.

**Comment by shuhei-matsumoto** [comment]
Hi @EugeneKochetov 

Sorry for my late reply. I have not added subsystem layer yet but remove the direct association between nvme_bdev and nvme_bdev_ns. Then I registered nvme_bdev as an io_device, created nvme_bdev_channel for nvme_bdev, and added a cache to nvme_bdev_ns to nvme_bdev_channel. The patch series starts from https://review.spdk.io/gerrit/c/spdk/spdk/+/6603. I hope you will have more concrete information. I'm adding more patches now. My progress is so slow and thanks for your patience.

**Comment by tomzawadzki** [comment]
@EugeneKochetov @shuhei-matsumoto There has been considerable progress done on multipath patches. Could you please post an update whether sparse namespaces issue has been resolved or there is more to be done and this issue should remain open to track that ?

**Comment by EugeneKochetov** [comment]
Hi @tomzawadzki 

Multipath patches do not address sparse namespaces issue. At least as far as get it. So, the issue should be kept open.

I'm actively working on patches right now. Review is in progress. There is quite a lot of conflicts with all the multipath related changes. I think, multipath should be merged first and then I will do a rebase and we will finalize this one.

**Comment by tomzawadzki** [comment]
@EugeneKochetov Can you update on the current status ? Are there specific patches in review that could be referenced in this issue ?

**Comment by EugeneKochetov** [comment]
Patches are on review here: https://review.spdk.io/gerrit/c/spdk/spdk/+/6510
They require rebase now. I'm working on it

**Comment by jimharris** [comment]
Patches from @benlwalker have been merged.
