### ISSUE TITLE
SPDK issue with Optane Memory

### ISSUE THREAD

**Issue by trevors3333** [spdk/spdk#167]
Hi,

I have been running SPDK on all sorts of NVME devices including with no problems. I tried running on Optane 32GB device and get the following message when I run the hello_world or per scripts.

[root@localhost hello_world]# ./hello_world 
Starting DPDK 17.02.0 initialization...
[ DPDK EAL parameters: hello_world -c 0x1 --file-prefix=spdk_pid4110 ]
EAL: Detected 8 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
Initializing NVMe Controllers
EAL: PCI device 0000:01:00.0 on NUMA socket 0
EAL:   probe driver: 8086:2522 spdk_nvme
Attaching to 0000:01:00.0
SET FEATURES (09) sqid:0 cid:63 nsid:0 cdw10:00000007 cdw11:03ff03ff
INTERNAL DEVICE ERROR (00/06) sqid:0 cid:63 cdw0:0 sqhd:0002 p:1 m:0 dnr:1
nvme_ctrlr.c: 646:nvme_ctrlr_set_num_qpairs: ***ERROR*** nvme_set_num_queues failed!
spdk_nvme_probe() failed

Any suggestions before I spend time looking at it on a PCIE analyzer?

Thanks in advance
Trevor

**Comment by benlwalker** [comment]
Is this one of the Optane Memory devices for client systems? We've never tested with that device before - the only Optane device we've tested with is the P4800X. Either way, I'm fairly confident I see what is happening here right away.

When the NVMe driver starts up it has to inform the device of the maximum number of queue pairs it is ever going to request. Since the API lets the user create/delete queue pairs dynamically, the NVMe driver doesn't actually know this value, so it wants to just say "whatever the device maximum is". To say that, it informs the device (via the set features command that is failing for you) that it'd like 1024 queues. Specification compliant devices are required to handle the case where a request is for more than the device is capable of supporting, in which case the device should return the number of queue pairs actually obtained in the command completion.

I'm reasonably confident that this device is just failing the set features command because we asked for more queues than it supports, instead of doing the correct behavior and giving us the device maximum. We can test this with a simple workaround in hello_word. Inside of the probe_cb function make the following change:

```
static bool
probe_cb(void *cb_ctx, const struct spdk_nvme_transport_id *trid,
	 struct spdk_nvme_ctrlr_opts *opts)
{
	printf("Attaching to %s\n", trid->traddr);

	opts->num_io_queues = 16;

	return true;
}
```
I just added the opts->num_io_queues = 16 line there. If you do that, it'll only request 16 instead of 1024. I think that should get it working. Let us know if you have any additional problems.

**Comment by trevors3333** [comment]
Hi Ben, thanks for the response, I will do the change, can you also let me know the correct build sequence to recompile it. I dont think its as easy as running make in the hello_world directory. I appreciate your help as I'm new to al of this.

**Comment by benlwalker** [comment]
Just re-run make from the root of the repository. It will only build what was modified the second time around.

**Comment by optimistyzy** [comment]
"nvme_ctrlr.c: 646:nvme_ctrlr_set_num_qpairs: ERROR nvme_set_num_queues failed!"  @trevors3333 Can you tell me  the type of your NVMe device? You can run identify program under ./examples/nvme/identify

**Comment by trevors3333** [comment]
Hi,

Tried setting to 16 queue pairs but still failed, also tried every value down to 1 queue pair with similar results: here is the error message for 16 queue pairs.

[root@localhost hello_world]# ./hello_world 
Starting DPDK 17.02.0 initialization...
[ DPDK EAL parameters: hello_world -c 0x1 --file-prefix=spdk_pid27785 ]
EAL: Detected 8 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
Initializing NVMe Controllers
EAL: PCI device 0000:01:00.0 on NUMA socket 0
EAL:   probe driver: 8086:2522 spdk_nvme
Attaching to 0000:01:00.0
SET FEATURES (09) sqid:0 cid:63 nsid:0 cdw10:00000007 cdw11:000f000f
INTERNAL DEVICE ERROR (00/06) sqid:0 cid:63 cdw0:0 sqhd:0002 p:1 m:0 dnr:1
nvme_ctrlr.c: 646:nvme_ctrlr_set_num_qpairs: ***ERROR*** nvme_set_num_queues failed!
spdk_nvme_probe() failed

Also got same problem with identify example.

**Comment by peluse** [comment]
guess I'm curious about the identify output asked for earlier... VID/DID looks off (but I don't know for sure, databases show this as a wlan device)

**Comment by dverkamp-intel** [comment]
It sounds like the SPDK identify utility won't work, since the error above is during the NVMe library startup (which identify also uses).  You can try the nvme-cli package instead (run `nvme list` and then `nvme id-ctrl /dev/nvme0` with the correct index when the kernel driver is loaded - run `scripts/setup.sh reset` if you have already set things up for SPDK).

Based on the title, I'm assuming this is one of these (but it would be good to have confirmation): https://ark.intel.com/products/series/99743/Intel-Optane-Memory-Series

I am guessing the Optane Memory M.2 devices use a different controller/firmware than the P4800X add-in cards (the P4800X series is tested and works with the latest SPDK).

**Comment by trevors3333** [comment]
Thanks for the responses, I will try your recommendations. Yes this device is the 32GB version as described in your link. Would it help to supply a PCIE analyzer trace?

**Comment by optimistyzy** [comment]
@trevors3333  Can you run kernel NVMe driver on the device you mentioned?  If you cannot, it seems a firmware issue with great probability.

**Comment by dverkamp-intel** [comment]
Please also try this patch as a workaround and let us know if it avoids the issue:

~~~
diff --git a/lib/nvme/nvme_ctrlr.c b/lib/nvme/nvme_ctrlr.c
index dc8bcb1..44c44ec 100644
--- a/lib/nvme/nvme_ctrlr.c
+++ b/lib/nvme/nvme_ctrlr.c
@@ -649,8 +649,24 @@ nvme_ctrlr_set_num_qpairs(struct spdk_nvme_ctrlr *ctrlr)
                spdk_nvme_qpair_process_completions(ctrlr->adminq, 0);
        }
        if (spdk_nvme_cpl_is_error(&status.cpl)) {
-               SPDK_ERRLOG("nvme_set_num_queues failed!\n");
-               return -ENXIO;
+               SPDK_WARNLOG("nvme_set_num_queues failed!\n");
+
+               /* WORKAROUND: get current number of queues */
+               status.done = false;
+               rc = spdk_nvme_ctrlr_cmd_get_feature(ctrlr, SPDK_NVME_FEAT_NUMBER_OF_QUEUES, 0,
+                                                    NULL, 0, nvme_completion_poll_cb, &status);
+
+               if (rc != 0) {
+                       return rc;
+               }
+
+               while (status.done == false) {
+                       spdk_nvme_qpair_process_completions(ctrlr->adminq, 0);
+               }
+               if (spdk_nvme_cpl_is_error(&status.cpl)) {
+                       SPDK_ERRLOG("get num queues failed!\n");
+                       return -ENXIO;
+               }
        }
 
        /*
~~~

**Comment by trevors3333** [comment]
Hi Thanks for the workaround, but it still failed.

[root@localhost hello_world]# ./hello_world 
Starting DPDK 17.02.0 initialization...
[ DPDK EAL parameters: hello_world -c 0x1 --file-prefix=spdk_pid14326 ]
EAL: Detected 8 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
Initializing NVMe Controllers
EAL: PCI device 0000:01:00.0 on NUMA socket 0
EAL:   probe driver: 8086:2522 spdk_nvme
Attaching to 0000:01:00.0
SET FEATURES (09) sqid:0 cid:63 nsid:0 cdw10:00000007 cdw11:000f000f
INTERNAL DEVICE ERROR (00/06) sqid:0 cid:63 cdw0:0 sqhd:0002 p:1 m:0 dnr:1
nvme_set_num_queues failed!
GET FEATURES (0a) sqid:0 cid:63 nsid:0 cdw10:00000007 cdw11:00000000
INTERNAL DEVICE ERROR (00/06) sqid:0 cid:63 cdw0:0 sqhd:0003 p:1 m:0 dnr:1
nvme_ctrlr.c: 661:nvme_ctrlr_set_num_qpairs: ***ERROR*** get num queues failed!
spdk_nvme_probe() failed

Thanks 

trevor

**Comment by dverkamp-intel** [comment]
OK, it looks like this device is just totally not implementing the Number of Queues feature (which is a required feature of NVMe since version 1.0).  As a last resort, you can try this patch (from master, not on top of the previous workaround) to try just assuming it supports one I/O queue and see if it makes any more progress: 

~~~
diff --git a/lib/nvme/nvme_ctrlr.c b/lib/nvme/nvme_ctrlr.c
index dc8bcb1..a77795f 100644
--- a/lib/nvme/nvme_ctrlr.c
+++ b/lib/nvme/nvme_ctrlr.c
@@ -650,7 +650,8 @@ nvme_ctrlr_set_num_qpairs(struct spdk_nvme_ctrlr *ctrlr)
        }
        if (spdk_nvme_cpl_is_error(&status.cpl)) {
                SPDK_ERRLOG("nvme_set_num_queues failed!\n");
-               return -ENXIO;
+               /* HACK: pretend that the device supports one I/O queue */
+               status.cpl.cdw0 = 0;
        }
 
        /*
~~~

Does this device work correctly with the Linux kernel `nvme` driver? I would expect it to have the same problem with this Set Features - Number of Queues command.

**Comment by optimistyzy** [comment]
@dverkamp-intel  We faced the similar issue (set num IO queue issue), it is the firmware issue.  So I suggest upgrading the firmware.

**Comment by trevors3333** [comment]
Thanks for the workaround, now I get a different error. Yes the standard nvme driver also fails. Also Anyone know where I find the firmware?

[root@localhost hello_world]# ./hello_world
Starting DPDK 17.02.0 initialization...
[ DPDK EAL parameters: hello_world -c 0x1 --file-prefix=spdk_pid12573 ]
EAL: Detected 8 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
Initializing NVMe Controllers
EAL: PCI device 0000:01:00.0 on NUMA socket 0
EAL:   probe driver: 8086:2522 spdk_nvme
Attaching to 0000:01:00.0
SET FEATURES (09) sqid:0 cid:63 nsid:0 cdw10:00000007 cdw11:00030003
INTERNAL DEVICE ERROR (00/06) sqid:0 cid:63 cdw0:0 sqhd:0002 p:1 m:0 dnr:1
nvme_ctrlr.c: 646:nvme_ctrlr_set_num_qpairs: ***ERROR*** nvme_set_num_queues failed!
nvme_ctrlr.c: 760:nvme_ctrlr_construct_namespaces: ***ERROR*** controller has 0 namespaces
spdk_nvme_probe() failed

**Comment by dverkamp-intel** [comment]
It looks like this device is not actually a standard NVMe controller, so we can't support it without firmware changes on the device.  Please keep us posted if you get any updates.
