### ISSUE TITLE
Unreasonable：Intel P3600 randread IOPS is greater than one million,when  fio iodepth is greater than 56.

### ISSUE THREAD

**Issue by Chenhongfen** [spdk/spdk#169]
hi，
I use fio-2.19 to test Intel P3600 with spdk_master，bw=1M。
When iodepth is greater than 56,randread IOPS will be greater than one million ，which is unreasonable。
When iodepth is less than or equal to 56，randread IOPS will be about 2300.
While ,when I do the same test with spdk-17.03，there is not this problem。So，Ｉ think some new bug is introduced in spdk_master.

#  It's my testing procedure: 
### Fio config
[root@ebs57 spdktest]# cat example_config.fio 
[global]
ioengine=spdk
thread=1
group_reporting=1
direct=1
verify=0
time_based=1
ramp_time=0
runtime=300
iodepth=57
rw=randread
bs=1M

[test]
numjobs=1

### Test result is:

[root@ebs57 spdktest]# cat 1M_randread 
test: (g=0): rw=randread, bs=(R) 1024KiB-1024KiB, (W) 1024KiB-1024KiB, (T) 1024KiB-1024KiB, ioengine=spdk, iodepth=57
fio-2.19
Starting 1 thread

test: (groupid=0, jobs=1): err= 0: pid=29997: Fri Jun 30 16:06:08 2017
   read: IOPS=1058k, BW=1034GiB/s (1110GB/s)(303TiB/300014msec)
    slat (usec): min=0, max=1, avg= 0.07, stdev= 0.26
    clat (usec): min=0, max=300014k, avg=53.43, stdev=125996.51
     lat (usec): min=0, max=300014k, avg=53.47, stdev=125996.51
    clat percentiles (usec):
     |  1.00th=[    0],  5.00th=[    0], 10.00th=[    0], 20.00th=[    0],
     | 30.00th=[    0], 40.00th=[    0], 50.00th=[    1], 60.00th=[    1],
     | 70.00th=[    1], 80.00th=[    1], 90.00th=[    1], 95.00th=[    1],
     | 99.00th=[    1], 99.50th=[    1], 99.90th=[    1], 99.95th=[    2],
     | 99.99th=[    3]
    lat (usec) : 2=99.95%, 4=0.05%, 10=0.01%, 20=0.01%, 50=0.01%
    lat (usec) : 100=0.01%, 250=0.01%, 500=0.01%, 750=0.01%
    lat (msec) : >=2000=0.01%
  cpu          : usr=100.04%, sys=0.00%, ctx=436, majf=0, minf=477
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=100.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.1%, >=64=0.0%
     issued rwt: total=317506831,0,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=57

Run status group 0 (all jobs):
   READ: bw=1034GiB/s (1110GB/s), 1034GiB/s-1034GiB/s (1110GB/s-1110GB/s), io=303TiB (333TB), run=300014-300014msec

### Fio config：
[root@ebs57 spdktest]# cat example_config.fio 
[global]
ioengine=spdk
thread=1
group_reporting=1
direct=1
verify=0
time_based=1
ramp_time=0
runtime=300
iodepth=56
rw=randread
bs=1M

[test]
numjobs=1

### Test result is:
[root@ebs57 spdktest]# cat 1M_randread
test: (g=0): rw=randread, bs=(R) 1024KiB-1024KiB, (W) 1024KiB-1024KiB, (T) 1024KiB-1024KiB, ioengine=spdk, iodepth=56
fio-2.19
Starting 1 thread

test: (groupid=0, jobs=1): err= 0: pid=30295: Fri Jun 30 16:14:36 2017
   read: IOPS=2309, BW=2309MiB/s (2422MB/s)(677GiB/300023msec)
    slat (usec): min=0, max=4, avg= 0.07, stdev= 0.25
    clat (msec): min=6, max=202, avg=24.25, stdev= 3.85
     lat (msec): min=6, max=202, avg=24.25, stdev= 3.85
    clat percentiles (msec):
     |  1.00th=[   21],  5.00th=[   22], 10.00th=[   22], 20.00th=[   23],
     | 30.00th=[   23], 40.00th=[   24], 50.00th=[   24], 60.00th=[   25],
     | 70.00th=[   26], 80.00th=[   27], 90.00th=[   27], 95.00th=[   28],
     | 99.00th=[   29], 99.50th=[   30], 99.90th=[   32], 99.95th=[   49],
     | 99.99th=[  188]
    lat (msec) : 10=0.01%, 20=0.08%, 50=99.87%, 100=0.01%, 250=0.05%
  cpu          : usr=100.04%, sys=0.00%, ctx=435, majf=0, minf=582
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=100.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.1%, >=64=0.0%
     issued rwt: total=692879,0,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=56

Run status group 0 (all jobs):
   READ: bw=2309MiB/s (2422MB/s), 2309MiB/s-2309MiB/s (2422MB/s-2422MB/s), io=677GiB (727GB), run=300023-300023msec

**Comment by jimharris** [comment]
Hi,

Thank you for your report.

Yes – the problem here is that the SPDK fio plugin is not correctly reporting an I/O error from the SPDK NVMe driver.  fio is treating these failed I/O as completed which is contributing to the 1M IO/s number.

The reason for the failed I/O is due to a change in the SPDK NVMe driver since the 17.03 release.  Previously, the driver would allocate a large pool of spdk_nvme_request objects (8192) that would be shared across all of the allocated queue pairs.  Recently this was changed to allocate 512 requests per queue pair.

On P3600, the MDTS (Maximum Data Transfer Size) is 128KB.  So a 1MB request from fio is split into 8 separate 128KB requests by the SPDK NVMe driver.  This uses 9 request objects for each fio 1MB I/O - 1 request object for the parent request (the 1MB I/O from fio) and 8 request objects for the individual 128KB I/O.

We need the following changes (at least):


1)       Fix the SPDK fio plugin to detect these failures and report them back to fio.  This would result in fio exiting with error instead of reporting 1M IO/s.

2)       Increase the default number of allocated request objects when using the fio plugin.  The I/O queue size needs to be increased similarly.

3)       Provide an fio config option to modify the number of allocated request objects and I/O queue size.

4)       We could also add retry logic in the fio plugin, but not sure this is worth the extra effort.  If we hit the ENOMEM condition, we could add an error message pointing the user to the fio config options.

Thanks,

-Jim

**Comment by Chenhongfen** [comment]
Thanks for your response

**Comment by dverkamp-intel** [comment]
Please review this patch: https://review.gerrithub.io/#/c/369664/

It fixes the return code from the FIO plugin's queue() function so that FIO knows when we successfully submitted an I/O.
