### ISSUE TITLE
spdk host "in-capsule data" support

### ISSUE THREAD

**Issue by ehudmarvell** [spdk/spdk#170]
Hi,

a.Is SPDK host side has nvme in-capsule data support?
According to nvme_rdma.c, it seem it doesn’t, because I didn’t see any usage with the following defines which expect from  the target side:
1. SPDK_NVME_TYPE_DATA_BLOCK
2. SPDK_NVME_SGL_SUBTYPE_OFFSET

b. According the code it seem SPDK target side support in-capsule data, if so, can you please elaborate how did you test it?

c. According the patch d0fb728ad2dc2c00763c20408d054a8dd84d699c:
nvmf/rdma: Don't use in-capsule buffers for READ/WRITE
Can you explain why we don’t want to use write in-capsule data?

Thanks,
Ehud

**Comment by dverkamp-intel** [comment]
You are correct - the current SPDK NVMe library RDMA host code doesn't support in-capsule data buffers (it is up to the host whether it wants to use them).  I think it would be fairly straightforward to add support: change send_sgl to an array of SGLs, and set the second SGL element to point directly at the user data buffer if it is less than the target's maximum in-capsule data size.

The SPDK NVMe-oF target does support in-capsule data, and it is tested against the Linux kernel nvme-rdma host code.  Our test scripts are checked in; for example, see https://github.com/spdk/spdk/blob/master/test/nvmf/fio/fio.sh

The change you mentioned in the target is a fix for a race condition. Previously, we would use in-capsule data buffers to hold data for requests that didn't actually have an in-capsule data buffer, as long as the data size was small enough, rather than waiting for a data buffer from the buffer pool.  However, as described in the commit message, the lifetime of the in-capsule data buffer was not long enough: we re-post the command buffer with ibv_post_recv() at a point where the data buffer may still be needed (for a controller to host data transfer), so the optimization of reusing the in-capsule data buffer space was not correct.  Note that this doesn't have anything to do with requests that actually have in-capsule data: they are always host-to-controller transfers, so the lifetime is correct.

**Comment by ehudmarvell** [comment]
Thanks you very much

**Comment by bharatpotnuri** [comment]
Hi @ehudmarvell,
Have you or anybody from SPDK community tried adding inline support to host?
Thanks,
Bharat.

**Comment by benlwalker** [comment]
This has now been added to the initiator. Closing this issue.
