### ISSUE TITLE
[performance] Read performance drop when increase the number of threads from 1 to 2

### ISSUE THREAD

**Issue by cighao** [spdk/spdk#1700]
Hardware: Intel P4610 1.6TB

When I use one thread to test the read performance, the latency is only 6.03 us. But when increasing the number of threads to 2, the latency will increase to 51.85us. I don't understand why there is such a big increase when only adding one more thread. Below is the results,

![image](https://user-images.githubusercontent.com/10767282/99970941-9954dd80-2dad-11eb-97e4-c9a83cd2c1fa.png)

Thanks.

**Comment by jimharris** [comment]
Hi @cighao,

Please retry your test, but with randread instead of read.

Some Intel SSDs will do prefetching when it detects QD=1 sequential read I/O.  This is why you are getting 6us latency for the single thread case - normally NAND latency is 50us+.  When you go to two threads, it is no longer QD=1 (it is QD=2 across two threads) and you see the more expected 50us latency.

Thanks,

Jim

**Comment by cighao** [comment]
Hi @jimharris ,

Thanks for your answer. Under rand read, the latency is about 50+us. It should be because of prefetching.  Thanks.

**Comment by jimharris** [comment]
Thanks for retesting @cighao.  May we close this issue?
