### ISSUE TITLE
"rdma_disconnect failed" error logs seen on SPDK NVMF target

### ISSUE THREAD

**Issue by bharatpotnuri** [spdk/spdk#1704]
Hi All,
When running SPDK NVMEoF, below logs are seen on target side per connection during disconnect:
[2020-11-21 00:16:05.310968] rdma_verbs.c: 119:spdk_rdma_qp_disconnect: ERROR: rdma_disconnect failed, errno Invalid argument (22)

## Current Behavior
below error logs for each connection disconnect:
[2020-11-25 19:49:43.406152] rdma_verbs.c: 119:spdk_rdma_qp_disconnect: *ERROR*: rdma_disconnect failed, errno Invalid argument (22)

## Possible Solution
During connection teardown, the peer reset over wire will already move the host QP to error state, i.e the connection is already closing by then. Now when host issues rdma_disconnect(), rdma_disconnect() will fail with -EINVAL, which is okay. So this should not be treated as error and printed to console.

## Steps to Reproduce
Here is the script I am using to create target:
```
#!/bin/bash

RPC_PATH=/home/spdk_nvme-cli/spdk/scripts

/home/spdk_nvme-cli/spdk/build/bin/nvmf_tgt -m 0x3FFF &

python3 $RPC_PATH/rpc.py nvmf_create_transport -t RDMA -u 131072 -c 8192 -n 8192 -b 256

for i in `seq 1 $1`
do
  python3 $RPC_PATH/rpc.py bdev_malloc_create -b Malloc$i 256 512
  python3 $RPC_PATH/rpc.py nvmf_create_subsystem  nqn.2016-06.io.spdk:cnode$i -a -s SPDK0000000000000$i -d SPDK_Controller$i
  python3 $RPC_PATH/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode$i Malloc$i
  python3 $RPC_PATH/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode$i -t rdma -a 10.0.3.2 -s 4420 -f ipv4
done
```
nvme command used for discover, to establish a connection, can use fio or any command:
`
nvme discover -t rdma -a 10.0.3.2 -s 4420
`
## Context (Environment including OS version, SPDK version, etc.)

spdk version: commit b8c99a3
rdma-core version: v32.0 (commit 7a4f9ad9a1d906c5f2bbb18b588309c3d12460ac)
kernel: 5.4.44

**Comment by AlekseyMarchuk** [comment]
I would like to clarify a part of the issue description about the disconnect process. We use RDMA_CM to create, connect and disconnect qpairs. It implements "out of band communication". 
When the initiator starts the disconnect process, it should first call rdma_disconnect. This function moves initiator's qpair to error state and sends RDMA_CM_EVENT_DISCONNECTED to the target and after that initiator should wait for RDMA_CM_EVENT_DISCONNECTED event from the target as a response to rdma_disconnect.
When target receives RDMA_CM_EVENT_DISCONNECTED event, its qpair still may be in RTS state (if no transport error or explicit request moved it to error state before handling this event, so the qpair is in RTS state in most cases). The target should also call rdma_disconnect to move its qpair to error state and send RDMA_CM_EVENT_DISCONNECTED back to the initiator.
In SPDK we call rdma_disconnect only once and even if qpair is already in error state this function should not return an error. I did a quick check, just called rdma_disconnect two times in a row. Another possible case is that ibv_qpair associated with rdmacm_id is already destroyed and rdma_disconnect may return an error, but I don't see how it can happen in SPDK.
So from RDMA_CM point of view, SPDK implements a correct qpair destruction process. More info about the disconnect process can be found here https://linux.die.net/man/7/rdma_cm

Since in #1697 you mentioned that you are using iWARP, I believe in this scenario you also use iWARP. As I see in rdma_cm and kernel drivers, iWARP disconnect in handled in a different way, so probably at the moment when we call rdma_disconnect qpair is already in error state or even destroyed. This needs additional investigation.

**Comment by bharatpotnuri** [comment]
> 
> 
> I would like to clarify a part of the issue description about the disconnect process. We use RDMA_CM to create, connect and disconnect qpairs. It implements "out of band communication".
> When the initiator starts the disconnect process, it should first call rdma_disconnect. This function moves initiator's qpair to error state and sends RDMA_CM_EVENT_DISCONNECTED to the target and after that initiator should wait for RDMA_CM_EVENT_DISCONNECTED event from the target as a response to rdma_disconnect.
> When target receives RDMA_CM_EVENT_DISCONNECTED event, its qpair still may be in RTS state (if no transport error or explicit request moved it to error state before handling this event, so the qpair is in RTS state in most cases). The target should also call rdma_disconnect to move its qpair to error state and send RDMA_CM_EVENT_DISCONNECTED back to the initiator.
> In SPDK we call rdma_disconnect only once and even if qpair is already in error state this function should not return an error. I did a quick check, just called rdma_disconnect two times in a row. Another possible case is that ibv_qpair associated with rdmacm_id is already destroyed and rdma_disconnect may return an error, but I don't see how it can happen in SPDK.
> So from RDMA_CM point of view, SPDK implements a correct qpair destruction process. More info about the disconnect process can be found here https://linux.die.net/man/7/rdma_cm
> 
> Since in #1697 you mentioned that you are using iWARP, I believe in this scenario you also use iWARP. As I see in rdma_cm and kernel drivers, iWARP disconnect in handled in a different way, so probably at the moment when we call rdma_disconnect qpair is already in error state or even destroyed. This needs additional investigation.

@AlekseyMarchuk Thanks for the description.
Yes, This is with iWARP. And rdma_disconnect() handled by IW CM unlike RoCE. First thing iwarp does incase of incoming disconnect is to move QP to error state. In this case when rdma_disconnect is called over a QP that is already in error. rdma_disconnect() failure in this case is still okay but printing error log gives an impression to user that something fatal has occured.

**Comment by AlekseyMarchuk** [comment]
@bharatpotnuri Thanks for clarification. Could you verify that this patch removes the error? https://review.spdk.io/gerrit/c/spdk/spdk/+/5314

**Comment by bharatpotnuri** [comment]
> 
> 
> @bharatpotnuri Thanks for clarification. Could you verify that this patch removes the error? https://review.spdk.io/gerrit/c/spdk/spdk/+/5314

@AlekseyMarchuk Thanks for the patch. Tested, Patch works as expected. 
The check in `lib/rdma/rdma_mlx5_dv.c` may not be needed as rdma_mlx5_dv.c is specific for Mellanox devices(IB and RoCE) and iWARP flows wont enter `lib/rdma/rdma_mlx5_dv.c`.
