### ISSUE TITLE
centos8-vg-autotest fails to start the VM

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1713]
`centos8` still doesn't seem to be stable, depending on which host it's being booted up. Opening this isssue as a drop-in for any other similar issues related to this job.

**Comment by karlatec** [comment]
My fault. I accidentally re-enabled centos8 tests in the CI. I already disabled them, so we should be fine for now, but let's leave this open

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_31640.html

**Comment by karlatec** [comment]
Issue solved; the problem was with duplicate call to dhclient when booting VM image. This resulted in a race condition and from time to time made libvirt <--> VM ssh communication impossible due to wrong IP address.
This was fixed in VM configuration and once #1736 is closed we can try to put CentOS8 VMs back into CI infrastructure.
