### ISSUE TITLE
test/nvmf: test cases run on unwanted NICs

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#1733]
When we run RDMA cases, we want these run on specialized NICs(Mellanox or Intel E810).
For example, there are 2 NICs in systerm, 
```
# ibv_devices
    device                 node GUID
    ------              ----------------
    rocep24s0f0         b8599f0300582580
    rocep24s0f1         b8599f0300582581
    iwo2                a4bf016edc770000
    iwo1                a4bf016edc760000
```
rocep24s0f* is Mellanox NIC,   iwo* is Intel X722(LAN network card which supports RDMA).
rdma_device_init() in autotest.sh can add iwo* into RDMA_IP_LIST, then SPDK selects ths first NIC of this list, so all RDMA test cases run on iwo* card. 

```
# rxe_cfg
  Name      Link  Driver     Speed   NMTU  IPv4_addr      RDEV  RMTU
  eno1      yes   i40e       10GigE  1500  10.67.111.131
  eno2      no    i40e       10GigE  1500  192.168.100.1
  ens785f0  no    mlx5_core          1500  192.168.100.8
  ens785f1  yes   mlx5_core          1500  192.168.3.11
```
```
 # RDMA_IP_LIST=
'10.67.111.131 (eno1)
192.168.100.1  (eno2)
192.168.100.8
192.168.3.11'
```
This may lead to some mistakes, such as below, this is what we don't want. 
```

************************************
START TEST nvmf_filesystem
************************************
 10:46:36       # xtrace_enable
 10:46:36       # test/nvmf/target/filesystem.sh --transport=rdma
......
 10:46:36       # RDMA_IP_LIST='10.67.111.131
192.168.100.1
192.168.100.8
192.168.3.11'
  10:46:36      # echo '10.67.111.131
192.168.100.1
192.168.100.8
192.168.3.11'
  10:46:36      # head -n 1
 10:46:36       # NVMF_FIRST_TARGET_IP=10.67.111.131
  10:46:36      # echo '10.67.111.131
192.168.100.1
192.168.100.8
192.168.3.11'
  10:46:36      # tail -n +2
  10:46:36      # head -n 1
 10:46:36       # NVMF_SECOND_TARGET_IP=192.168.100.1
 10:46:36       # '[' -z 10.67.111.131 ']'
......
************************************
START TEST filesystem_btrfs
************************************
 10:46:40       # xtrace_enable
 10:46:40       # nvmf_filesystem_create btrfs nvme0n1
 10:46:40       # fstype=btrfs
 10:46:40       # nvme_name=nvme0n1
 10:46:40       # make_filesystem btrfs /dev/nvme0n1p1
 10:46:40       # local fstype=btrfs
 10:46:40       # local dev_name=/dev/nvme0n1p1
 10:46:40       # local i=0
 10:46:40       # local force
 10:46:40       # '[' btrfs = ext4 ']'
 10:46:40       # force=-f
 10:46:40       # mkfs.btrfs -f /dev/nvme0n1p1
btrfs-progs v4.17.1
See http://btrfs.wiki.kernel.org for more information.

Detected a SSD, turning off metadata duplication.  Mkfs with -m dup if you want to force metadata duplication.
Label:              (null)
UUID:               78deada8-cc2c-41ed-b9b4-76700c117dd0
Node size:          16384
Sector size:        4096
Filesystem size:    64.00MiB
Block group profiles:
  Data:             single            6.38MiB
  Metadata:         single            6.38MiB
  System:           single            4.00MiB
SSD detected:       yes
Incompat features:  extref, skinny-metadata
Number of devices:  1
Devices:
   ID        SIZE  PATH
    1    64.00MiB  /dev/nvme0n1p1

 10:46:40       # return 0
 10:46:40       # mount /dev/nvme0n1p1 /mnt/device
 10:46:40       # touch /mnt/device/aaa
 10:46:40       # sync
 10:46:40       # rm /mnt/device/aaa
 10:46:40       # sync
[2021-01-06 10:46:40.849119] rdma.c:3780:_qp_reset_failed_sends: *ERROR*: Failed to post a send for the qpair 0x1278e60 with errno -22
```

While we only run ./test/nvmf/target/filesystem.sh --transport=rdma. rdma_device_init() don't run, there is no error. This case run on Mellanox NIC.
```
18:01:23       # RDMA_IP_LIST='192.168.100.8
192.168.3.11'
  18:01:23      # echo '192.168.100.8
192.168.3.11'
  18:01:23      # head -n 1
 18:01:23       # NVMF_FIRST_TARGET_IP=192.168.100.8
  18:01:23      # echo '192.168.100.8
192.168.3.11'
  18:01:23      # tail -n +2
  18:01:23      # head -n 1
 18:01:23       # NVMF_SECOND_TARGET_IP=192.168.3.11
 18:01:23       # '[' -z 192.168.100.8 ']'

```
LAN network card in CI doesn't  supports RDMA, so CI didn't find the problem.

## Expected Behavior

RDMA cases run on specialized NICs(Mellanox or Intel E810) and all passed.

## Current Behavior

RDMA cases don't run on specialized NICs(Mellanox or Intel E810) and some failed.

## Possible Solution
Solution 1：We don't  modprobe  "i40e" "i40iw" driver.
function detect_pci_nics() {
	detect_nics_and_probe_drivers "Mellanox" "ConnectX-4" "mlx4_core" "mlx4_ib" "mlx4_en"
	detect_nics_and_probe_drivers "Mellanox" "ConnectX-5" "mlx5_core" "mlx5_ib"
	#detect_nics_and_probe_drivers "Intel" "X722" "i40e" "i40iw"
	detect_nics_and_probe_drivers "Chelsio" "Unified Wire" "cxgb4" "iw_cxgb4"
......

Solution 2：
We select Mellanox or Intel E810 NICs form RDMA_IP_LIST designately.

## Steps to Reproduce

1. SPDK_TEST_NVMF=1
2. ./autorun.sh

## Context (Environment including OS version, SPDK version, etc.)
Fedora release 29, kernel 5.4.5
SPDK commit 05c573be5dd47f045d66bb9fabde3e7682913339

**Comment by wanqunintel** [comment]
@karlatec , this is the issue that we discuss last time, it seems that the following code will enable the LAN network port in our environment to run test with rdma transport
----detect_nics_and_probe_drivers "Intel" "X722" "i40e" "i40iw"

**Comment by changpe1** [comment]
@wanqunintel Can you just describe the  failure cases and the environment?

**Comment by changpe1** [comment]
If the failure cases are related with specific NICs, there should be vendor specific bugs.

**Comment by wanqunintel** [comment]
This is somehow depend on the CI hardware environment, @karlatec , this will need your input.

**Comment by karlatec** [comment]
@wanqunintel I think CI hardware environment is fine, as the tests are currently passing and this problem is not reproducible. The issue itself IS hardware dependent because of using i40w NIC instead of Mellanox.
@wanghailiangx I don't think I agree with proposed solutions. Test scripts seem fine to me, and removing i40 driver and/or explicitly always selecting Mellanox NIC in scripts looks more like avoiding the issue to me.

@jimharris @AlekseyMarchuk can you take a look?
If I remember correctly the test does not just end with `rdma.c:3780:_qp_reset_failed_sends: *ERROR*: Failed to post a send for the qpair 0x1278e60 with errno -22` and exists, but rather it seems to gets stuck and we have to kill it manually (which looks about right, considering there's a loop jsut after this error message in code). Any chance that there's some hw specific part in there?

**Comment by jimharris** [comment]
Hi @wanghailiangx,

Can you help clarify the original description?  Not in a new comment here, but please edit the original description.

It is not clear whether the problem is with the script or with the application.  If the Intel NIC supports RDMA, then it seems the test should pass.  Making the script skip the Intel NICs just doesn't seem like a good solution since we want to use these scripts to test Intel NICs.

@optimistyzy or @changpe1, could you talk more with @wanghailiangx and help provide some clarity?

Thanks,

Jim

**Comment by optimistyzy** [comment]
@wanghailiangx @jimharris @karlatec  My suggestion is that:  We need to define a control path IP range (e.g., 10.**.*) macro.  For those NICs used by management (control path), we would not probe it any more.  It would be better to  not i40e NIC. May be some customers would use i40e NIC in the datapath, but have another NIC (e.g., 1G NIC) for management purpose.

**Comment by wanghailiangx** [comment]
@jimharris If the Intel NIC supports RDMA, then it seems the test should pass. But the current code is a bit confusing when creating the $RDMA_IP_LIST. 
If there are only NICs (control plane, **supports RDMA**) but no NICs (data plane) in system, the nvmf test will report an error, "no NIC for nvmf test" and exit.
If there are all NICs (control plane and data plane), autotest.sh will select NICs (control plane) to create $RDMA_IP_LIST.
This is not the result we want. I don't mean not to test the intel NICs.
So we tested in a server which have older NICs (control plane, **doesn't support RDMA**) and NICs (data plane) in system, autotest.sh can select NICs (data plane) to create $RDMA_IP_LIST and run pass in this time.

**Comment by karlatec** [comment]
@wanghailiangx 

> current code is a bit confusing when creating the $RDMA_IP_LIST.

It's just going through all /sys/class/infiniband/* interfaces, assigning them IP's starting at 192.168.100.8.

> If there are only NICs (control plane, supports RDMA) but no NICs (data plane) in system, the nvmf test will report an error, "no NIC for nvmf test" and exit.
If there are all NICs (control plane and data plane), autotest.sh will select NICs (control plane) to create $RDMA_IP_LIST.
This is not the result we want. I don't mean not to test the intel NICs.
So we tested in a server which have older NICs (control plane, doesn't support RDMA) and NICs (data plane) in system, autotest.sh can select NICs (data plane) to create $RDMA_IP_LIST and run pass in this time.

I found a server with X722 in our lab and I can easily reproduce the issue. udaddy RDMA tool fails with a similar error. Only in my case it's a pretty new server with up-to-date kernel & drivers (5.9.14-200.fc33)

```
udaddy: starting client
udaddy: connecting
libi40iw-i40iw_ucreate_qp: failed to create QP, unsupported QP type: 0x4
udaddy: unable to create QP: Cannot allocate memory
test complete
return status -1
```
Can you share how to check if a NIC only supports control plane and not data? The issue was closed, but was there any code change created as part of the fix? I think we should update the test scripts with that logic too, so we don't bump into the same issue in the future.

**Comment by wanghailiangx** [comment]
@karlatec This is how I recognize it: eno1/eno2. This method may not be very good and needs to be discussed again.  There is not any code change to fix it. Once there is a solution, we can submit a patch.

**Comment by changpe1** [comment]
@karlatec SPDK_NVMF_TEST is the top level configuration test switch, users can enable it  or not based on CI environment.

You may export an environment variable for this case, it's only valid for this scenario(not CI).

**Comment by karlatec** [comment]
@changpe1 Sorry, I don't really understand. Could you explain a bit more?

**Comment by changpe1** [comment]
This is manual test case, for the NIC that users want to test with, we can export a environment variable(NIC name) to cover this case.

**Comment by karlatec** [comment]
Sorry, I still don't follow. @wanghailiangx is clearly running test `test/nvmf/target/filesystem.sh --transport=rdma`, which is part of our automation scripts. Even if the fail was on his local machine and not in the CI, then this should still be fixed in our test scripts. This is just in case we ever attach a system with X722 card to CI.
