### ISSUE TITLE
packaging spdk

### ISSUE THREAD

**Issue by brianjmurrell** [spdk/spdk#1750]
I've been looking at upgrading our SPDK packaging to the latest version, 20.10 and wanted to get a perspective of how you see this as being done in particular given the submodules you employ in your git tree.

Since you do not produce any kind of specific release assets (i.e. tarballs with submodule code included), you are relying on GitHub's automated means of producing a tarball from a tag.  Which is fair enough.  We do the same thing.

But when GitHub does that, it does not include the source for any submodules.  This is ultimately probably the best thing since it avoids the "bundling" headaches (bundling is generally bad) of packaging and distribution.

So given this, the expectation of an spdk package is that a dpdk{,-devel} package is built and available externally to spdk for the spdk packaging effort.  Is the expectation accurate with your view of packaging?

What about the patches you put onto dpdk in your fork of it, which spdk uses?  Are those merely for the convenience of minimising the dpdk build that spdk needs?  Is there anything in those patches that would be required of an external dpdk build that would not be included in dpdk's default build?

What about minimum versions?  I see your dpdk fork/submodule is at ~20.08 of dpdk.  I also notice that the dpdk-devel dependency in your specfile has no minimum version required:
https://github.com/spdk/spdk/blob/a26adb0d6c43dd92776a1edf1dcae5b106197bee/pkg/spdk.spec#L25

There does seem to be a minimum version attached to the runtime dependency though:
https://github.com/spdk/spdk/blob/a26adb0d6c43dd92776a1edf1dcae5b106197bee/pkg/spdk.spec#L33

Is that `17.11` really the current minimum version required?

What about using a dpdk that is newer than 20.08?  Are there any pitfalls in doing such a thing given that you have held back to 20.08 in your fork/submodule?

**Comment by changpe1** [comment]
@brianjmurrell the minimum DPDK version is 19.11 and for coming SPDK release DPDK 20.11 will be supported.
I will submit a patch to change 17.11 to 19.11.

**Comment by tomzawadzki** [comment]
Hi @brianjmurrell thanks for rising some very good points here !

>So given this, the expectation of an spdk package is that a dpdk{,-devel} package is built and available externally to spdk for the spdk packaging effort. Is the expectation accurate with your view of packaging?

That is correct. 

> What about the patches you put onto dpdk in your fork of it, which spdk uses? Are those merely for the convenience of minimising the dpdk build that spdk needs? Is there anything in those patches that would be required of an external dpdk build that would not be included in dpdk's default build?

The purpose of spdk/dpdk fork is two fold. One as you mentioned to minimize build time. Another is to include fixes that will be submitted to upstream DPDK. The latter are usually few and far between.
I believe that by default DPDK builds every component in can, not sure what exactly is packaged in most systems. There are SPDK components that require specific DPDK libraries, so we'd just have to make sure they are available if they are to be part of SPDK package (ex. crypto/reduce).

>What about minimum versions? I see your dpdk fork/submodule is at ~20.08 of dpdk. 

@changpe1 summited patch for the packaging requirements https://review.spdk.io/gerrit/c/spdk/spdk/+/5999

SPDK LTS aims to support two last DPDK LTS releases, so the upcoming SPDK 21.01 will support DPDK 19.11 and DPDK 20.11.
The SPDK quarterly releases track after last DPDK release, adjusting to any changes.

>What about using a dpdk that is newer than 20.08? Are there any pitfalls in doing such a thing given that you have held back to 20.08 in your fork/submodule?

There was specific issue [#1671] that needed SPDK changes before applying DPDK 20.11. Since it has been resolved, update to latest SPDK with DPDK 20.11 should be merged soon https://review.spdk.io/gerrit/c/spdk/spdk/+/5347.

**Comment by tomzawadzki** [comment]
The submodule was updated to DPDK 20.11 in the patch linked above.

@brianjmurrell Hopefully the previous comment has cleared up the questions you've had on packaging. Please feel free to re-open if there are more.
