### ISSUE TITLE
Jenkins build failed but Subbuild show all Pass

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#1807]
## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_37160.html

## Execution failed at
Build Summary
Result 
Test Failure

Subbuild Summary
Result
All Pass

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @JiangMaox. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_37160.html

**Comment by karlatec** [comment]
It's not an intermittent failure. Looks like everything is as expected.
Please see:  https://ci.spdk.io/results/autotest-per-patch/builds/37160/archive/post_process/build.log for "Tests Missing From Build" and compare the list with spdk/test/common/skipped_tests.txt

I imagine some tests failed to start because of this change https://review.spdk.io/gerrit/c/spdk/spdk/+/6361, as rebasing your patch solved the problem.

I'll leave this open for a couple more days just in case anyone hits this too.
