### ISSUE TITLE
SPDK perf can only receive one async event from the target

### ISSUE THREAD

**Issue by sunmingbao** [spdk/spdk#1825]
## Expected Behavior

Each time the file "/sys/kernel/config/nvmet/subsystems/nqn_name/namespaces/ns_id/enable" on the target side was changed, the app perf on the host side should receive an async event from the target.
## Current Behavior

Only the first async event was received by perf.
## Steps to Reproduce

1. on host-A, set up an NVMe_OF RDMA target (nqn_name is testnqn_1) with 7 name-spaces (ns_id is 1 ~ 7). 
2. enable the first 6 name-spaces (ns_id is 1 ~ 6), and disable the last name-space.
3. then, on host-B, start-up app perf and keep perf accessing the above target.
4. then, on host-A, perform the following steps.
murray-dirt:/sys/kernel/config/nvmet/subsystems/testnqn_1/namespaces # echo 1 >7/enable
murray-dirt:/sys/kernel/config/nvmet/subsystems/testnqn_1/namespaces # echo 0 >7/enable
murray-dirt:/sys/kernel/config/nvmet/subsystems/testnqn_1/namespaces # echo 1 >7/enable
murray-dirt:/sys/kernel/config/nvmet/subsystems/testnqn_1/namespaces # echo 0 >7/enable
## Context (Environment including OS version, SPDK version, etc.)

You know, with the above steps, the perf should receive 4 async events (async_event_type is SPDK_NVME_ASYNC_EVENT_TYPE_NOTIC, async_event_info is SPDK_NVME_ASYNC_EVENT_NS_ATTR_CHANGED).
But by adding debug print at the beginning of function nvme_ctrlr_async_event_cb, it was found that only the first async event was received.

The SPDK version used is v20.04.1.

**Comment by sunmingbao** [comment]
By using the kernel host and capturing packets on the target side (kernel target), it is found that for each change in the file "/sys/kernel/config/nvmet/subsystems/nqn_name/namespaces/ns_id/enable", the target does send back an AER event (type: NVME_AER_TYPE_NOTICE, info: NVME_AER_NOTICE_NS_CHANGED).

**Comment by sunmingbao** [comment]
By debugging the kernel target, the following clues were found:
When the SPDK host was used, for the non-first call to nvmet_ns_changed, the condition "nvmet_aen_bit_disabled(ctrl, NVME_AEN_BIT_NS_ATTR)" was matched, thus the AER event sending was canceled.

**Comment by sunmingbao** [comment]
According to the code of kernel target, if the host sends a nvme_admin_get_log_page command with  NVME_LOG_CHANGED_NS as the  cmd->get_log_page.lid, the bit NVME_AEN_BIT_NS_ATTR in ctrl->aen_masked would got cleared.
I will try to add such an operation (get log page) on the SPDK host side.

**Comment by sunmingbao** [comment]
By adding the operation of "spdk_nvme_ctrlr_cmd_get_log_page(ctrlr, SPDK_NVME_LOG_CHANGED_NS_LIST, SPDK_NVME_GLOBAL_NS_TAG, ...)" at the SPDK host side, the problem got fixed.

**Comment by Comphix** [comment]
Thanks @sunmingbao on your analysis and findings. Will you raise a patch of your change? Thanks, Gang.

**Comment by sunmingbao** [comment]
@Comphix My local modification for this issue was mixed with some other modifications for the very special non-general requirements of our products. And the code style is not compliant with that of SPDK.
In addition, in our company, approval must be obtained first before contributing to open-source community.

Anyway, once I got the approval later, I would prepare and raise a proper clean patch dedicated to this issue.

**Comment by Comphix** [comment]
Thanks @sunmingbao

**Comment by sun-mingbao** [comment]
Hi @Comphix 
This is another account of @sunmingbao registered with the company e-mail address.
I will use this account to provide the patch (based on branch v20.04.x) for this issue.
Could you tell us the steps for providing the patch?

**Comment by Comphix** [comment]
Thanks @sun-mingbao . You can refer https://spdk.io/cn/development/ webpage for the environment setup and code submission. Thanks for your support!

**Comment by sun-mingbao** [comment]
The patch is already in the approval process of our company.

**Comment by changpe1** [comment]
@sunmingbao for this issue, you may consider adding this log in the nvme_ctrlr_async_event_cb() function, just after the nvme_ctrlr_identify_active_ns() call.  I think it's better to add it in the NVMe driver instead of perf tool.

**Comment by sun-mingbao** [comment]
@changpe1 
Exactly :)
I just inserted an action of getting ns-changed-log in nvme_ctrlr_async_event_cb().

**Comment by sun-mingbao** [comment]
@Comphix @changpe1 
I tried to push the commit to the gerrit repo, but failed.
Could you help to have a look?
BTW: I have just set up the email and HTTP password in gerrit. 

Following are the logs:

[C:\files\src\ttmmpp\provide_patch\spdk]$ git branch
* v20.04.x

[C:\files\src\ttmmpp\provide_patch\spdk]$ git status
On branch v20.04.x
Your branch is ahead of 'origin/v20.04.x' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
[C:\files\src\ttmmpp\provide_patch\spdk]$

[C:\files\src\ttmmpp\provide_patch\spdk]$ git remote set-url origin https://review.spdk.io/spdk/spdk

[C:\files\src\ttmmpp\provide_patch\spdk]$ git push
warning: redirecting to https://review.spdk.io/gerrit/spdk/spdk/
remote: error: branch refs/heads/v20.04.x:        
remote: To push into this reference you need 'Push' rights.        
remote: User: sun-mingbao        
remote: Contact an administrator to fix the permissions        
remote: Processing changes: refs: 1, done            
To https://review.spdk.io/spdk/spdk
 ! [remote rejected]     v20.04.x -> v20.04.x (prohibited by Gerrit: not permitted: update)
error: failed to push some refs to 'https://review.spdk.io/spdk/spdk'

**Comment by changpe1** [comment]
you can use master branch for upstreaming.

**Comment by sun-mingbao** [comment]
@Comphix @changpe1
I switched to master branch.
But the Change-Id was not generated after the commit.
Could you help to have a look?

Following are the logs:

linux-15v9:/mnt/ttmmpp/provide_patch/spdk_github # ls -l .git/hooks/commit-msg
-rwxr-xr-x 1 root root 2174 Mar 25 14:26 .git/hooks/commit-msg

linux-15v9:/mnt/ttmmpp/provide_patch/spdk_github # more .git/hooks/commit-msg
#!/bin/sh
# From Gerrit Code Review 3.3.2
#
# Part of Gerrit Code Review (https://www.gerritcodereview.com/)
#
# Copyright (C) 2009 The Android Open Source Project


linux-15v9:/mnt/ttmmpp/provide_patch/spdk_github # git commit --amend --no-edit
Running check_format.sh ...
[master 152b70696] nvme: fix receive async events of ns enabling/disabling from target Fixes #1825 Each time the file "/sys/kernel/config/nvmet/subsystems/nqn_name/namespaces/ns_id/enable" on the target side was changed, the SPDK initiator should receive an async event (type: SPDK_NVME_ASYNC_EVENT_TYPE_NOTICE, info: SPDK_NVME_ASYNC_EVENT_NS_ATTR_CHANGED). But actually not. Since for SPDK, when target sent the non-first event, the condition "nvmet_aen_bit_disabled(ctrl, NVME_AEN_BIT_NS_ATTR)" that prevents target from sending event was matched. This commit fix this issue by issuing a get_log_page cmd for each async event received, just as the kernel initiator does.
 Author: tyler.sun <tyler.sun@dell.com>
 Date: Fri Mar 12 15:31:12 2021 +0800
 1 file changed, 53 insertions(+)


linux-15v9:/mnt/ttmmpp/provide_patch/spdk_github # git log | more
commit 152b70696a323c303054a733d9294d021b6d8f9f
Author: tyler.sun <tyler.sun@dell.com>
Date:   Fri Mar 12 15:31:12 2021 +0800

    nvme: fix receive async events of ns enabling/disabling from target
    Fixes #1825
    Each time the file "/sys/kernel/config/nvmet/subsystems/nqn_name/namespaces/ns_id/enable" on the target si
de was changed, the SPDK initiator should receive an async event (type: SPDK_NVME_ASYNC_EVENT_TYPE_NOTICE, inf
o: SPDK_NVME_ASYNC_EVENT_NS_ATTR_CHANGED).
    But actually not.
    Since for SPDK, when target sent the non-first event, the condition "nvmet_aen_bit_disabled(ctrl, NVME_AEN
_BIT_NS_ATTR)" that prevents target from sending event was matched.
    This commit fix this issue by issuing a get_log_page cmd for each async event received, just as the kernel
 initiator does.
    
    Signed-off-by: tyler_sun <tyler_sun@dell.com>

**Comment by Comphix** [comment]
You may take a look at below webpage:

https://spdk.io/development/#patch

The major steps

0. get latest master code (git checkout master && git pull && git submodule update --init)
1. create you own branch (git checkout -b your_branch)
2. make your changes (git add your_file)
3. commit your changes (git commit -s -m "module_name: description of your change")
4. push your changes (git push review)

**Comment by sun-mingbao** [comment]
Following patch submitted:

https://review.spdk.io/gerrit/c/spdk/spdk/+/7100
