### ISSUE TITLE
spdk to use the native network stack in Seastar project

### ISSUE THREAD

**Issue by gocamero** [spdk/spdk#184]
Hi,

Do you see any value to use the native nework stack from the Seastar/Scylladb, e.g. the included iscsi_tgt could use the native stack from the Seastar? SPDK use to have a libuns in the roadmap?

Thanks,

Jin

**Comment by benlwalker** [comment]
I'm familiar with Seastar, but I haven't been deep into the internals. My understanding is that it works a lot like the SPDK event framework (lib/event) where it spawns one thread per core and connects all of the threads with lockless queues for message passing. In that sense, it's a great fit for SPDK in general.

There are a few technical challenges I think though. Namely, Seastar is a framework, so you have to buy in to that to use it. SPDK contains a framework used in our example applications, but we make (and continue to make) an effort to make as much of the code framework-agnostic as we possibly can. In that sense, it probably makes a lot more sense to integrate SPDK libraries into Seastar rather than the Seastar TCP/IP stack into SPDK.

The basic outline of what you'd do is write a new iSCSI target using the Seastar framework, but using the SPDK libraries in lib/iscsi, lib/scsi, lib/bdev, and lib/nvme for the core logic. The bdev and nvme libraries are all set up to do this - they have nicely documented public APIs and no/minimal dependencies. The iscsi and scsi libraries are not quite in as good of shape because they're only consumed by SPDK's iscsi_tgt application. The main effort for those libraries would be two things: 1) clarify the public API in include/spdk/iscs.h and include/spdk/scsi.h and 2) remove or formalize any assumptions about threading models these two libraries make. These changes can all be up-streamed into SPDK. Then there is a third thing to do, which is to reimplement the SPDK environment abstraction library (lib/env_dpdk) to use Seastar instead of DPDK directly. Seastar is using DPDK underneath, so that should be a reasonably easy to do.

At a high level, our goal with SPDK is that everything in the lib/ directory (except lib/event) is a "passive" C library, with a clear public API defined in include/spdk, that makes as few assumptions about threading models and has as few dependencies as possible. Then, these SPDK libraries can be easily consumed into other frameworks like Seastar. We've made a lot of progress in this area recently, but we're not all the way there just yet.

**Comment by gocamero** [comment]
Agree that more sense to integrate SPDK library into Seastar than vice verse.  Thanks for thoughts and further directions!
