### ISSUE TITLE
spdk_pci_device_cfg_read32 cannot read extended capabilities when vfio-pci is used

### ISSUE THREAD

**Issue by aohzju** [spdk/spdk#1857]
I'm running spdk on a Centos 8.3 machine. My program calls spdk_pci_device_cfg_read32 to read configure space location 0x100, it always returns 0, while it's actually not. The same program works on Centos 7 or Ubutun 18.

It's very likely it is related to vfio. The output from dmesg shows:

**[  105.951045] VFIO - User Level meta-driver version: 0.3
[  224.992830] vfio_ecap_init: 0000:41:00.0 hiding ecap 0x19@0x100
[  224.992837] vfio_ecap_init: 0000:41:00.0 hiding ecap 0x25@0x300
[  224.992841] vfio_ecap_init: 0000:41:00.0 hiding ecap 0x26@0x1f0
[  224.992844] vfio_ecap_init: 0000:41:00.0 hiding ecap 0x27@0x220**

How to fix this? Is there any system parameters I can tweak to get ecap unhidden?

**Comment by jimharris** [comment]
I am not aware of any system parameters to get these unhidden.

Just looking at the first one, 0x19@0x100 - 0x19 = PCI_EXT_CAP_ID_SECPCI (Secondary PCIe capability).  drivers/vfio/pci/vfio_pci_config.c is responsible for determining what is hidden, and this capability is clearly marked as "masked from the user" when you look at the pci_ext_cap_length map at the beginning of this file.

git blame shows all of the related code here basically hasn't changed since 2012.  I can't explain why this would have worked on Ubuntu 18.  You may need to dig into the distro kernel source.

Closing issue since this is not SPDK related.  Feel free to ask more questions here though.
