### ISSUE TITLE
perf_test: you need to specify size=

### ISSUE THREAD

**Issue by ShuaiGeng** [spdk/spdk#187]
i have specified the "size=100%", in fio_test.conf.

root@shuai-MS-7A71:/home/shuai/spdk/scripts/perf/nvme# ./run_fio_test.sh 
Running Test: IO Size= 4096  QD= 1  Mix= 100 CPU Mask= 0x1
perf_test: you need to specify size=
fio: pid=0, err=22/file:filesetup.c:833, func=total_file_size, error=Invalid argument
Traceback (most recent call last):
  File "/home/shuai/spdk/scripts/perf/nvme/run_fio_test.py", line 149, in <module>
    run_fio(s, q, m, c, i, w, t)
  File "/home/shuai/spdk/scripts/perf/nvme/run_fio_test.py", line 49, in run_fio
    output = subprocess.check_output(command, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'BLK_SIZE=4096 RW=randrw MIX=100 IODEPTH=1 RUNTIME=60 IOENGINE=/home/shuai/spdk/examples/nvme/fio_plugin/fio_plugin fio /home/shuai/spdk/scripts/perf/nvme/fio_test.conf_1ssds -output=s_4096_q_1_m_100_c_0x1_run_0 -output-format=json' returned non-zero exit status 1
System does not have  2  NVMe SSDs.
System does not have  4  NVMe SSDs.
System does not have  8  NVMe SSDs.

**Comment by Comphix** [comment]
Hi Shuai,

Which fio version and SPDK code do you use? It looks like in my below environment, I can run the test with size=100% where I also tried size=2G, size=50%. SPDK is the latest code on github.

[root@localhost nvme]# fio --version
fio-2.21

[root@localhost nvme]# cat fio_test.conf
[global]
ioengine=${IOENGINE}
thread=1
group_reporting=1
direct=1
verify=0
norandommap=1
cpumask=1
percentile_list=50:90:99:99.5:99.9:99.99:99.999

[perf_test]
stonewall
description="Run NVMe driver performance test for a given workload"
bs=${BLK_SIZE}
rw=${RW}
rwmixread=${MIX}
iodepth=${IODEPTH}
time_based=1
ramp_time=10s
runtime=${RUNTIME}
size=50%  <<<<<<

**Comment by ShuaiGeng** [comment]
Hi Comphix
see below for my versio of fio
root@shuai-MS-7A71:/home/shuai/spdk/scripts# fio --version
fio-3.0-27-g63463

can you tell me how check the spdk version in local?

**Comment by Comphix** [comment]
Hi Shuai,

Tried the 3.0 fio and looks like this problem is also not seen. One issue is that the result parse has one issue to have "lat_ns" instead of "lat".

I've also tried to run the fio manually with size=10% and it works here. Below is the result:

[root@localhost nvme]# fio --name=nvme --numjobs=1 --filename="trtype=PCIe traddr=0000.81.00.0 ns=1" --bs=4K --iodepth=1 --ioengine=.../spdk/examples/nvme/fio_plugin/fio_plugin --direct=1 --sync=0 --norandommap --group_reporting **_**--size=10%**_** --runtime=3 -rwmixwrite=30 --thread=1 --rw=rw
nvme: (g=0): rw=rw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=spdk, iodepth=1
**fio-3.0**
Starting 1 thread
Starting DPDK 17.05.0 initialization...
[ DPDK EAL parameters: fio -c 0x1 -m 512 --file-prefix=spdk_pid21376 ]
EAL: Detected 72 lcore(s)
EAL: Probing VFIO support...
EAL: PCI device 0000:81:00.0 on NUMA socket 1
EAL:   probe driver: 8086:953 spdk_nvme
Jobs: 1 (f=0): [f(1)][-.-%][r=0KiB/s,w=0KiB/s][r=0,w=0 IOPS][eta 00m:00s]
nvme: (groupid=0, jobs=1): err= 0: pid=21451: Tue Aug 29 21:33:09 2017
   read: IOPS=81.0k, BW=320MiB/s (336MB/s)(961MiB/3001msec)
    slat (nsec): min=103, max=7553, avg=140.84, stdev=47.75
    clat (usec): min=4, max=2795, avg= 8.53, stdev=44.06
     lat (usec): min=4, max=2796, avg= 8.67, stdev=44.06

**Comment by ShuaiGeng** [comment]
Hi Comphix
I have already updated the new spdk code from master, but still have a couple of problem:
**Problem 1 with fio plugin**
root@shuai-MS-7A71:/home/shuai/spdk/scripts# fio --name=nvme --numjobs=1 --filename="trtype=PCIe traddr=0000.81.00.0 ns=1" --bs=4K --iodepth=1 --ioengine=.../spdk/examples/nvme/fio_plugin/fio_plugin --direct=1 --sync=0 --norandommap --group_reporting --size=10% --runtime=3 -rwmixwrite=30 --thread=1 --rw=rw
fio: engine .../spdk/examples/nvme/fio_plugin/fio_plugin not loadable
fio: failed to load engine .../spdk/examples/nvme/fio_plugin/fio_plugin
fio: file:ioengines.c:91, func=dlopen, error=.../spdk/examples/nvme/fio_plugin/fio_plugin: cannot open shared object file: No such f

**Problem 2 with direct libaio**
root@shuai-MS-7A71:/home/shuai/spdk/scripts# fio --name=nvme --numjobs=1 --filename="trtype=PCIe traddr=0000.81.00.0 ns=1" --bs=4K --iodepth=1 --ioengine=libaio --direct=1 --sync=0 --norandommap --group_reporting --size=10% --runtime=3 -rwmixwrite=30 --thread=1 --rw=rw
nvme: (g=0): rw=rw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=1
fio-3.0-27-g63463
Starting 1 thread
nvme: you need to specify size=
fio: pid=0, err=22/file:filesetup.c:973, func=total_file_size, error=Invalid argument


Run status group 0 (all jobs):

**Comment by ShuaiGeng** [comment]
I am now right to with perf script, not sure why it doesn't work with fio command manually .

**Comment by Comphix** [comment]
For problem 1, you can refer to https://github.com/spdk/spdk/blob/master/examples/nvme/fio_plugin/README.md to properly build.

For problem 2, as it is with libaio and not goes to the SPDK code here, please investigate whether there is some issue on the fio. Also the filename here shall be /dev/nvmeXnY for libaio instead of "trtype=..." which is for SPDK fio ioengine.

Thanks, Gang

**Comment by Comphix** [comment]
Hi Shuai,

Any feedback on this?

Thanks,
Gang

**Comment by ShuaiGeng** [comment]
Hi Gang
I am now work with script run, 
Thank you

**Comment by Comphix** [comment]
Thanks for the updates. We can close this issue.

**Comment by dwy189** [comment]
I was using VirtualBox and on the Ubuntu 16.04 version. My fio version was: 2.2.10. I tried the same procedures as the original author did and I thought I followed the instruction from the fio plugin README page. But I still got the following error: 

weiyoud@weiyoud-VirtualBox:~/spdk/examples/nvme/fio_plugin$ LD_PRELOAD=/home/weiyoud/spdk/examples/nvme/fio_plugin/fio_plugin /home/weiyoud/fio/fio example_config.fio 
ERROR: ld.so: object '/home/weiyoud/spdk/examples/nvme/fio_plugin/fio_plugin' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
fio: engine spdk not loadable
fio: failed to load engine
fio: file:ioengines.c:89, func=dlopen, error=spdk: cannot open shared object file: No such file or directory

Any ideas?
