### ISSUE TITLE
NVMe-oF tests will use local NVMe SSDs if they are present rather than connecting to the new NVMe-oF SSD as expected

### ISSUE THREAD

**Issue by benlwalker** [spdk/spdk#1919]
Running some of the tests in /test/nvmf in --iso mode while having a local NVMe SSD will end up routing I/O to that local NVMe SSD instead of the newly created NVMe-oF disks. Most importantly, they'll do this even if the NVMe SSD *has an existing filesystem and was ignored by setup.sh*. This corrupts the data on the disk.

We likely need to track which disks were present on the system at the beginning of the test run and never use those under any circumstances.

**Comment by mikeBashStuff** [comment]
@benlwalker Would you kindly give an example of the test which behaves in such a way? Have you run the entire `./test/nvmf/nvmf.sh` suite or some specific tests? Asking since there's a lot of use-cases covered and going through them one by one may be quite cumbersome. :) 

In general, from the top of my head, most of the tests should use stuff like `get_nvme_bdfs()` or `nvme_in_userspace()` (or just `scripts/gen_nvme.sh` for the whole sub config) which would hijack nvme controller only if it was bound to other driver than `nvme`. So if `setup.sh` ignored the nvme dev because it was in use these function should not pick up the device.

**Comment by benlwalker** [comment]
I was trying to run the whole nvmf.sh suite and it corrupted one of my other disks. I didn't notice it right away so I don't have the exact test that did it handy. But I'm fairly positive it was due to the kernel NVMe initiator connecting to the SPDK NVMe-oF target, then fio being run against that kernel block device but incorrectly selecting my local NVMe SSD at /dev/nvme0n1 rather than the new kernel block device at /dev/nvme1n1.

Just poking around, I think the culprit is `scripts/fio.py` - it seems to automatically run against all nvme SSDs that appear in `lsblk -l -o NAME`.

**Comment by changpe1** [comment]
[Bug Scrub] scripts/fio.py maybe can take a parameter for disks that can run over fio tests, @mikeBashStuff could you take a look?

**Comment by mikeBashStuff** [comment]
@changpe1 Sure, will check it out.

**Comment by mikeBashStuff** [comment]
Testing following approach: https://review.spdk.io/gerrit/c/spdk/spdk/+/7684
