### ISSUE TITLE
SPDK build deps not satisfied by RPMs on EL7 in python3 env

### ISSUE THREAD

**Issue by tanabarr** [spdk/spdk#1974]
In DAOS we provide RPM packages for SPDK and are working on upgrading to 21.07 (currently trending master), I am stuck with build requirements on centos7, RPM builds won't work unless we can satisfy the python3 elftools requirement via RPMs.

## Expected Behavior

Installing python-pyelftools satisfies the elftools requirement in the python3 environment during our scons build enabling meson to build SPDK/DPDK.

## Current Behavior

During DAOS build in docker container (in CI), python-pyelftools RPM is included in dockerfile and is installed but presumably only as part of the python2 environment and therefore not detected by meson.
```
[2021-06-01T20:52:47.599Z] Program python3 found: YES (/usr/bin/python3)
[2021-06-01T20:52:47.599Z] buildtools/meson.build:45:2: ERROR: Problem encountered: missing python module: elftools
```

Source builds can satisfy elftools requirement through pkgdep.sh which installs a package through pip directly but in order to support EL7 RPM building then we need to satisfy the requirement through RPMs, not pip.

## Possible Solution

EL8 seems to have python3-pyelftools which may cover the situation for EL8, I don't know the best way forward for EL7 RPM builds.

## Steps to Reproduce

1. Install meson, ninja-build and python-pyelftools RPMs with yum.
2. Build SPDK with python3 default environment.

## Context (Environment including OS version, SPDK version, etc.)

SPDK master commit 4e4c2cd8e325652892d0511669744dc3f83080da
CentOS 7.9

**Comment by jimharris** [comment]
We can track this issue here in SPDK, but this looks like more of a DPDK issue than SPDK issue (since DPDK drives the pyelftools dependency).

A few notes:
DPDK recommends using pip3 to install pyelftools:  https://doc.dpdk.org/guides/linux_gsg/sys_reqs.html

DPDK seems to have other issues with RHEL/CentOS 7, the link above includes this note:  "pkg-config 0.27, supplied with RHEL-7, does not process the Libs.private section correctly, resulting in statically linked applications not being linked properly."

**Comment by mikeBashStuff** [comment]
I guess the other approach would be to just build the rpms under different distro (e.g. centos8) and then just provide the resulted packages for Centos7 (not the prettiest of solutions but there shouldn't be any major incompatibilities involved)?  

That said, depending on how you build the rpms you can just remove|ignore that particular build requirement (like removing it from the actual .spec). In fact, the 7a5cc6cad5ed7afbc2dac958abf6857e3e41dbc8 doesn't define any build requirements only the installation ones - this was done to make the whole build process a bit easier and don't block it in case some pieces cannot be provided via dist packaging (but still can be satisfied via some 3rd party packaging like pip's).  For this one I tested both sides of the coin, building and installation - with `rpmbuild/*` suite you should be able to build all the rpms on centos8, fedora{30..33} (possibly on other rhel variants too), install it there but also install it on centos7 (it's not possible to build rpms with this particular suite on centos7 directly since the `rpmbuild` itself is, unfortunately, too old there to understand the .spec|cmdline that's used).

**Comment by tanabarr** [comment]
Thank you for the responses, we have packaged python3-pyelftools in our local repo: https://github.com/daos-stack/pyelftools/pull/1 as a workaround. Now to update daos-stack dpdk/spdk RPM repos to support meson build in specfiles.

**Comment by changpe1** [comment]
[Bug Scrub] SPDK will not fix it, closing this issue for now. You can ask more questions here.
