### ISSUE TITLE
Mac OS X Support

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#2]
Requested by @harshavardhana.

**Comment by bwalker-intel** [comment]
This issue will remain open to track the request, but this is not likely to be implemented. Mac OS X is also an unlikely candidate OS for actual software deployments using SPDK, since SPDK makes the most sense on dedicated servers in a data center. 

Further, DPDK does not support Mac OS X. While SPDK has taken some steps to make it easy to swap out DPDK for another similar framework, it's unlikely that other similar frameworks will exist on Mac OS X either.

**Comment by benlwalker** [comment]
I'm closing this issue. We cannot foresee any point in the future at which it makes sense to run SPDK natively on macOS. You can use QEMU to start a VM to emulate an NVMe device for testing purposes.
