### ISSUE TITLE
spdk gerrit: git clone problem

### ISSUE THREAD

**Issue by hellowaywewe** [spdk/spdk#201]
Hi,  all. 
When I wanted to download the SPDK from the  gerrit by executing command like 'git clone...', It's always up to 95 percent that it doesn't work. And I tried many times through different ways, such as to use vpn and local network.
I want to kown whether I am the only one who ran into this problem? Is  it caused by my network problem or the problem of the server of gerrit itself?

```
[WedeMacBook-Pro:myspdk wewe$ git clone https://review.gerrithub.io/bsedyang/spdk && scp -p -P 29418 hellowaywewe@review.gerrithub.io:hooks/commit-msg spdk/.git/hooks/

Cloning into 'spdk'...
remote: *********************************************************************
remote: New and exciting features are coming for this year Gerrit User Summit
remote: with the launch of Ver. 2.15, NoteDb, high-availability, multi-master
remote: Register NOW for the FREE London-based event, 2-3 October 2017
remote: Still a few places available, hurry up !!
remote: ---------------------------------------------------------------------
remote: Gerrit User Summit registration page: https://goo.gl/nTw3JF
remote: *********************************************************************
remote: Counting objects: 24415, done
remote: Finding sources: 100% (24415/24415)
error: RPC failed; curl 56 SSLRead() return error -9806 KiB/s    
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```
Could someone offer some help? And how can I do to solve it?

**Comment by dverkamp-intel** [comment]
It looks like this may be an issue with your network (are you behind some kind of proxy/filter?) - the clone command works here.

A few other notes:
- You are cloning bsedyang/spdk, not spdk/spdk - not sure if that was intentional.
- You can clone the spdk/spdk repository from GitHub even if you are using GerritHub - the GitHub repo is automatically synced from GerritHub.  You still need to push commits for review via GerritHub, but you don't have to fetch from there.

**Comment by hellowaywewe** [comment]
Yeah, I just tested it, it works. It is really caused by my network. Thx .
