### ISSUE TITLE
[spdk_top] Poller status does not change from busy to idle

### ISSUE THREAD

**Issue by Maciej-Szwed** [spdk/spdk#2037]
In pollers tab, in poller status column we can get "busy" or "idle" string. In case poller was idle and it becomes busy the label changes correctly, but in case busy poller becomes idle again the label stays "busy".
 
I tested it with 21.04 release and some quite recent versions of main branch.

**Comment by KKaras169169** [comment]
I was able to reproduce this on my development machine. The problem was: spdk_top would only check if poller had a busy counter larger than 0 and since our RPCs do not return a difference, only total values for poller busy count, the condition would always be true and red "Busy" would display. 

This is a possible fix to this issue: https://review.spdk.io/gerrit/c/spdk/spdk/+/8755
