### ISSUE TITLE
coredump file size of vhost app

### ISSUE THREAD

**Issue by subo7** [spdk/spdk#215]
If a vhost app coredump when vm with vhost-user-scsi devices connecting to it, the generated coredump file size is huge. 
Is there any way to filter vm memory addresses mmaped to vhost, so we can limit the size of coredump file?

**Comment by pawelwod** [comment]
You can select what core file will contain. See `man 5 core`.

**Comment by jimharris** [comment]
SPDK probably should by default call madvise() with MADV_DONTDUMP on memory regions mapped from the VM.

**Comment by pawelwod** [comment]
I think that using core file filters is better choice since setting MADV_DONTDUMP will defeat any postmortem debug since we will be unable to inspect data in mapped area.

**Comment by jimharris** [comment]
MADV_DONTDUMP would make shared VM memory behave similarly for core dumps to DPDK memory.  DPDK memory does not get dumped because default core settings will not dump hugepage memory.

This ensures that by default, a core file does not generate GBs of core dump data.

If we want to enable full core dumps, with a dump of all mapped memory (both DPDK and VMs) – that should be done separately.
