### ISSUE TITLE
[nvmf_example] Fail due to insufficient number of tcp interfaces

### ISSUE THREAD

**Issue by KKaras169169** [spdk/spdk#2187]
# CI Intermittent Failure

During nvmf-tcp-phy-autotest, nvmf_example test returned error on bash test for available tcp interface number.

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_59469.html

## Execution failed at

```
00:02:59.744  ************************************
00:02:59.744  START TEST nvmf_example
00:02:59.744  ************************************
00:02:59.744   13:11:01	-- common/autotest_common.sh@959 -- # xtrace_enable
00:02:59.744   13:11:01	-- common/autotest_common.sh@960 -- # test/nvmf/target/nvmf_example.sh --transport=tcp
00:02:59.804  * Looking for test storage...
00:02:59.809  * Found test storage at /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/test/nvmf/target
00:02:59.810    13:11:01	-- common/autotest_common.sh@1415 -- # xtrace_enable
00:02:59.810   13:11:01	-- target/nvmf_example.sh@6 -- # source /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/test/nvmf/common.sh
00:02:59.810    13:11:01	-- nvmf/common.sh@1 -- # NVMF_PORT=4420
00:02:59.811    13:11:01	-- nvmf/common.sh@2 -- # NVMF_SECOND_PORT=4421
00:02:59.811    13:11:01	-- nvmf/common.sh@3 -- # NVMF_THIRD_PORT=4422
00:02:59.811    13:11:01	-- nvmf/common.sh@4 -- # NVMF_IP_PREFIX=192.168.100
00:02:59.811    13:11:01	-- nvmf/common.sh@5 -- # NVMF_IP_LEAST_ADDR=8
00:02:59.811    13:11:01	-- nvmf/common.sh@6 -- # NVMF_TCP_IP_ADDRESS=127.0.0.1
00:02:59.812    13:11:01	-- nvmf/common.sh@7 -- # NVMF_TRANSPORT_OPTS=
00:02:59.812    13:11:01	-- nvmf/common.sh@8 -- # NVMF_SERIAL=SPDK00000000000001
00:02:59.812    13:11:01	-- nvmf/common.sh@29 -- # : 0
00:02:59.812    13:11:01	-- nvmf/common.sh@30 -- # export NVMF_APP_SHM_ID
00:02:59.812    13:11:01	-- nvmf/common.sh@31 -- # build_nvmf_app_args
00:02:59.813    13:11:01	-- nvmf/common.sh@11 -- # '[' 0 -eq 1 ']'
00:02:59.813    13:11:01	-- nvmf/common.sh@15 -- # NVMF_APP+=(-i "$NVMF_APP_SHM_ID" -e 0xFFFF)
00:02:59.813    13:11:01	-- nvmf/common.sh@17 -- # '[' -n '' ']'
00:02:59.813    13:11:01	-- nvmf/common.sh@19 -- # '[' 0 -eq 1 ']'
00:02:59.814    13:11:01	-- nvmf/common.sh@33 -- # have_pci_nics=0
00:02:59.814   13:11:01	-- target/nvmf_example.sh@8 -- # rpc_py=/var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/scripts/rpc.py
00:02:59.814   13:11:01	-- target/nvmf_example.sh@10 -- # NVMF_EXAMPLE=("$SPDK_EXAMPLE_DIR/nvmf")
00:02:59.814   13:11:01	-- target/nvmf_example.sh@12 -- # MALLOC_BDEV_SIZE=64
00:02:59.814   13:11:01	-- target/nvmf_example.sh@13 -- # MALLOC_BLOCK_SIZE=512
00:02:59.814   13:11:01	-- target/nvmf_example.sh@22 -- # build_nvmf_example_args
00:02:59.815   13:11:01	-- target/nvmf_example.sh@16 -- # '[' 0 -eq 1 ']'
00:02:59.815   13:11:01	-- target/nvmf_example.sh@19 -- # NVMF_EXAMPLE+=(-i "$NVMF_APP_SHM_ID" -g 10000)
00:02:59.815   13:11:01	-- target/nvmf_example.sh@38 -- # timing_enter nvmf_example_test
00:02:59.815   13:11:01	-- common/autotest_common.sh@592 -- # xtrace_disable
00:02:59.816   13:11:01	-- common/autotest_common.sh@14 -- # '[' '' '!=' yes ']'
00:02:59.816   13:11:01	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:02:59.816   13:11:01	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:02:59.816   13:11:01	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:02:59.817   13:11:01	-- common/autotest_common.sh@19 -- # set +x
00:02:59.817   13:11:01	-- common/autotest_common.sh@594 -- # xtrace_enable
00:02:59.817   13:11:01	-- target/nvmf_example.sh@39 -- # nvmftestinit
00:02:59.818   13:11:01	-- nvmf/common.sh@412 -- # '[' -z tcp ']'
00:02:59.818   13:11:01	-- nvmf/common.sh@417 -- # trap 'process_shm --id $NVMF_APP_SHM_ID || :; nvmftestfini' SIGINT SIGTERM EXIT
00:02:59.818   13:11:01	-- nvmf/common.sh@419 -- # '[' '' == iso ']'
00:02:59.818   13:11:01	-- nvmf/common.sh@429 -- # NVMF_TRANSPORT_OPTS='-t tcp'
00:02:59.819   13:11:01	-- nvmf/common.sh@430 -- # [[ tcp == \r\d\m\a ]]
00:02:59.819   13:11:01	-- nvmf/common.sh@438 -- # [[ tcp == \t\c\p ]]
00:02:59.819   13:11:01	-- nvmf/common.sh@439 -- # nvmf_tcp_init
00:02:59.819   13:11:01	-- nvmf/common.sh@351 -- # NVMF_INITIATOR_IP=10.0.0.1
00:02:59.819   13:11:01	-- nvmf/common.sh@352 -- # NVMF_FIRST_TARGET_IP=10.0.0.2
00:02:59.820   13:11:01	-- nvmf/common.sh@353 -- # TCP_INTERFACE_LIST=($(get_tcp_if_list_by_driver))
00:02:59.820    13:11:01	-- nvmf/common.sh@353 -- # get_tcp_if_list_by_driver
00:02:59.820    13:11:01	-- nvmf/common.sh@219 -- # local driver
00:02:59.820    13:11:01	-- nvmf/common.sh@220 -- # driver=ice
00:02:59.821    13:11:01	-- nvmf/common.sh@225 -- # sleep 1
00:03:00.820    13:11:02	-- nvmf/common.sh@227 -- # shopt -s nullglob
00:03:00.820    13:11:02	-- nvmf/common.sh@228 -- # tcp_if_list=(/sys/bus/pci/drivers/$driver/0000*/net/*)
00:03:00.820    13:11:02	-- nvmf/common.sh@229 -- # shopt -u nullglob
00:03:00.820    13:11:02	-- nvmf/common.sh@230 -- # printf '%s\n' enp8s0f1
00:03:00.821   13:11:02	-- nvmf/common.sh@354 -- # (( 1 == 0 ))
00:03:00.821   13:11:02	-- nvmf/common.sh@360 -- # (( 1 > 1 ))
00:03:00.821    13:11:02	-- nvmf/common.sh@360 -- # trap - ERR
00:03:00.822    13:11:02	-- nvmf/common.sh@360 -- # print_backtrace
00:03:00.822    13:11:02	-- common/autotest_common.sh@988 -- # [[ ehxBET =~ e ]]
00:03:00.822    13:11:02	-- common/autotest_common.sh@990 -- # args=("${BASH_ARGV[@]}")
00:03:00.822    13:11:02	-- common/autotest_common.sh@990 -- # local args
00:03:00.823    13:11:02	-- common/autotest_common.sh@992 -- # xtrace_disable
00:03:00.823    13:11:02	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:03:00.823    13:11:02	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:03:00.823    13:11:02	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:03:00.823    13:11:02	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:03:00.824    13:11:02	-- common/autotest_common.sh@19 -- # set +x
00:03:00.824  ========== Backtrace start: ==========
00:03:00.824  
00:03:00.829  in /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/test/nvmf/common.sh:360 -> nvmf_tcp_init([])
00:03:00.829       ...
00:03:00.829     355 			nvmf_veth_init
00:03:00.829     356 			return 0
00:03:00.829     357 		fi
00:03:00.829     358 	
00:03:00.829     359 		# We need two net devs at minimum
00:03:00.829  => 360 		((${#TCP_INTERFACE_LIST[@]} > 1))
00:03:00.829     361 	
00:03:00.829     362 		NVMF_TARGET_INTERFACE=${TCP_INTERFACE_LIST[0]}
00:03:00.829     363 		NVMF_INITIATOR_INTERFACE=${TCP_INTERFACE_LIST[1]}
00:03:00.829     364 	
00:03:00.829     365 		# Skip case nvmf_multipath in nvmf_tcp_init(), it will be covered by nvmf_veth_init().
00:03:00.829       ...
00:03:00.837  in /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/test/nvmf/common.sh:439 -> nvmftestinit([])
00:03:00.837       ...
00:03:00.837     434 			if [ -z $NVMF_FIRST_TARGET_IP ]; then
00:03:00.837     435 				echo "no RDMA NIC for nvmf test"
00:03:00.837     436 				exit 0
00:03:00.837     437 			fi
00:03:00.837     438 		elif [[ "$TEST_TRANSPORT" == "tcp" ]]; then
00:03:00.837  => 439 			nvmf_tcp_init
00:03:00.837     440 			NVMF_TRANSPORT_OPTS="$NVMF_TRANSPORT_OPTS -o"
00:03:00.837     441 		fi
00:03:00.837     442 	
00:03:00.837     443 		if [ "$TEST_TRANSPORT" == "tcp" ] || [ "$TEST_TRANSPORT" == "rdma" ]; then
00:03:00.837     444 			# currently we run the host/perf test for TCP even on systems without kernel nvme-tcp
00:03:00.837       ...
00:03:00.844  in test/nvmf/target/nvmf_example.sh:39 -> main(["--transport=tcp"])
00:03:00.844       ...
00:03:00.844     34  		waitforlisten $nvmfpid
00:03:00.844     35  		timing_exit start_nvmf_example
00:03:00.844     36  	}
00:03:00.844     37  	
00:03:00.844     38  	timing_enter nvmf_example_test
00:03:00.844  => 39  	nvmftestinit
00:03:00.844     40  	nvmfexamplestart "-m 0xF"
00:03:00.844     41  	
00:03:00.844     42  	#create transport
00:03:00.844     43  	$rpc_py nvmf_create_transport $NVMF_TRANSPORT_OPTS -u 8192
00:03:00.844     44  	#create malloc bdev
00:03:00.844       ...
00:03:00.844  
00:03:00.844  ========== Backtrace end ==========
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_59469.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_59494.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_59507.html

**Comment by jimharris** [comment]
so all of these are on GP9 - which I'm guessing now has an E810 (ice) NIC installed

nvmf_tcp_init calls get_tcp_if_list_by_driver, which by default looks for ice interfaces - if it finds one interface, this function returns to nvmf_tcp_init and will *not* configure the veth and instead fails on the check that @KKaras169169 shows above

looks like commit 460bacc914 added these changes - @wanghailiangx @mikeBashStuff can you take a look?

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_59576.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_59579.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_59572.html

**Comment by mikeBashStuff** [comment]
These failures actually happened on GP2 - not sure why jenkins reported GP9 as the remote node, odd (later in the log you can see actual hostname of the system. The pci addresses of the ice ctrls also don't match what's available on GP9, but they do match GP2's). 

Also, this points at the fact that there's proper amount of devices available on the node:

```
00:03:49.990   04:35:24	-- nvmf/common.sh@67 -- # nvmf_nic_bdfs='0000:08:00.0
00:03:49.990  0000:08:00.1'
```

however, one of the net devices is not available - that's because of the lingering namespace that missing devices was put into. I thought that 4f99de088e would mitigate issues like that but apparently that's not the case. Maybe we need to be more proactive and always attempt to remove the target namespace prior looking up the net devices we want to use for the tests (so before or as part of `get_tcp_if_list_by_driver()`).

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_59791.html

**Comment by wanghailiangx** [comment]
@jimharris Thank you for your advice, I added a NIC interface number vaule for tcp test, this patch has been updated.

**Comment by mikeBashStuff** [comment]
There's also an ongoing plan to refactor the way how we detect devices needed for the nvmf tests - https://review.spdk.io/gerrit/c/spdk/spdk/+/7849. Mentioning it here just in case we attempt to mitigate this particular issue by introducing more  changes to the `test/nvmf` suite.

**Comment by mikeBashStuff** [comment]
@jimharris 
>One request that I'm sure you're already considering is that any refactoring takes into account running these tests locally on development systems

Current nvmf test cases are currently written in a specific and not very flexible way. For instance, as this may be not be very clear, `nvmf-phy-autotest` is targeting the mlx setup, while `nvmf-tcp-phy-autotest` the ice - this is handled by shuffling drivers on the target system by the CI (it basically unloads modules from the kernel for interfaces we don't want to test and keep those we do want) prior running the actual tests.

The https://review.spdk.io/gerrit/c/spdk/spdk/+/7849 is meant to change that such that the nvmf suite will look up the env to see what devices should be used for the tests instead (currently mlx or ice to keep what CI was targeting) and look for them on its own. If env doesn't provide that info it will take the entire list of what it found (mlx, e810, x722) and build setup around it (so if you had 1 ice and some mlx it would mix those together). If it doesn't find any, the fallback depends on what transport is being tested (softroce for rdma, veth for tcp).

>I even wonder if by default, these tests should always use veth instead of physical interfaces.

From the CI perspective and in the context of phy systems, we don't really want that since we want to make sure we are testing nvmf under specific hardware. That said, for the users, I can add additional patches on top of 7849 which would add another env switch telling the suite what type of devices we would want to use; something along the lines of `NET_TYPE={virt,phy}` - so CI for phy-autotests would export `NET_TYPE=phy` while for vg-autotests `NET_TYPE=virt` and local users would adjust it however they want. Having it by default set to `virt` would be then an option.

**Comment by mikeBashStuff** [comment]
There's ongoing series addressing general refactor of the way how nvmf tests pick up proper hardware for the tests here: https://review.spdk.io/gerrit/c/spdk/spdk/+/7849 - this should also help to mitigate similar issues (some other mitigations were already merged as well). And since the last report is from over a month ago I think we can close this for now.
