### ISSUE TITLE
RBD bdev performance doesn't scale when adding more RBD images

### ISSUE THREAD

**Issue by EugeneKochetov** [spdk/spdk#2204]
# Bug report

Performance of one RBD image (bdev_rbd) is usually quite low and SPDK is not a bottle neck. When more RBD bdevs are added to loadshare and improve overall performance, SPDK becomes a limiting factor because only one SPDK core is handling all RBD IOs.

Issue was introduced by this patch: https://github.com/spdk/spdk/commit/e1e73440d37b1b9ee3ab5a5497e52b7187e4eebd. The patch itself is good and fixes another scalability issue with Ceph exclusive lock contention. But it can be improved.

Currently each RBD bdev has associated main thread. All submitted IOs on other threads are forwarded to this main thread and submitted to librbd. Polling for completions is also done on the main thread. Main thread is assigned when the first IO channel is requested for RBD bdev and is set to the current thread. It may depend on application but with nvmf_tgt it is always the first nvmf_poll_group thread, i.e. the first CPU core. It is not a big issue with one RBD bdev since Ceph is slow. But when we have many RBD bdevs it becomes a problem.

## Expected Behavior

RBD bdev IOs are handled by multiple SPDK cores. At least IOs to different RBD bdevs.

## Current Behavior

IOs for all RBD bdevs are served by single SPDK core.

## Possible Solution

Add load sharing (at least simple round-robin) when selecting main thread for RBD bdev.
A work in progress patch with solution proposal can be found here: https://review.spdk.io/gerrit/c/spdk/spdk/+/9895

## Steps to Reproduce

Originally it was reproduced with spdk_tgt app configured to forward IOs from NVMf RDMA target to Ceph. But it can also be reproduced with bdevperf test tool.

1. Use bdevperf and create multiple RBD bdevs
2. Run IO to all bdevs. It is important to start bdevperf with -C to use all cores to all bdevs
3. Check core load with spdk_top - one core will have significantly higher load

## Context (Environment including OS version, SPDK version, etc.)

SPDK 21.10-pre.

**Comment by EugeneKochetov** [comment]
Hi,

Solution for this scaling issue is ready here: https://review.spdk.io/gerrit/c/spdk/spdk/+/9895. Could you please have a look?

As @tanlong0121 reported, the patch mentioned by @jimharris above causes performance degradation. We have some ideas why it can be. But analysis and fix will require some time.
@jimharris is it OK with you to revert this patch for now?

**Comment by jimharris** [comment]
> Hi,
> 
> Solution for this scaling issue is ready here: https://review.spdk.io/gerrit/c/spdk/spdk/+/9895. Could you please have a look?
> 
> As @tanlong0121 reported, the patch mentioned by @jimharris above causes performance degradation. We have some ideas why it can be. But analysis and fix will require some time. @jimharris is it OK with you to revert this patch for now?

Thanks @EugeneKochetov.  Can you share the initial ideas you have on why it is causing performance degradation?  It really is a nice cleanup, avoiding the extra epoll.  It's really perplexing why removing the epoll would have such a big impact especially on something like 1M sequential reads.

Do you have data on overall CPU utilization before and after the epoll patch?  And also what kind of configuration you used for the benchmark comparison, including number of CPU cores available on the system, how many used for the target app (vs. how many are free to run Ceph RBD threads) and the RPCs used to set up the rbd bdevs.  For example, want to make sure you're using the bdev_rbd_register_cluster RPC to minimize the number of threads that librbd is spawning.

I'm open to reverting it, but I'd like to understand the current thinking a bit more before we do it.

**Comment by tanlong0121** [comment]
Hi,

Testing system is on my hand, I will retest the patch before and after, and collect the info @jimharris mentioned, this may need some time, I will sync the results once completing. We use bdev_rbd_create to create rbd bdev, I will try bdev_rbd_register_cluster also.

Regarding the patch https://review.spdk.io/gerrit/c/spdk/spdk/+/9895, I have another thinking of the solution, we know the bottleneck is all the rbd dev are running on the same core, and solution is assigning different dev IO threads on different cores, but how to assign the threads, there is another possible thinking. When create rbd dev, bdev_rbd_create_cb will be called first time, mian_thread is determined and open rbd for IO comamnds later, then the rbd dev(like: Ceph 0) is attached as a namespace of nvmf subystem, the bdev_rbd_create_cb is called by app each poller threads, in our system, we use nvmf_tgt app and start with -m 0xff, so the threads from nvmf_tgt_poll_group_0 to nvmf_tgt_poll_group_7 will call bdev_rbd_create_cb, but do not enter the branch "if (disk->ch_count == 0)", so can we  reuse these threads for handing IO commands instead of creating additional threads as shown in the patch? I see more protocal modules implementations, like nvme, there is no additional threads created in nvme bdev module to distribut IO for different devs, I think the principal should be who call bdev_io_submit to send IO, it should make sure the IO pressure is shared on different threads and different cores, return back our scenario, the nvmf target receive IO commands from nvmf initiator, and send to rbd bdev, we can also reuse the nvmf target threads, these threads are created on each reactor core. Except avoid creating additonal threads, the higher meaning is we should create a common mechanism for all bdevs who only use one thread for one bdev to send IO commands, like iscsi, it also use "main thread" to send IO, I'm not sure if it also has this issue, if yes, we should use the same common mechanism to handle, instead of also creating addtional threads to fix. Expect to hear your thinking on this probelm.

**Comment by tanlong0121** [comment]
And there are another 2 patches to fix rbd issues about performance: https://review.spdk.io/gerrit/c/spdk/spdk/+/10198 and https://review.spdk.io/gerrit/c/spdk/spdk/+/10201/2, could you please take a look?

**Comment by EugeneKochetov** [comment]
> Thanks @EugeneKochetov. Can you share the initial ideas you have on why it is causing performance degradation? It really is a nice cleanup, avoiding the extra epoll. It's really perplexing why removing the epoll would have such a big impact especially on something like 1M sequential reads.

@jimharris, here are my thoughts on possible root cause for degradation. With epoll completion mechanism all IO completion handling was done in scope of SPDK thread. Once epoll was removed we partly do it in completion callback in the context of librbd thread. librbd threads are very CPU intensive and we take some precious CPU time for SPDK needs. Solution can be to just spdk_thread_send_msg to submit_td and do all the processing there.

Just for records, I have one more concern regarding [rbd_aio_create_completion()](https://github.com/ceph/ceph/blob/4035ba419decbdb825db489d58c77a2a17038b44/src/librbd/librbd.cc#L6105) and [rbd_aio_release()](https://github.com/ceph/ceph/blob/4035ba419decbdb825db489d58c77a2a17038b44/src/librbd/io/AioCompletion.h#L168) functions. I see that they use dynamic memory allocation and we usually try to avoid it on data path. Maybe we can pre-create a pool of completions and use them in data path. Not sure if it will work with librbd and give any significant improvement. Anyway, this is another improvement not related to this issue.

Regarding our patch for this issue. Looks like approach with bdev_rbd threads will not work. It fails with bdev fio plugin. fio plugin doesn't use SPDK application framework and it looks like our bdev_rbd threads are not polled and IOs do not progress. As far as I see, fio plugin only polls threads that it has created.

**Comment by jimharris** [comment]
> @jimharris, here are my thoughts on possible root cause for degradation. With epoll completion mechanism all IO completion handling was done in scope of SPDK thread. Once epoll was removed we partly do it in completion callback in the context of librbd thread. librbd threads are very CPU intensive and we take some precious CPU time for SPDK needs. Solution can be to just spdk_thread_send_msg to submit_td and do all the processing there.

Yeah, I was thinking along these lines too, but for 1M sequential reads, we aren't doing very many completions, so it's surprising that we'd see 14% degradation (compared to only 3% for random 4KB write).

I think it's really important for us to go back and re-run the performance data using the bdev_rbd_register_cluster RPC.  That will significantly cut down on the number of threads spawned by librbd which will likely have a noticeable effect on the numbers.  I'd like to see if and how much that impacts the performance degradation observed with commit https://github.com/spdk/spdk/commit/62210eff55bd8c002711b31981c7c84817ebf861 before we revert it.  If it's still noticeable, I'm OK reverting it while we debug further.


> Just for records, I have one more concern regarding [rbd_aio_create_completion()](https://github.com/ceph/ceph/blob/4035ba419decbdb825db489d58c77a2a17038b44/src/librbd/librbd.cc#L6105) and [rbd_aio_release()](https://github.com/ceph/ceph/blob/4035ba419decbdb825db489d58c77a2a17038b44/src/librbd/io/AioCompletion.h#L168) functions. I see that they use dynamic memory allocation and we usually try to avoid it on data path. Maybe we can pre-create a pool of completions and use them in data path. Not sure if it will work with librbd and give any significant improvement. Anyway, this is another improvement not related to this issue.
> 
> Regarding our patch for this issue. Looks like approach with bdev_rbd threads will not work. It fails with bdev fio plugin. fio plugin doesn't use SPDK application framework and it looks like our bdev_rbd threads are not polled and IOs do not progress. As far as I see, fio plugin only polls threads that it has created.

**Comment by changpe1** [comment]
@EugeneKochetov Does your application only use one core? e.g: if we use RBD images as SPDK vhost target backend devices, then the RBD image should span to different threads based on the configuration of vhost controller core mask.  From the code, it's up to caller to decide using which core.

**Comment by changpe1** [comment]
> SPDK becomes a limiting factor because only one SPDK core is handling all RBD IOs

I'm a little confused about the description "SPDK becomes a limiting factor because only one SPDK core is handling all RBD IOs", do you mean SPDK is processing all IOs from different RBD images in one core?

**Comment by EugeneKochetov** [comment]
Hi @changpe1,

We test with spdk_tgt application that comes with SPDK. spdk_tgt is run on multiple cores (8). We create 8 or 16 rbd bdevs. All rbd bdevs are assigned by SPDK to the same main thread (rbd->main_td). This means that all IOs submitted to any rbd bdev submitted from any core will be forwarded to the same SPDK thread (core) to do the actual submission to librbd. This is not a problem with single rbd bdev since Ceph performance is quite low. But when we add more rbd bdevs this becomes a bottleneck.

In the latest master version this applies only to submission flow. Completions don't go to main_td.

The same issue may be reproduced with bdevperf. We create 8 rbd bdevs and run bdevperf test with 8 cores. When bdevperf is run wihtout "-C" option, each rbd bdev is assigned a different main_td and performance is good. When we run bdevperf with "-C" option all rbd bdevs are assigned to the same main_td and performance drops.

It all depends on who will be the first to call spdk_bdev_get_io_channel(). And it may vary from app to app. I'd say some predictability or configuration would be good to have.

**Comment by EugeneKochetov** [comment]
Hi @jimharris 

> I think it's really important for us to go back and re-run the performance data using the bdev_rbd_register_cluster RPC. That will significantly cut down on the number of threads spawned by librbd which will likely have a noticeable effect on the numbers. I'd like to see if and how much that impacts the performance degradation observed with commit [62210ef](https://github.com/spdk/spdk/commit/62210eff55bd8c002711b31981c7c84817ebf861) before we revert it. If it's still noticeable, I'm OK reverting it while we debug further.

We tested with bdev_rbd_register_cluster RPC and it didn't help. In fact, it made things worse. Without cluster registration we see that librbd uses many cores (40) and all are pretty busy (around 70%). With cluster registration we see only 4 librbd threads. They also very busy but overall performance drops. And looks like drop is proportional to decrease in number of cores. Do you know if we can control number of threads created by librbd?

**Comment by EugeneKochetov** [comment]
In fact, we're discussing several issue and improvements here. So, I'd like to bring some order.

This is the current list of issues and improvements mentioned in the thread:

1. Original issue from description - performance scalability problem because all rbd bdev IOs are handled by single core (same main_td). I believe this must be addressed somehow.
2. Performance degradation in the 21.10 release due to remove of epoll. This is still to be confirmed. @tanlong0121 will retest and get back with results.
3. librbd threads affinity patches https://review.spdk.io/gerrit/c/spdk/spdk/+/10198. May give additional performance gain and make results more stable and predictable.

Please correct me if I missed something.

**Comment by jimharris** [comment]
> Hi @jimharris
> 
> > I think it's really important for us to go back and re-run the performance data using the bdev_rbd_register_cluster RPC. That will significantly cut down on the number of threads spawned by librbd which will likely have a noticeable effect on the numbers. I'd like to see if and how much that impacts the performance degradation observed with commit [62210ef](https://github.com/spdk/spdk/commit/62210eff55bd8c002711b31981c7c84817ebf861) before we revert it. If it's still noticeable, I'm OK reverting it while we debug further.
> 
> We tested with bdev_rbd_register_cluster RPC and it didn't help. In fact, it made things worse. Without cluster registration we see that librbd uses many cores (40) and all are pretty busy (around 70%). With cluster registration we see only 4 librbd threads. They also very busy but overall performance drops. And looks like drop is proportional to decrease in number of cores. Do you know if we can control number of threads created by librbd?

I think we can only indirectly controller the number of threads created by librbd, by changing the number of cluster objects we create in SPDK.

Creating one cluster object for each RBD bdev is terrible if you have 10s or 100s of bdev, since you end up with 4 threads per bdev.  But having just one cluster object doesn't necessarily work either as you've shown here.

Was this test still with 8 disks (rbd bdevs)?  If so, then your numbers make sense - 8 rbd bdevs * 4 librbd threads per bdev = 32 threads.  If those threads are getting scheduled periodically across 40 cores, and those cores are pretty much always busy than 70-80% per core seems right.

So in your case, if you're testing with 8 disks, you could try calling bdev_rbd_register_cluster twice (for example) to create two cluster objects, and then call bdev_rbd_create 4 times with each cluster object.

**Comment by jimharris** [comment]
> In fact, we're discussing several issue and improvements here. So, I'd like to bring some order.
> 
> This is the current list of issues and improvements mentioned in the thread:
> 
> 1. Original issue from description - performance scalability problem because all rbd bdev IOs are handled by single core (same main_td). I believe this must be addressed somehow.
> 2. Performance degradation in the 21.10 release due to remove of epoll. This is still to be confirmed. @tanlong0121 will retest and get back with results.
> 3. librbd threads affinity patches https://review.spdk.io/gerrit/c/spdk/spdk/+/10198. May give additional performance gain and make results more stable and predictable.
> 
> Please correct me if I missed something.

This is a good summary.  I made some comments on the 10198 patch - I think it's a bug that the spdk unaffinitized routines only remove affinity of the calling CPU core instead of all of the core's in the application's core mask.

**Comment by tanlong0121** [comment]
@EugeneKochetov @jimharris 

We re-run the tests several times with 4 versions, and summarize the results below:

Version A: commit id 59305582120723733348d8d91847a4d6b8d02dbd + https://review.spdk.io/gerrit/c/spdk/spdk/+/9895
Version B: commid id 3b1f13ef29058782e0a7d1ac1799648a69c14ec8 + https://review.spdk.io/gerrit/c/spdk/spdk/+/9895
Version C: commid id 4e4f11ff7840f02cb6d9497acd42897844a43f87 + https://review.spdk.io/gerrit/c/spdk/spdk/+/9895
Version D: commid id 4e4f11ff7840f02cb6d9497acd42897844a43f87 + https://review.spdk.io/gerrit/c/spdk/spdk/+/9895 - https://github.com/spdk/spdk/commit/62210eff55bd8c002711b31981c7c84817ebf861

Version A is the higher performance version mentioned above, and the patch removing epoll has not been merged. Version B is the lower performance version mentioned above, and the patch removing epoll has been merged. Version C is a recent version of upstream. Version D is add the epoll mechanism back compared with version C. 

Results:
1. Version B is lower than version A as I described above, we re-run the 2 versions several times, this is comfirmed. 
2. Version C is closed with version D, and they are also closed with version A, so it looks the degradation is not affected by removing epoll, because the base of version A and version B are different, so may be other changes lead the degradation.

We are sorry for confusing you due to more changes betwwen version A and version B instead of only epoll mechanism. Anyway, the latest code looks good for performance, so it is no need to revert removing epoll.

**Comment by EugeneKochetov** [comment]
@tanlong0121, thanks for your update.

@jimharris, we pushed for review another solution for loadsharing issue: https://review.spdk.io/gerrit/c/spdk/spdk/+/10295
The solution is very simple. We don't pass IO to main_td and just submit from original thread. This means that multiple SPDK threads may submit IO to the same librbd image context. We rely here on thread safety of librbd `rbd_aio_read/write()` functions. The problem is that it is not explicitly stated anywhere if these functions are thread-safe. In fact, we didn't find any documentation on librbd C API. We asked in Ceph community but didn't get any response so far.

@tanlong0121 mentioned above that he has another solution for this issue.

@jimharris, could you please share your thoughts on it?

**Comment by tanlong0121** [comment]
@jimharris

I have submitted a patch with my idea mentioned above: https://review.spdk.io/gerrit/c/spdk/spdk/+/10416/, and I describe the difference with https://review.spdk.io/gerrit/c/spdk/spdk/+/9895 and https://review.spdk.io/gerrit/c/spdk/spdk/+/10295 in the patch, the results show in our scenario it is working well and the CPU utilization decresed compare with 9895, and keep the policy that one thread for one rbd bdev to send IOs. Could you please take a look, and share your view of the 3 solutions, or you have better solution?

**Comment by jimharris** [comment]
> @tanlong0121, thanks for your update.
> 
> @jimharris, we pushed for review another solution for loadsharing issue: https://review.spdk.io/gerrit/c/spdk/spdk/+/10295 The solution is very simple. We don't pass IO to main_td and just submit from original thread. This means that multiple SPDK threads may submit IO to the same librbd image context. We rely here on thread safety of librbd `rbd_aio_read/write()` functions. The problem is that it is not explicitly stated anywhere if these functions are thread-safe. In fact, we didn't find any documentation on librbd C API. We asked in Ceph community but didn't get any response so far.
> 
> @tanlong0121 mentioned above that he has another solution for this issue.
> 
> @jimharris, could you please share your thoughts on it?

10295 seems like the cleanest solution, if we can get confirmation that these APIs are thread-safe.

**Comment by tanlong0121** [comment]
In most scenarios，multiple threads write to a rbd image is safe, but we cannot enusre users will not write the same block in a very short time, single thread is safe definitely. Because ceph is a slow storage, the performance bottneck is not in client, so multi-threads cannot bring much benifit, contrarily, it will lead competition betwwen threads and higher cpu load compare with single thread.

**Comment by EugeneKochetov** [comment]
> In most scenarios，multiple threads write to a rbd image is safe, but we cannot enusre users will not write the same block in a very short time, single thread is safe definitely. Because ceph is a slow storage, the performance bottneck is not in client, so multi-threads cannot bring much benifit, contrarily, it will lead competition between threads and higher cpu load compare with single thread.

@tanlong0121, how is 10295 different from other suggested solutions? Could you please clarify?
If app generates IO to the same block from multiple threads, no one can guarantee the order. And I'm not sure what competition do you mean. As far as I understand, IOs are handled in the context of internal librbd threads. So, it should not matter which SPDK thread submitted the IO.
There may be some lock competition if IPC to librbd threads is not lockless. If it is an issue, it can be identified in tests.

Anyway, we don't have any proof of thread-safety yet.

**Comment by tanlong0121** [comment]
> 

Let me clarify the patch 10416 I submitted first. The main thinking of 10416 is to use the threads that rbd bdev io channels were created on, for example, in our scenario, the app is started as: ./build/bin/nvmf_tgt -m 0xff, there are 8 threads(named nvmf_tgt_poll_group_0 to nvmf_tgt_poll_group_7) are created on each core, a rbd bdev is created by rpc: ./scripts/rpc.py bdev_rbd_create -b rbd0 volumes rbd0 512, and create a nvmf target: ./scripts/rpc.py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001, attach the rbd bdev as the ns of the nvmf target: ./scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 rbd0, here we can see bdev_rbd_create_cb is called 8 times on the threads from nvmf_tgt_poll_group_0 to nvmf_tgt_poll_group_7, the upstream code take the first thread as the main thread for each rbd bdev, so that is why you see all the rbd bdev IO are running on nvmf_tgt_poll_group_0, and other threads are quite idle. 10295 is trying to schedule this 8 threads to rbd bdevs in roud-robin fashion, because bdev_rbd_create_cb is also called by auto examin when the rbd is created, this is the first call, and the thread is app_thread, but we do not want to app_thread to handle IO, so the patch collect the threads from the second call, and the main  thread is updated from app_thread to nvmf_tgt_poll_group_0, when nvmf_tgt_poll_group_1 call the function, it will check if the main thread has been saved in the list, and also need to check if cuurent thread has been saved in the list, then reschdule the main thread from the list in round-robin fashion, and this step only need once, so add the flag main_td_rescheduled for that. Now we can see the difference of 10295 and other suggested solutions:

1. 10295 and 9895: 10295 send IO on the threads from nvmf_tgt_poll_group_0 to nvmf_tgt_poll_group_7 for each rbd bdev, 9895 will schedule the IO thread from the one(nvmf_tgt_poll_group_0 ~ nvmf_tgt_poll_group_7) to another one(selected in bdev_rbd_thread_0 ~ bdev_rbd_thread_7)
2. 10295 and 10416: 10416 select one thread in bdev_rbd_thread_0 ~ bdev_rbd_thread_7 as the main thread, so 1/8 will not reschedule the IO context, 10295 send IO commands directly.
3. 9895 and 10416: 10416 do not create additonal threads to handle rbd bdev IO commands and reuse nvmf_tgt_poll_group_x, so no cpu competion for each core and the cpu load is decreased indeed from the test results.

**Comment by Bianyfan** [comment]
Hi, @jimharris , we did some test locally and found the same issue. When we use spdk_tgt to run on multiple cores(4) with creating 8 rbd bdevs for 8 images, only one SPDK core is handling all IO. Actually, all the IOs are handled by main spdk_thread. A simple way to find this core bottleneck is to use ./build/bin/spdk_top to check the core status. Also, we did some tests based on above patches.
Both of 10295 and 10416 could resolve this issue. But for 10295, it looks clean and IO request will be sent directly without spdk_thread, I'm not sure this solution is thread safety and whether it is reasonable to provide this API. As for 10416, it will reuse the spdk_thread that we created before and make a load balance for different cores. Could you help review two solutions? In my option, reuse the spdk_thead and balance the IO on different cores may be better and safer. Besides, there may be the same issue in iscsi bdev, but I'm not sure.
There are two solution links:
https://review.spdk.io/gerrit/c/spdk/spdk/+/10295
https://review.spdk.io/gerrit/c/spdk/spdk/+/10416

**Comment by jimharris** [comment]
> Hi, @jimharris , we did some test locally and found the same issue. When we use spdk_tgt to run on multiple cores(4) with creating 8 rbd bdevs for 8 images, only one SPDK core is handling all IO. Actually, all the IOs are handled by main spdk_thread. A simple way to find this core bottleneck is to use ./build/bin/spdk_top to check the core status. Also, we did some tests based on above patches.
> Both of 10295 and 10416 could resolve this issue. But for 10295, it looks clean and IO request will be sent directly without spdk_thread, I'm not sure this solution is thread safety and whether it is reasonable to provide this API. As for 10416, it will reuse the spdk_thread that we created before and make a load balance for different cores. Could you help review two solutions? In my option, reuse the spdk_thead and balance the IO on different cores may be better and safer. Besides, there may be the same issue in iscsi bdev, but I'm not sure.
> There are two solution links:
> https://review.spdk.io/gerrit/c/spdk/spdk/+/10295
> https://review.spdk.io/gerrit/c/spdk/spdk/+/10416

I agree that 10295 would most ideal.

I have reached out to one of my colleagues who knows more about rbd/rados internals, to see if we can get guidance on whether these APIs are thread-safe.  I will report back here once I have info to share.

**Comment by Bianyfan** [comment]
> > Hi, @jimharris , we did some test locally and found the same issue. When we use spdk_tgt to run on multiple cores(4) with creating 8 rbd bdevs for 8 images, only one SPDK core is handling all IO. Actually, all the IOs are handled by main spdk_thread. A simple way to find this core bottleneck is to use ./build/bin/spdk_top to check the core status. Also, we did some tests based on above patches.
> > Both of 10295 and 10416 could resolve this issue. But for 10295, it looks clean and IO request will be sent directly without spdk_thread, I'm not sure this solution is thread safety and whether it is reasonable to provide this API. As for 10416, it will reuse the spdk_thread that we created before and make a load balance for different cores. Could you help review two solutions? In my option, reuse the spdk_thead and balance the IO on different cores may be better and safer. Besides, there may be the same issue in iscsi bdev, but I'm not sure.
> > There are two solution links:
> > https://review.spdk.io/gerrit/c/spdk/spdk/+/10295
> > https://review.spdk.io/gerrit/c/spdk/spdk/+/10416
> 
> I agree that 10295 would most ideal.
> 
> I have reached out to one of my colleagues who knows more about rbd/rados internals, to see if we can get guidance on whether these APIs are thread-safe. I will report back here once I have info to share.

It sounds great, thanks

**Comment by tsg-** [comment]
Follow-up with Ceph RBD maintainer (Illya) here:  https://lists.ceph.io/hyperkitty/list/dev@ceph.io/thread/SFWONIWKX5NOUSJSJIQN4LWCR3U6EFCN/

**Comment by tomzawadzki** [comment]
[Bug scrub] @jimharris will take a look at the patch on Gerrit and how to proceed with it.

**Comment by jimharris** [comment]
[Bug scrub] @sdpeters shared with me offline that someone is looking at updates to the 10416 patch to fix this issue.

@sdpeters - can you share any additional details?  And may I assign this issue to you?

-Jim

**Comment by sdpeters** [comment]
> [Bug scrub] @sdpeters shared with me offline that someone is looking at updates to the 10416 patch to fix this issue.
> 
> @sdpeters - can you share any additional details? And may I assign this issue to you?

Go ahead and assign this to me.

Many of these issues come from the Ceph/NVMe-oF gateway project, which has certain performance targets for the RBD bdev.

Specifically, the gateway currently applies these SPDK patches to its SPDK fork, and is working towards getting them merged so the gateway can use an unmodified SPDK release:

https://review.spdk.io/gerrit/c/spdk/spdk/+/16451 (submitted by @tanlong0121, required for https://github.com/ceph/ceph-nvmeof/issues/88)

https://review.spdk.io/gerrit/c/spdk/spdk/+/10416 (required for https://github.com/ceph/ceph-nvmeof/issues/89)

**Comment by optimistyzy** [comment]
My colleague @CongMinYin did some performance test upon this patch: https://review.spdk.io/gerrit/c/spdk/spdk/+/17644 (have to write a new one, since the change of the master)  with the following environment configuration on one ceph cluster.
The conclusion is that: 1 This patch can both improve the performance and solves the load balance issue among different cpu cores owned by SPDK applications (e.g., spdk bdevperf)

1 Perf test tool: 
 ./build/examples/bdevperf -q 1024 -o 4096 -w randread -t 300 -m 0xf -k 0 -C -z

2 Create bdev with the following script.

root@ceph-client4:/mnt/test-fio/spdk# cat create_image.sh
#!/bin/bash
ceph osd pool create spdktest 256
rbd pool init spdktest
for i in {0..3}
do
  rbd create --size 102400 --image spdktest/iscsidev$i
done 

root@ceph-client4:~/spdk# cat test.sh
#!/bin/bash
./scripts/rpc.py bdev_rbd_register_cluster nvme_cluster --config-file /etc/ceph/ceph.conf
echo "register cluster complete"
for number in {0..3}
do
./scripts/rpc.py bdev_rbd_create spdktest iscsidev$number 4096 -c nvme_cluster
done
exit 0


3 start test with the following script:
root@ceph-client4:~/spdk# PYTHONPATH=$PYTHONPATH:./python/ examples/bdev/bdevperf/bdevperf.py perform_tests


Ceph special configuration:
[client]
    ms_async_op_threads = 8
    librados_thread_count = 8


2 Then we get some performance test result among: master, patch, v22.05

We get the total IOPS comparison result,  it showed the the performance can be improved.

![image](https://user-images.githubusercontent.com/4121731/234167708-eb6336f3-5e0f-42bf-bf4a-0876b0dd41d5.png)

With our patch, the load balance issue can be eliminated if we use spdk_top to test.

The following shows the load balance issue in master branch if we test rand write:

![image](https://user-images.githubusercontent.com/4121731/234168035-d35d28a0-df3d-47af-8322-a87c7318528d.png)


With our patch,

![image](https://user-images.githubusercontent.com/4121731/234168128-bb38cf76-093e-4f05-9e23-af3ada0f5475.png)

**Comment by sdpeters** [comment]
To clarify (@optimistyzy ): Does https://review.spdk.io/gerrit/c/spdk/spdk/+/17644 (just merged) completely replace the (unmerged) "Loadshare IOs for rbd bdevs between CPU cores" patch (https://review.spdk.io/gerrit/c/spdk/spdk/+/10416) currently used by the Ceph NVMe-oF gateway? If so I'll mark that one abandoned, and note why.

Your recent comments on the librbd thread core mask patch (https://review.spdk.io/gerrit/c/spdk/spdk/+/16451), which the gateway also uses, indicate we still need that one.

**Comment by jimharris** [comment]
> To clarify (@optimistyzy ): Does https://review.spdk.io/gerrit/c/spdk/spdk/+/17644 (just merged) completely replace the (unmerged) "Loadshare IOs for rbd bdevs between CPU cores" patch (https://review.spdk.io/gerrit/c/spdk/spdk/+/10416) currently used by the Ceph NVMe-oF gateway? If so I'll mark that one abandoned, and note why.
> 
> Your recent comments on the librbd thread core mask patch (https://review.spdk.io/gerrit/c/spdk/spdk/+/16451), which the gateway also uses, indicate we still need that one.

I've marked 10416 as abandoned, it's no longer needed (and actually conflicts directly with the master and the merged 17644 patch).

Yes, I think you still want 16451.  It will let you configure where the librbd threads will execute.

**Comment by jimharris** [comment]
> > To clarify (@optimistyzy ): Does https://review.spdk.io/gerrit/c/spdk/spdk/+/17644 (just merged) completely replace the (unmerged) "Loadshare IOs for rbd bdevs between CPU cores" patch (https://review.spdk.io/gerrit/c/spdk/spdk/+/10416) currently used by the Ceph NVMe-oF gateway? If so I'll mark that one abandoned, and note why.
> > Your recent comments on the librbd thread core mask patch (https://review.spdk.io/gerrit/c/spdk/spdk/+/16451), which the gateway also uses, indicate we still need that one.
> 
> I've marked 10416 as abandoned, it's no longer needed (and actually conflicts directly with the master and the merged 17644 patch).
> 
> Yes, I think you still want 16451. It will let you configure where the librbd threads will execute.

But the bigger question is can we close this issue now?  @EugeneKochetov, what do you think?

**Comment by EugeneKochetov** [comment]
As for me, the original problem with scaling is resolved now. I'm OK to close the issue.

**Comment by sdpeters** [comment]
> As for me, the original problem with scaling is resolved now. I'm OK to close the issue.

I think we're only waiting for 16451, which the Ceph NVMe-oF gateway needs.

**Comment by tomzawadzki** [comment]
This issue seems to be resolved looking at the latest comments and following patches merged:
https://review.spdk.io/gerrit/c/spdk/spdk/+/17644
https://review.spdk.io/gerrit/c/spdk/spdk/+/16451
