### ISSUE TITLE
How to do memcpy with spdk_ioat concerning file mmap

### ISSUE THREAD

**Issue by Lyhugo** [spdk/spdk#2234]
Specifically，I would like to do memcpy between buffer and the address of file mmap. If successful, I will try to do it on PMEM next.

I have made some try. I mmap the file to the address spdk_malloc allocate, and set the flags of mmap with MAP_FIXED, and transmit the data from buffer to it. But it seems to fail.  The target address can receive the data but the data cannot flush to the file. The following is my key code.
  
```
    char* src = (char*)spdk_malloc(buffer_size , 8, NULL, SPDK_ENV_LCORE_ID_ANY, SPDK_MALLOC_DMA);
    char* dst = (char*)spdk_malloc(buffer_size , 8, NULL, SPDK_ENV_LCORE_ID_ANY, SPDK_MALLOC_DMA);
    
    std::string value;
    int v= 0;

   //fill the buffer
    for(int i = 0; i < buffer_size; i++){
        value.append(std::to_string((v+1)%10));
        v++;
    }
    std::memcpy(src, value.c_str(), buffer_size);
    bool copy_done = false;

    if ((fd = open(path.data(), O_CREAT|O_RDWR, 0666)) < 0) {
		perror("open");
		exit(1);
	}

    mmap(dst, buffer_size, PROT_READ | PROT_WRITE, MAP_FIXED | MAP_SHARED, fd, 0);

    spdk_ioat_submit_copy(
        chan,
        &copy_done,
        req_cb,
        dst,
        src,
        buffer_size);
    
    do
    {
        spdk_ioat_process_events(chan);
    } while (!copy_done);
```
How could I possibly achieve this function? Thank you very much!

## Context (Environment including OS version, SPDK version, etc.)
ubuntu1~16.04.12
SPDK v21.10

**Comment by benlwalker** [comment]
Unfortunately, this is not possible with IOAT.

In your code specifically, you cannot mmap over top of an allocation like that. Linux will simply mmap to a new address in that case, since the range you asked it to mmap into has already been allocated to a huge page by spdk_malloc earlier. What would have made sense to try would be to mmap the file and then call spdk_mem_register to prepare that memory for DMA by programming it's addresses into the IOMMU.

However, memory registration will fail in this case because Linux file-backed pages cannot support long term pins. Only anonymous memory can. The reason for this is page pins can prevent critical filesystem functions such as garbage collection. Without the ability to pin the pages, the virtual to physical/bus memory address mappings are volatile. IOAT requires physical/bus addresses to perform DMA, but without the guarantee that the virtual to physical/bus mappings are constant this will just result in corrupt data.

If you were to try to do this on PMEM-backed memory you'll hit a similar problem if you are using fsdax. It won't work there. If you use devdax then it will work - you can use IOAT to copy to/from PMEM with devdax - but IOAT doesn't understand CPU cache flushing requirements so writes are not guaranteed to be persistent when they complete.

In the near future, DMA engines will begin to support something called Shared Virtual Addressing or Shared Virtual Memory, which will allow them to do data transfers from virtual addresses without pinning (and handle faults and all the complexity that virtual memory introduces). That would allow you to accomplish what you're trying to do here - you'll just have to wait for an upcoming platform with a DMA engine such as Intel Data Streaming Accelerator (DSA) that can do this. DSA also understands how to flush/bypass CPU caches to make data fully persistent in PMEM.

**Comment by Lyhugo** [comment]
> Unfortunately, this is not possible with IOAT.
> 
> In your code specifically, you cannot mmap over top of an allocation like that. Linux will simply mmap to a new address in that case, since the range you asked it to mmap into has already been allocated to a huge page by spdk_malloc earlier. What would have made sense to try would be to mmap the file and then call spdk_mem_register to prepare that memory for DMA by programming it's addresses into the IOMMU.
> 
> However, memory registration will fail in this case because Linux file-backed pages cannot support long term pins. Only anonymous memory can. The reason for this is page pins can prevent critical filesystem functions such as garbage collection. Without the ability to pin the pages, the virtual to physical/bus memory address mappings are volatile. IOAT requires physical/bus addresses to perform DMA, but without the guarantee that the virtual to physical/bus mappings are constant this will just result in corrupt data.
> 
> If you were to try to do this on PMEM-backed memory you'll hit a similar problem if you are using fsdax. It won't work there. If you use devdax then it will work - you can use IOAT to copy to/from PMEM with devdax - but IOAT doesn't understand CPU cache flushing requirements so writes are not guaranteed to be persistent when they complete.
> 
> In the near future, DMA engines will begin to support something called Shared Virtual Addressing or Shared Virtual Memory, which will allow them to do data transfers from virtual addresses without pinning (and handle faults and all the complexity that virtual memory introduces). That would allow you to accomplish what you're trying to do here - you'll just have to wait for an upcoming platform with a DMA engine such as Intel Data Streaming Accelerator (DSA) that can do this. DSA also understands how to flush/bypass CPU caches to make data fully persistent in PMEM.

Thank you for your reply! Sorry for not responding in time. And I am looking forward to the new platform.

According to your reply, if I apply  IOAT to copy to/from PMEM with devdax, writes are not guaranteed to be persistent when they are complete. In my opinion, I think it doesn't matter. Here are my brief thoughts.

I will use PMDK to access PMEM and use `pmem_map_file ` in libpmem library to map the file to memory and then call `spdk_mem_register` to register the specified memory region. As you said, IOAT can transmit the data from a buffer to the virtual memory successfully. Later I can use the function in PMDK to assure persistence like
```
if (is_pmem)
	pmem_persist(dst, buffer_size);
else
	pmem_msync(dst, buffer_size);
```
I think it can work，but  I haven't put it into practice yet. What do you think is there any problem with it?

**Comment by benlwalker** [comment]
Yes - you can issue the sync operations from code and that will make it persistent. You can do that in the completion callback from IOAT. I don't know how well that will perform, but it will be functionally correct.

**Comment by Lyhugo** [comment]
> Yes - you can issue the sync operations from code and that will make it persistent. You can do that in the completion callback from IOAT. I don't know how well that will perform, but it will be functionally correct.

Thank you very much! I'll do some experiments later.

**Comment by Lyhugo** [comment]
I have successfully used spdk_ioat to do memcpy between buffer and the address of a regular file mmap.
In brief, I mmap a file with the flag of MAP_HUGETLB to use the 2MB-align page and then use `spdk_mem_register` to register the specified memory region.

Next, I would like to do some tests in pmem with a similar approach, but the results are different.
At first, I equipped ext4-DAX with 2MB hugepages by referring
> https://pmem.io/2018/05/15/using_persistent_memory_devices_with_the_linux_device_mapper.html#verifying-io-alignment

And then, I apply the `pmem_map_file` in libpmem to mmap pmem and register the address later.
But in the procedure of `spdk_mem_register`, I can not register successfully.

I have try a lot but it's not work. Is there any step that went wrong? What is a possible solution？
Thank you very much!
