### ISSUE TITLE
spdk perf with meta data 

### ISSUE THREAD

**Issue by eyuval** [spdk/spdk#2241]
I tested the following scenario:
sudo perf  -c 0x1 -M 50 -q 31 -o 131072 -w read -t 2 -r 'trtype:RDMA adrfam:IPv4 traddr:2.2.2.49 trsvcid:4420 subnqn:nqn.2020-02.com.xxxxxx:nvme:sn-9830A01BTVYE ' -e 'PRACT=1,PRCHK=GUARD'
What I see in wireshark is, that the read commands are split into 2 reads, one of 131040 and the other of 2080 bytes. This causes an overflow on the target if the queue there is only of size 32, since I chose the queue depth according to my size on the target. Basically the number of commands submitted is doubled by perf in this scenario, contrary to my expectation according to the -q option. Additionally it is not clear to me, why perf splits the read into 2 separate reads, since I expected a single read with a size of 133120 bytes and honoring the queue depth provided on the command line.

**Comment by jimharris** [comment]
Hi @eyuval,

My guess is that you are using the default options on the target side when creating the RDMA transport, which includes a max io size of 131072.  The nvme driver on the initiator/perf side, has to split the 133120 payload to accommodate that max io size.

perf tries to account for this - see register_ns().  It looks at things like max_io_xfer_size() and figures out what the actual queue depth is needed on the NVMe queue pair to satisfy the QD+size specified on the perf command line.  But it's not accounting for metadata, so that's a bug.

Can you try specifying something like "-I 133120" to nvmf_create_transport RPC and confirm that fixes this problem for now?  Meantime we'll need to fix up perf to account for the metadata in this case.

-Jim

**Comment by Comphix** [comment]
One slight update, the max_io_size parameter is "-i 133120" for nvmf_create_transport RPC. Also assign to @MengjinWu to have a try in our local environment.

**Comment by eyuval** [comment]
Many thanks for the explanation. I will adjust my max_io_size parameter.
