### ISSUE TITLE
rdma qpair in connecting state is added to connected list

### ISSUE THREAD

**Issue by dashan8020** [spdk/spdk#2252]
# Bug report
in function nvme_rdma_qpair_init(), if poll group is used, the qpair is added to connected list iwhen "nvme_rdma_poll_group_connect_qpair" is called, which is no correct.

## Expected Behavior
the qpair shiuld be added to connected list of poll group after it is real connected.

## Current Behavior
the qpair is added to connected list from disconnected list of poll group when it is in init stage

## Possible Solution
replace "nvme_poll_group_connect_qpair" with "nvme_rdma_poll_group_connect_qpair"

## Steps to Reproduce

1.
2.
3.
4.

**Comment by AlekseyMarchuk** [comment]
Hi @dashan8020 
Thank you for reporting this issue. Do you want to submit a patch to address it?

**Comment by dashan8020** [comment]
if necessary, I'd like to prepare the patch.
to master branch?

**Comment by AlekseyMarchuk** [comment]
Well, it is not necessary, only if you want to contribute to the project :)
Yes, please push a patch to master branch. Please refer to https://spdk.io/development/ if you haven't checked this doc yet

**Comment by changpe1** [comment]
> if necessary, I'd like to prepare the patch. to master branch?

@dashan8020 Yeah, you can refer to the development guide and submit your fix patch.

**Comment by dashan8020** [comment]
ok, I will prepare one, thx

**Comment by dashan8020** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/10438

**Comment by AlekseyMarchuk** [comment]
From discussion in gerrit review: we should add a qpair to the poll group connected_qpairs list since poll group also handles RDMA WRs batching of qpairs on the connected_qpairs list. I'm working on the async connect/disconnect and I'll try to address this problem

**Comment by dashan8020** [comment]
> From discussion in gerrit review: we should add a qpair to the poll group connected_qpairs list since poll group also handles RDMA WRs batching of qpairs on the connected_qpairs list. I'm working on the async connect/disconnect and I'll try to address this problem

hi, has the issue been fixed in release v22.1?

**Comment by AlekseyMarchuk** [comment]
@dashan8020 There are patches from @shuhei-matsumoto to enable async connect/disconnect. I haven't reviewed the whole series yet so I don't know it the issue is addressed. Will update you later.
BWT could you post here your problem which is caused by qpairs in connected_list?

**Comment by shuhei-matsumoto** [comment]
Hi @dashan8020

I am sorry that I did not notice this issue and your patch.
We need to insert the being connected (or connecting) qpair into any queue to poll it until it is actually connected.
We can add connecting_qpairs to poll_group but I think it is OK to use connected_qpairs for connecting qpairs.

We will make both qpair connection and qpair disconnection asynchronus.
For the being disconnected qpair, we use disconnected_qpair to poll it until it is actually disconnected.

As Alexey asked, what is your real problem caused by this implementation?

TCP transport uses connected_qpairs list for connecting qpairs. I will follow it.

Thanks for pinging me about this issue, @AlekseyMarchuk

**Comment by tomzawadzki** [comment]
@dashan8020 Please feel free to reopen then issue when you had a chance to test with latest SPDK and there are more details on the resulting problems.
