### ISSUE TITLE
[NVMeOverTCP] Pdu corruption when the data digest is enabled.

### ISSUE THREAD

**Issue by balamsg** [spdk/spdk#2279]
# Bug report
While running the DT tool on the ESX host , there is a PDU corruption happening when the data digest is enabled in NVMe Over TCP..
The spdk_accel_submit_crc32cv( ) submits the data to the accel module for the CRC calculation and the callback data_crc32_accel_done( ) is called when the calculation completes. Inside data_crc32_accel_done( ), there is a batch submission to the socket & if it fails, then all the requests in the "qpair->outstanding" is freed. And since this callback ( data_crc32_accel_done ) is already registered to the accel module for the outstanding PDU's , the data_crc32_accel_done( )  is called with freed pdu as the argument.

## Expected Behavior
Either the outstanding PDU's must be freed after the callback data_crc32_accel_done( ) is called OR the callback must be deregistered while freeing the PDU.

## Current Behavior
The spdk_accel_submit_crc32cv( ) submits the data to the accel module for the CRC calculation and the callback data_crc32_accel_done( ) is called when the calculation completes. Inside data_crc32_accel_done( ), there is a batch submission to the socket & if it fails, then all the requests in the "qpair->outstanding" is freed. And since this callback ( data_crc32_accel_done ) is already registered to the accel module for the outstanding PDU's , the data_crc32_accel_done( )  is called with freed pdu as the argument.

## Possible Solution
Either the outstanding PDU's must be freed after the callback data_crc32_accel_done( ) is called OR the callback must be deregistered while freeing the PDU.

## Steps to Reproduce
1. Enable the data digest 
2. Run normal IO's in the ESX host with the DT tool . 

## Context (Environment including OS version, SPDK version, etc.)
SPDK Version: 21.10
Environment: This issue is seen while running the DT tool in the windows VM of the ESX host.

**Comment by jimharris** [comment]
@peluse can you take a look at this?

**Comment by peluse** [comment]
@jimharris you bet! @balamsg is this the DT tool you are using? https://github.com/RobinTMiller/dt 
 I'll review the code first and try on Linux but if I need to do something with ESC I'll need your help :) Will et ya know...

**Comment by peluse** [comment]
@balamsg as I'm not quite as familiar with the TCP code here as I am the accel code, and since you can repro it sounds pretty easily, can you elaborate a bit more (using function names, line numbers, etc) on the following:

* what file/function are you referring to here: "there is a batch submission to the socket & if it fails, then all the requests in the "qpair->outstanding"?
* what file/function are you referring to here: "the data_crc32_accel_done( ) is called with freed pdu as the argument."?
* when you suggest "the outstanding PDU's must be freed after the callback data_crc32_accel_done( ) is called" do you mean before the call to _pdu_write_done() inside of data_crc32_accel_done()?
* I'm not sure what you mean with "OR the callback must be deregistered while freeing the PDU" as the callback function data_crc32_accel_done() isn't "registered" anywhere, it's passed in by the caller and simply used once when the accel operation completes.  Where are you seeing it being called upon freeing? (if that's what you're saying)

**Comment by balamsg** [comment]
Hi @peluse , this issue is due to the zcopy changes which was made by Mathew [ https://review.spdk.io/gerrit/c/spdk/spdk/+/9478/11/lib/nvmf/nvmf.c ] where the function spdk_nvmf_terminate_io( ) frees all the outstanding requests while the callback is still active for that requests.

**Comment by peluse** [comment]
Hi @balamsg thanks - that patch isn't yet merged, is that what you're using?

**Comment by balamsg** [comment]
Yes @peluse , i am using his patch and the function spdk_nvmf_terminate_io( ) which frees the outstanding requests is the root cause of this issue. 

spdk_nvmf_qpair_disconnect(struct spdk_nvmf_qpair *qpair, nvmf_qpair_disconnect_cb cb_fn, void *ctx) {
         ........
	/* Check for outstanding I/O */
	if (!TAILQ_EMPTY(&qpair->outstanding)) {
		qpair->state_cb = _nvmf_qpair_destroy;
		qpair->state_cb_arg = qpair_ctx;
		nvmf_qpair_free_aer(qpair);
		spdk_nvmf_terminate_io(qpair);  <<<<<<<<<<<<<<<<<<<  Frees the outstanding request.
		return 0;
	}
}

**Comment by peluse** [comment]
@balamsg OK thanks.  I don't mean to "pass the buck" but issues are for code on master, not pending patches.  You should put a -1 vote on the patch along with your comments and work with the patch submitter to assure that they are introducing bugs into master.  If I've understood this correctly and it makes sense to you, please close this issue and go update the patch as I mentioned.  Thanks!
