### ISSUE TITLE
DPDK lib code assumes userspace virtual addresses are 47-bit

### ISSUE THREAD

**Issue by stevecapperarm** [spdk/spdk#230]
Hello,
We have code sequences like the following in various parts of the lib code:
```
if ((uintptr_t)vaddr & ~MASK_128TB) {
        DEBUG_PRINT("invalid usermode virtual address %p\n", vaddr);
        return -EINVAL;
}
```
On both Arm (with 48-bit VA support) and upcoming x86 platforms (with 56-bit VA support) this check may spuriously fail.

I am happy to submit a fix for this, but thought I should raise a discussion first. Essentially, I would like to know:
 * Why are we performing the check in the first place? (isn't the best way to test for pointer validity to dereference it?)
 * Would a preferred fix for this involve:
    * removing the check entirely? or,
    * introducing a function along the lines of `is_kernel_address` (with Arm and x86 implementations)?

Cheers,
Steve

cc @tone-zhang, @JunHe77, @eugene-xie

**Comment by dverkamp-intel** [comment]
The intent is to catch addresses that won't be correctly stored in the virtual to physical mapping table, and the mask was originally based on the x86-64 Linux memory layout, which has 47 bits of valid addresses for user space. In a recent commit, we increased the size one bit to accommodate full 48-bit addresses for ARM64 platforms: 33e88d790f0c26e0e2abb0a80ed2cb209ba8b04a

However, increasing the size to allow full 56-bit virtual addresses for 5-level paging on x86-64 would be a bigger deal; we would probably need to add another level to the lookup table to avoid making the top level of the table very large.  I don't think this is currently necessary, since the 5-level paging support added to Linux apparently will not map anything in the high region unless the application explicitly hints support for it via mmap(): https://www.kernel.org/doc/Documentation/x86/x86_64/5level-paging.txt

**Comment by stevecapperarm** [comment]
Thanks Daniel,
I had managed to completely miss the internal table logic :-), many thanks for the commit reference too.

[ In future there will be 52-bit VA support on Arm, but it will most likely employ the same mmap hinting mechanism as found on x86. ]

Cheers,
Steve
