### ISSUE TITLE
setup.sh should consider nvme/virtio devices that are member disks of other block devices

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#2327]
setup.sh today will check if an NVMe SSD has an active mount point.  If it does, it will not try to unbind it from the kernel driver.

But we should also consider the case where an NVMe SSD is a member disk of another block device - i.e. an MD-RAID volume or ZFS pool.  Even if that MD-RAID volume or ZFS pool does not have an active mount point, we should not unbind it from the kernel driver.

To reproduce:

```
mdadm --create --verbose /dev/md0 --level=0 --raid-devices=1 /dev/nvme0n1 --force
lsblk -o NAME, SIZE, FSTYPE, TYPE, MOUNTPOINT
scripts/setup.sh
lsblk -o NAME, SIZE, FSTYPE, TYPE, MOUNTPOINT
```

**Comment by mikeBashStuff** [comment]
Here's a suggestion on how to handle potential holders when devices are not mounted: https://review.spdk.io/gerrit/c/spdk/spdk/+/11109. 

However, I am not sure how to really handle zfs. If all pools are unmounted, the only way to check if given device is part of it is to use dedicated tooling (so that introduces extra dependency on the `setup.sh`) like `zpool` since otherwise we would need to read the device directly to look for some zfs_member sigs or similar (`zpool` actually connects to `zfs-fuse` to get that info, at least under most linux distros). 

But this begs the question if we should do that for all potential filesystems? I mean, what's the difference if a target device has zfs installed on top (or is part of a zfs pool) or ext4? Technically speaking, in both cases the target device should be considered as being in-use.

So I think this enhancement is more about answering a question what devices `setup.sh` is allowed to touch in general. Currently, it's "every device, except when there are any active mount points associated with it". That means that even if the nvme drive is fully partitioned, and all the partitions have fs installed, but are not mounted, we would use it (same case if the target device is hold by some other like lvm, mdadm, etc.). In my mind, this issue essentially extends that to "use only these devices which are not associated with ANY configuration". Unless, the zfs stuff is meant to be the only exception from the currently used approach. :)

**Comment by mikeBashStuff** [comment]
Ok, I think this approach should cover most of the cases out there now (tested with md, dm, zfs pools, etc.): https://review.spdk.io/gerrit/c/spdk/spdk/+/11111 - with this, `setup.sh` should pick only devices which don't have any data on them.

**Comment by jimharris** [comment]
> Here's a suggestion on how to handle potential holders when devices are not mounted: https://review.spdk.io/gerrit/c/spdk/spdk/+/11109.

Thanks @mikeBashStuff!

> However, I am not sure how to really handle zfs. If all pools are unmounted, the only way to check if given device is part of it is to use dedicated tooling (so that introduces extra dependency on the `setup.sh`) like `zpool` since otherwise we would need to read the device directly to look for some zfs_member sigs or similar (`zpool` actually connects to `zfs-fuse` to get that info, at least under most linux distros).
> 
> But this begs the question if we should do that for all potential filesystems? I mean, what's the difference if a target device has zfs installed on top (or is part of a zfs pool) or ext4? Technically speaking, in both cases the target device should be considered as being in-use.

It's a great question.  I'm thinking of ZFS differently than other filesystems like ext4.  Someone may want to use the aio or io_uring bdev module with a ZFS volume or MD-RAID volume.  I guess I'm saying that an NVMe SSD device that is part of a ZFS pool is much more in-use than an NVMe SSD with an unmounted ext4 partition.

**Comment by recklessnl** [comment]
Out of interest, if one were to create io_uring bdevs with SPDK and feed them to ZFS, would that make ZFS use io_uring by definition? It's not technically supported as of yet on ZFS (at least, I can't find a source confirming it does) so I'm curious about if this potential interoperability between SPDK and ZFS actually works in practice.

I use ZFS and enjoy using it for its many features and reliability - but SPDK's performance is hard to beat.

**Comment by jimharris** [comment]
Hi @recklessnl,

I don't think this would work, if I'm understanding your question correctly.  An SPDK io_uring bdev is an SPDK block device that is backed by a kernel block device.  SPDK communicates with the kernel block device using the io_uring interface.

So to feed these SPDK userspace bdevs to ZFS, ZFS itself would need to be running in userspace.  I think there are people running ZFS in userspace out there, you may want to reach out to the ZFS community.  @nconnolly1 may also have some input on this, you can find Nick on Slack as well.

-Jim

**Comment by nconnolly1** [comment]
There is a version of ZFS that runs in user space in OpenEBS (https://github.com/openebs/cstor). It's intended for use as part of the OpenEBS project, but there is work ongoing to upstream the changes to OpenZFS (https://github.com/openzfs/zfs/pull/11766).

**Comment by tomzawadzki** [comment]
This issue can be closed once following patches are merged:
[scripts/setup: Skip devices which have any valid data present](https://review.spdk.io/gerrit/c/spdk/spdk/+/11111/3)
[scripts/setup: Check if target block device is hold by other devices](https://review.spdk.io/gerrit/c/spdk/spdk/+/11109/4)

**Comment by tomzawadzki** [comment]
Both patches are merged, the issue can be closed.
