### ISSUE TITLE
[nvmf_failover]  Timeout while waiting for response after nvmf_subsystem_remove_listener 

### ISSUE THREAD

**Issue by KKaras169169** [spdk/spdk#2335]
# CI Intermittent Failure

During /nvmf-tcp-uring-vg-autotest, nvmf_failover aborted with timeout after the 

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_68791.html

## Execution failed at

00:08:03.498   08:55:59	-- host/failover.sh@38 -- # /home/vagrant/spdk_repo/spdk/scripts/rpc.py -s /var/tmp/bdevperf.sock bdev_nvme_attach_controller -b NVMe0 -t tcp -a 10.0.0.2 -s 4420 -f ipv4 -n nqn.2016-06.io.spdk:cnode1
00:08:03.758  NVMe0n1
00:08:03.758   08:55:59	-- host/failover.sh@39 -- # /home/vagrant/spdk_repo/spdk/scripts/rpc.py -s /var/tmp/bdevperf.sock bdev_nvme_attach_controller -b NVMe0 -t tcp -a 10.0.0.2 -s 4421 -f ipv4 -n nqn.2016-06.io.spdk:cnode1
00:08:04.330  
00:08:04.330   08:56:00	-- host/failover.sh@41 -- # /home/vagrant/spdk_repo/spdk/test/bdev/bdevperf/bdevperf.py -s /var/tmp/bdevperf.sock perform_tests
00:08:04.330   08:56:00	-- host/failover.sh@42 -- # rpc_pid=25352
00:08:04.330   08:56:00	-- host/failover.sh@44 -- # sleep 1
00:08:05.271   08:56:01	-- host/failover.sh@46 -- # /home/vagrant/spdk_repo/spdk/scripts/rpc.py nvmf_subsystem_remove_listener nqn.2016-06.io.spdk:cnode1 -t tcp -a 10.0.0.2 -s 4420
00:08:05.532   08:56:01	-- host/failover.sh@48 -- # sleep 3
00:08:08.829   08:56:04	-- host/failover.sh@50 -- # /home/vagrant/spdk_repo/spdk/scripts/rpc.py -s /var/tmp/bdevperf.sock bdev_nvme_attach_controller -b NVMe0 -t tcp -a 10.0.0.2 -s 4422 -f ipv4 -n nqn.2016-06.io.spdk:cnode1
00:08:08.829  
00:08:08.829   08:56:04	-- host/failover.sh@51 -- # /home/vagrant/spdk_repo/spdk/scripts/rpc.py nvmf_subsystem_remove_listener nqn.2016-06.io.spdk:cnode1 -t tcp -a 10.0.0.2 -s 4421
00:08:09.089   08:56:05	-- host/failover.sh@53 -- # sleep 3
00:08:12.387   08:56:08	-- host/failover.sh@56 -- # /home/vagrant/spdk_repo/spdk/scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t tcp -a 10.0.0.2 -s 4420
00:08:12.387  [2022-01-20 08:56:08.377835] tcp.c: 819:nvmf_tcp_listen: *NOTICE*: *** NVMe/TCP Target Listening on 10.0.0.2 port 4420 ***
00:08:12.387   08:56:08	-- host/failover.sh@58 -- # sleep 1
00:08:13.336   08:56:09	-- host/failover.sh@60 -- # /home/vagrant/spdk_repo/spdk/scripts/rpc.py nvmf_subsystem_remove_listener nqn.2016-06.io.spdk:cnode1 -t tcp -a 10.0.0.2 -s 4422
00:08:13.624   08:56:09	-- host/failover.sh@62 -- # wait 25352
00:09:09.888  Timeout while waiting for response:
00:09:09.888  
00:09:09.888  
00:09:09.888    08:57:00	-- host/failover.sh@62 -- # trap - ERR
00:09:09.888    08:57:00	-- host/failover.sh@62 -- # print_backtrace
00:09:09.888    08:57:00	-- common/autotest_common.sh@991 -- # [[ ehxBET =~ e ]]
00:09:09.888    08:57:00	-- common/autotest_common.sh@993 -- # args=('--transport=tcp')
00:09:09.888    08:57:00	-- common/autotest_common.sh@993 -- # local args
00:09:09.888    08:57:00	-- common/autotest_common.sh@995 -- # xtrace_disable
00:09:09.888    08:57:00	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:09:09.888    08:57:00	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:09:09.888    08:57:00	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:09:09.888    08:57:00	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:09:09.888    08:57:00	-- common/autotest_common.sh@19 -- # set +x
00:09:09.888  ========== Backtrace start: ==========
00:09:09.888  
00:09:09.888  in test/nvmf/host/failover.sh:62 -> main(["--transport=tcp"])
00:09:09.888       ...
00:09:09.888     57  	
00:09:09.888     58  	sleep 1
00:09:09.888     59  	
00:09:09.888     60  	$rpc_py nvmf_subsystem_remove_listener nqn.2016-06.io.spdk:cnode1 -t $TEST_TRANSPORT -a $NVMF_FIRST_TARGET_IP -s $NVMF_THIRD_PORT
00:09:09.888     61  	
00:09:09.889  => 62  	wait $rpc_pid
00:09:09.889     63  	
00:09:09.889     64  	killprocess $bdevperf_pid
00:09:09.889     65  	
00:09:09.889     66  	cat $testdir/try.txt
00:09:09.889     67  	# if this test fails it means we didn't fail over to the second
00:09:09.889       ...
00:09:09.889  
00:09:09.889  ========== Backtrace end ==========

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_68791.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_68838.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_69025.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_69183.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_69303.html

**Comment by AlekseyMarchuk** [comment]
I'll try to reproduce this issue locally. It seems that it affects RDMA transport too

**Comment by shuhei-matsumoto** [comment]
Hi @AlekseyMarchuk 

Due to my bugs, I could reproduce this issue almost always for the RDMA transport.
This behavior occurs when the bdevperf hung up and could not know the end of its runtime.
rpc_pid may be better to rename as bdevperf_run_id.

In my case, it looks that we did not get RDMA_CM_EVENT_ESTABLISHED when this issue occurred.

We can update the test script to investigate this issue a little more easily.

For TCP transport, this issue is very rare and for RDMA transport, I see this issue only if I added more multipath patches.

Please shift your effort to other important work for now.

**Comment by shuhei-matsumoto** [comment]
Hi @AlekseyMarchuk 

If I reverted the patch https://github.com/spdk/spdk/commit/e0415f1720a094894971ac0ab930c14299274aac#diff-f6caac1518ffe3529d1937a64beac4cd440cc815aa1cca852561fe37844597ac, I don't reproduce this issue even if I add multipath patches for asynchronous connect/disconnect.

And ctrl + c worked.

So it looks that I/O retry + non-multipath failover + async disconnect occupied CPU and the run timer was not expired.

I will continue my investigation.

**Comment by shuhei-matsumoto** [comment]
@AlekseyMarchuk @KKaras169169 and all,

I am not certain if this applies to the TCP transport yet, but I found a root cause of this failure for the RDMA transport.

For some reason, the NVMe bdev module got ANA error even if the target did not enable ANA reporting, and marked the namespace as pending to read ANA log page. However, the NVMe bdev module had no way to read ANA log page. So the pending flag was left to be true. So pending I/Os were not submitted because they waited until ANA log page was read.

 I found not only the fix but also a few bugs. So I will create a patch series for this issue.

For TCP transport, the probability is quite low and for RDMA transport, I have seen this issue only if I add async connect/disconnect patches.

I want to add patches and keep monitoring this issue.

-Shuhei

**Comment by shuhei-matsumoto** [comment]
I will also investigate why we got ANA error even if the target did not enable ANA reporting. I do not know why that happened yet.

**Comment by shuhei-matsumoto** [comment]
I pushed three small patches starting from https://review.spdk.io/gerrit/c/spdk/spdk/+/11399 on gerrit.
Please review these when you can.

**Comment by shuhei-matsumoto** [comment]
Finally I found the root cause.
The fix is done by https://review.spdk.io/gerrit/c/spdk/spdk/+/11402/1

nvmf_ctrlr_get_ana_state() returned inaccessible if ctrlr->listener was NULL. However we did not check if ctrlr->subsys->flags.ana_reporting is true. The target unintentionally sent ANA error and the initiator received unexpected ANA error.
The initiator could not process the unexpected ANA error and continued I/O pending infinitely.

I added fixes both for initiator and target.

This bug is not transport specific.
