### ISSUE TITLE
nvme: nvme_ctrlr_destruct: fix free order

### ISSUE THREAD

**Issue by ehudmarvell** [spdk/spdk#240]
Hi,

I tried to push the fix as commit but had some issues

fixing nvme_ctrlr_destruct order because nvme_transport_ctrlr_destruct may use a destroyed mutex
    
 nvme_ctrlr_destruct() free "ctrlr_lock" and after that call
 nvme_transport_ctrlr_destruct()->nvme_pcie_ctrlr_destruct()(with pci)->
 nvme_ctrlr_proc_get_devhandle()->nvme_robust_mutex_lock(&ctrlr->ctrlr_lock);

before:

> nvme_ctrlr_destruct(struct spdk_nvme_ctrlr *ctrlr)
> {	
> ...
> 	pthread_mutex_destroy(&ctrlr->ctrlr_lock);
> 	nvme_transport_ctrlr_destruct(ctrlr);
> 

after

> nvme_ctrlr_destruct(struct spdk_nvme_ctrlr *ctrlr)
> {	
> ...
> 	nvme_transport_ctrlr_destruct(ctrlr);
> 	pthread_mutex_destroy(&ctrlr->ctrlr_lock);
>

**Comment by dverkamp-intel** [comment]
We can't quite just reverse the order of these statements, since nvme_transport_ctrlr_destruct() is responsible for freeing the memory for ctrlr; this would cause the ctrlr->ctrlr_lock access to be a use-after-free.

The cleanest fix might be to add a new function, something like nvme_ctrlr_destruct_finish(), that the transport needs to call after completing its cleanup but before freeing the ctrlr memory.  This function would simply contain the pthread_mutex_destroy() call currently.

Could you elaborate on what problems you had pushing this as a review, so we can try to help resolve them?

**Comment by ehudmarvell** [comment]
Thank you for your quick response

I upload the patch according to your comments:
https://review.gerrithub.io/#/c/399605/

**Comment by dverkamp-intel** [comment]
This has been merged as commit c83cd9375bce67599280235b1f06fb682f27e580 - thanks for the report and the patch!
