### ISSUE TITLE
Vhost(reactor) takes too much memory!

### ISSUE THREAD

**Issue by zbhhbzzbh** [spdk/spdk#2427]
# Bug report

I'm trying to deploy vhost-user for QEMU, and after I launch vhost, the reactor takes too much memory(128GB).

## Expected Behavior

I expect the memory usage of reactor should be much less than 128GB
## Current Behavior

After the command : "build/bin/vhost -S /var/tmp -m 0x1
the reactor_0 takes 128GB virtual memory. 

## Possible Solution

My suspicion is that there is some bug at memory usage of reactor/vhost should be fixed.
## Steps to Reproduce

1. sudo HUGEMEM=2048 scripts/setup.sh 
2.sudo build/bin/vhost -S /var/tmp -m 0x1
3. top.4. 
4. check the virtual memory usage of reactor_0
## Context (Environment including OS version, SPDK version, etc.)

OS: fedora33
SPDK: 22.05

I'm not an expert in SPDK , please help me with more effective ways to produce more information to solve this.

**Comment by tomzawadzki** [comment]
The specific memory you are describing is `virtual memory` [`VIRT` in `top`], rather than `physical memory` [`RES` in `top`]. In general terms, it only describes maximum amount of memory that a process could use. Is there any issue that you encounter with that amount of `virtual memory` ?

You can read more about this behavior in DPDK docs https://doc.dpdk.org/guides/prog_guide/env_abstraction_layer.html#memory-mapping-discovery-and-memory-reservation, specifically `3.1.4.5. Maximum Amount of Memory` section.

**Comment by zbhhbzzbh** [comment]
It just looks odd to me that a reactor should "occupy" so much virtual memory.
But indeed my test was able to go through.



---- 回复的原邮件 ----
| 发件人 | Tomasz ***@***.***> |
| 日期 | 2022年03月15日 20:46 |
| 收件人 | ***@***.***> |
| 抄送至 | Bing ***@***.******@***.***> |
| 主题 | Re: [spdk/spdk] Vhost(reactor) takes too much memory! (Issue #2427) |

The specific memory you are describing is virtual memory [VIRT in top], rather than physical memory [RES in top]. In general terms, it only describes maximum amount of memory that a process could use. Is there any issue that you encounter with that amount of virtual memory ?

You can read more about this behavior in DPDK docs https://doc.dpdk.org/guides/prog_guide/env_abstraction_layer.html#memory-mapping-discovery-and-memory-reservation, specifically 3.1.4.5. Maximum Amount of Memory section.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
