### ISSUE TITLE
[nvme_multi_secondary] EAL: Driver cannot detach the device

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#2456]
# CI Intermittent Failure

00:03:59.637  ************************************
00:03:59.637  START TEST nvme_multi_secondary
00:03:59.637  ************************************
00:03:59.637   04:14:19	-- common/autotest_common.sh@963 -- # xtrace_enable
00:03:59.637   04:14:19	-- common/autotest_common.sh@964 -- # nvme_multi_secondary
00:03:59.637   04:14:19	-- nvme/nvme.sh@47 -- # pid0=287375
00:03:59.637   04:14:19	-- nvme/nvme.sh@46 -- # /var/jenkins/workspace/nvme-phy-autotest/spdk/build/examples/perf -i 0 -q 16 -w read -o 4096 -t 5 -c 0x1
00:03:59.637   04:14:19	-- nvme/nvme.sh@49 -- # pid1=287376
00:03:59.637   04:14:19	-- nvme/nvme.sh@50 -- # /var/jenkins/workspace/nvme-phy-autotest/spdk/build/examples/perf -i 0 -q 16 -w read -o 4096 -t 3 -c 0x4
00:03:59.637   04:14:19	-- nvme/nvme.sh@48 -- # /var/jenkins/workspace/nvme-phy-autotest/spdk/build/examples/perf -i 0 -q 16 -w read -o 4096 -t 3 -c 0x2
00:04:02.929  EAL: Driver cannot detach the device (0000:65:00.0)
00:04:02.929  EAL: Driver cannot detach the device (0000:65:00.0)
00:04:02.929  EAL: Failed to hotplug remove device on secondary
00:04:02.929  EAL: Failed to hotplug remove device
00:04:02.929  Initializing NVMe Controllers
00:04:02.929  Attached to NVMe Controller at 0000:65:00.0 [8086:0a54]
00:04:02.929  Associating PCIE (0000:65:00.0) NSID 1 with lcore 1
00:04:02.929  Initialization complete. Launching workers.

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_75027.html

## Execution failed at

00:04:13.409  ========== Backtrace start: ==========
00:04:13.409  
00:04:13.409  in test/nvme/nvme.sh:61 -> nvme_multi_secondary([])
00:04:13.409       ...
00:04:13.409     56  		pid0=$!
00:04:13.409     57  		$SPDK_EXAMPLE_DIR/perf -i 0 -q 16 -w read -o 4096 -t 3 -c 0x2 &
00:04:13.409     58  		pid1=$!
00:04:13.409     59  		$SPDK_EXAMPLE_DIR/perf -i 0 -q 16 -w read -o 4096 -t 5 -c 0x4
00:04:13.409     60  		wait $pid0
00:04:13.409  => 61  		wait $pid1
00:04:13.409     62  	}
00:04:13.409     63  	
00:04:13.409     64  	if [ $(uname) = Linux ]; then
00:04:13.409     65  		# check that our setup.sh script does not bind NVMe devices to uio/vfio if they
00:04:13.409     66  		# have an active mountpoint
00:04:13.409       ...
00:04:13.409  in /var/jenkins/workspace/nvme-phy-autotest/spdk/test/common/autotest_common.sh:964 -> run_test(["nvme_multi_secondary"],["nvme_multi_secondary"])
00:04:13.409       ...
00:04:13.409     959 		timing_enter $test_name
00:04:13.409     960 		echo "************************************"
00:04:13.409     961 		echo "START TEST $test_name"
00:04:13.409     962 		echo "************************************"
00:04:13.409     963 		xtrace_restore
00:04:13.409  => 964 		time "$@"
00:04:13.409     965 		xtrace_disable
00:04:13.409     966 		echo "************************************"
00:04:13.409     967 		echo "END TEST $test_name"
00:04:13.409     968 		echo "************************************"
00:04:13.409     969 		timing_exit $test_name
00:04:13.409       ...
00:04:13.410  in test/nvme/nvme.sh:140 -> main([])
00:04:13.410       ...
00:04:13.410     135 	run_test "nvme_overhead" $testdir/overhead/overhead -s 4096 -t 1 -H -i 0
00:04:13.410     136 	run_test "nvme_arbitration" $SPDK_EXAMPLE_DIR/arbitration -t 3 -i 0
00:04:13.410     137 	
00:04:13.410     138 	if [ $(uname) != "FreeBSD" ]; then
00:04:13.410     139 		run_test "nvme_startup" $testdir/startup/startup -t 1000000
00:04:13.410  => 140 		run_test "nvme_multi_secondary" nvme_multi_secondary
00:04:13.410     141 		trap - SIGINT SIGTERM EXIT
00:04:13.410     142 		kill_stub
00:04:13.410     143 	fi
00:04:13.410     144 	
00:04:13.410     145 	if [[ $CONFIG_FIO_PLUGIN == y ]]; then
00:04:13.410       ...
00:04:13.410  
00:04:13.410  ========== Backtrace end ==========

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_75027.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_75033.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_75029.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_75087.html

**Comment by changpe1** [comment]
00:04:04.839   04:14:24	-- nvme/nvme.sh@52 -- # wait 287376
00:04:04.839   04:14:24	-- nvme/nvme.sh@56 -- # pid0=287393
00:04:04.839   04:14:24	-- nvme/nvme.sh@55 -- # /var/jenkins/workspace/nvme-phy-autotest/spdk/build/examples/perf -i 0 -q 16 -w read -o 4096 -t 3 -c 0x1
00:04:04.839   04:14:24	-- nvme/nvme.sh@58 -- # pid1=287394
00:04:04.839   04:14:24	-- nvme/nvme.sh@59 -- # /var/jenkins/workspace/nvme-phy-autotest/spdk/build/examples/perf -i 0 -q 16 -w read -o 4096 -t 5 -c 0x4
00:04:04.839   04:14:24	-- nvme/nvme.sh@57 -- # /var/jenkins/workspace/nvme-phy-autotest/spdk/build/examples/perf -i 0 -q 16 -w read -o 4096 -t 3 -c 0x2
00:04:08.132  EAL: Driver cannot detach the device (0000:65:00.0)
00:04:08.132  EAL: Driver cannot detach the device (0000:65:00.0)
00:04:08.132  EAL: Failed to hotplug remove device on secondary
00:04:08.132  EAL: Failed to hotplug remove device
00:04:08.132  EAL: failed to send to (/var/run/dpdk/spdk0/mp_socket_287393_7f33264097fe) due to No such file or directory
00:04:08.132  EAL: Fail to send request /var/run/dpdk/spdk0/mp_socket_287393_7f33264097fe:eal_dev_mp_request
00:04:08.132  EAL: rte_mp_request_sync failed
00:04:08.132  EAL: Failed to send hotplug request to secondary
00:04:08.132  Initializing NVMe Controllers
00:04:08.132  Attached to NVMe Controller at 0000:65:00.0 [8086:0a54]
00:04:08.132  Associating PCIE (0000:65:00.0) NSID 1 with lcore 0
00:04:08.132  Initialization complete. Launching workers.
00:04:08.132  ========================================================
00:04:08.132                                                                             Latency(us)
00:04:08.132  Device Information                     :       IOPS      MiB/s    Average        min        max
00:04:08.132  PCIE (0000:65:00.0) NSID 1 from core  0:   82019.64     320.39     194.77      29.20    3019.00
00:04:08.132  ========================================================
00:04:08.132  Total                                  :   82019.64     320.39     194.77      29.20    3019.00
00:04:08.132  
00:04:08.132  EAL: Failed to hotplug remove device
00:04:08.132  perf: pci.c:539: pci_device_fini: Assertion `!dev->internal.removed' failed.
00:04:13.409  EAL: Fail to recv reply for request /var/run/dpdk/spdk0/mp_socket_287394_7f33267a39b4:eal_dev_mp_request
00:04:13.409  EAL: rte_mp_request_sync failed
00:04:13.409  EAL: Failed to send hotplug request to secondary
00:04:13.409  EAL: failed to send to (/var/run/dpdk/spdk0/mp_socket_287394_7f33267a39b4) due to No such file or directory
00:04:13.409  EAL: failed to send response to secondary
00:04:13.409  EAL: failed to send response to secondary
00:04:13.409  EAL: Driver cannot detach the device (0000:65:00.0)
00:04:13.409  EAL: Failed to hotplug remove device on primary
00:04:13.409  EAL: Failed to hotplug remove device

**Comment by jimharris** [comment]
This looks related to both #2320 and #2351.

#2320 was closed after merging a small fix to the test script causing the failure in this issue.
#2351 showed this exact same failure, but was closed when it did not reproduce over a couple of weeks.

Note that all 4 failures listed in this issue happened on SM11.  It's not clear whether that is relevant yet or not.  Unfortunately the logs from #2351 have already been culled - I cannot access them to see what systems they occurred on.

**Comment by tomzawadzki** [comment]
[Bug scrub] @xjjx Can you please run patch https://review.spdk.io/gerrit/c/spdk/spdk/+/12261 multiple times through the CI using specifically the SM11 node ?

**Comment by xjjx** [comment]
Test results were sent to @jimharris in separate email.
4 of 6 runs passed
2 of 6 runs failed

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_75968.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_75974.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_76371.html

**Comment by jimharris** [comment]
The assert that is failing should be removed.  See commit message on https://review.spdk.io/gerrit/c/spdk/spdk/+/12454:

```
    When using the SPDK nvme driver in multi-process mode,
    and multiple processes detach from their devices
    (i.e. at application exit) very close to each other,
    there are cases where a process can have started its
    own detach, and then get two remove notifications - one
    from its own detach, and another from another process'
    detach.

    So we need to remove the assertion in pci_device_fini(),
    if the removed flag has already been set.
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_76468.html
