### ISSUE TITLE
spdk_subsystem_fini() takes very long time to complete

### ISSUE THREAD

**Issue by NiuYawei** [spdk/spdk#2502]
# Bug report

We recently observed that on some installation, spdk_subsystem_fini() takes more than 100 seconds to complete, it usually takes only few seconds on other installations.

## Expected Behavior

I was expecting that few seconds are enough for spdk_subsystem_fini() to complete.

## Current Behavior

spdk_subsystem_fini() takes more than 100 seconds on some installations (with VMD enabled), not sure if that's expected behavior.

## Steps to Reproduce

Our app (DAOS io engine) just simply calls spdk_subsystem_init_from_json_config() then open the blobstore on SSD on initialization; On app exiting, blobstore is closed and spdk_subsystem_fini() is called, no blobs were involved (no blobs created on the blobstore).

## Context (Environment including OS version, SPDK version, etc.)

OS:     SLES15 SP3
SPDK: v21.07
VMD:  Enabled
Device Details: Model=SAMSUNG MZWLR15THALA-00007 FW Revision=MPK92B5Q

**Comment by jimharris** [comment]
Hi @NiuYawei,

The fini code path in the bdev nvme module synchronously detached controllers one at a time in the v21.07 release (using spdk_nvme_detach() API).  Detach process issues a shutdown notification to the controller, and response time from the SSD on the shutdown can vary widely between different models of SSDs.  So this could explain why some systems may take longer for subsystem_fini then others.

v21.10 switched this code path to use the spdk_nvme_detach_async() API, which enables many SSDs to be detached in parallel.

Note that issue #2423 (submitted by @sydneyvanda and fixed by @ravalsam) is directly related to this.  In #2423, there were long delays when unbinding all of the SSDs from the kernel nvme driver.  If they are unbound one at a time, the kernel driver also issues the shutdown notification.

-Jim

**Comment by NiuYawei** [comment]
Thanks for the info, Jim. We've scheduled a SPDK upgrade for later version, and I suppose this problem will be largely alleviated then.

**Comment by NiuYawei** [comment]
The problem is addressed since v21.10 by detaching all devices in parallel, let's close this one.
