### ISSUE TITLE
Not persistent device UUIDs

### ISSUE THREAD

**Issue by rafalste** [spdk/spdk#2516]
Currently there is no way to get a unique and persistent device identifier, that could be used across SPDK app restarts. Even the documentation of spdk_bdev_get_uuid() says that "All bdevs will have a UUID, but not all UUIDs will be persistent across application runs." This applies not only to virtual bdevs but also to some bdevs created directly from hardware device, e.g. with bdev_nvme_attach_controller call.

Since now devices are recognized only by a user given names, this creates potential data corruption issue while using OCF, if user accidentally use the same name for a different core device that is a part of OCF cache setup.
This can occur in following scenario:
1. add two devices for OCF cache and core - Dev1, Dev2
2. create OCF cache using those two devices (now Dev1 contains OCF metadata - it is used as cache)
3. restart SPDK application
4. add Dev1 device with OCF metadata
5. add different device (with same size as previous Dev2) and name it Dev2
6. SPDK automatically reads metadata on Dev1 and - as soon as Dev2 appears - loads OCF cache setup with those devices (no need to issue additional call to load OCF cache - it is loaded automatically when devices appear)

We could mitigate this problem by using some unique and persistent identifiers stored in cache device metadata, thus using only devices that were actually a part of that setup before.
One can say that this is just user's responsibility to take care of device naming, but it's never a bad idea to give the user a bigger margin for errors, especially when it comes to data corruption, and when this data corruption can occur in such early and unexpected stage - when devices appears in SPDK, without the need to issue any additional call.

So, my question is if there is a way to implement a UUID that will always be persistent? This OCF example is just one motivation to have such functionality, but I believe this will be beneficial also in other scenarios.

**Comment by benlwalker** [comment]
`
So, my question is if there is a way to implement a UUID that will always be persistent? This OCF example is just one motivation to have such functionality, but I believe this will be beneficial also in other scenarios.
`

There is no good way to implement persistent UUIDs that I see.

**Comment by jimharris** [comment]
> > So, my question is if there is a way to implement a UUID that will always be persistent? This OCF example is just one motivation to have such functionality, but I believe this will be beneficial also in other scenarios.
> 
> There is no good way to implement persistent UUIDs that I see.

Some bdevs do have persistent UUIDs already.  NVMe namespaces can report UUIDs which are persistent.  Logical volumes also report UUIDs which are persistent.

So we can recommend that users use UUIDs and not the 'simple names' when specifying the cache and core devices.

This does lead to problems if an NVMe namespace does not report a UUID (since they are optional).  I don't have a good read though on the prevalence of NVMe devices that don't support UUIDs.

But I agree that if the bdev type doesn't natively support persistent UUIDs, I don't see a good way to add that kind of persistence.

**Comment by jimharris** [comment]
> > > So, my question is if there is a way to implement a UUID that will always be persistent? This OCF example is just one motivation to have such functionality, but I believe this will be beneficial also in other scenarios.
> > 
> > 
> > There is no good way to implement persistent UUIDs that I see.
> 
> Some bdevs do have persistent UUIDs already. NVMe namespaces can report UUIDs which are persistent. Logical volumes also report UUIDs which are persistent.
> 
> So we can recommend that users use UUIDs and not the 'simple names' when specifying the cache and core devices.
> 
> This does lead to problems if an NVMe namespace does not report a UUID (since they are optional). I don't have a good read though on the prevalence of NVMe devices that don't support UUIDs.
> 
> But I agree that if the bdev type doesn't natively support persistent UUIDs, I don't see a good way to add that kind of persistence.

Currently bdev_register() generates a UUID if the bdev module did not specify one (i.e. UUID is all zeroes).  I think we need to revisit that.  Upper layers (including a virtual bdev module like OCF) need to know if a bdev's uuid is persistent or not.

**Comment by tomzawadzki** [comment]
Bug scrub: Users of the bdev API expect the UUID to always be the same for the exact same bdev, which cannot be true for persistent bdevs that do not generate one. Generation of the UUID on bdev layer is part of the problem, since the expectations are then the same for persistent and non-persistent bdevs. The solution proposed during the bug scrub is to:
1) Remove the generation of UUID for bdevs that do not provide one. Then it is clear whether that field can be depended upon.
2) Add option to `bdev_nvme_set_options` that would allow to generate a unique identifier for NVMe devices that do not have one. It could be based upon the hash of a serial number of the device.

**Comment by rafalste** [comment]
Thank you all for taking a look at this problem!
I think that with those outcomes we can improve OCF adapter to be more reliable with the autoloading mechanism.

**Comment by KKaras169169** [comment]
Series of two patches to introduce this enhancement: https://review.spdk.io/gerrit/c/spdk/spdk/+/15150
https://review.spdk.io/gerrit/c/spdk/spdk/+/15151

**Comment by KKaras169169** [comment]
The discussion about this topic is being continued in #2788 and since the original goal of implementing the persistent UUIDs mechanism has been achieved, I'm closing this issue.
