### ISSUE TITLE
build/examples/identify example outputs an error

### ISSUE THREAD

**Issue by ft-ksc** [spdk/spdk#2536]
# Bug report

I receive the following output when I run the command "sudo build/examples/identify"

> EAL: No available 1048576 kB hugepages reported
> TELEMETRY: No legacy callbacks, legacy socket not created
> No NVMe controllers found.

## Context (Environment including OS version, SPDK version, etc.)

Ubuntu 21.04
AMD Ryzen Threadripper PRO 3995WX 64-Cores
Samsung SSD 980 PRO 1TB

**Comment by Comphix** [comment]
Have you run the ./scripts/setup.sh and please also output the ./scripts/setup.sh status here

Also please follow the template to include as much information as possible.

**Comment by Comphix** [comment]
From above log, it means this SSD has created partitions on it so that SPDK will not unbind the kernel driver from it as it is expected there is other usage on this SSD.

If these partitions and data are not needed on this SSD, you may try to delete them and try again.

Or you may use another SSD for the testing.
