### ISSUE TITLE
spdk/vhost: vhost-block readonly flag not visible in qemu branch spdk-2.12-pre

### ISSUE THREAD

**Issue by nedved1** [spdk/spdk#254]
In qemu spdk-2.12-pre branch, vhost block controllers with readonly option enabled are not visible as readonly disks. This is causing /test/vhost/readonly/readonly.sh to fail:
[test_log.txt](https://github.com/spdk/spdk/files/1781554/test_log.txt)

The "RO" flag is not visible in VM
```
root@ubuntu:~# lsblk
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
fd0      2:0    1     4K  0 disk
sda      8:0    0   5.5G  0 disk
`-sda1   8:1    0   5.5G  0 part /
vda    253:0    0 745.2G  0 disk
`-vda1 253:1    0 745.2G  0 part
```

**Comment by changpe1** [comment]
Thanks for submitting this issue, @nedved, I will submit a patch to fix this. The main reason is that when starting the QEMU, users must append config-ro=true for Read Only disks.

**Comment by wanqunintel** [comment]
@ChenWang01 will you verify it with the latest code? thanks

**Comment by ChenWang01** [comment]
I have verified this issue with latest code, and  it can't be reproduced.
It's fixed by https://review.gerrithub.io/#/c/408266/ patch.
And it can't be reproduced in SPDK test pool nightly cases, too. We can check the details using following link.
https://ci.spdk.io/spdk/builds/review/17b362422b7db5fa77ed709c9606538b2d4ba731.1526993009/fedora-08/build.log
So, we can close this issue.

Thanks,
Chen
