### ISSUE TITLE
spdk_nvmf_qpair_disconnect segfault

### ISSUE THREAD

**Issue by abbycin** [spdk/spdk#2560]
# Bug report

![图片](https://user-images.githubusercontent.com/6814167/174582390-851526f4-9844-4fad-84ad-5469a3b7b6e0.png)

it seems use after free, the `qpair->group` is invalid

![图片](https://user-images.githubusercontent.com/6814167/174582539-4abf45ae-3dd2-49eb-9e28-d6efd01289a3.png)

## Steps to Reproduce
it's hard to reproduce, in our envrionment, it happens only twice in four months

## Context (Environment including OS version, SPDK version, etc.)

OS: Ubuntu 20.04.1 docker container
SPDK: 21.01

**Comment by yidong0635** [comment]
It seems that the codes have been changed a lot,  Could you check the latest SPDK?

**Comment by changpe1** [comment]
@abbycin can you provide more information when the issue happen? e.g: ctrlr information.

**Comment by changpe1** [comment]
The `qpair->state` 33022 is weird to me, we don't have such state definition in SPDK.

**Comment by abbycin** [comment]
[2300.txt](https://github.com/spdk/spdk/files/8966233/2300.txt)

@yidong0635  @changpe1 
the text is gdb log from another core, I'm not sure it's useful or not

**Comment by yidong0635** [comment]
@abbycin From the log we can see:
you are using a newer target with gdb opening an old coredump file, that's why it reports  can't find the source file.
and you can tracing this with gdb always on:
1. gdb --args ./build/bin/nvmf_tgt XXXX
2. handle SIGINT nostop pass

I'm afraid the issue was fixed  already.
@changpe1 What's your opinion?
