### ISSUE TITLE
Why spdk_dma_malloc spend 10ms

### ISSUE THREAD

**Issue by zp841126** [spdk/spdk#2645]
# Bug report

I using spdk_dma_malloc to allocate 8M buffer, but sometimes, it will spend 10ms, is it by design?

## Steps to Reproduce

1.
2.
3.
4.

**Comment by AlekseyMarchuk** [comment]
Hi @zp841126 

The `spdk_dma_malloc` API is a wrapper over DPDK `rte_malloc_socket` function, so any its execution time depends on DPDK implementation only.
From my experience, even 4KiB allocation may take a few milliseconds, it depends on the number of existing allocations. Internal DPDK implementation has a map of free chunks (thousands entries) and iteration of the map can take some time. I haven't investigated why some allocations took so many time, but I guess it is due to cache misses - some load instructions were very slow.

**Comment by jimharris** [comment]
> Hi @zp841126
> 
> The `spdk_dma_malloc` API is a wrapper over DPDK `rte_malloc_socket` function, so any its execution time depends on DPDK implementation only. From my experience, even 4KiB allocation may take a few milliseconds, it depends on the number of existing allocations. Internal DPDK implementation has a map of free chunks (thousands entries) and iteration of the map can take some time. I haven't investigated why some allocations took so many time, but I guess it is due to cache misses - some load instructions were very slow.

By default, SPDK configures DPDK to allocate huge pages on demand.  So if any buffer allocation in the app requires DPDK to allocate another huge page, the cost of that allocation will be observed directly by the application.

In general, for smaller allocations, it is best to use a mempool, and allocate/free from the mempool rather than using spdk_malloc for each one, for the reasons that @AlekseyMarchuk stated above.  For larger allocations, you can also do a mempool, depending on why you need to allocate 8MB buffers.

Another option is to use the mem_size option (-s) on the command line, to tell DPDK to pre-allocate a certain amount of hugepage memory.  Of course this requires knowing upfront how much memory your application will consume.  You can use the env_dpdk_get_mem_stats RPC on a running application to get an idea of how much hugepage memory your application is consuming at any given point.
