### ISSUE TITLE
multi process init bug

### ISSUE THREAD

**Issue by ShaoxunZeng** [spdk/spdk#2657]
# Bug report

`spdk_tgt -i` to lauch two processes in multi process mode, but init failed.

## Current Behavior
![581661086490_ pic_hd](https://user-images.githubusercontent.com/35787647/186150730-5eb8dba2-b0b1-4f7e-82dc-e6e1f60478df.jpg)

## Possible Solution

currently I comment the `iscsi` subsystem registry to prevent it from initing
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/35787647/186151082-52c91f3d-e0a8-4146-b838-aecdaf3a15f1.png">

## Steps to Reproduce

1. start primary process `spdk_tgt -i 1`
2. start secondary process `spdk_tgt -i 1`

**Comment by ksztyber** [comment]
This patch should fix this: https://review.spdk.io/gerrit/c/spdk/spdk/+/14181

**Comment by jimharris** [comment]
> This patch should fix this: https://review.spdk.io/gerrit/c/spdk/spdk/+/14181

SPDK only supports multi-process in the nvme driver.  Not even the bdev/nvme module.  There are cases where you can have two SPDK apps running in multi-process mode together, but it's a very minimal set of use cases.  For example, see test/app/stub which just probes and attaches nvme devices, to accelerate a secondary process like spdk_tgt to more quickly initialize since the SSDs are already initialized.  We use this in CI for example to more quickly run a bunch of nome-based test applications and reduce overall test time.

But iSCSI (and nvmf and vhost) don't support multi-process, and likely never will.   All of these libraries are heavily dependent on the thread library, and the thread library doesn't know about threads in other applications, meaning things like io_channels, spdk_for_each_thread, spdk_thread_send_msg, can't work.

So my proposal would be to keep the current naming, but check the return code for ENOMEM v. ENOENT and indicate with an error message that the configuration is not supported.

**Comment by ksztyber** [comment]
Thanks for the explanation Jim. I agree, we shouldn't allow the secondary process initialize if it's linked to libraries that don't support multiprocess.

> So my proposal would be to keep the current naming, but check the return code for ENOMEM v. ENOENT and indicate with an error message that the configuration is not supported.

That would work, but it'd probably be a bit cumbersome, as these functions don't return an error code, so we'd have to do that in  env layer and that's pretty generic, so the error message would also have to be generic.

How about instead of relying on the `spdk_mempool_create()` failing, we check if we're running in a secondary process? That would have the extra benefit of being able to fail the initialization early in libraries that don't support multiprocess and don't use mempools. Something like this: https://review.spdk.io/gerrit/c/spdk/spdk/+/14199

**Comment by jimharris** [comment]
> Thanks for the explanation Jim. I agree, we shouldn't allow the secondary process initialize if it's linked to libraries that don't support multiprocess.

There are a limited set of cases where it's fine for the iscsi library to initialize in a secondary process.  For example, primary process is test/app/stub, and secondary process is iscsi_tgt or spdk_tgt.

> > So my proposal would be to keep the current naming, but check the return code for ENOMEM v. ENOENT and indicate with an error message that the configuration is not supported.
> 
> That would work, but it'd probably be a bit cumbersome, as these functions don't return an error code, so we'd have to do that in env layer and that's pretty generic, so the error message would also have to be generic.

Ugh, I forgot that these errnos are assigned to the DPDK rte_errno and not returned from the function directly.  That does make this more problematic.

> How about instead of relying on the `spdk_mempool_create()` failing, we check if we're running in a secondary process? That would have the extra benefit of being able to fail the initialization early in libraries that don't support multiprocess and don't use mempools. Something like this: https://review.spdk.io/gerrit/c/spdk/spdk/+/14199

What if instead the libraries used spdk_mempool_lookup if the spdk_mempool_create fails?  It's a bit kludgy, but if the lookup returns non-NULL then we know that two different applications have initialized the library in a multi-process configuration.

**Comment by ksztyber** [comment]
> There are a limited set of cases where it's fine for the iscsi library to initialize in a secondary process. For example, primary process is test/app/stub, and secondary process is iscsi_tgt or spdk_tgt.

You're right, I haven't though about that.

> What if instead the libraries used spdk_mempool_lookup if the spdk_mempool_create fails? It's a bit kludgy, but if the lookup returns non-NULL then we know that two different applications have initialized the library in a multi-process configuration.

Makes sense, here's a patch that adds this: https://review.spdk.io/gerrit/c/spdk/spdk/+/14234

**Comment by jimharris** [comment]
Patch merged.
