### ISSUE TITLE
lvol&malloc backend can't auto-generate the valid configfile with SIGUSR1 signal

### ISSUE THREAD

**Issue by chenlo2x** [spdk/spdk#276]
## **Hardware firmware and OS**
Item|Description
-- | --
CPU Model | Intel(R) Xeon(R) CPU E5-2699 v4 @ 2.20GHz
OS version | Fedora 25
Kernel version | 4.8.6-300
SPDK Commit ID | bb2b98523abb43e268f4998278db63b35062288a

## **Problem statement**
After receiving the SIGUSR1 signal, the iscsi target can't generate the valid tmp config file.

## **Steps to reproduce**
run below script
![image](https://user-images.githubusercontent.com/32083937/38532845-32f64e9a-3ca9-11e8-85e1-a2a1e3d3cc0d.png)

##  **Expected Result**
lvol&malloc backend can generate the valid configfile.

## **Actual Result**
lvol&malloc backend can not generate the valid configfile.

**Comment by shuhei-matsumoto** [comment]
Hi, 

As described in http://www.spdk.io/doc/logical_volumes.html, lvol can be configured only by JSON-RPC now. Upcoming JSON config file may support LVOL but more consideration will be required.

**Comment by dverkamp-intel** [comment]
In addition to what Shuhei mentioned, lvol doesn't need any configuration section because it will automatically examine bdevs as they are added and expose valid lvols as bdevs.  However, in the case of a malloc backend in particular, no data is stored on disk (the malloc bdev is just backed by memory, as its name implies), so there will be no lvolstore on the malloc disk on the second app invocation.  You could make this a valid test case by replacing malloc with any other bdev that actually stores the data (e.g. nvme).

**Comment by dverkamp-intel** [comment]
Also, in the future, please post test scripts as text, not screenshots.
