### ISSUE TITLE
buffers acquired by spdk_bdev_io_get_buf() are released on a different thread with QoS

### ISSUE THREAD

**Issue by ksztyber** [spdk/spdk#2815]
With QoS enabled, bdev_ios are sent to a single thread to be submitted to a bdev module. If a bdev module wants to acquire a buffer through `spdk_bdev_io_get_buf()` it'll use `spdk_bdev_mgmt_channel` associated with the QoS thread. Once bdev_io is completed, it's sent to the thread on which the user submitted it, before executing user's completion callback. That means that `spdk_bdev_free_io()`, which releases the buffers, is executed on the thread which submitted the IO, which can be different from the QoS thread which acquired them.

If a buffer cannot be acquired at the time `spdk_bdev_io_get_buf()` is called, bdev_io will be put on a wait queue tied to a associated with `spdk_bdev_mgmt_channel` on that thread (QoS). Once a buffer is released (on a non-QoS thread), we check this queue associated with the calling thread and pass the buffer to the first bdev_io on that queue. So, under memory pressure, if none of the bdev_ios are submitted from the QoS thread, we can get completely stuck, as nobody will check the queue on the QoS thread.

To solve this, we'll need to remember the thread on which a buffer was acquired and make `bdev_io_put_buf()` asynchronous - it'd need to send a message to that thread to release the buffer.

**Comment by AlekseyMarchuk** [comment]
Hi Konrad,

There seems to be another QoS issue related to performance - all IO requests are submitted from QoS thread which makes a high pressure on this thread and it is not optimal since we utilize only 1 IO channel (e.g. nvme qpair). If I understand QoS design correctly, QoS thread is used to avoid cross thread synchronisation  on QoS data, that is not necessary to submit IO from one thread, we just need a dispatcher of IOs.
So I think we could improve QoS:
1. Send IO to QoS thread from the original
2. QoS thread decides that IO can be submitted and sends smg to the original thread
3. Original thread allocates buffers and submits IO
4. IO completed on original thread

**Comment by jimharris** [comment]
> Hi Konrad,
> 
> There seems to be another QoS issue related to performance - all IO requests are submitted from QoS thread which makes a high pressure on this thread and it is not optimal since we utilize only 1 IO channel (e.g. nvme qpair). If I understand QoS design correctly, QoS thread is used to avoid cross thread synchronisation on QoS data, that is not necessary to submit IO from one thread, we just need a dispatcher of IOs. So I think we could improve QoS:
> 
> 1. Send IO to QoS thread from the original
> 2. QoS thread decides that IO can be submitted and sends msg to the original thread
> 3. Original thread allocates buffers and submits IO
> 4. IO completed on original thread

Yeah, this is exactly what we should do.  Thanks @AlekseyMarchuk.

@Comphix, do you want to take a look at implementing this idea from Alexey?

**Comment by Comphix** [comment]
Sure. I will take a look and work on it.

**Comment by Comphix** [comment]
working on this.

**Comment by Comphix** [comment]
Patch has been merged.

**Comment by Comphix** [comment]
Close it. If there is other issue, please let me know. Thanks, Gang.
