### ISSUE TITLE
why spdk_nvme_transport_ops not support rdma connect qpair by socketapi？Did there a plan to support this ?

### ISSUE THREAD

**Issue by luo-city** [spdk/spdk#2898]
Now, nvme of rdma only support cm , when support connect qp with socketapi , like tcp?

**Comment by jimharris** [comment]
Hi,

If by socketapi, you mean spdk_sock API, then no, there is no plan to extend this to RDMA.  spdk_sock API is only intended for TCP sockets.

There is SPDK rdma API, see include/spdk_internal/rdma.h.  There are two implementations there, one for ibverbs, another for mlx5_dv.

If this answers your question, please close this issue.  Otherwise please clarify more what you are looking for.

Thanks,

Jim

**Comment by AlekseyMarchuk** [comment]
The spec requires to use rdma connection manager to connect qpairs. Please refer to chapter `3.1.1 Transport Specific Address Subtype and Transport Service Identifier`: The RDMA Internet Protocol Connection Management (RDMA IP CM) Service shall be used with the RDMA transport.
As Jim said, could you clarify what you mean by socketapi? Is it implementation of rdma connection manager (functionality provided by librdmacm) using a plain POSIX socket API? If I'm right then I guess no one has plans to do it.

**Comment by luo-city** [comment]
thanks。
