### ISSUE TITLE
NVMe-oF RDMA Initiator performance degradation

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#2927]
# Sighting report

Performance degradation detected on [performance.spdk.io](https://performance.spdk.io/d/upDz4sOVz/spdk-nvme-of-rdma-performance?orgId=1&refresh=5s&from=now-30d&to=now).

On Feb 16th there was a bulk of patches merged which affect RDMA initiator performance:
![image](https://user-images.githubusercontent.com/28856727/221878883-c63001e8-e36c-4c1c-a405-985cad71230c.png)

In detail the difference for one of the test runs look like this:
![image](https://user-images.githubusercontent.com/28856727/221879187-cc3ae4c5-0de8-423d-ac79-e46b2da23068.png)

Last good test result was with c30dfbc2d7c72eef8a655b225b2662977a38b4c0 and first bad results with 461321cc2631e9ec6cc475402d2aef3957fb3949.
Further bisecting leads to 55f94793336673906f60713bb9ddae425da8062c as first faulty commit.

There are no SPDK target or initiator warning or error messages present in the log output.

## Expected Behavior

N/A

## Current Behavior

N/A

## Context (Environment including OS version, SPDK version, etc.)

SPDK 55f94793336673906f60713bb9ddae425da8062c

**Comment by karlatec** [comment]
Tagging @ksztyber as owner of the bisected patch.

**Comment by jimharris** [comment]
Commit 55f9479 changes `bdev_nvme_readv` and `bdev_nvme_writev` to always use the vectored NVMe APIs.  Previously it would use the non-vectored API when iovcnt == 1.  We have seen cases before where the vectored APIs cause some extra overhead, since there are callbacks to reset the iov array and then iterate the array (in this case, it's just an array of 1).  So this is a very possible cause of the degradation.

@ksztyber said he will develop a test patch to help prove/disprove this theory.  Changing ownership to @ksztyber for now.

**Comment by ksztyber** [comment]
@karlatec could you check https://review.spdk.io/gerrit/c/spdk/spdk/+/16961?

**Comment by karlatec** [comment]
Did a test run using provided patch. Results are very close to results from before degradation. +2 from me!

**Comment by tomzawadzki** [comment]
Patch https://review.spdk.io/gerrit/c/spdk/spdk/+/16961 is now merged. Thank you @ksztyber  and @karlatec !
