### ISSUE TITLE
Error while connecting to /var/tmp/spdk.sock Error details: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by repu1sion** [spdk/spdk#295]
any time I run scripts/rpc.py with any option I see such error:

[root@roman spdk]# ./scripts/rpc.py get_bdevs
Error while connecting to /var/tmp/spdk.sock
Error details: [Errno 2] No such file or directory

[root@roman spdk]# ./scripts/rpc.py get_rpc_methods
Error while connecting to /var/tmp/spdk.sock
Error details: [Errno 2] No such file or directory

The socket file is really not present.
I run scripts/setup.sh before
CentOS 7.4 
python 2.7.5

**Comment by jimharris** [comment]
Hi,

The socket file is created by an SPDK application, such as the iscsi NVMf or vhost Target.  The setup script does not start an SPDK application - it only prepares the system so that one can be started.

Jim

On May 9, 2018, at 7:23 AM, repu1sion <notifications@github.com<mailto:notifications@github.com>> wrote:


any time I run scripts/rpc.py with any option I see such error:

[root@roman spdk]# ./scripts/rpc.py get_bdevs
Error while connecting to /var/tmp/spdk.sock
Error details: [Errno 2] No such file or directory

[root@roman spdk]# ./scripts/rpc.py get_rpc_methods
Error while connecting to /var/tmp/spdk.sock
Error details: [Errno 2] No such file or directory

The socket file is really not present.
I run scripts/setup.sh before
CentOS 7.4
python 2.7.5

**Comment by alekseymmm** [comment]
In case you don't really need any nvmeof targets (the way @wanqunintel mentioned) but just want to play around with rpc.py you could do something like this.
1. make config that just create socket and start listening on it. I use this one 
[Global]
[Rpc]<
  Enable Yes
  Listen 127.0.0.1
2. start it 
`./app/spdk_tgt/spdk_tgt -c etc/spdk/rpc_listen.conf.in`

Then you can run any rpc.py commands
I did this and it worked for me.

**Comment by jimharris** [comment]
This is a great idea.  It’s actually even simpler than Alexei mentioned though.  You do not even need to create the config file.  The SPDK applications will automatically start an RPC listening port on the /var/tmp/spdk.sock UNIX domain socket by default.

Note this default was added in SPDK v18.01 release.  Earlier releases would need a config file as Alexei mentioned.

**Comment by wanqunintel** [comment]
@alekseymmm great idea, it will be more common than any app like nvmf and iscsi. thanks for sharing

**Comment by wanqunintel** [comment]
@repu1sion as the titled issue can be solved with the spdk_tgt running, we will close this one

**Comment by erikliu123** [comment]
> So I call spdk_allocate_thread(), then spdk_bdev_initialize(). And what should I do next to get a bdev block device?

how do you create a NVMe device which attached to host without RPC , i have the same issue.
