### ISSUE TITLE
Question about bdevs / vbdevs initialization order.

### ISSUE THREAD

**Issue by alekseymmm** [spdk/spdk#306]
I have a question not an issue regarding spdk bdev modules.
My question is what defines the order of calling module_init function  for all the modules that are in /lib/bdev/ (both virtual  bdev and  normal bdev). I have read in the code that virtual bdevs (those having examine callback) should be initialized first. That is understandable. What about all the  modules? What if there are some dependencies between modules, and let say module "A" should be initialized only if  module "B"  has already been initialized and not earlier. Is it possible to define some order in module_init calling? Is there any order of initialization right now, except vbdev before bdev ?

**Comment by alekseymmm** [comment]
The example I have in mind is when you want to create one vbdev over the other vbdev.  They could be both virtual bdevs but providing different functionality. Since there is no ordering in init_module calling then I think that I have to write some tricky examine callback in this case for the "higher" level vbdev . Am I right ?

**Comment by jimharris** [comment]
This type of layering is done through the examine callbacks – not module init.

Let’s take logical volumes and GPT as an example, and assume we have an SSD attached with a GPT containing one partition.  That partition has an SPDK logical volume store with one logical volume.

The module init routines for logical volumes and GPT do not do anything related to creating bdevs.  They only do enough to be ready to process examine() callbacks.  This is why the virtual bdev modules init routines are called first.

When the NVMe drivers init routine is called, it will probe and attach the SSD and register the NVMe namespace as a new bdev.  When the NVMe namespace is registered, the examine() routine for both lvol and GPT will be called.  The lvol module reads the first sector and does not see a logical volume store superblock, so it does nothing.  But the GPT module reads the first sector and finds a valid partition table with one valid partition.  It then registers this partition as a new bdev.  Note that these examine() routines are called in parallel.

This then triggers the examine() routine for both lvol and GPT to be called again – this time for the new partition bdev.  In this case, the lvol module will find a valid logical volume store superblock in the first sector of this new bdev (which is the first sector of the partition – not the first sector of the SSD itself) and will then register the logical volume as a new bdev.

Now the examine() routines are called again.  This time, neither the lvol module nor the gpt module will create any new bdevs – since the logical volume contains neither a GPT nor a logical volume store superblock.

-Jim

**Comment by peluse** [comment]
Another mechanism that may help, depending on your exact use case, is the recently added .init_complete module function callback.  The bdev layer will call the bdev module's function after the subsystem has been initialized if the module provided a function pointer when it was initialized.  The intent is for a module that does something like RAID where it would like to know when all the initial examine() calls have been done in case it has some dependency on some other bdev(s) being exposed. For example, if you are a vbdev that is building a RAID5 based on 3 other bdevs (or vbdevs) and you get 2 examine callbacks - do you build a degraded RAID5 vbdev or just wait forever and simply not build anything if the 3rd doesn't show up, or wait some fixed time? The answer would be to  use this callback to know that all the initial "discovery" work has completed.  Not sure if that helps your situation or not but wanted to throw it out there.  It's only real use right now is in a patch (crypto) that is not yet merged so can't really point you to any fully functional examples...

**Comment by alekseymmm** [comment]
@jimharris Thanks for the example with lvol and gpt. It helped me understand the logic of what is happening. You mentioned that examine is called asynchronously. Is it true that all the other callbacks (like module_init,  init_complete etc )are called in parallel for all modules ?

@peluse This is the perfect example for me. Thanks a lot. To sum up your words.The sequence of calling is like this :
1. call .module_init callbacks for vbdevs modules
2. call .mudule_init callback for bdevs modules.
3. After each bdev and vbdev module init is done the examine callback of those who have it is called.
4. After all examine callbacks the init complete is called.

is my understanding correct?

**Comment by peluse** [comment]
Take a look at these two func in bdev.c and it will make it super clear I think.  Per Jim's ordering comment see spdk_bdev_module_list_add() as the order of init is essentially determined by the list order.  Then check out spdk_bdev_init_complete() for the comment I made on how a module can get notified when all the startup init stuff is done at bring-up

**Comment by alekseymmm** [comment]
Thanks . I have checked the code now it is clear for me.
