### ISSUE TITLE
Logical volume creation fails on AIO bdev

### ISSUE THREAD

**Issue by alekseymmm** [spdk/spdk#307]
## Expected Behavior

./rpc.py construct_lvol_bdev  creates lvol_bdev without errors 
## Current Behavior

./rpc.py construct_lvol_bdev lvol1 25 -l lvs 
In log I see :
vbdev_gpt.c: 297:spdk_gpt_bdev_complete: *ERROR*: Gpt: bdev=74c5b4bd-0d6a-4057-b9e6-5b505228284f io error status=0

if I run ./rpc get_bdevs  then lvs/lvol1 presents in bdevs list, but i believe it was   creation errors.
## Possible Solution

?
## Steps to Reproduce

1. create rpc listen config etc/spdk/rpc_listen.conf.in 

[Global]
[Rpc]
  Enable Yes
  Listen 127.0.0.1
2. Start rpc listening
` ./app/spdk_tgt/spdk_tgt -c etc/spdk/rpc_listen.conf.in`
3. create AIO bdev 
` ./rpc.py construct_aio_bdev /dev/sdX AIO_0 4096`
4. create lvol store 
`./rpc.py construct_lvol_store AIO_0 lvs`
5. create lvol volume
`./rpc.py construct_lvol_bdev lvol1 10000 -l lvs`

then error in log :
vbdev_gpt.c: 297:spdk_gpt_bdev_complete: *ERROR*: Gpt: bdev=74c5b4bd-0d6a-4057-b9e6-5b505228284f io error status=0
## Context (Environment including OS version, SPDK version, etc.)

* Centos 7.4
* Linux Kernel 4.11.6
* SPDK commit 3148c48079731e121ec2fc81fb15293219da1789

**Comment by jimharris** [comment]
You shouldn’t need the rpc_listen.conf.in file at all.  By default, the app will listen on a UNIX domain socket at /var/run/spdk.sock.  The Rpc section in the config file has been deprecated and is ignored by the application.

But that is not related to the error.  I suspect this error is due to AIO requiring a buffer aligned on an LBA boundary.  The AIO module sets need_aligned_buffer, but that probably doesn’t get propagated to the lvol bdevs.  So then when GPT tries to read the partition table, it allocates a buffer that isn’t aligned on an LBA boundary.

**Comment by dverkamp-intel** [comment]
I have pushed a patch for review that should fix this issue: https://review.gerrithub.io/#/c/spdk/spdk/+/412064
