### ISSUE TITLE
[nvmf-tcp-phy] Core dump syslog-ng

### ISSUE THREAD

**Issue by MaciejMis** [spdk/spdk#3110]
# CI Intermittent Failure

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/107826/archive/nvmf-tcp-phy-autotest_48472/build.log

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @MaciejMis. log: https://ci.spdk.io/public_build/autotest-per-patch_107826.html

**Comment by mikeBashStuff** [comment]
So our collector caught a core from a process that is completely irrelevant from the autotest perspective. This may happen since we overwrite the global core_pattern setting so whenever a core must be written out by the kernel, our tool will be used. 

To mitigate issues like that, our core collector should filter out cores and pick only what we are interested in.

**Comment by mikeBashStuff** [comment]
Patch in review here: https://review.spdk.io/gerrit/c/spdk/spdk/+/19766

**Comment by mikeBashStuff** [comment]
Patch merged, closing.
