### ISSUE TITLE
json server fail to parse single-line comment 

### ISSUE THREAD

**Issue by moshe-shahar** [spdk/spdk#3155]
During `jsonrpc_parse_request`, calling to `jsonrpc_log` removes new lines.
If the RPC request contains a single-line comment, removing new lines affects the functionality of JSON RPC objects.
https://github.com/spdk/spdk/blame/631e75fc03a79bb5fe45a53d293e30bfabd947d8/lib/jsonrpc/jsonrpc_server.c#L51-L55

Example:
```
{
  "method":"bdev_malloc_create",
    "params": {
      // some comment
      "num_blocks": 1024,
      "block_size": 512
    }
}
```

Workaround:
Use multi-line comment `/* comment */`

**Comment by shuhei-matsumoto** [comment]
Hi @moshe-shahar 

Thank you for posting this issue.

I may be wrong but JSON is data only format. Comments in the form //, #, or /* */, which are used in popular programming languages, are not allowed.
However, SPDK has a flag SPDK_JSON_PARSE_FLAG_ALLOW_COMMENTS defined in include/spdk/json.h.
And, then SPDK_JSON_PARSE_FLAG_ALLOW_COMMENTS is set when reading JSON config file. 
On the other hand, SPDK JSON RPC server does not set SPDK_JSON_PARSE_FLAG_ALLOW_COMMENTS.
Hence, this is not issue?
Please correct me if I am wrong.

**Comment by shuhei-matsumoto** [comment]
This change you pointed out was to log JSON RPC request and response.

**Comment by moshe-shahar** [comment]
Yes, @shuhei-matsumoto,
this is an issue and you can reproduce it also on master.
```
$ cat config.json
{
  "subsystems": [
    {
      "subsystem": "bdev",
      "config": [
        {
          "method": "bdev_malloc_create",
          "params": {
            // some comment
            "num_blocks": 524288,
            "block_size": 512,
            "name": "Malloc0"
          }
        }
      ]
    }
  ]
}
```
```
$ sudo ./build/bin/spdk_tgt -c config.json
[2023-10-19 14:32:21.089787] Starting SPDK v24.01-pre git sha1 631e75fc0 / DPDK 23.07.0 initialization...
[2023-10-19 14:32:21.089999] [ DPDK EAL parameters: spdk_tgt --no-shconf -c 0x1 --huge-unlink --no-telemetry --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid28493 ]
[2023-10-19 14:32:21.218764] app.c: 794:spdk_app_start: *NOTICE*: Total cores available: 1
[2023-10-19 14:32:21.564887] reactor.c: 937:reactor_run: *NOTICE*: Reactor started on core 0
[2023-10-19 14:32:21.590227] jsonrpc_server_tcp.c: 296:jsonrpc_server_conn_recv: *ERROR*: jsonrpc parse request failed
[2023-10-19 14:32:21.590440] app.c: 906:spdk_app_stop: *WARNING*: spdk_app_stop'd on non-zero
```

**Comment by shuhei-matsumoto** [comment]
Thank you @moshe-shahar , I missed that JSON config file may have comments.

newline will come after single line comment. Hence, we can stop removing newlines safely if we may find single line comment, and skip logging. I added a patch to fix this issue. Will you test if this works? https://review.spdk.io/gerrit/c/spdk/spdk/+/20360

**Comment by shuhei-matsumoto** [comment]
@moshe-shahar  I think removing comments (// and /* */) or (at least //) will be better. I will rework my patch and will let you know here once patch is ready.

**Comment by shuhei-matsumoto** [comment]
@moshe-shahar 

The following is my conclusion.
JSON RPC client sets SPDK_JSON_PARSE_FLAG_ALLOW_COMMENTS but JSON RPC server does not set SPDK_JSON_PARSE_FLAG_ALLOW_COMMENTS. Hence, if JSON config file contains comments, it fails to be loaded.

JSON is data only format and does not allow C style comments officially. Hence, I do not want to add SPDK_JSON_PARSE_FLAG_ALLOW_COMMENTS to JSON RPC server.

On the other hand, I think we can make JSON RPC client remove comments.
Based on this, I updated the patch to add a helper function to remove comments to JSON RPC client.
https://review.spdk.io/gerrit/c/spdk/spdk/+/20360

Will you give any feedback on this?

**Comment by shuhei-matsumoto** [comment]
Hi @moshe-shahar 

I marked this issue as enhancement because regardless of removing new lines no C style comment is allowed in SPDK JSON config file now.

I want to hear your expectation on this issue again.

Adding SPDK_JSON_PARSE_FLAG_ALLOW_COMMENTS to SPDK JSON RPC server is enough? Limitation is the following comment (you said on the gerrit patch) is still not allowed.
```
{
key = "some string that contains // in the middle "
}
```

JSON RPC logging is optional. Hence, I can make removing newlines conditional. Is this necessary?

Thanks in advance.

**Comment by moshe-shahar** [comment]
Hi @shuhei-matsumoto ,

I expect the logging to preserve user input. For a better experience when logging remove only the `\n` from the log message not from the input.

Yes, removing newlines conditionally is also a good idea.

Br,
Moshe

**Comment by shuhei-matsumoto** [comment]
> Yes, removing newlines conditionally is also a good idea.
I see. Let me update my patch.
But, the title was about single-line comment. Can we change the title of this issue?

**Comment by shuhei-matsumoto** [comment]
So, honestly I am confused. single line comment is not supported. Not good manner may not be bug. Your help is appreciated.

**Comment by moshe-shahar** [comment]
You can remove the support of single-line comments.
But, as long as `json_valid_comment` accepts single-line comments, this is a bug.

**Comment by shuhei-matsumoto** [comment]
When lib/jsonrpc/jsonrpc_server calls spdk_json_parse(), it does not set SPDK_JSON_PARSE_FLAG_ALLOW_COMMENTS.
Hence, if a JSON config file has C style comment, lib/jsonrpc/jsonrpc_server rejects it.

> [root@fedora spdk]# ./build/bin/spdk_tgt -c config.json
[2023-11-02 05:40:21.973432] Starting SPDK v24.01-pre git sha1 631e75fc0 / DPDK 23.03.0 initialization...
[2023-11-02 05:40:21.973945] [ DPDK EAL parameters: spdk_tgt --no-shconf -c 0x1 --huge-unlink --no-telemetry --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid8159 ]
[2023-11-02 05:40:22.002044] app.c: 794:spdk_app_start: *NOTICE*: Total cores available: 1
[2023-11-02 05:40:22.029074] reactor.c: 937:reactor_run: *NOTICE*: Reactor started on core 0
[2023-11-02 05:40:22.104196] jsonrpc_server_tcp.c: 296:jsonrpc_server_conn_recv: *ERROR*: jsonrpc parse request failed
[2023-11-02 05:40:22.105308] app.c: 906:spdk_app_stop: *WARNING*: spdk_app_stop'd on non-zero


This is unrelated with JSON RPC logging.
That's why I thought this is not a bug.

**Comment by shuhei-matsumoto** [comment]
@moshe-shahar 

Thank you!

It is difficult for me to
- convert single line comment (//) to multiple line comments (/* */) and
- support comment in JSON string. ("abc //def")
However, I can make newline removal optional. The following change can be a workaround for your use case?
https://review.spdk.io/gerrit/c/spdk/spdk/+/20505

**Comment by moshe-shahar** [comment]
@shuhei-matsumoto and @tomzawadzki ,

Yes, that resolved my issue.

Thank you very much!
