### ISSUE TITLE
Can't use --with-uring arm64 Ubuntu 22.04

### ISSUE THREAD

**Issue by fdr** [spdk/spdk#3162]
# Sighting report

On an aarch64/arm64 system, trying to use `pkgdep.sh -u` and then `./configure --with-uring`, it crashes saying `uring` is not installed.

## Expected Behavior

spdk should link against the uring installed by `pkgdep.sh`

## Current Behavior

It can't detect uring, and crashes.

## Possible Solution

Install uring in /usr/lib rather than /usr/lib64. Or, if statically linking is desirable (since 22.04's liburing isn't new enough, right?), install it somewhere else entirely and add a lot of paths to the compiler to find it.

## Steps to Reproduce

On an arm64 computer with Ubuntu 22.04:

```
scripts/pkgdep.sh -u
./configure --with-uring
```

## Context (Environment including OS version, SPDK version, etc.)

I encountered this on SPDK 23.09, Ubuntu 22.04.

I managed to "fix" it with this patch:

```patch
diff --git a/scripts/pkgdep/common.sh b/scripts/pkgdep/common.sh
index 0f7151fc3..7fe86a5c9 100755
--- a/scripts/pkgdep/common.sh
+++ b/scripts/pkgdep/common.sh
@@ -15,8 +15,7 @@ install_liburing() {
        fi
        # Use commit we know we can compile against. See #1673 as a reference.
        git -C "$liburing_dir" checkout liburing-2.2
-       (cd "$liburing_dir" && ./configure --libdir=/usr/lib64 --libdevdir=/usr/lib64 && make install)
-       echo /usr/lib64 > /etc/ld.so.conf.d/spdk-liburing.conf
+       (cd "$liburing_dir" && ./configure --libdir=/usr/lib --libdevdir=/usr/lib && make install)
        ldconfig
 }
 ```

**Comment by mikeBashStuff** [comment]
I believe this happens because ubuntu2204's build of the aarch64 linker (checked this quickly under VM) doesn't include `/usr/lib64` in its `SEARCH_DIR` - this is not the case for x86_64 linker for instance. This is why `configure` fails while trying to compile simple test against uring with `-luring` (it simply can't find it). 

We can't just change `/usr/lib64` to `/usr/lib` as different distros handle these differently - the solution suggested in the description may potentially break liburing installation on all rhel-based distros that we support - i.e. building SPDK may succeed but then runtime linking of shared libraries (liburing.so in this case) would most definitely  fail without proper .so cache around. 

To mitigate, we could simply include `-L/usr/lib64` in `configure`'s `BUILD_CMD[@]`. Or, and I believe this solution would be better, relay on `pkg-config` to find proper Libs args for liburing. (but this would also need to take into consideration issues similar to fecffda6ecf8853b82edccde429b68252f0a62c5).

**Comment by fdr** [comment]
I'm a bit confused about the deployment theory of spdk in general with regard to liburing. Given it ends up in `/usr/lib64` (not `/opt` or a `local` flavor directory), it seems strange that it is not in a package. 

But, if there was a package, presumably pkgdep would install that.

**Comment by mikeBashStuff** [comment]
I believe this approach was chosen because the packaged version of liburing (back in the day), under various distros, was lacking in functionality that SPDK would depend on. For instance, ubuntu is a bit behind (under 2204, by default, they ship 2.1, whereas pkgdep aims at 2.2), hence we don't relay on its repos. 

This is true, `pgkdep` doesn't try to verify the sanity of the environment SPDK may be built in, i.e. it doesn't care if there's already existing liburing lib installed under `/usr/lib64` (it did in the past, but then verifying if what exists meets our needs impose unnecessary effort in the scope pkgdep provides). So I would consider the `pgkdep` here more as a "development helper" rather then "deployment dependency" - If I attempt to build  SPDK `--with-uring`, and build infra rejects it by stating "there's no liburing" around then I can either install it from a package or use the `pkgdep` helper. All in all it boils down to user's awareness in making a decision which option is best for him. 

> (...) (not /opt or a local flavor directory, or even statically linked or part of spdk's build output) (...)

Some other projects - I think `xnvme` could be a good example (though please correct me if I am wrong) - once did what you suggest here; they provided liburing as a subproject which was indeed then built into a static lib for shipping together with other pieces. But now, as far as I recall, they dropped this approach and now solely depend on what given distro provides (i.e. what's already installed). By doing this, the responsibility of providing this particular dependency was shifted to the user. What SPDK does is quite similar, but it also provide a simple tool which helps in putting that dependency in place. 

Also, what's worth pointing out, there's a `--with-liburing=[dir]` variant which allows user to point at where `liburing` actually lives.

As I am not an actual developer, I can't say for sure which approach is best, but from the devops-ish perspective, current approach is just fine, especially in context of provisioning "clean-slate" distros (i.e. those which are supported by pkgdep) - and this is what SPDK's CI infra has been successfully using for quite a long time now. :)

**Comment by fdr** [comment]
In my opinion, if the platform does not have a new enough liburing, the thing to do would be to statically link. Granted: it's work. But leaving dependencies to loose binaries installed as a side effect of the build instructions is worse, I think.

It's also a bit cheeky that pkgdep takes liberties to install loose files, and not even into `/usr/local`, without much fanfare, rather than being constrained to packages: it is called `pkgdep` after all. It's the kind of program people are liable to run with root, expecting it to manipulate the package manager alone.

No biggie in the grand scheme of things, and hopefully it's an unsatisfactory element that will be obsolete as of Ubuntu 24.04, which will sport a modern enough liburing. But I hope the method is not repeated if spdk finds itself needing newer libraries than commonly available again.
