### ISSUE TITLE
bdev_malloc_create - name length validation

### ISSUE THREAD

**Issue by slawekptak** [spdk/spdk#3173]
# Sighting report

The following RPC command cases rpc.py errors:
./scripts/rpc.py bdev_malloc_create -b [VERY_LONG_NAME] 512 512
for VERY_LONG_NAME length of e.g. 60k characters.

## Expected Behavior

There should be a maximum length of the bdev name defined (256 characters?) and validated, resulting in a graceful error message if length exceeded.

## Current Behavior

Very long names are accepted, and at some point rpc.py reports errors.

**Comment by tomzawadzki** [comment]
> Very long names are accepted, and at some point rpc.py reports errors.

Can you please post bit more details what kind of error you are experiencing ?

**Comment by karlatec** [comment]
Ping @slawekptak

**Comment by tomzawadzki** [comment]
Since the issue lacks in detail, I'm guessing what you've done was similar to issuing:
```
sudo ./scripts/rpc.py bdev_malloc_create -b "$(tr -dc A-Za-z0-9 </dev/urandom | head -c $((2 ** 15)))" 512 512
```
Where rpc.py reports back error `ConnectionResetError: [Errno 104] Connection reset by peer`. 

If this is what you've ran into, then it is not related to bdev name at all. Instead to the size of JSON request sent/received through the socket.  There is `SPDK_JSONRPC_RECV_BUF_SIZE (32 * 1024)` that limits the size of each request. `jsonrpc_server_conn_recv()` will not read from the socket past that amount, thus resulting in closing the socket.

There might be more to do here. For example report back more specific error when `conn->recv_len` exceeds `SPDK_JSONRPC_RECV_BUF_SIZE`, but the end behaviour would be the same.
Alternatively explore extending this limit (for send too then) to handle larger requests. The question is there a valid case for such large single request ?

**Comment by slawekptak** [comment]
Can we just validate and limit the size of the bdev name alone, to something like 256 characters?

**Comment by tomzawadzki** [comment]
> @tomzawadzki thanks for the analysis. Yes, this was the result I got. I agree the issue is not related to bdev name. I think we can close the issue.

The comment was edited, to suggest closing the issue.
