### ISSUE TITLE
spdk_dd frezz with empty file and count flag bigger then 1

### ISSUE THREAD

**Issue by masuski** [spdk/spdk#3213]
# Sighting report

spdk_dd frezzes when run on empty input file with count flag bigger then 1.
It had to be killed after few minutes.

Standard dd passes immediately with similar parameters.  

## Current Behavior

```
msuski@msuski:~/repo_ssh/spdk/build/bin$ ./spdk_dd --if testfile --of testfile2 --count 9
[2023-12-14 08:47:09.127836] Starting SPDK v24.01-pre git sha1 83a7cf2ed / DPDK 23.07.0 initialization...
[2023-12-14 08:47:09.127923] [ DPDK EAL parameters: spdk_dd --no-shconf -c 0x1 --huge-unlink --no-telemetry --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid975390 ]
EAL: No free 2048 kB hugepages reported on node 1
[2023-12-14 08:47:09.284726] app.c: 794:spdk_app_start: *NOTICE*: Total cores available: 1
[2023-12-14 08:47:09.383354] reactor.c: 937:reactor_run: *NOTICE*: Reactor started on core 0
Copying: 0/36864 [B] (0 Bps)Killed

msuski@msuski:~/repo_ssh/spdk/build/bin$ dd if=testfile of=testfile2 count=9
0+0 records in
0+0 records out
0 bytes copied, 8.4221e-05 s, 0.0 kB/s
``` 

## Steps to Reproduce

manual reproduction

1. create empty file eg.    touch testfile
3. run spdk_dd with count flag eg. ./spdk_dd --if testfile --of testfile2 --count 9 

## Context (Environment including OS version, SPDK version, etc.)

Operating System: Ubuntu 22.04.2 LTS
Kernel: Linux 5.15.0-86-generic
SPDK v24.01-pre git sha1 83a7cf2ed

**Comment by masuski** [comment]
Same issue found with --skip 9 flag

**Comment by tomzawadzki** [comment]
As for the 'empty file' being the problem, spdk_dd points to the reason why size of input files are not checked https://github.com/spdk/spdk/blame/726c8313fd559711a456cae2c335638f31aa79a6/app/spdk_dd/spdk_dd.c#L1083. Have not verified veracity of those claims, but might be worth checking it.

The actual problem is while processing I/O, see https://github.com/spdk/spdk/blame/726c8313fd559711a456cae2c335638f31aa79a6/app/spdk_dd/spdk_dd.c#L856.
The rc is used to account for number of I/O returned from `io_getevents()` and while processing them setting rc to actual errno does not process remaining I/O. Never processing some of the submitted `g_job.outstanding`.
Double checking for similar behaviour in other loops copying the data should be done too (besides AIO).

This might be great issue for someone relatively new to pick up.

**Comment by masuski** [comment]
Fix in review: https://review.spdk.io/gerrit/c/spdk/spdk/+/21792

**Comment by masuski** [comment]
Fix merged
