### ISSUE TITLE
why spdk vhost disable postcopy by default?

### ISSUE THREAD

**Issue by jialei-jialei** [spdk/spdk#3235]
# Sighting report

qemu Postcopy live-migration failed

## Expected Behavior

qemu Postcopy live-migration sucess

## Current Behavior

live-migration failed

## Possible Solution

enable postcopy

## Steps to Reproduce

1.create malloc bdev
2.create vhost-blk ctrlr
3.add to a vm
4.do live-migration

## Context (Environment including OS version, SPDK version, etc.)

1.spdk v21.04
2.qemu 6.2.0

![image](https://github.com/spdk/spdk/assets/13553842/1eba3076-4eb7-4d5f-a6b2-68062f27bf68)

only enable RTE_VHOST_USER_ASYNC_COPY ?
Is there a bug in Postcopy？

**Comment by changpe1** [comment]
@jialei-jialei SPDK doesn't enable post-copy feature, only pre-copy is enabled, for vhost-user cases, since the shared storage volumes are used both in source VM and destination VM, so we could enable this feature for shared storage case.  As for the ASYNC_COPY feature, there are cases that using local attached SSDs as the backend of vhost-blk, so we enable this feature bit by default.

**Comment by jialei-jialei** [comment]
@changpe1 Thank you for your reply.
