### ISSUE TITLE
Error occurs when creating malloc or nvme bdev after error bdev

### ISSUE THREAD

**Issue by pawelkax** [spdk/spdk#325]
## Expected Behavior
Creating malloc bdev should end with no error.

## Current Behavior
After creating malloc bdev follwing error appears:
bdev.c:2769:spdk_bdev_open: *ERROR*: Could not open Malloc0 - already claimed 

## Possible Solution
None

## Steps to Reproduce
1. source ./test/common/autotest_common.sh
2. app/spdk_tgt/spdk_tgt &
3. pid=$!
4. waitforlisten $pid
5. ./scripts/rpc.py construct_error_bdev Malloc0
6. ./scripts/rpc.py construct_malloc_bdev -b Malloc0 512 512
7. kill -9 $pid
8. wait $pid

## Context (Environment including OS version, SPDK version, etc.)
Virtual machine with ubuntu 16.4 and two emulated nvme devices (1G, 2G).

**Comment by optimistyzy** [comment]
create different dev with same name， should fail，it is expected behaviour

2018年6月6日星期三，pawelkax <notifications@github.com> 写道：

**Comment by dverkamp-intel** [comment]
It looks like vbdev_error currently must be created after the base bdev exists (unlike e.g. vbdev_split, which creates a list of bdevs to split and claims them as they appear in the examine callback).

**Comment by jimharris** [comment]
No – this is related to the bdev_lvol module needing write privileges to examine a new bdev.  Vbdev_error has specifically been set up so that you can specify up front a bdev that it should attach to once it appears.  That part is working correctly.  When the bdev does appear, vbdev_error claims it correctly – but then bdev_lvol fails because it tries to open it with write privileges which we don’t allow currently since its already been claimed.

**Comment by pelplinski** [comment]
The proposed solution for this is to split examine into two parts:
First examine callback is based on config file for modules like vbdev_error or vbdev_split and no disk access is allowed.
Then, *if none of the modules claimed bdev* second type of examine is called, which allow reading data from base bdev and allows to claim bdev by modules like vbdev_lvol or vbdev_gpt.

**Comment by pawelkax** [comment]
This bug will be fixed together with issue #312
