### ISSUE TITLE
regression/nvme: single core performance degradation detected

### ISSUE THREAD

**Issue by mchomnic** [spdk/spdk#3298]
# Sighting report

[Nvme performance regerssion](https://performance.spdk.io/d/xyCvX5jVk/spdk-nvme-performance?from=1709638163120&to=1709799406000) tests detected a performance drop in regression in Bdev Single Core run.
![image](https://github.com/spdk/spdk/assets/61413529/8f36f142-2d90-49f6-bf08-b2dd02ab8e52)

For tests run with NVMes 6~14 there is performance dropped. 

## Expected Behavior

N/A

## Current Behavior

N/A

## Possible Solution

N/A

## Context (Environment including OS version, SPDK version, etc.)
spdk master (v24.05) with commit id 81beca343 and 5fa0d85. There is observed a degradation with commit a3bc732

- a3bc7320b bdev/nvme: Replace spdk_bdev_io module_link with per-io ctx retry_link
- 5fa0d8503 bdev/null: Use per-io context to allocate TAILQ_ENTRY
- 99094461 bdev/error: Use per-io context to allocate TAILQ_ENTRY
- 8130039ee build: don't create symlinks inside isa-l dirs
- d965bc4d0 configure: put isa-l configure logs in rootdir

**Comment by mchomnic** [comment]
Thank you @AlekseyMarchuk , let's wait for the final merge. I will check and post updates.

**Comment by tomzawadzki** [comment]
It seems that even after the series the performance is not back to the state before whole series. See [here](https://performance.spdk.io/d/xyCvX5jVk/spdk-nvme-performance?orgId=1&var-rw=randread&var-tc1_disks=1&var-tc2_cpus=2&var-tc3_qd=1&var-tc4_qd=1&var-manual_builds=true&from=1709539957179&to=1710411263733&viewPanel=35) (enable build annotations). Comparing left side (before the merge), then following commits show degradation (after merge of https://github.com/spdk/spdk/commit/a3bc7320b3a53a10ae77c907deb03b146dc56c83). Meanwhile last manual build on the right is from https://review.spdk.io/gerrit/c/spdk/spdk/+/22005/2, where performance is not back to level before whole series. It is closer, but not there yet.
View from link above:
![image](https://github.com/spdk/spdk/assets/24698708/716436e9-80ae-4cbf-a1b3-ceed3c99a250)
Before series:
![image](https://github.com/spdk/spdk/assets/24698708/4ae2a9a9-9e20-49f1-8730-ec2caf21b257)
After series:
![image](https://github.com/spdk/spdk/assets/24698708/453b2516-d8b9-4eb7-bb46-a4a0d594accf)

I'm holding off from merging currently reviewed parts. Since the series was done to improve performance, degradation here is troublesome. We can either revert what was merged so far, or proceed to add changes on top to improve it further.

@benlwalker Please let me know how you would like to proceed with this series.

**Comment by ksztyber** [comment]
[Bugscrub] Seems like this happens due to the patches removing module_link from spdk_bdev_io. We could try to revert those patches and retest on performance.spdk.io. @benlwalker could you take a look at this one?

**Comment by benlwalker** [comment]
Current theory:
* bdev_nvme polls queue for completions, gets callback. Let's say it's bdev_nvme_readv_done but all callbacks have same behavior
* The completion callback calls bdev_nvme_io_complete_nvme_status
* bdev_nvme_io_complete_nvme_status calls bdev_nvme_check_retry_io and bdev_nvme_queue_retry_io speculatively. It does not actually go down this branch, but they touch the retry list which previously used the module_ctx in spdk_bdev_io
* Touching module_ctx brings bdev_io->internal.ch into the cache.
* spdk_bdev_io_complete is called and the first thing it does is ask for the channel and then does another data dependent load on a member in the channel

The patch in question breaks this by shifting where the retry list pointers are. They no longer share a cache line with bdev_io->internal.ch. Attempting a fix via pre-fetch instructions here: https://review.spdk.io/gerrit/c/spdk/spdk/+/22510/1

**Comment by tomzawadzki** [comment]
@benlwalker We can provide perf record data for two commits. Can you please point to specific ones you'd find most useful to test ? For example latest on current series and commit before the original patch from this issue.

**Comment by benlwalker** [comment]
The two you listed would be perfect

**Comment by mchomnic** [comment]
Dear Ben,
I'm sending perftop results for commits:
- master before the series: 8130039
- top of the series: 863a4e0
The results you can check as always on the website: [performance.spdk.io](https://performance.spdk.io/d/xyCvX5jVk/spdk-nvme-performance?orgId=1&var-rw=randread&var-tc1_disks=1&var-tc2_cpus=2&var-tc3_qd=2&var-tc4_qd=1&var-manual_builds&viewPanel=38) 
![image](https://github.com/spdk/spdk/assets/61413529/cbdffe5c-0cb2-4233-931f-77797a6394ca)

[archive_863a4e0.zip](https://github.com/spdk/spdk/files/15061676/archive_863a4e0.zip)
[archive_8130039.zip](https://github.com/spdk/spdk/files/15061708/archive_8130039.zip)

**Comment by tomzawadzki** [comment]
The performance difference is in favor of the revert patches - https://review.spdk.io/gerrit/c/spdk/spdk/+/23191/

Master:
![3298_before](https://github.com/spdk/spdk/assets/24698708/c1511bd9-8a2d-4998-a485-469277b38347)
After reverts: 
![3298_after](https://github.com/spdk/spdk/assets/24698708/11811846-a84e-4a89-bf44-cdaa746f1803)

[performance.spdk.io](https://performance.spdk.io/d/d252f6f5-4b2d-441c-84a2-89e9f1820ff8/spdk-nvme-performance?orgId=1&var-rw=randread&var-tc1_disks=1&var-tc2_cpus=2&var-tc3_qd=1&var-tc4_qd=1&var-manual_builds&from=1715746413100&to=1715861910214&viewPanel=35)

Unfortunately the results are not back to level before the change - possibly due to other changes occurring on master in the meantime.
