### ISSUE TITLE
[nvme-vg-autotest] ftl_write_after_write test fails with ftl_band_ops.c:34: write_rq_end: Assertion `false' failed.

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#3299]
# Sighting report

Hit an assert when trying to enable some FTL tests in nightly tests.

`ftl_write_after_write` test fails due to:
```
00:17:25.650  fio: ftl_band_ops.c:34: write_rq_end: Assertion `false' failed.
00:17:35.622  /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh: line 1312: 75981 Aborted                 (core dumped) LD_PRELOAD="$asan_lib $plugin" "$fio_dir"/fio "$@"
```
Full build log:
https://ci.spdk.io/public_build/autotest-per-patch_118714.html
https://ci.spdk.io/results/autotest-per-patch/builds/118714/archive/nvme-vg-autotest_71041/build.log
[ftl_write_after_write_build.txt](https://github.com/spdk/spdk/files/14588055/ftl_write_after_write_build.txt)
[fio_75981.core.bt.txt](https://github.com/spdk/spdk/files/14588057/fio_75981.core.bt.txt)

## Steps to Reproduce

1. Build SPDK with:
```
./configure --enable-debug --enable-werror \
--with-rdma --with-idxd --with-fio=/usr/src/fio \
--with-iscsi-initiator --disable-unit-tests --enable-ubsan \
--enable-asan --enable-coverage --with-ublk \
--with-xnvme --with-shared
make -j
```
2. Run FTL tests
```
sudo -E test/ftl/ftl.sh
```

## Context (Environment including OS version, SPDK version, etc.)

SPDK fed383aca03e97ad769a8c21ac5558515fd3664e
Linux fedora38-cloud-1705279005-2131 6.7.0-68.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Jan 15 00:59:40 UTC 2024 x86_64 GNU/Linux

**Comment by karlatec** [comment]
Issue can be retested with: https://review.spdk.io/gerrit/c/spdk/spdk/+/22319/1

**Comment by mmkayPL** [comment]
FTL has a minimum base device size of 20GiB, however no such devices were added. As a result a workaround was added - if the base device doesn't have the required size, a thin provisioned lvol is created on top of it. For non-extended tests this wasn't a problem, since they don't write that much data, however the extended (and nightly) tests do. For example the write_after_write.fio job sends a total of 10GiB of data, however the FTL is created on top of a base bdev which is only 5GiB in size, so when it eventually gets to that amount, the write fails, FTL asserts and the test fails.

If it isn't possible to add a machine with a bigger emulated NVMe drive, then I suggest removing the mention of these extended/nightly tests alltogether.

**Comment by karlatec** [comment]
There's no way to support bigger emulated NVMe drives at the moment.
Isn't there any way to handle this a bit more gracefully than assert & crash?

**Comment by ksztyber** [comment]
[Bugscrub] Let's remove the tests for now. The issue should not happen in production environment.
