### ISSUE TITLE
trace: trace init error when CPU core larger than 128

### ISSUE THREAD

**Issue by ygtzf** [spdk/spdk#3301]
# Sighting report

We encountered an issue with Vhost using the 129 core of the CPU, which failed to start with the error log:
`trace.c: 242:spdk_trace_init: *ERROR*: user threads overlap with the threads on dedicated cpus. `

I have a rough look at the code, there are a lot of doubts about this code, why there are SPDK_TRACE_MAX_LCORE restrictions, this shouldn't be hard code. 
Code：lib/trace/trace.c:241
```
if (g_user_thread_index_start + num_threads > SPDK_TRACE_MAX_LCORE) {
    SPDK_ERRLOG("user threads overlap with the threads on dedicated cpus\n");
    return 1;
  }

```
## Expected Behavior

Vhost can start normally, regardless of which CPU core is used.

## Current Behavior

If the CPU core is greater than 128, the vhost fails to start.

## Steps to Reproduce

1. start vhost with --cpumask [129]
2. vhost start failed

## Context (Environment including OS version, SPDK version, etc.)

SPDK Version: v24.01
OS version: EL9

**Comment by jimharris** [comment]
I'll take a look at this next week @ygtzf after I get back from a short vacation.

**Comment by ygtzf** [comment]
@jimharris  I've found that you can circumvent this problem by using the lcores parameter at vhost or target startup. So setting this macro to 128 doesn't seem to matter, right?

**Comment by jimharris** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/22418

SPDK_TRACE_MAX_LCORE was originally needed to limit the size of trace files to a reasonable amount, since each core's circular trace buffer consumed a lot of memory.

But the trace files are now dynamically sized based on the number of cores actually used by the application, so this limit isn't as important now. The above patch bumps the limit to 1024. We do allocate a small char array per lcore for a thread name, so 1024 seemed like a reasonable number to land on.

**Comment by tomzawadzki** [comment]
@ygtzf with that patch above merged, the issue should be resolved. Correct ?

**Comment by ygtzf** [comment]
Yes, this patch is ok.
