### ISSUE TITLE
[nvmf/tcp] requests are not getting completed when working with ZCOPY and host disconnects during C2HData PDU transfers

### ISSUE THREAD

**Issue by ZivHirsch13** [spdk/spdk#3309]
# Sighting report

When working with TCP target and ZCOPY, the requests are not getting completed when the host disconnects during C2HData PDU transfers.
This seems to be because of [72925e3](https://github.com/spdk/spdk/commit/72925e3db811f79859ac06ac82fd20046b608f41).
I compiled SPDK with debug mode in order to get more info, and I saw that we enter the following `if` statement in `nvmf_tcp_req_process()`:
```
case TCP_REQUEST_STATE_COMPLETED:
    spdk_trace_record(TRACE_TCP_REQUEST_STATE_COMPLETED, tqpair->qpair.qid, 0, (uintptr_t)tcp_req,
              tqpair);
    /* If there's an outstanding PDU sent to the host, the request is completed
     * due to the qpair being disconnected.  We must delay the completion until
     * that write is done to avoid freeing the request twice. */
    if (spdk_unlikely(tcp_req->pdu_in_use)) {
        SPDK_DEBUGLOG(nvmf_tcp, "Delaying completion due to outstanding "
                  "write on req=%p\n", tcp_req);
        /* This can only happen for zcopy requests */
        assert(spdk_nvmf_request_using_zcopy(&tcp_req->req));
        assert(tqpair->qpair.state != SPDK_NVMF_QPAIR_ACTIVE);
        break;
    }

    ...
```
and the `_req_pdu_write_done()` callbacks are not getting called, so the requests are never completed.

## Expected Behavior

Requests should be completed.

## Current Behavior

Host disconnects unexpectedly, so we try to disconnect its controllers due to keep-alive timeout, and some requests are not getting completed, which also leads to the qpairs and the controllers not getting closed. 

## Steps to Reproduce

Can be reproduced by running the following SPDK's perf cmd to a single subsystem with a single namespace based on bdev_malloc:
`./perf -w randread -t 60 -q 128 -o $((1024*1024)) -r 'trtype:TCP adrfam:IPv4 traddr:<> trsvcid:4420 subnqn:<>'`
and while `perf` is running, run `ifconfig <> down` in the host.

## Context
SPDK v24.01

**Comment by ksztyber** [comment]
I'm able to reproduce this with malloc bdev and the nvme_perf command suggested by @ZivHirsch13. I've spent some time debugging this and I can see that we don't receive the callbacks from the `spdk_sock_writev_async()`. What I think is happening is that when you set the interface down, the target only sees that something's wrong because it doesn't receive ACKs on the data it has transmitted, but that's not reflected in the state of the socket (i.e. the `sendmsg()` calls are successful), so we get stuck. Actually, we do get "unstuck" after a long while (a little over ~15m on my system) and the qpair does get deleted, which I think happens due to the timeout on those ACKs. Adjusting `TCP_USER_TIMEOUT` seems to fix this.
@ZivHirsch13 could you cherry-pick this patch [1], set `ack_timeout` to something non-zero, and check if it also fixes the issue on your and?

[1] https://review.spdk.io/gerrit/c/spdk/spdk/+/22400

**Comment by ZivHirsch13** [comment]
@ksztyber thanks!! I'll try and update.

**Comment by ZivHirsch13** [comment]
@ksztyber it fixed my issue! Thanks again!
