### ISSUE TITLE
Performance for Raid0 with malloc bdevs is not linear?

### ISSUE THREAD

**Issue by hxlpub** [spdk/spdk#3315]
# Sighting report
When I test raid0 with bdevperf, the performance for raid0 with two  malloc bdevs is not doubled.

## Expected Behavior
The performance should be doubled or linear. 

## Current Behavior
IOPS degraded from 1377105.18 for raid0 with 1 malloc bdev  to  1168733.41 for raid0 with 2 malloc bdevs. 

## Steps to Reproduce
1../build/examples/bdevperf -q 64 -t 60 -m 0x1 -o 4096 -w randwrite -z &

2. create raid0 with two Malloc bdevs
for i in $(seq 0 1);do
    ./scripts/rpc.py bdev_malloc_create -b Malloc$i 10240 4096
done

3. ./scripts/rpc.py bdev_raid_create -n Raid0 -z 64 -r 0 -b "Malloc0 Malloc1"

4../examples/bdev/bdevperf/bdevperf.py perform_tests

## Context (Environment including OS version, SPDK version, etc.)
5.14.0-58.el9.x86_64
spdk v23.09

**Comment by apaszkie** [comment]
The performance improvement of raid0 comes from the ability to utilize more hardware resources in parallel. It allows to combine the performance of multiple drives. When using malloc bdevs, no performance gain should be expected because adding more malloc bdevs doesn't increase the memory bandwidth, only the amount of used memory. Performance can even be worse (as observed above) because of the processing overhead of raid0 and an additional bdev.

**Comment by apaszkie** [comment]
Can the issue be closed now?
