### ISSUE TITLE
Building SPDK with enable-lto fails with "undefined reference to `__wrap_RAND_bytes'" error

### ISSUE THREAD

**Issue by quatvle** [spdk/spdk#3386]
# Sighting report

make failed with the following error: 
spdk/lib/nvmf/auth.c:676: undefined reference to `__wrap_RAND_bytes'

## Expected Behavior

All binaries under spdk/build/ should be created successfully.

## Current Behavior

echo "  LINK auth_ut"; cc -o auth_ut -g -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wmissing-declarations -fno-strict-aliasing -I/home/qvle/spdk/include -march=native -mno-avx512f -flto=auto -Wformat -Wformat-security -D_GNU_SOURCE -fPIC -fstack-protector -fno-common -DNDEBUG -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -DSPDK_GIT_COMMIT=4199e7b -pthread -Wno-pointer-sign -Wstrict-prototypes -Wold-style-definition -std=gnu11 -I/usr/include/openssl11   -I/home/qvle/spdk/lib -I/home/qvle/spdk/module -I/home/qvle/spdk/test -ffunction-sections -DSPDK_UNIT_TEST=1 -flto=auto -Wl,-z,relro,-z,now -Wl,-z,noexecstack -fuse-ld=bfd -L/usr/lib64/openssl11 -lssl   -Wno-maybe-uninitialized -Wl,--wrap,RAND_bytes -Wl,--wrap,calloc -Wl,--wrap,pthread_mutexattr_init -Wl,--wrap,pthread_mutex_init -Wl,--wrap,recvmsg -Wl,--wrap,sendmsg -Wl,--wrap,writev -Wl,--gc-sections auth_ut.o  -lcunit /home/qvle/spdk/build/lib/libspdk_thread.a /home/qvle/spdk/build/lib/libspdk_trace.a /home/qvle/spdk/build/lib/libspdk_util.a /home/qvle/spdk/build/lib/libspdk_log.a /home/qvle/spdk/build/lib/libspdk_ut.a -Wl,--whole-archive /home/qvle/spdk/build/lib/libspdk_ut_mock.a -Wl,--no-whole-archive   -libverbs -lrdmacm -pthread -lrt -luuid -lssl -lcrypto -lm -lfuse3
  LINK auth_ut
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld.bfd: /tmp/auth_ut.rmydZ3.ltrans0.ltrans.o: in function `nvmf_auth_recv_challenge':
/home/qvle/spdk/lib/nvmf/auth.c:676: undefined reference to `__wrap_RAND_bytes'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld.bfd: /home/qvle/spdk/lib/nvmf/auth.c:621: undefined reference to `__wrap_RAND_bytes'
collect2: error: ld returned 1 exit status

## Steps to Reproduce

cd spdk
./configure --enable-lto
make V=1

## Context (Environment including OS version, SPDK version, etc.)

OS version:       OL7.9
gcc version:      9.3.1
SPDK version:   master

**Comment by jimharris** [comment]
I also saw this with gcc v11.4.

I've pushed a fix here: https://review.spdk.io/gerrit/c/spdk/spdk/+/23306

The problem was that these wrapper functions seems to require an `__attribute__((used))`, which `__wrap_RAND_bytes()` did not have. This gets applied for wrapper functions defined using `DEFINE_WRAPPER`, but that didn't happen here since the wrapper function needed a more custom definition. So the fix is to apply the `__attribute__((used))` in `DECLARE_WRAPPER` which gets used in all cases.

I fixed up a few other LTO warnings I uncovered while looking at this.  There is one outstanding that I still can't figure out:

```
nvme_pcie_common_ut.c: In function ‘test_nvme_pcie_poll_group_get_stats’:
nvme_pcie_common_ut.c:572:9: error: ‘__builtin_memcmp_eq’ specified bound 72 exceeds source size 0 [-Werror=stringop-overread]
  572 |         CU_ASSERT(memcmp(&tgroup_stat->pcie, &pgroup->stats, sizeof(struct spdk_nvme_pcie_stat)) == 0);
      |         ^
lto1: all warnings being treated as errors
```

...but that's not related to this issue at all - just something that would need to be fixed if we ever wanted to do `--enable-lto --enable-werror` builds.
