### ISSUE TITLE
pkgdep.sh script fails to install dependencies on Rockylinux 8

### ISSUE THREAD

**Issue by velomatt** [spdk/spdk#3403]
# Sighting report

On Rockylinux 8 and possibly other RHEL-based distros, the `scripts/pkgdep.sh` script installs and configures a yum repository for EOL'd CentOS-8-stream packages.

The CentOS-8-Stream repos were EOL'd on May 31, 2024, and removed from the internet by their maintainers and all mirrors.
 
## Expected Behavior

`scripts/pkgdep.sh` should install a working set of dependencies on supported distributions.

## Current Behavior

On Rockylinux 8, `scripts.pkgdep.sh` installs the `centos-release-ceph-pacific` package from the `extras` repo. This package attempts to configure a yum repo for CentOS 8-Stream which no longer exists.

## Possible Solution

If Ceph is required, then a working version of the upstream centos-release-ceph-pacific should be identified and installed by pkgdep.sh. Perhaps this dependency can be optionally excluded via some passed argument? Otherwise, perhaps this dependency should be removed for RHEL-like distros running version 8.

## Steps to Reproduce

1. git clone https://github.com/spdk/spdk
2. cd spdk
3. ./scripts/pkgdep.sh

Result:

```
Error: Failed to download metadata for repo 'centos-ceph-pacific': Cannot prepare internal mirrorlist: No URLs in mirrorlist
Error!
```

Additionally, if a Rockylinux 8 system has already been configured via `pkgdep.sh` - yum will be unusable on the system until this repo has been disabled by the user: `yum-config-manager --disable centos-ceph-pacific`

## Context (Environment including OS version, SPDK version, etc.)

OS details:

```
NAME="Rocky Linux"
VERSION="8.9 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.9 (Green Obsidian)"
```

Tested via docker (image: `rockylinux:8`)

spdk version: latest, commit ID `e55c9a81251968acc91e4d44169353be1987a3e4`

**Comment by mikeBashStuff** [comment]
We dropped {centos,rocky}8 from the CI pool some time ago and we should probably do the very same thing for the `pkgdep`.  

The alternative here is to taint .repo files but it's not something I would love to support here (e.g. to add metalink and point at `centos-storage-sig-ceph-pacific-9-stream`. This of course creates a scary hybrid where we mix different `$stream` variants).

Granted, this could be also parametrized but we already have plenty of those for different components.

>  yum will be unusable on the system until this repo has been disabled by the user: yum-config-manager --disable centos-ceph-pacific

Well, this depends -  if you use `skip_if_unavailable=True` then this is not the case. We do this for more wonky distros, like {centos,rocky}, due to issues like this one which were popping up in the past (different repos|packages were being dropped left and right when centos8 was dying). In fact, I just temporary hooked rocky8.9 back to our build infra and `pkgdep`, despite the issue with ceph repo, installed all other dependencies without any hiccups.

In general and in context of ceph, `pkgdep` is responsible only for setting up repositories since the actual tools are installed by `autotest_setup.sh` (since it's a autotest dependency, it's not really needed for development). This split is unfortunate and in hindsight doesn't have much sense.

The overall split between `pkgdep.sh` and `autotest_setup.sh` is something i very much dislike - if these were merged into one, and by supporting proper modes like `--autotest, --development` etc., it would be possible to parametrize all this even further, e.g. by grouping packages into `--autotest=nvme,no-ceph --development=static-analysis` or similar. That's something that would of course require a proper refactor.

**Comment by mikeBashStuff** [comment]
I had to remind myself that we already do similar sort of HACKing for actual `rhel` distro, so having something like this could be still considered as a mitigation I guess: https://review.spdk.io/gerrit/c/spdk/spdk/+/23599.

**Comment by karlatec** [comment]
@velomatt the change @mikeBashStuff mentioned was merged.
Does that fix the issue for you?

**Comment by karlatec** [comment]
Change with mitigation was merged, so I am assuming this fixed the issue. Closing.
