### ISSUE TITLE
Error while activating network: Call to virNetworkCreate failed:

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#3446]
```
00:12:23.005  ==> default:     -> value=-device, 
00:12:23.005  ==> default:     -> value=nvme,id=nvme-1,serial=12341,addr=0x11, 
00:12:23.005  ==> default:     -> value=-drive, 
00:12:23.005  ==> default:     -> value=format=raw,file=/var/lib/libvirt/images/backends/ex0-nvme-multi0.img,if=none,id=nvme-1-drive0, 
00:12:23.005  ==> default:     -> value=-device, 
00:12:23.005  ==> default:     -> value=nvme-ns,drive=nvme-1-drive0,bus=nvme-1,nsid=1,zoned=false,logical_block_size=4096,physical_block_size=4096, 
00:12:23.005  ==> default:     -> value=-drive, 
00:12:23.005  ==> default:     -> value=format=raw,file=/var/lib/libvirt/images/backends/ex0-nvme-multi1.img,if=none,id=nvme-1-drive1, 
00:12:23.005  ==> default:     -> value=-device, 
00:12:23.005  ==> default:     -> value=nvme-ns,drive=nvme-1-drive1,bus=nvme-1,nsid=2,zoned=false,logical_block_size=4096,physical_block_size=4096, 
00:12:23.005  ==> default:     -> value=-drive, 
00:12:23.005  ==> default:     -> value=format=raw,file=/var/lib/libvirt/images/backends/ex0-nvme-multi2.img,if=none,id=nvme-1-drive2, 
00:12:23.005  ==> default:     -> value=-device, 
00:12:23.005  ==> default:     -> value=nvme-ns,drive=nvme-1-drive2,bus=nvme-1,nsid=3,zoned=false,logical_block_size=4096,physical_block_size=4096, 
00:12:23.274  ==> default: Creating shared folders metadata...
00:12:23.849  Error while activating network: Call to virNetworkCreate failed: Requested operation is not valid: network is already active.
00:12:23.874  [Pipeline] }
00:12:23.898  [Pipeline] // stage
00:12:23.906  [Pipeline] }
00:12:23.927  [Pipeline] // wrap
00:12:23.938  [Pipeline] }
00:12:23.942  ERROR: script returned exit code 1
00:12:23.942  Setting overall build result to FAILURE
00:12:23.958  [Pipeline] // catchError
```

**Comment by mikeBashStuff** [comment]
@jimharris Would you kindly link the build that got hit by this issue? This snippet is missing some relevant parts without which it's hard to investigate this further (entire build.log would be best, or at least the beginning of it (where the VM setup is logged)).

**Comment by jimharris** [comment]
> @jimharris Would you kindly link the build that got hit by this issue? This snippet is missing some relevant parts without which it's hard to investigate this further (entire build.log would be best, or at least the beginning of it (where the VM setup is logged)).

It was patchset 9 on https://review.spdk.io/gerrit/c/spdk/spdk/+/23488. I'm not sure why CI didn't post that failure here though.

**Comment by mikeBashStuff** [comment]
So the unfortunate part here is that our vagrant setup is inherently racy. The way how `vagrant-libvirt` plugin manages the network it connects the VM to has been problematic for a long time now. 

Each vagrant call (i.e. each process that handles setup of a single VM) will attempt to create the `vagrant-libvirt` network. This network is then associated with that particular VM. When said VM instance is destroyed, the network associated with it is destroyed as well. Note that with the version of the plugin that we are using, only the instance associated with creation of this network can also destroy it. Meaning, that if new VM instances are being created (which is mostly the case since we run multiple VMs in parallel under our VM hosts)  they will be attached to the very same network, but they won't be able to destroy it on their own (this for instance changed in newer versions where EVERY VM can destroy said network). 

So the only reason I can think of for this to happen:

```
Error while activating network: Call to virNetworkCreate failed: Requested operation is not valid: network is already active.
```

is when multiple vagrant instances, at the same time, attempt to create `vagrant-libvirt` network (so it had to be previously destroyed or at least deactivated) with only one succeeding and rest (like the one from this issue) failing. 

I have a workaround in mind but need to test it out. For what's it worth, the above scenario is very unlikely to happen but indeed possible.

**Comment by mikeBashStuff** [comment]
All in all, this is not issue related to SPDK, but to specifics of the CI infra, so I will close it for now.
