### ISSUE TITLE
[WFP50] Clock skew detected

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#3462]
# CI Intermittent Failure

Job times out due to building taking over 30 minutes. Most probable cause is the clock skew on this (maybe other?) machine.
There is bunch of other warnings, but hard to tell how relevant they are.

```
00:03:03.483  make[1]: warning:  Clock skew detected.  Your build may be incomplete.
00:03:04.424  configure.ac:52: warning: The macro `AC_PROG_CC_STDC' is obsolete.
00:03:04.424  configure.ac:52: You should run autoupdate.
00:03:04.424  ./lib/autoconf/c.m4:1666: AC_PROG_CC_STDC is expanded from...
00:03:04.424  configure.ac:52: the top level
00:03:04.424  configure.ac:50: warning: The macro `AC_PROG_CC_STDC' is obsolete.
00:03:04.424  configure.ac:50: You should run autoupdate.
00:03:04.424  ./lib/autoconf/c.m4:1666: AC_PROG_CC_STDC is expanded from...
00:03:04.424  configure.ac:50: the top level
00:03:04.424  configure.ac:80: warning: back quotes and double quotes must not be escaped in: upgrade your compiler to support SVE2, or run \"./configure --disable-sve2\"
00:03:04.424  configure.ac:90: warning: The macro `AC_TRY_COMPILE' is obsolete.
00:03:04.424  configure.ac:90: You should run autoupdate.
00:03:04.424  ./lib/autoconf/general.m4:2847: AC_TRY_COMPILE is expanded from...
00:03:04.424  configure.ac:90: the top level
00:03:11.007  make[2]: Warning: File 'Makefile.am' has modification time 1572 s in the future
00:03:11.007  make[2]: Warning: File 'Makefile.am' has modification time 1550 s in the future
00:03:11.945  configure.ac:50: warning: The macro `AC_PROG_CC_STDC' is obsolete.
00:03:11.945  configure.ac:50: You should run autoupdate.
```

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/127148/archive/nvme-phy-autotest_78285/build.log

## Execution failed at

Job times out.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_127148.html

**Comment by mikeBashStuff** [comment]
Granted, most of the hw clocks on our systems is actually a bit off  in relation to the sys clocks - during boot, sys clocks is set through ntp but it seems that due to the fact all our phy systems are short-lived, it may be not synced back to hw (in most cases at least). Essentially:

```
# hw clock is kept in UTC
[root@spdk-wfp-50 ~]# echo $(($(date -u +%s) - $(< /sys/class/rtc/rtc0/since_epoch)))
1980
```
In normal circumstances, this should be close to 0. Above we can see that hw clock is behind about 1980s. This is quite close to what we initially see in the build.log (~1600s) - the difference probably stems from the fact that `chrony` already started to adjust the sys clock - so the build was probably queued up right after the machine went online.

So to mitigate issues like this from suddenly popping up we would need force the systohc early on when the machine goes online.

**Comment by mikeBashStuff** [comment]
Mitigation on CI's end just got merged so I will proceed with closing this issue. Note that there's still a small chance of this issue happening, but now all the hwclocks, across all our systems, should be in sync with the ntp so drifts like the one seen in my previous comments should be gone (or at least kept to the very minimum across reboots).
