### ISSUE TITLE
Why abort pending spdk_bdev_io at QoS disable?

### ISSUE THREAD

**Issue by zbenlong** [spdk/spdk#357]
spdk_bdev_qos.queued should have accumulated bunch of pending spdk_bdev_io at QoS disablement from RPC. The current SPDK implementation choose to abort these with SPDK_BDEV_IO_STATUS_FAILED (as in _spdk_bdev_abort_queued_io). Why not just issue them instead?

## Current Behavior
spdk_bdev_io terminated with spdk_bdev_io_complete(bdev_io, SPDK_BDEV_IO_STATUS_FAILED);

## Possible Solution
submit to underlying driver module

## Steps to Reproduce

1.
2.
3.
4.

**Comment by jimharris** [comment]
I'm working on a patch + unit test for this.

**Comment by jimharris** [comment]
https://review.gerrithub.io/#/c/spdk/spdk/+/418128/

**Comment by Benlegend** [comment]
Cool, thank you for the code! @jimharris

So each spdk_bdev_io is being redirected back to its original thread. But I think we can simply send from the QoS thread too, _spdk_bdev_io_complete() should make the iostats channel right.

And may I ask can I get the SPDK Automated Test System as we wanna setup the autotest internally for our customized repo.

Thank you!

**Comment by jimharris** [comment]
We cannot easily send them from the QoS thread.  Once QoS is disabled, the QoS thread will release its reference on the channel (spdk_put_io_channel) - if this was the last reference on the channel, the channel and its resources will be deleted.  So if we send them from the QoS thread, we would have to defer releasing the reference on the channel which really complicates things unnecessarily.

It's much simpler to just redirect the spdk_bdev_io back to its original thread.

For the automated test system - all tests are in the SPDK repository.  If you have additional questions, I would suggest asking a question on the SPDK mailing list rather than this unrelated GitHub issue.

Thanks,

-Jim

**Comment by liang2yan** [comment]
@Benlegend , can we close this issue? Since the patch already merged.

**Comment by zbenlong** [comment]
@liang2yan Oh, not know the opener is expected to close ASAP. Sure I will close this.
