### ISSUE TITLE
Abort with default configuration of dpdk2.1 (CONFIG_RTE_MAX_MEMSEG)

### ISSUE THREAD

**Issue by zhouyuan** [spdk/spdk#4]
<...>
EAL: Requesting 512 pages of size 2MB from socket 0
EAL: Requesting 512 pages of size 2MB from socket 1
EAL: Can only reserve 569 pages from 1024 requested
Current CONFIG_RTE_MAX_MEMSEG=256 is not enough
Please either increase it or request less amount of memory.

recompile dpdk with CONFIG_RTE_MAX_MEMSEG=512 works fine

**Comment by bwalker-intel** [comment]
Your system seems to have highly fragmented huge page allocations and therefore the default DPDK configuration does not work on your system. DPDK has given you a mechanism to adjust this that works for you.

Since SPDK cannot control the default configuration of DPDK, and since DPDK already has a mechanism to adjust the maximum number of memory segments, I'm closing this issue.
