### ISSUE TITLE
Segmentation fault (core dumped) after issuing write and trim in certain orders on same block.

### ISSUE THREAD

**Issue by hfingler** [spdk/spdk#43]
I have written a little benchmark for testing delays for read, write and operations in different orders and different number of blocks, and it worked in an older version of spdk - I checked and that is 454 commits behind. With the current version I get a _Segmentation fault (core dumped)_ whenever I do some certain permutations of commands.

 These sequences work (r = read, w = write, t = trim):  wrt, twr.
 These fail: rwt, wtr, rtw.

 Is this expected or is my code wrong? 

 Current algorithm (for _rwt_, it's similar for the other sequences, just change the order):
- Send read command
- Read completion callback issues write command.
- Write completion callback issues trim command.
- Trim completion does nothing (sets "done" flag to 1 so program ends). 

 Should I remove the nesting? Issue commands outside the callback? This is a single thread only, just a sequence of three commands, reset everything, sleep half a second (was getting some noise), repeat to gather more timing data.

 Thank you.

**Comment by benlwalker** [comment]
I just tested this with my own code and it works fine in any order using an algorithm similar to what you describe, so there is some mistake in your code. However, doing this made me realize that the trim interface we're presenting has a number of caveats and hidden requirements. Notably the payload must be allocated from pinned memory, be in a very specific format, and must exist for the lifetime of the command.

Instead of trying to debug your issue directly, I just wrote a smarter wrapper around dataset management operations that should help you avoid some of the trickier aspects of the previous interface. Now, you can allocate the array of LBA descriptors on the stack and pass them to the SPDK function and it will just do the right thing. See commit f4140ad.

**Comment by hfingler** [comment]
Thanks for the reply!

> so there is some mistake in your code.
 Might be, what is weird is that it was working 100% with the older version. I got numbers for all the sequences I wanted.

> However, doing this made me realize that the trim interface we're presenting has a number of caveats and hidden requirements.

 The block sequence struct required searching through the source code to figure out how to set it up. Couldn't find any file or test that actually used it.

> Instead of trying to debug your issue directly, I just wrote a smarter wrapper around dataset management operations that should help you avoid some of the trickier aspects of the previous interface. Now, you can allocate the array of LBA descriptors on the stack and pass them to the SPDK function and it will just do the right thing. See commit f4140ad.

 Awesome, I'll check it out. And now that you said it's working for you, we've been having issues with other stuff (hugepages are one of them, they never get freed); we just changed environment (new kernel, new machine, 4KB blocks instead of 512B) and it all broke after this. I guessed that since I pulled the last version of SPDK that was the culprit.

 After fixing everything and refactoring I'll comment here to let you know how it went.

 Thank you!

**Comment by benlwalker** [comment]
Closing this issue because I believe it is resolved. If your testing shows that there is still some problem, feel free to re-open or file a new issue.
