### ISSUE TITLE
vhost-user-scsi-pci is unusable with Windows 10

### ISSUE THREAD

**Issue by blu3bird** [spdk/spdk#432]
When starting a Windows 10 VM (fresh install) in QEMU with a vhost-user-scsi-pci device attached, the boot already takes quite long, way longer than it should. Once the OS is finally booted, trying to use the disk, for instance to partition it using disk manager, produces I/O errors.
When booting the VM with a Linux ISO (systemrescuecd-x86-5.2.2.iso), the disk works perfectly.

## Expected Behavior
Windows should be able to use the disk.

## Current Behavior
Disk is unusable, I/O errors whenever trying to access it. Boot takes quite long. 

## Possible Solution
When using construct_malloc_bdev instead of construct_aio_bdev the disk is usable and the boot delay disappears.

## Steps to Reproduce
- create basic VM with Windows 10 (1803)
- start vhost app, add an aio-bdev and vhost-scsi controller/lun
- start VM with [...] -chardev socket,id=vhostuser1,path=/run/vhost.1 -device vhost-user-scsi-pci,chardev=vhostuser1 [...]
- install driver (virtio-win-0.1.160.iso, but older versions also produce the error)
- start disk manager
- try to create a simple partition on the disk

## Context (Environment including OS version, SPDK version, etc.)
Host-OS: Gentoo Linux with kernel 4.18.6
SPDK: Current git head, commit b6938efd
DPDK: via submodule from spdk git head, commit c860b292
Qemu: 3.0.0
Backend-Dev: AIO, USB-Stick with a blocksize of 512
RPC-Calls: construct_aio_bdev /dev/sdd aio.0 && construct_vhost_scsi_controller vhost.1 && add_vhost_scsi_lun vhost.1 0 aio.0

Already talked to Jim Harris on IRC, he told me to enable the trace-flags aio, bdev, vhost_scsi, vhost_scsi_queue, vhost_scsi_data and scsi. The debug log is attached, I tried to partition the disk at 23:32:12, the I/O error appeared at 23:32:20.
[vhost-user-scsi-pci.debug.log](https://github.com/spdk/spdk/files/2362597/vhost-user-scsi-pci.debug.log)

If you need more information or want me to test something just let me know.

Regards,
Friedrich

**Comment by pawelwod** [comment]
> When using construct_malloc_bdev instead of construct_aio_bdev the disk is usable and the boot delay disappears.

> Backend-Dev: AIO, USB-Stick with a blocksize of 512

Hmmm... USB-stick is insanely slow vs malloc bdev :) Can you check local SSD drive as AIO bdev?

**Comment by blu3bird** [comment]
I originally used an lvm volume on top of my nvme as bdev, which had the same symptoms and failures as the usb stick.
The reason I switched to a usb stick was that the lvm volume had a blocksize of 4096 and there were lot's of 'blocksize 512' messages in the log. I wanted to eliminate any potential issue with block size mismatch.

**Comment by pawelwod** [comment]
I don't see any failures in your log. Can you pls check SSD drive as AIO bdev? I don't think you will get any usable performance from USB Strick with 512LBA and SPDK on it.

**Comment by tomzawadzki** [comment]
@jimharris We do have automated tests running daily for vhost - against Windows SCSI Compliance Test 2.0 (LOGO). There are no fails reported at this time for those. It runs on other version of Windows.
https://docs.microsoft.com/en-us/windows-hardware/test/hlk/testref/d1f2fbbe-d5e4-439d-819a-dc100df0e9ba

@blu3bird 
Thank you for submitting. We will try to reproduce this issue and will keep you posted.

**Comment by tomzawadzki** [comment]
It seems that it was possible to reproduce an issue. I've ran script below to verify different backends (NVMe, AIO, malloc) and block sizes (512 vs 4096). It occurs on any block size of AIO backend from script.
The steps for reproduction are close to what you did. Environment was similar, but with couple differences (older Windows and driver):
Host-OS: Fedora 28 with kernel 4.17.19
SPDK: commit b6938ef
Qemu: 3.0.0
Windows: Windows Server 2012 R2
Windows driver: Red Hat VirtIO SCSI pass-through controller 62.73.104.12600 from virtio-win-0.1.126.iso

Since all AIO cases failed, I will be focusing on AIO based on file with 4096 block size. Logs that fail attached at the bottom.

It seems to be directed at interactions between AIO and vhost, as per @pawelwod suggestion offline - disabling O_DIRECT flag when opening the AIO file seems to no longer present the issue. At least in very rudimentary tests I've done so far (initialize and format the disk fully). 

@blu3bird A workaround/test patch can be found [here](https://review.gerrithub.io/#/c/spdk/spdk/+/425495/). Could you please check if this resolves your issue ? If yes, proper patch could be build off of it.

Script:
[repro_sh.txt](https://github.com/spdk/spdk/files/2379537/repro_sh.txt)

Logs:
[config_file_4096.log](https://github.com/spdk/spdk/files/2379531/config_file_4096.log)
[spdk_file_4096.log](https://github.com/spdk/spdk/files/2379532/spdk_file_4096.log)

**Comment by jimharris** [comment]
This is probably a buffer alignment issue.  AIO requires data buffers aligned on LBA size alignment.

Sent from my iPhone

On Sep 13, 2018, at 6:52 AM, Tomasz Zawadzki <notifications@github.com<mailto:notifications@github.com>> wrote:


It seems that it was possible to reproduce an issue. I've ran script below to verify different backends (NVMe, AIO, malloc) and block sizes (512 vs 4096). It occurs on any block size of AIO backend from script.
The steps for reproduction are close to what you did. Environment was similar, but with couple differences (older Windows and driver):
Host-OS: Fedora 28 with kernel 4.17.19
SPDK: commit b6938ef<https://github.com/spdk/spdk/commit/b6938efd0b8a3a85bb0b65091eafbb79d8165108>
Qemu: 3.0.0
Windows: Windows Server 2012 R2
Windows driver: Red Hat VirtIO SCSI pass-through controller 62.73.104.12600 from virtio-win-0.1.126.iso

Since all AIO cases failed, I will be focusing on AIO based on file with 4096 block size. Logs that fail attached at the bottom.

It seems to be directed at interactions between AIO and vhost, as per @pawelwod<https://github.com/pawelwod> suggestion offline - disabling O_DIRECT flag when opening the AIO file seems to no longer present the issue. At least in very rudimentary tests I've done so far (initialize and format the disk fully).

@blu3bird<https://github.com/blu3bird> A workaround/test patch can be found here<https://review.gerrithub.io/#/c/spdk/spdk/+/425495/>. Could you please check if this resolves your issue ? If yes, proper patch could be build off of it.

Script:
repro_sh.txt<https://github.com/spdk/spdk/files/2379537/repro_sh.txt>

Logs:
config_file_4096.log<https://github.com/spdk/spdk/files/2379531/config_file_4096.log>
spdk_file_4096.log<https://github.com/spdk/spdk/files/2379532/spdk_file_4096.log>

**Comment by blu3bird** [comment]
@tomzawadzki after applying the patch the disk works as expected. I tested it by partitioning, mounting and reading/writing files onto it.

**Comment by blu3bird** [comment]
Still reproducable with 9f9cfdc5.

@wanqunintel the merged patch (https://review.gerrithub.io/#/c/spdk/spdk/+/425213/) did not solve the issue, it was just to enhance logging.
