### ISSUE TITLE
iscsi_tgt/fio failed with conf file in NIGHTLY master test with RSYC ERRORS

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#439]
iscsi_tgt/fio.sh reports conf file error in NIGHTLY master test everyday.

In fedora-02 server:
= = = = = = = = = = = = = = = = = = = =
 iSCSI target running config
= = = = = = = = = = = = = = = = = = = =
[crypto]

*ERROR*: === BACKTRACE START ===
vbdev_crypto.c: 221:vbdev_crypto_init_crypto_drivers: *ERROR*: error creating virtual PMD crypto_aesni_mb

This issue can be reproduced in local server.

## Expected Behavior
iscsi_tgt/fio.sh passed.

## Current Behavior
iscsi_tgt/fio.sh failed with generated conf file.

## Possible Solution
May be due to the contents of the configuration file is empty.

## Steps to Reproduce
1. view https://review.gerrithub.io/#/c/spdk/spdk/+/393768/
2. view https://ci.spdk.io/spdk/builds/review/d4db15db8a1ba5a2ac8e07a092c08b745ba11391.1537274055/fedora-02/build.log
(search "Backtrace start")

## Context (Environment including OS version, SPDK version, etc.)
SPDK Change-Id: f8d0f6d6ccddc0dac44f49b8cd927d0379faf922

**Comment by xuhuagen** [comment]
@wanghailiangx  it need to notice that ReactorMask config option is deprecated.  Use -m/--cpumask 
in file /tmp/iscsi.conf.

**Comment by liang2yan** [comment]
@wanghailiangx , please create separate issues for two errors. the crypto issue to be paul luse.

**Comment by liang2yan** [comment]
@wanghailiangx , Assign the RAID issue to yourself.

**Comment by peluse** [comment]
strange, you'd think this would have failed quite often by now.  I'll take a look

**Comment by peluse** [comment]
FYI crypto should behave fine with an empty config section, I just tested it

**Comment by peluse** [comment]
Oh, here's the problem:
CRYPTODEV: rte_cryptodev_pmd_create() line 121: [crypto_aesni_mb] Failed to allocate crypto device for crypto_aesni_mb

Note that this is DPDK output.  I'm not sure why it couldn't create this.  Will have to go look at the aesni crypto driver but our module did the right thing, threw an error.  Now, we might want to fix one thing though, we always create the aesni driver even if they didn't configure it in the config file (just because). In this case if it wasn't configure then the error would be unexpected for sure.  I'll first look at why the DPDK driver might have failed.

**Comment by peluse** [comment]
Looks like the only thing that could have happend, the only path that doesn't print something else, is an actual memory allocation error.  This test does run nightly and has been running for a while right?

**Comment by peluse** [comment]
Also, its stated that "This issue can be reproduced in local server." can you provide the exact steps to reproduce on a local system?

**Comment by wanghailiangx** [comment]
Yes, this test runs nightly and has been running for a while right, reports error almost every day.
I will list local steps for a while.

**Comment by wanghailiangx** [comment]
It is a great pity that I can't reproduce in local now. I only run ./test/iscsi_tgt/iscsi_tgt.sh posix.
I'll try add [crypto] in conf.in and retest later. The former two questions were originally put together, and the other bdev_raid was reproduced. I haven't changed this description here yet.

**Comment by peluse** [comment]
@wanghailiangx the last question there was for you :) .

**Comment by peluse** [comment]
Also, looking at the last few failures it's not the same signature as the one you pointed out earlier, the one about the DPDK AESNI driver not having enough memory.  It looks like most of these failures are somewhere in the ext4test but its not jumping out at me where (but then again I've never looked at this test before).

Can you please take another look at the logs and let me know if you are seeing what I am seeing?

**Comment by peluse** [comment]
@wanghailiangx it looks like *most* of these test, maybe all but one, failed because of an rsync issue, not a crypto issue. And the crypto issue you pointed out, again, was an out of memory error condition in DPDK so not clear how easy that is to repro.

 08:16:33	# rsync -qav --exclude=.git /home/sys_sgsw/build_pool/agent/repo/ /mnt/sdbdir/spdk
rsync: write failed on "/mnt/sdbdir/spdk/test/unit/lib/nvme/nvme_ctrlr.c/nvme_ctrlr_ut.gcno": No space left on device (28)
rsync error: error in file IO (code 11) at receiver.c(374) [receiver=3.1.3]

Please take another look at the se and see if maybe some more . disk space is needed or a lesser number of files rscync'd or something

**Comment by wanghailiangx** [comment]
In recent days' logs of NIGHTLY test, the issue can't be reproduced, because "running_config
" had been commented out in test/iscsi_tgt/fiofio.sh. I am trying to reproduce it in local.

**Comment by peluse** [comment]
OK thanks,.  I'd say focus on the rsync errors,

**Comment by jimharris** [comment]
https://review.gerrithub.io/#/c/spdk/spdk/+/429517/ was merged yesterday - it should fix the rsync errors.

**Comment by jimharris** [comment]
Jim to increase size of malloc bdev used for backing storage for iSCSI LUN.

**Comment by peluse** [comment]
has anyone tried @jimharris earlier suggestion to increase the malloc size? There's another issue waiting to retest on this as well so would be good to take a few minutes to try  it

**Comment by wanghailiangx** [comment]
In ext4test.sh, size of malloc bdev is 512M,
`$rpc_py construct_malloc_bdev 512 4096 --name Malloc0`

But now there is no error report about "est/iscsi_tgt/ext4test/ext4test.sh" recently. I close the issue.
If the issue reproduces, I will increase size of malloc bdev again.
