### ISSUE TITLE
initiator connect fails after hard power off

### ISSUE THREAD

**Issue by jonathanrichardson** [spdk/spdk#450]
When a connection from the spdk initiator (perf) to spdk target (nvmf_tgt) is established and data transfer is occurring, powering off the initiator by pulling the power prevents the initiator from connecting again when the machine is brought back up. 

## Expected Behavior

The initiator should be able to connect again. The only way is to restart nvmf_tgt. It should be able to recover eventually but doesn't look like the state flow is happening properly.

## Current Behavior
The spdk target sends the initiator a ConnectReject with reason code 10 (stale connection). The spdk initiator (perf) exits with these errors:
nvme_rdma.c: 221:nvme_rdma_get_event: *ERROR*: Expected RDMA_CM_EVENT_ESTABLISHED but received RDMA_CM_EVENT_REJECTED (8) from CM event channel (status = 10)
nvme_rdma.c: 548:nvme_rdma_connect: *ERROR*: RDMA connect error
nvme_rdma.c: 852:nvme_rdma_qpair_connect: *ERROR*: Unable to connect the rqpair
nvme_rdma.c:1393:nvme_rdma_ctrlr_construct: *ERROR*: failed to create admin qpair

It's never able to recover. The target also sends a Disconnect Request but the initiator does nothing. nvmf_tgt exits the time wait state and refuses any further connections.

## Possible Solution
After going through the spec it sounds like the initiator should be acting on the ConnectReject and disconnecting or cleaning up the connection after going into a TimeWait state. Note the linux kernel initiator (4.14) has the same behavior. With the kernel, if the initiator is rebooted gracefully or shutdown, the driver sends a disconnect and spdk cleans up the connection allowing future connections when it has rebooted. 

## Steps to Reproduce

1. Run nvmf_tgt on target.
2. Run spdk perf on initiator
3. Pull the power on initiator and reboot it.
4. Run spdk perf again on initiator.

## Context (Environment including OS version, SPDK version, etc.)

 SPDK 18.04
librdmacm 1.1.0
libibverbs 1.2.0

**Comment by wanqunintel** [comment]
@jonathanrichardson , it seems that your network configuration for rdma nic need to be reconfigured after reboot on the initiator, @WenqianZong can help to provide more detailed info later.

**Comment by WenqianZong** [comment]
@jonathanrichardson After reboot initator ,you need do following operation:
1. configure ip and ping target machine successful
2.modprobe mlx5_ib
   modprobe mlx4_ib
   modprobe nvme_rdma
   modprobe nvme_fabrics
3.run perf with rdma

**Comment by jonathanrichardson** [comment]
Yes that's what I do. But on power loss spdk thinks the initiator is still connected. This is what happens:

1.	Initiator connects after reboot
2.	Target sends ConnectReject with reason “connection stale”
3.	Target sends DisconnectRequest
4.	Initiator gives up saying can't connect. According to the spec it should move into a Time Wait state. 
From the IB spec:
 Stale connection The recipient of the REQ/REP determined that it already had a connection with the “Local QPN” or “Local EECN” specified in the REQ/REP. Upon receiving a REJ with this reason, the REJ recipient shall cause the QP or EE context to be placed into the TimeWait state as described in section 

It looks like spdk target is giving the initiator a chance to disconnect with the DisconnectRequest, initiator ignores, exits, and can never connect again unless you restart the target. I've attached a packet capture where 192.168.1.10 is the target (sorry, only inbound packets are available). 

[connect-after-powerloss.zip](https://github.com/spdk/spdk/files/2489236/connect-after-powerloss.zip)

**Comment by jimharris** [comment]
@Maciej-Szwed is working on this.  The changes are fairly complex.

@Maciej-Szwed - could you provide an update here that explains the fixes that you are working on.

**Comment by liang2yan** [comment]
@Maciej-Szwed , any info about your fixes?

**Comment by Maciej-Szwed** [comment]
I'm planing to have it ready next week. I'm sorry for delayed response.

**Comment by darsto** [comment]
Bug scrub: We still need to discuss what the next steps are.

**Comment by peluse** [comment]
@Maciej-Szwed please talk to @benlwalker about this one while you're in Chandler

**Comment by darsto** [comment]
Bug scrub: no update, @jimharris wants to help

**Comment by jimharris** [comment]
Bug scrub: Seth plans to retest this again after recent changes that have gone into the upcoming 19.10 release.

**Comment by Seth5141** [comment]
After wrestling with the configuration a little this afternoon, I can verify that this is still an issue on master. From where I'm at right now, the change seems pretty small. I will take a crack at fixing it this afternoon and hopefully have a patch up for testing.

**Comment by Seth5141** [comment]
There is a change out here: https://review.gerrithub.io/c/spdk/spdk/+/473063. I have verified that it fixes the reconnect problem after a hard reboot. However the solution in that change isn't very elegant or flushed out yet. I think there are a few issues that I have with trying to solve this resonnect inside the RDMA transport:
1. We just implemented the rest of the reconnect logic to take place at the application level.
2. Having reconnect logic inside the rdma transport means we have a 1 off reconnect counter and timeout inside a specific transport.
3. This creates problems for Soft-Roce (https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48731.html) which isn't a huge deal since it's not real hardware, but we still use it to test right now.

I am thinking about implementing this as part of an effort to return tranport specific error codes when we get things like failed connections, disconnects, resets, etc. Not really sure what's best. But I wanted to provide an update.

**Comment by Seth5141** [comment]
Updated patch set is here https://review.gerrithub.io/c/spdk/spdk/+/473063/4 I moved the internal reconnects to the create_qpair function. I think we will need to do the reconnect attempts internally because there is no way to inform the application during a probe sequence that their ctrlr couldn't be created because of a stale connection error code while connecting the admin qpair.

@jonathanrichardson I know this issue was opened quite some time ago, but if you're still interested, I'd like to know if you can corroborate that the fix above works. Thanks!

**Comment by jimharris** [comment]
Closing issue.  @jonathanrichardson please reopen if you retest and still see failures.
