### ISSUE TITLE
build.log not generated in "fedora-03" server for NIGHTLY Test

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#470]
Logs generated in "fedora-03" server for NIGHTLY Test, but no "build.log".
[TXT] agent_timing.txt                                                         2018-10-22 05:48    3   
[TXT] all_tests.txt                                                            2018-10-22 05:48  842   
[TXT] dmesg.log                                                                2018-10-22 05:48    0   
[TXT] doxygen.log                                                              2018-10-22 05:48    0   
[   ] pass                                                                     2018-10-22 05:48    0   
[TXT] test_completions.txt                                                     2018-10-22 05:48  259   
[IMG] timing.svg                                                               2018-10-22 05:48   35K  
[TXT] timing.txt                                                               2018-10-22 05:48  3.6K  

## Expected Behavior
build.log should be generated in "fedora-03" server.

## Current Behavior
build.log not generated in "fedora-03" server

## Possible Solution
N/A

## Steps to Reproduce
1. view https://review.gerrithub.io/#/c/spdk/spdk/+/393768/
2. view https://ci.spdk.io/spdk/builds/review/c5be776542f0972e8f6563c5f10962c342b1bc3d.1540210370/
3. view https://ci.spdk.io/spdk/builds/review/c5be776542f0972e8f6563c5f10962c342b1bc3d.1540210370/fedora-03/
4.

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit 83b1102f7b0ffe8b0356157614507135a66f6c86

**Comment by wanghailiangx** [comment]
By the way, build.log also not generated in "fedora-09" server.

**Comment by Seth5141** [comment]
I did a little digging into this issue. It turns out that we had set a limit for filesize in the script we use to copy to ci.spdk.io. This was initially intended to keep us from copying core files output from the builds in order to prevent us from taking up too much space on the public server. 
Since we have been hitting this issue quite frequently recently, I have updated the script to allow for larger individual files (up to 16MiB). This should largely fix the problem.

Either way, this is not an SPDK bug, but more of a tooling and test infrastructure bug, so I believe it should be closed.

**Comment by liang2yan** [comment]
@Seth5141 , yes, we can close this issue. And when can we fix this tooling and test infrastructure bug?

**Comment by Seth5141** [comment]
@liang2yan I have increased the size of the files we will try to rsync to the public server. This should fix the tooling and infrastructure bug, except in extreme cases where our build logs are larger than 16MiB. I think it is reasonable to set that as the limit for copying to the public server since we have limited space on that server.
So both the SPDK and tooling bug can be considered closed as of now.
