### ISSUE TITLE
Abort of requests that are on the queuedReq list

### ISSUE THREAD

**Issue by cmicalizzi** [spdk/spdk#51]
In the case that an SQ is full the code queues new requests to:
    STAILQ_HEAD(, nvmeRequest)  queuedReq; of the corresponding Queue Pair Struct.
However, when nvme_ctrlr_cmd_abort is called it issues an NVMe Abort command to the corresponding Controllers Admin SQ. 
Shouldn't the code first search the queuedReq list for the target request?
Also, if the Request to be aborted is on the queuedReq list the cid will be 0 as it hasn't been assigned a Tracker yet. The way the code is today this would result in an Abort being issued for the wrong Request, meaning the Request with cid = 0 will be aborted by the drive.

thank you

chuck

**Comment by dverkamp-intel** [comment]
You are correct - code that wants to abort a request should first check whether it is on queued_req, because if so, it has not actually been submitted to the controller yet, and sending an abort for it would be incorrect.

However, the current SPDK code base does not actually call nvme_ctrlr_cmd_abort() anywhere (except one place in a unit test).

The current nvme_ctrlr_cmd_abort() is left over from the original import of the FreeBSD NVMe driver; it needs to be updated to actually be usable. Adding the queued_req check would be a required part of exposing abort as part of the public NVMe library API.  Additionally, the current implementation does not acquire the ctrlr_lock as it ought to be doing.

Exposing abort to the public API is somewhat problematic, since the NVMe request object is not part of the public API.  All of the current public APIs that issue requests just track the request internally and call the user-provided callback on completion.  The API user has no request to pass to the abort function to identify which command to abort.  We could potentially change the API to make all functions that issue I/O requests return the request pointer so that it could be passed to abort, but this would be a fairly major API change, requiring all users to modify their code.

**Comment by cmicalizzi** [comment]
Daniel,

     Thank you for the reply.

     I guess the only hammer the user has for freeing stuck I/Os is 
controller reset.

chuck

**Comment by benlwalker** [comment]
I think, in practice, that using a reset is the only way forward anyway. An I/O should never hang at the device if the device is functioning correctly. So if an I/O does hang at the device, that means the firmware at that device has done something wrong. What, then, are the chances that the already known to be flawed firmware will correctly handle an abort appearing later in the queue for the hung command if it isn't capable of not hanging in the first place? I'd say the chances of that are very low in actual practice. This has just been my experience as the author of SATA/SAS/NVMe drivers over the years - abort is one of those things that's great on paper but in practice it almost never works because the only time you'd use it is when you're already dealing with a faulty device.

I'm certainly not opposed to adding an abort interface if we can work through the problem of identifying which I/O to abort, which is not currently in the public API.

**Comment by cmicalizzi** [comment]
Ben,

     Thanks for the reply. I agree that reset makes much more sense than 
trying to abort a single request.
     I've had my share of "abort wars" over the years with customers.

chuck

**Comment by benlwalker** [comment]
We've added support for I/O timeouts and aborts, so I'm closing this issue. If additional functionality around aborts is required we can open up a new, more specific issue.
