### ISSUE TITLE
Jenkins: vote not posted for patch that passed test pool

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#534]
Link to status page:  https://ci.spdk.io/spdk-jenkins/public_build/autotest-per-patch_16737.html
Link to Gerrit review:  https://review.gerrithub.io/#/c/spdk/spdk/+/436231/

**Comment by jimharris** [comment]
Here's another example:

https://review.gerrithub.io/#/c/spdk/spdk/+/435937/
http://ci.spdk.io/spdk-jenkins/public_build/autotest-per-patch_16724.html

**Comment by jimharris** [comment]
https://ci.spdk.io/spdk-jenkins/public_build/autotest-per-patch_16776.html
https://review.gerrithub.io/#/c/spdk/spdk/+/436301/

**Comment by jimharris** [comment]
https://review.gerrithub.io/#/c/spdk/spdk/+/436302/
https://ci.spdk.io/spdk-jenkins/public_build/autotest-per-patch_16775.html

**Comment by peluse** [comment]
@karlatec is this because of what you mentioned on IRC about accidentally leaving the REST API enabled?

**Comment by karlatec** [comment]
Yes, that's right. I gave update to Jim about his on IRC but forgot to write it down here.
Most of these builds which Jim linked did not get a vote becuase of that. So Gerrit plugin REST API username/passwd fields were filled, but it wasn't working due to a proxy. It seems that the plugin did get the events from original SSH connection, but failed to give a vote back through REST API.

REST API is disabled now and it fields cleared, and I didn't see any missed or skipped build votes.
Let me know if I can close the issue.

Karol

**Comment by jimharris** [comment]
Thanks @karlatec.  Closing this issue.
