### ISSUE TITLE
SPDK and non-ssd hard disk

### ISSUE THREAD

**Issue by Moqavemat** [spdk/spdk#539]
I would like to improve my C project's I/O speed and one of my options is SPDK libraries. Unfortunately there is an ambiguity that has not been clearing even after seeking SPDK documents. According to SPDK documents which is located in https://spdk.io/doc/index.html and it's explanation in https://spdk.io/doc/about.html one of it's bedrock is NVMe driver (which has been designed to capitalize on the low latency and internal parallelism of solid-state storage devices.). In addition in aforementioned link, there is SSD internal section that it's description is intended to help software developers understand what is occurring inside the SSD. So it seems that SPDK designation is for working with SSD storage devices but I doubt to my conclusion. So any help to make a definite conclusion about Can I use SPDK libraries for my non-SSD hard disk, would be appreciated.

**Comment by nmarusha** [comment]
You can use the libaio backend (BDEV) I believe (instead of the NVMe driver). That being said, the SW can’t make the physical devices go faster than their capabilities. When using HDDs, SW overhead is typically not the challenge, the problem is the devices themselves are slow and insert all of the overhead.

Thanks,
Nate

On Dec 12, 2018, at 1:28 AM, Moqavemat <notifications@github.com<mailto:notifications@github.com>> wrote:


I would like to improve my C project's I/O speed and one of my options is SPDK libraries. Unfortunately there is an ambiguity that has not been clearing even after seeking SPDK documents. According to SPDK documents which is located in https://spdk.io/doc/index.html and it's explanation in https://spdk.io/doc/about.html one of it's bedrock is NVMe driver (which has been designed to capitalize on the low latency and internal parallelism of solid-state storage devices.). In addition in aforementioned link, there is SSD internal section that it's description is intended to help software developers understand what is occurring inside the SSD. So it seems that SPDK designation is for working with SSD storage devices but I doubt to my conclusion. So any help to make a definite conclusion about Can I use SPDK libraries for my non-SSD hard disk, would be appreciated.
