### ISSUE TITLE
question: compression dev test in SPDK v19.01

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#558]
I noticed "reduce" lib and unit test had been added to SPDK dir. Now I want to do functional test, does anyone know where is the example/app? Or need us to develop it?

**Comment by wanghailiangx** [comment]
@peluse Hi , I heard you did some compression app tests, is that so?

**Comment by peluse** [comment]
@wanghailiangx thanks for jumping on this!  Reducelib is planned to only be consumed internally by the compression vbdev that is WIP.  It has its own set of unit tests that @jimharris is working on as he develops the library.  Although we could develop another vbdev "test only" module I think we're probably better off relying on UT and system/functional tests that use the compression vbdev.

That said, I'm probably only a week or so (not working full time this week or next due to holiday) from having the vbdev module in a state where it can do IO however it won't be doing compression for a while longer, there's still some API to work out between reducelib and the vbdev module.  

Anyway, there will be some tests to develop for sure as we'll want to execute various scenarios due to the additional complexity of having metadata and having it stored somewhere else other than the backing disk.  I think this would be a great community meeting topic or dist list discussion once we're a little closer to doing IO.

I'll consider this closed for now, lets pick it up after the holidays in one of the comm channels I just mentioned if that's OK with you.
