### ISSUE TITLE
Maximum write size for a single channel

### ISSUE THREAD

**Issue by xxks-kkk** [spdk/spdk#578]
I slightly modified the `hello_bdev.c` program. Instead of writing `blk_size` using `spdk_bdev_write`, I write a buffer which is 70MB size. There are two things I observed:

1. `nbytes` parameter cannot be arbitrary: it has to be a multiple of blk_size
2. it seems that there is a limit on the amount of data can be written through one channel. In my case, I cannot write 70MB (i.e., 73400320 bytes, which a multiple of 512 bytes, blk_size) through a single channel and I got the following error:

```
hello_bdev.c: 259:hello_start: *NOTICE*: Writing to the bdev
bdev_nvme.c:1526:bdev_nvme_queue_cmd: *ERROR*: writev failed: rc = -22
hello_bdev.c: 162:write_complete: *ERROR*: bdev io write error: 5
```

I'm wondering if my observations are correct? If so, what's the upper bound for the write size I can do through a single channel? Is there any example I can reference if I want to write 70MB or even larger like 1GB using `bdev.h` through multiple channels?

I haven't tested this behavior on the latest SPDK version. Maybe this is something that is already fixed, which can motivate me to bump my SPDK dependency to the latest one.

## Expected Behavior
`hello_bdev.c` should execute successfully.

## Current Behavior
Fail with -22

## Steps to Reproduce

Add the following code to the `hello_bdev.c`

```c
#include <assert.h>
#include <fcntl.h>
#include <float.h>
#include <float.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>

static int buffer_size = 73400320;

int fill_fixed(void *buffer, int size, char *pattern, int pattern_size);

int fill_fixed(void *buffer, int size, char *pattern, int pattern_size) {
  int left_to_write = size;
  int write_start = 0;
  int n_to_write = pattern_size;
  while (left_to_write > 0) {
    if (write_start + n_to_write > size) {
      n_to_write = left_to_write;
    }
    // +1 due to snprintf's size parameter includes '\0' as well
    int write_size =
        snprintf(buffer + write_start, n_to_write + 1, "%s", pattern);
    // snprintf return number of characters written excluding '\0'
    assert(write_size == pattern_size);
    write_start += write_size;
    left_to_write -= write_size;
  }
  return 0;
}

hello_context->buff = spdk_dma_zmalloc(buffer_size, buf_align, NULL);

int ret = fill_fixed(hello_context->buff, buffer_size, "AAAAA", 5);
assert(ret == 0);

rc = spdk_bdev_write(hello_context->bdev_desc, hello_context->bdev_io_channel,
                       hello_context->buff, 0, buffer_size, write_complete,
                       hello_context);
```

## Context (Environment including OS version, SPDK version, etc.)

- SPDK 18.07
- Ubuntu 16.04

**Comment by benlwalker** [comment]
The underlying device, if it is an NVMe device at least, has a maximum I/O size. It's usually somewhere around 128KiB. When a larger I/O is submitted, SPDK automatically attempts to split that I/O. We elected to do automatic splitting so that the same application code can run against any type of device without implementing its own splitting logic each time. SPDK allocates a pool of objects used during this splitting operation internally. When faced with an extreme case, two errors can occur. The first is that we don't currently have enough of the internal objects to handle the splitting, but at some point in the future we likely will. In that case, the operation returns ENOMEM (12). The second case is where the I/O is so large that we'll never have sufficient internal objects to perform the split. In that case, we return EINVAL (22).

You can still write large amounts of data from an application. Just do it in smaller chunks. Probably 1MB at a time is a good choice. You won't lose any performance doing it that way and it bounds the memory requirements to track all of the outstanding I/O.

**Comment by xxks-kkk** [comment]
@benlwalker Thanks for the reply. I'm wondering if I split say 70MB into 70 pieces, do I need to open multiple channels doing this to maintain the same performance? or it's ok that I just sequentially send 1MB write through one channel to the device?

Thanks!

**Comment by benlwalker** [comment]
It isn't a requirement of the NVMe specification, but in practice you can always get the full performance of an NVMe device using just one queue pair (i.e. one channel). You just need to give the device enough data to keep all of the NAND dies busy. Sending the data in 1MB chunks (maybe using queue depth 2) is likely more than enough to do that, so I would expect you'd see the maximum performance for the device.

**Comment by xxks-kkk** [comment]
@benlwalker Thanks for the reply. I'm new to SPDK. I'm wondering how I can specify the queue depth? What's the default depth for the queue? How can I check this using existing API?

Thanks!

**Comment by benlwalker** [comment]
You can just keep calling functions like spdk_bdev_read() in quick succession to submit multiple overlapped I/O. The bdev layer doesn't expose the maximum queue depth of each channel publicly (it's different for each type of bdev and we instead do software queueing if necessary to make all of the bdevs behave the same way). Usually for NVMe devices, it's between 128 and 1024 NVMe commands per queue.

**Comment by xxks-kkk** [comment]
Thanks for the help!
