### ISSUE TITLE
Cant use vfio on EC2 instance

### ISSUE THREAD

**Issue by kreuzerkrieg** [spdk/spdk#594]
Hi,
I have EC2 instance (m5d.2xlarge) with NVMe disks. Then I set the environment variable DRIVER_OVERRIDE=vfio-pci 
Just for test run `nvme list` and get 

> Node             SN                   Model                                    Namespace Usage                      Format           FW Rev  
> ---------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
> /dev/nvme0n1     AWS1166E44E880DFD41B Amazon EC2 NVMe Instance Storage         1         300.00  GB / 300.00  GB    512   B +  0 B   0
> /dev/nvme1n1     vol094712008d8d18e2a Amazon Elastic Block Store               1           0.00   B /   8.59  GB    512   B +  0 B   1.0 
> 

Then I run `sudo -E ~/spdk/scripts/setup.sh` and get the following output

> Active mountpoints on /dev/nvme1n1, so not binding PCI dev 0000:00:04.0
> 0000:00:1f.0 (1d0f cd01): nvme -> vfio-pci
> 
> Current user memlock limit: 1048576 MB
> 
> This is the maximum amount of memory you will be
> able to use with DPDK and VFIO if run as current user.
> To change this, please adjust limits.conf memlock limit for current user.

And then, just to be sure `sudo -E ~/spdk/scripts/setup.sh status` with the following output

> Hugepages
> node     hugesize     free /  total
> node0   1048576kB        0 /      0
> node0      2048kB     1024 /   1024
> NVMe devices
> BDF		Numa Node	Driver name		Device name
> 0000:00:04.0	0		nvme			nvme0
> 0000:00:1f.0	0				-
> I/OAT DMA
> BDF		Numa Node	Driver Name
> virtio
> BDF		Numa Node	Driver Name		Device Name

Looks like the setup did not pick the device, it is not using kernel driver anymore, but it didnt get attached to SPDK NVMe driver

All the above works with `uio_pci_generic`.

OS: Ubuntu, 18.04.1
kernel: 4.19.0-rc6 (AFAIR it doesnt work with vanilla either)
 SPDK v19.01-pre / DPDK 18.08.0 (happens with current master)

**Comment by benlwalker** [comment]
When you run `sudo -E ~/spdk/scripts/setup.sh` does dmesg have any interesting output? Does your EC2 instance have an IOMMU?

**Comment by kreuzerkrieg** [comment]
Back then, when the question was asked I did not find anything interesting, will re-check tomorrow, meanwhile if you have ideas what additional stuff I can check, let me know, will do as soon as I return to office

Looks like initially it didn’t have IOMMU enabled, then I enabled it using kernel start up options, will check what exactly I’ve used back then 

Sent from Mail for Windows 10

**Comment by kreuzerkrieg** [comment]
Now I see following:

> Jan 24 07:37:07 ip-172-31-13-147 kernel: [  395.975686] VFIO - User Level meta-driver version: 0.3
> Jan 24 07:37:07 ip-172-31-13-147 kernel: [  396.278863] vfio-pci: probe of 0000:00:1f.0 failed with error -22
> Jan 24 07:37:07 ip-172-31-13-147 kernel: [  396.278897] vfio-pci: probe of 0000:00:1f.0 failed with error -22
> Jan 24 07:38:47 ip-172-31-13-147 kernel: [  496.251176] vfio-pci: probe of 0000:00:1f.0 failed with error -22
> Jan 24 07:38:47 ip-172-31-13-147 kernel: [  496.251217] vfio-pci: probe of 0000:00:1f.0 failed with error -22

As well, IOMMU is enabled according to dmesg

> Jan 14 06:13:47 ip-172-31-13-147 kernel: [    0.000000] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-4.15.0-1031-aws root=UUID=bbf64c6d-bc15-4ae0-aa4c-608fd9820d95 ro console=tty1 console=ttyS0 nvme.io_timeout=4294967295 intel_iommu=on
> Jan 14 06:13:47 ip-172-31-13-147 kernel: [    0.000000] DMAR: IOMMU enabled

I'm attaching the whole file in case you want to inspect it
[kern.log](https://github.com/spdk/spdk/files/2790651/kern.log)

**Comment by darsto** [comment]
Bug scrub: we already have plans to run some tests on EC2. @Seth5141 to try to run initial tests.

**Comment by Seth5141** [comment]
@kreuzerkrieg I apologize to have takenso long to get back to you on this one. It took me a bit to get spun up with AWS.
I brought up an m5d.large instance and enabled the IOMMU instance in the same way that you did. However, there is no real IOMMU in the machine, and virtualization has been disabled (try cat /proc/cpuinfo | grep svm). That also explains why you had to use DRIVER_OVERRIDE=vfio-pci, when we detect that /sys/kernel/iommu_groups is not empty, we try to probe that driver by default. 
I am not 100% sure what your use case is, and if you specifically needed to use the IOMMU, but it looks like this will not be an option for the m5d instances. Depending on your use-case, next steps might be one of the following:
1. If you really need access to the IOMMU, you may have to use an i3.metal instance which will for sure have an IOMMU, but ma be pricey.
2. If you aren't worried about using the IOMMU, but just need to bind to something so that you can run tests, etc. and found that uio_pci_generic wasn't included in your OS (my experience) you can build the igb_uio driver with SPDK and insert it into the kernel. I am going to work on a couple patches to setup.sh to make this process more intuitive and upload links here.

**Comment by Seth5141** [comment]
Please see the following issue for some more information on igb_uio and uio_pci_generic https://github.com/spdk/spdk/issues/210

**Comment by kreuzerkrieg** [comment]
@Seth5141, no rush, I'm happily live with `uio_pci_generic` for a month or so. Glad you got to the AWS stuff, because I was feeling I'm exploring kind of terra incognita, didn't find any information about SPDK in the cloud on the net.
Regarding IOMMU, I guess there is no sense to try other storage optimized instances since (my guess) I will run into the same problem. As for i3 metal instances, yes, it is pricy, I dont really know what are `vfio` benefits compared to the `uio`, so, I'm not sure we want to pay the price. In any case `cat /proc/cpuinfo | grep svm` is a useful input since I guess at some point we will try to run the same code in the Azure/Google Cloud, where the IOMMU may be available. 

Regarding the setup.sh, it is another story. Whatever you are going to do with it is appreciated, once it is more intuitive it is a great thing. My five cents here. If we got to the cloud, lets talk Kubernetes and pods. It is native environment for running stuff in cloud. Consider make it runnable in pods (actually docker instances) Today, setup.sh modprobes vfio/uio, as far as I understand you cant do it in pod, so I have to change the setup.sh and disable modprobing. One have to modprobe in the host, not in the pod, and then run the script (essentially the same setup.sh with modprobe commented out) in the pod. Second, I learned it a hard way that I have to remount /dev and /sys in r/w mode. It will save a lot of time for the next person trying to run SPDK in pod if you could detect and report these issues (read only fs parts SPDK needs) in the setup.sh. See details [here](https://github.com/spdk/spdk/issues/597)
Same goes for hugepages, EAL tests for hugepages accessibility, not sure if it is setup.sh or EAL duty to check it, but both fail in detecting hugepages problems in the pod, like I have it on the host, but not mounted it to the pod, then EAL fails with some esoteric segmentation fault deep inside DPDK. If the problem could be detected in setup.sh/DPDK (when initializing) it would save a time in diagnosing the problem.

**Comment by kreuzerkrieg** [comment]
> Please see the following issue for some more information on igb_uio and uio_pci_generic #210

We have `uio` since we provide it in our own AMI. What the deal with `igb_uio`? Any particular reason I have to prefer it over `uio`? `vfio`?

**Comment by Seth5141** [comment]
@kreuzerkrieg 
If you are using SPDK (especially the NVMe driver) in a production environment, you will absolutely want to use vfio-pci for security reasons. VFIO places your NVMe drive behind the IOMMU and prevents it from doing nefarious things to memory it shouldn't be accessing. The following is a good intro to vfio-pci: https://www.kernel.org/doc/Documentation/vfio.txt. You may also want to look up DMA attacks for information on how DMA can be exploited without an IOMMU.
As far as igb_uio and uio_pci_generic go I don't know that there are any significant differences for our purposes. We typically use uio_pci_generic because it is in tree in the kernel. But if it doesn't happen to exist natively in a given distro and you can't find a package to download the module, you can build the igb_uio driver locally from the dpdk submodule.

If you are interested, here are the patches related to setup.sh that I have started: https://review.gerrithub.io/#/c/spdk/spdk/+/444122/

Thank you for the information about docker containers and hugepages. I think supporting some of those features in setup.sh would be useful. Have you created an enhancement request here on GitHub for those features?

**Comment by kreuzerkrieg** [comment]
> Thank you for the information about docker containers and hugepages. I think supporting some of those features in setup.sh would be useful. Have you created an enhancement request here on GitHub for those features?

Nope, since I was not sure you guys gonna pursuit the path of cloud/containers. Should I create such a request now?

**Comment by kreuzerkrieg** [comment]
>However, there is no real IOMMU in the machine, and virtualization has been disabled (try cat /proc/cpuinfo | grep svm). That also explains why you had to use DRIVER_OVERRIDE=vfio-pci, when we detect that /sys/kernel/iommu_groups is not empty, we try to probe that driver by default.

BTW, shouldnt it be `grep vmx` for Intel or just `grep -E 'svm|vmx' for AMD|Intel?

**Comment by Seth5141** [comment]
Ah, you're right, thanks. I mixed those two up in my response.
Yeah, go ahead and open an enhancement request.  We aren't sure if we are going to use Docker in the test pool, but it's something that has been tossed around. Besides, we want to enable as many testing configurations as possible.
I am going to close this one since we have gotten to the bottom of why VFIO doesn't work on your EC2 instance, but please open up the enhancement request with the details you mentioned above so that we don't lose them.

**Comment by kreuzerkrieg** [comment]
Will do
