### ISSUE TITLE
Clone based on non-existing snapshot

### ISSUE THREAD

**Issue by mkrzywie** [spdk/spdk#631]
After creating 2 snapshots of lvol, decoupling it from snapshot and removal of snapshots we have bdev that is clone based on just removed snapshot.

## Expected Behavior
In result of this operation chain we should get thick provisioned lvol that is neither clone or snapshot

## Current Behavior
We got lvol that is clone based on non existing (deleted) snapshot 

## Possible Solution
1. Inflate clone when removing it's parent snapshot
or
2. Block deletion of snapshot that is parent for clone.

## Steps to Reproduce
1. scripts/rpc.py construct_lvol_bdev lvol2 25 -l lvs
2. scripts/rpc.py snapshot_lvol_bdev lvs/lvol2 snap4
3. scripts/rpc.py snapshot_lvol_bdev lvs/lvol2 snap5
 
4. scripts/rpc.py decouple_parent_lvol_bdev lvs/lvol2
5. scripts/rpc.py delete_bdev lvs/snap5
6. scripts/rpc.py delete_bdev lvs/snap4

7. scripts/rpc.py get_bdevs

## Context (Environment including OS version, SPDK version, etc.)
SPDK 18.10.1
OS: Ubuntu 18.04

**Comment by tomzawadzki** [comment]
@mkrzywie Thank you for submitting the issue.

First of all, please do not use _delete_bdev_ RPC. It was intended only for debug purpose and all bdev modules have separate calls. Its intention was to allow simulating hot-remove event, which cannot happen from 'inside' lvol virtual bdev - only bdev lvol store is based on can be hot-removed. **This is what caused incorrect listing in _get_bdevs_ RPC.**
Please use **_destroy_lvol_bdev_** RPC.

Contrary to what one might understand at first glance from [documentation](https://spdk.io/doc/logical_volumes.html#lvol_inflation). **_decouple_parent_lvol_bdev_** removes **single dependency in chain**, rather than all the way down. In your case this means that after single call to decouple, lvs/lvol2 is no longer dependent on snap5, but it still points to snap4 as its parent. This will allow to call **_destroy_lvol_bdev_** on snap5, yet snap4 will not be able to be destroyed until lvs/lvol2 is decoupled from snap4 as well (by calling it again). **Sorry for the confusion, I will submit patch clarifying documentation for this.**

One could call inflate as noted in Possible Solutions section, since this one actually _removes all dependencies down the chain_. This results in thick provisioned clone. If keeping thin-provisioning as much as possible is expected, then multiple decouple calls will help with this.

**Comment by tomzawadzki** [comment]
Submitted patch clarifying docs for decouple functionality [here](https://review.gerrithub.io/#/c/spdk/spdk/+/442848/).

@mkrzywie Please let me know if changing to destroy_lvol_bdev RPC and keeping the actual functionality of decouple in mind resolves the issue.

**Comment by mkrzywie** [comment]
I verified that destroy_lvol_bdev method doesn't cause this error. 
Thanks for clarification.
