### ISSUE TITLE
QOS test failure in CI

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#651]
Seems unrelated to the patch, I'm going to retrigger to get it moving and will dig more into this later if nobody grabs it in the meantime.  Here is the log https://ci.spdk.io/spdk-jenkins/results/autotest-per-patch/builds/21945/archive/RBD_autotest/build.log

**Comment by jimharris** [comment]
I'm assigning it to @Comphix for now.

Gang - please take a look at other test runs, and see if the QoS result is too low.  We allow 5% discrepancy, but really there's no reason it shouldn't be much smaller than that.

**Comment by jimharris** [comment]
Running this iSCSI QoS locally on my system, with a debug/asan/ubsan enabled build, I get 20.02 MB/s (vs. 20.00 MB/s expected).

**Comment by jimharris** [comment]
Similar iSCSI QoS failure here:

https://ci.spdk.io/spdk-jenkins/results/autotest-per-patch/builds/22008/archive/iscsi_autotest/build.log

**Comment by jimharris** [comment]
And here:

https://ci.spdk.io/spdk-jenkins/results/autotest-per-patch/builds/22013/archive/RBD_autotest/build.log

**Comment by jimharris** [comment]
https://ci.spdk.io/spdk-jenkins/results/autotest-per-patch/builds/22007/archive/RBD_autotest/build.log

**Comment by jimharris** [comment]
I suspect this is all because we're running all of these tests in a VM, and for some reason the virtual core running the iSCSI target gets limited in some way that it can't even hit the very limited QoS limit.

@peluse, @karlatec @Seth5141 On the bare metal systems, how are we allocating the cores assigned to the build pool VMs?

**Comment by karlatec** [comment]
VMs are configured via virt-manager / virsh. Host CPU passthru, 16 cores. Specific cores are not set, so VMs may share CPUs in case of high intensity activity.
Relevant Qemu args from ps aux:
```
-cpu host,+vmx 
-smp 16,sockets=16,cores=1,threads=1 
```

**Comment by jimharris** [comment]
I'm spent more time looking at this today.  I was able to reproduce the general problem on my bare metal host.  It's not 100% reproducible, but if I run the qos.sh test a few times in succession, one of them will run at a much lower I/O rate overall.  It's not specific to QoS, but this qos.sh test is really the only one in our per-patch tests that is performance sensitive.

I think the best solution is to make qos a bdev test rather than iSCSI.  We don't need iSCSI for this test - and from my investigation, it's the iSCSI part of this that's resulting in extra kernel code running on the SPDK core running the iscsi_tgt.  It's clear (at least on my system) that when we're running at lower performance, core 0 has a much higher rate of time spent on soft irqs ("si" in top).

I added "isolcpus=0" to my kernel command line, and this completely fixed the problem on my system.  This ensured this extra code did not run on core 0.

isolcpus is a good idea in general, but I don't think that's the right fix here.  Let's have qos.sh start bdevperf to run for a very long period of time.  This replaces starting the iscsi_tgt.

1) Create a patch to modify bdevperf to start the RPC server.
2) Start bdevperf for a very long period of time.  Maybe 3600 seconds.
3) Use the same check_qos_works_well function in qos.sh, but instead of running fio.py, just sleep for X number of seconds.

**Comment by pawelwod** [comment]
The same issue here 
https://ci.spdk.io/spdk-jenkins/results/autotest-per-patch/builds/22297/archive/RBD_autotest/build.log

Failed in
```
 05:03:51	# '[' true = true ']'
  05:03:51	# echo '20000*0.95 < 18731 && 18731 < 20000*1.05'
  05:03:51	# bc
 05:03:51	# retval=0
 05:03:51	# '[' 0 -eq 0 ']'
 05:03:51	# echo 'Failed to limit the io read rate of malloc bdev by qos'
Failed to limit the io read rate of malloc bdev by qos
```

```
   33  	run_test suite ./test/iscsi_tgt/fio/fio.sh
=> 34  	run_test suite ./test/iscsi_tgt/qos/qos.sh
   35  	run_test suite ./test/iscsi_tgt/ip_migration/ip_migration.sh
```

**Comment by Comphix** [comment]
@jimharris , based on your comment, this looks like not stable with the iSCSI testing due to the kernel operations, so that we'd like to use the bdevperf? Is this understanding correct? If so, I will work on that. Thanks, Gang

**Comment by jimharris** [comment]
Hi @Comphix - yes, that is correct.

On a related note, currently the QoS tests do not test any of the inter-thread operations.  Let's first do the patches above, but then I think the test should be modified to:

1) create malloc bdev
2) create split bdevs from the malloc bdev
3) test qos on the malloc bdev (not the split bdev)

**Comment by darsto** [comment]
@Comphix was there any update?

**Comment by Comphix** [comment]
Working on one patch to enhance the current QoS testing with iSCSI.
https://review.gerrithub.io/#/c/spdk/spdk/+/447133/

Later will drive the other changes.

**Comment by Comphix** [comment]
Related patch to fix the iSCSI testing failure with QoS has been merged.

https://review.gerrithub.io/#/c/spdk/spdk/+/447133/ 

Please monitor this and if this is no longer there, please help to close this issue.

Thanks,
Gang
