### ISSUE TITLE
Retrieving QP status string

### ISSUE THREAD

**Issue by kreuzerkrieg** [spdk/spdk#657]
I want to report errors in my application, `spdk_nvme_cpl` `status` contains status code and type, which is not too verbose, looks like `get_status_string` is a good bet but for some reason it is static free function that I cant use because of internal linkage. Did I miss a function that can translate status code to string or there is no such a thing in SPDK (publicly available)? May we have this function exposed?

**Comment by jimharris** [comment]
I don't have a problem with exporting this function.  How about spdk_nvme_cpl_get_status_string?

I think I'd prefer the exported function to take a struct spdk_nvme_cpl pointer as a parameter, instead of the raw uint16_ts.  Then just change the single caller in nvme_qpair.c to use the new function signature.

Let us know if you'd like to submit a patch for this.  If not, someone else will surely pick it up.

-Jim

**Comment by kreuzerkrieg** [comment]
Will try to submit the patch tomorrow

**Comment by kreuzerkrieg** [comment]
Pushed for review

First time using gerrit, so dont smack me in my face right away :)

**Comment by jimharris** [comment]
Thanks @kreuzerkrieg!  Don't worry - we will take it easy on you.  :-)

**Comment by jimharris** [comment]
FYI for others - patch is here:  https://review.gerrithub.io/c/spdk/spdk/+/444519/1

**Comment by jimharris** [comment]
Overall the patch looks great.  I just posted a couple of minor feedback items.  You can update the patch and push it to GerritHub again - just edit your existing patch (keeping the same Change-Id) and Gerrit will keep the new version associated with version 1.  Please reach out if you have any questions on pushing a new version of the patch.
