### ISSUE TITLE
"Ceph rbd" information should be hidden when use "lsscsi"

### ISSUE THREAD

**Issue by liupan1111** [spdk/spdk#66]
When I use spdk iscsi to create a lun for a ceph image, then discovery, login....

When I input "isscsi", it will display "INTEL" and "Ceph rbd":
[14:0:0:0]   disk    Intel    Ceph rbd         0001  /dev/sdc

I looked up the usage of isscsi, it says: 

_"**iSCSI**

The lsscsi command won't show anything iSCSI related on a machine with a iSCSI target running (either as a kernel driver or as a user space daemon). The following output is from a machine running a iSCSI initiator with a session established:
$ lsscsi
[2:0:0:0]    disk    IET      VIRTUAL-DISK     0     /dev/sda"_

I tried the well-known open-source tgtd, which supports librbd also, the result is same as the usage of iscsi.

In my opinion, at last, we shouldn't display "Ceph rbd": the user doesn't need to care which storage software in the back end. Only one thing is: OK, I get a new sdX now.  The admin may want to know which image/pool this sdx maps to, and we need to supply another tool(may be enhance rpc.py) to satisfy. "

@dverkamp-intel @optimistyzy,

What is your opinion? If you agree, I could pull a request to resolve it.

Thanks
Pan

**Comment by dverkamp-intel** [comment]
The information printed by lsscsi is the SCSI vendor and product name information generated by the SCSI bdev translation layer: https://github.com/spdk/spdk/blob/8b449060ebf94848f8fc7dd6e7614be0dd63b6de/lib/scsi/scsi_bdev.c#L275-L304

This is using whatever the bdev provides as product_name and name.

What information would you expect to see here?  I'm not clear what the issue is.
