### ISSUE TITLE
[Jenkins] Files not getting copied for external access

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#667]
https://ci.spdk.io/spdk-jenkins/public_build/autotest-per-patch_22831.html

https://ci.spdk.io/spdk-jenkins/public_build/autotest-per-patch_22835.html

Both of these finished hours ago.

**Comment by jimharris** [comment]
Is it possible that these results already got purged?  I'm not able to read related files through the internal status page either.

I am able to see the files directly from the Jenkins UI.

**Comment by peluse** [comment]
I can take a quick look but Pawel/Karol may need to investigate further

**Comment by peluse** [comment]
Looking at the Console Output fro the job there are Jave and Hudson exceptions that occur at the start of the archiving.  I suspect this is why but can't comment on root cause.  We've seen other general Java exceptions that result in failure and I've suggested before that we try and figure out how to catch those and somehow communicate "internal error" on the status page so it doesn't look like a real test failure w/missing logs.

**Comment by jimharris** [comment]
This seems to be fixed.
