### ISSUE TITLE
NVMeOF performance degradation between 18.10 and 19.01

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#699]
## Current Behavior
Performance drop for NVMeOF feature between 18.10 and 19.01 releases.

## Steps to Reproduce
1. 0b20f2e55 nvmf/rdma: Remove data buffer num dependency on SPDK_NVMF_MAX_SGL_ENTRIES
2. Build with: 
```
git submodule update --init; ./configure --with-fio=/usr/src/fio --with-rdma; make clean; make -j100
```
3. Performance test setup:
```
(Configuration from NVMeOF Benchmarking report TC #1)
SPDK NVMeOF with 16 NVMe drives, 16 NVMeOF subsystems (each has 1 NVMe as namespace). 8 subsystems listening on RDMA NIC 1, latter 8 subsystems listening on NIC2. Using 4 CPU cores for target.

2 separate servers working as SPDK NVMeOF initiators. Each connecting to 8 serparate subystems.
```
4. On both initiators connect to target with fio bdev plugin and run workload:
```
[global]
ioengine=/tmp/spdk/examples/bdev/fio_plugin/fio_plugin
spdk_conf=/home/sys_sgci/repro_configs/bdev.conf
thread=1
group_reporting=1
direct=1
norandommap=1
rw={read/rw}
rwmixread=70
bs=128k
iodepth=8
time_based=1
ramp_time=30
runtime=180

[filename0]
filename=Nvme0n1
[filename1]
filename=Nvme1n1
[filename2]
filename=Nvme2n1
[filename3]
filename=Nvme3n1
[filename4]
filename=Nvme4n1
[filename5]
filename=Nvme5n1
[filename6]
filename=Nvme6n1
[filename7]
filename=Nvme7n1
```
5. Performance results:
read: 156k IOPS / 19134 MBps BW / 875usec avg lat
rw: 82k IOPS / 10194 MBps BW / 1570 usec avg lat

6. Re-run test workload with 1 commit before that (8b4534e43 nvmf_rdma: When destroying a qpair, fail the I/O.)
read: 200k IOPS / 26931 MBps BW / 637 usec avg lat
rw: 241k IOPS / 32216 MBps BW / 528 usec avg lat

## Context (Environment including OS version, SPDK version, etc.)
Affects SPDK since: 0b20f2e55

**Comment by Seth5141** [comment]
Thanks for doing this @karlatec! It looks like that change lowered the default number of buffers significantly. This change (https://review.gerrithub.io/c/spdk/spdk/+/446525) fixes that. I think it's good to keep the higher default to avoid discrepancies.
Good news is num_shared_buffers is a user configurable value so you can change your transport create rpc command to get the proper performance on vanilla 19.01.
~~~
rpc.py nvmf_create_transport -t RDMA -n 4096
~~~
You could just put a note in the test file that changing the RPC like this gives an apples to apples comparison between the two tests.

As a tangent, I think it would be fun to see what the performance profile looks like as we scale that number up and down. My gut feeling is that we see a linear increase until we get to the number that saturates all of the qpairs. But I wonder if there might be a law of diminishing returns thing there since not all requests will be in the same state at once. Doing a performance analysis like that might be useful for developing heuristics for customers trying to minimize their memory footprint. Minimizing memory footprint is something some users have been looking at recently with features like shared receive queue.

**Comment by karlatec** [comment]
Seth, I quickly re-tested 19.01 with RPC parameter suggestion.
Results are better, but still worse than 18.04.
For 128k rw QD=8:
165k IOPS, ~2100MBps, 1500usec avg_lat. 

Please mind that this was just a quick-retest, I will re-run the whole test suite soon.

**Comment by karlatec** [comment]
Adding this for the record, I already mentioned this in email communitaion.
Re-tested previously mentioned workloads with current 19.01.1 backport. 
Results:
```
128k read qd=8
19.01 ---> 160k IOPS / 19995MBps / 801 usec avg_lat
19.01.X HEAD (792b36e89) ---> 200k IOPS / 24940MBps / 641 usec avg_lat
19.01.X (7838bb3a1) (not merged) ---> 200k IOPS / 24938MBps / 641 usec avg_lat

128k rw qd=8; 70%read
19.01 ---> 80k IOPS / 10029MBps / 3190 usec avg_lat
19.01.X HEAD (792b36e89) ---> 243k IOPS / 21321MBps / 670 usec avg_lat
19.01.X (7838bb3a1) (not merged) ---> 243k IOPS / 30273MBps / 527usec avg_lat
```

So I think we're looking good for perf benchmarking using 19.01.1

**Comment by darsto** [comment]
Bug scrub: let's leave the issue open till 19.01.1 is released.

**Comment by karlatec** [comment]
@darsto 19.01.1 is out, results look pretty good so I guess we can close this one

**Comment by nagendra-v** [comment]
@karlatec 
Question on code base which has performance fixes.
I don't see [0b20f2e](https://review.gerrithub.io/c/spdk/spdk/+/437808) changes in github master or 19.01.0x branches. 
In your comment you mentioned "19.01.X (7838bb3a1) (not merged) ---> 243k IOPS / 30273MBps / 527usec avg_lat. Just wondering which code base you are referring here.

**Comment by karlatec** [comment]
@nagendra-v 

> I don't see 0b20f2e changes in github master or 19.01.0x branches.
```
klateck@GrizzlyPass7:~/work/spdk$ git branch | grep ^\* && git log --oneline 0b20f2e -n 1
* master
0b20f2e nvmf/rdma: Remove data buffer num dependency on SPDK_NVMF_MAX_SGL_ENTRIES

klateck@GrizzlyPass7:~/work/spdk$ git branch | grep ^\* && git log --oneline 0b20f2e -n 1
* v19.01.x
0b20f2e nvmf/rdma: Remove data buffer num dependency on SPDK_NVMF_MAX_SGL_ENTRIES
```

> In your comment you mentioned "19.01.X (7838bb3) (not merged) ---> 243k IOPS / 30273MBps / 527usec avg_lat. Just wondering which code base you are referring here.

As for the 7838bb3 commit - it's actually this [change](https://review.gerrithub.io/#/c/spdk/spdk/+/447622). Commit hash I used in comment was out-of-date as the commit was patched several times.

**Comment by nagendra-v** [comment]
@karlatec 
Thanks for the information, looks like 19.04 has the changes.
