### ISSUE TITLE
One queue per thread limitation

### ISSUE THREAD

**Issue by hlitz** [spdk/spdk#7]
The spdk does not expose queues to the user. Instead it assignes one queue per thread. Now, if I want to handle 1000 concurrent streams I can either spawn 1000 threads or use number of core threads (say 32) and do stream to nvme queue multiplexing in software. How does spdk map the 65K virtual queues to the (32) hardware queues? Is there any advantage in performance in letting the spdk/nvme doing the multiplexing over doing it in software? Running too many threads has its own issues so I would like to limit their number to the amount of cores.

**Comment by bwalker-intel** [comment]
We're open to an API change that exposes queue selection to the user, but we haven't yet because we are attempting to provide an API that forces developers to make the best decisions in terms of threading model for their application. 

There is absolutely no advantage gained **in the device itself** (for the devices we have available today) for using more than one queue. Multiple queues provide an advantage only on the host software side where software can do simultaneous submissions without taking a lock or sharing states. Therefore, the most reasonable threading model is to assign one queue per thread. That is why our API is forcing you into this model - it's almost certainly the right choice. That said, don't be surprised if we do make a change to allow explicit management of queues in the future, especially if devices start to benefit from additional concurrency.

As far as your question about virtual queues, everything in SPDK is a hardware queue. There is no concept of virtual queues. Therefore, if your device supports 32 hardware queues, you cannot initialize more than 32 threads for I/O with SPDK. You can certainly implement a virtual queue system in your application software though.

We highly recommend that you structure your software around one thread per CPU core and pass messages between them, essentially following a [shared nothing architecture] (https://en.wikipedia.org/wiki/Shared_nothing_architecture) where each CPU core is a node. This is the model that will yield the best performance when paired with our asynchronous, poll-mode drivers.
