### ISSUE TITLE
nvme_sigbus_fault_sighandler should not rely on thread-local storage

### ISSUE THREAD

**Issue by Mic92** [spdk/spdk#712]
Currently SPDK uses a thread-local storage variable to store the current nvme controller in a variable to access in case of an segfault the same from the segfault [handler](https://github.com/spdk/spdk/blob/f1da65ef283b9016e3a6362ac15044659f30a381/lib/nvme/nvme_pcie.c#L210). However there is no guarantee from operating system that signal handler, will be processed by the same thread that triggered the [segfault](http://man7.org/linux/man-pages/man7/signal.7.html):

> A process-directed signal may be delivered to any
> one of the threads that does not currently have the signal blocked.
> If more than one of the threads has the signal unblocked, then the
> kernel chooses an arbitrary thread to which to deliver the signal.

## Expected Behavior

SPDK should likewise DPDK iterate through all available devices and compare the bar address with the address given to the fault handler. This was suggested by @darsto 

## Current Behavior

SPDK by chance uses the right NVME controller if the correct thread
is scheduled to the handle the signal.

## Steps to Reproduce
I have not actually confirmed this bug as I only have one controller.

## Context (Environment including OS version, SPDK version, etc.)

Linux, spdk @ 6ff6f6d6f8fa6891737ed8b4e194dd1d3918c927

**Comment by jimharris** [comment]
But just before that quoted text from signal(7) is this:

A signal may be generated (and thus pending) for a process as a whole (e.g., when sent using kill(2)) or for a specific thread (e.g., certain signals, such as SIGSEGV and SIGFPE, generated as a consequence of executing a specific machine-language instruction are thread directed, as are signals targeted at a specific thread using pthread_kill(3)).

The SIGBUS handler clearly falls into the "specific thread" category, since it is triggered by a "machine-language instruction" executed by that thread - i.e. writing to the doorbell on the NVMe SSD.

**Comment by Mic92** [comment]
Ok. Then this is a non-issue.
