### ISSUE TITLE
Performance very slow ...

### ISSUE THREAD

**Issue by ack72tdp** [spdk/spdk#731]
After issue #704 is resolved .. 

SPDK based nvme devices seems to perform really bad .. compared to the nvme devices created using kernel drivers .. both are using MaxQueuesPerSession 16

linux-qgd9:~ # lsblk
NAME     MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
nvme2n1  259:4    0   200G  0 disk  // created using SPDK
nvme3n1  259:5    0   200G  0 disk  // created using SPDK
nvme0n1  259:0    0   304G  0 disk  // created using KERNEL 
nvme1n2  259:3    0   304G  0 disk  // created using KERNEL

sudo fio --name=read_bandwidth_test --filename=/dev/nvme2n1 --filename=/dev/nvme3n1  --filesize=200G --time_based --ramp_time=2s --runtime=1m --ioengine=libaio --direct=1 --verify=0 --randrepeat=0 --numjobs=4 --bs=4K --iodepth=64 --rw=randread --group_reporting

//SPDK results for random read 4k with FIO 
IOPS=3671, BW=14.4MiB/s (15.1MB/s)

read_bandwidth_test: (groupid=0, jobs=4): err= 0: pid=71890: Thu Mar 28 10:25:35 2019
  read: IOPS=3671, BW=14.4MiB/s (15.1MB/s)(862MiB/60014msec)
    slat (nsec): min=0, max=3481.7k, avg=6244.45, stdev=26727.99
    clat (nsec): min=0, max=1143.2M, avg=69652375.30, stdev=223205585.77
     lat (nsec): min=0, max=1143.2M, avg=69658809.53, stdev=223205382.78
    clat percentiles (msec):
     |  1.00th=[   13],  5.00th=[   13], 10.00th=[   14], 20.00th=[   14],
     | 30.00th=[   14], 40.00th=[   14], 50.00th=[   15], 60.00th=[   15],
     | 70.00th=[   15], 80.00th=[   16], 90.00th=[   20], 95.00th=[  927],
     | 99.00th=[ 1011], 99.50th=[ 1053], 99.90th=[ 1150], 99.95th=[ 1150],
     | 99.99th=[ 1150]
   bw (  KiB/s): min=    0, max= 9312, per=40.09%, avg=5893.89, stdev=3101.09, samples=299
   iops        : min=    0, max= 2328, avg=1473.45, stdev=775.28, samples=299
  lat (msec)   : 10=0.10%, 20=90.16%, 50=4.16%, 100=0.01%, 1000=4.05%
  cpu          : usr=0.36%, sys=0.79%, ctx=211645, majf=0, minf=58
  IO depths    : 1=0.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=100.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.1%, >=64=0.0%
     issued rwts: total=220312,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=64

Run status group 0 (all jobs):
   READ: bw=14.4MiB/s (15.1MB/s), 14.4MiB/s-14.4MiB/s (15.1MB/s-15.1MB/s), io=862MiB (903MB), run=60014-60014msec

Disk stats (read/write):
  nvme2n1: ios=115944/0, merge=0/0, ticks=8141512/0, in_queue=8143148, util=99.90%
  nvme3n1: ios=115949/0, merge=0/0, ticks=7725732/0, in_queue=7727720, util=99.93%

Compared to NVME targets created using the same block devices with standard kernel drivers..

sudo fio --name=read_bandwidth_test --filename=/dev/nvme0n1 --filename=/dev/nvme1n2  --filesize=200G --time_based --ramp_time=2s --runtime=1m --ioengine=libaio --direct=1 --verify=0 --randrepeat=0 --numjobs=4 --bs=4K --iodepth=64 --rw=randread --group_reporting

//NVME KEREL DRIVERS results for random read 4k with FIO 
IOPS=146k, BW=571MiB/s (599MB/s)

read_bandwidth_test: (groupid=0, jobs=4): err= 0: pid=20885: Mon Mar 18 11:14:17 2019
  read: IOPS=146k, BW=571MiB/s (599MB/s)(33.5GiB/60009msec)
    slat (nsec): min=0, max=402739, avg=4337.69, stdev=2045.93
    clat (nsec): min=0, max=250136k, avg=1744551.66, stdev=1861786.35
     lat (nsec): min=0, max=250139k, avg=1749027.86, stdev=1861805.53
    clat percentiles (usec):
     |  1.00th=[  359],  5.00th=[  416], 10.00th=[  461], 20.00th=[  562],
     | 30.00th=[  725], 40.00th=[  955], 50.00th=[ 1237], 60.00th=[ 1614],
     | 70.00th=[ 2089], 80.00th=[ 2671], 90.00th=[ 3589], 95.00th=[ 4490],
     | 99.00th=[ 6980], 99.50th=[ 8455], 99.90th=[17433], 99.95th=[22938],
     | 99.99th=[63701]
   bw (  KiB/s): min=    0, max=174664, per=25.00%, avg=146258.85, stdev=17554.89, samples=480
   iops        : min=    0, max=43666, avg=36564.70, stdev=4388.72, samples=480
  lat (usec)   : 250=0.01%, 500=14.55%, 750=16.80%, 1000=10.39%
  lat (msec)   : 2=26.53%, 4=24.49%, 10=6.96%, 20=0.21%, 50=0.06%
  lat (msec)   : 100=0.02%, 250=0.01%, 500=0.01%
  cpu          : usr=8.68%, sys=20.12%, ctx=5215528, majf=0, minf=7103
  IO depths    : 1=0.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=100.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.1%, >=64=0.0%
     issued rwts: total=8776699,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=64

Run status group 0 (all jobs):
   READ: bw=571MiB/s (599MB/s), 571MiB/s-571MiB/s (599MB/s-599MB/s), io=33.5GiB (35.9GB), run=60009-60009msec

Disk stats (read/write):
  nvme0n1: ios=4490093/0, merge=0/0, ticks=7884060/0, in_queue=7951512, util=100.00%
  nvme1n2: ios=4490100/0, merge=0/0, ticks=7883676/0, in_queue=7938212, util=100.00%

Any thoughts?

Thanks

**Comment by ack72tdp** [comment]
Config file is default .. nothing changed ..  except these ..
app/nvmf_tgt/nvmf_tgt -c etc/spdk/nvmf.conf.in -L RDMA

[Malloc]
  NumberOfLuns 2
  LunSizeInMB 64

[Transport]
  MaxQueuesPerSession 16

[Subsystem2]
  NQN nqn.2016-06.io.spdk:cnode2
  Listen RDMA 192.168.1.50:4422
  AllowAnyHost yes
  Host nqn.2016-06.io.spdk:init
  SN SPDK00000000000002
  #Namespace Malloc0
  #Namespace Malloc1
  Namespace AIO0
  #Namespace AIO14^Z^Z
[Subsystem3]
  NQN nqn.2016-06.io.spdk:cnode3
  Listen RDMA 192.168.2.50:4423
  AllowAnyHost yes
  Host nqn.2016-06.io.spdk:init
  SN SPDK00000000000003
  #Namespace Malloc0
  #Namespace Malloc1
  Namespace AIO1
  #Namespace AIO1

**Comment by Seth5141** [comment]
@ack72tdp It looks like subsystem 2 and subsystem 3 in your SPDK configuration are exposing linux aio bdevs. I believe that's what the nvme2n1 and nvme3n1 you are testing against in the spdk case are.
If you kept the SPDK configuration file the same as nvmf.conf.in, but modified the BDFs to point to the NVMe drives you wanted to test and properly unbound them from the kernel NVMe driver, I would expect them to be exposed as nvme0n1 and nvme0n2.

The configuration files supplied in the spdk directory are meant to show a sampling of possible configurations and options you can put together. I would recommend paring your configuration file down to just the sections you need.
[Nvmf]
.
.
.
[Transport]
.
.
.
[Nvme]
  TransportID "trtype:PCIe traddr:BDF0" Nvme0
  TransportID "trtype:PCIe traddr:BDF1" Nvme1
[Subsystem1]
.
.
.
[Subsystem2]
.
.
.

Removing all references to AIO bdevs and Malloc bdevs in your configuration file will ensure that you don't expose Non-NVMe drives.

**Comment by ack72tdp** [comment]
I don't have NVME devices in my setup. It has AIO based block devices created using our underlying storage subsystem. .. I only want to use AIO bdevs .. to create the target ... 
 
Like i mentioned, I have 4 AIO bdevices coming from our storage system .. 2 of them used to create RDMA target using SPDK and 2 of them used to create RDMA target using system drivers.

System drivers created targets work much faster, than the ones created using SPDK.

I am trying to figure out why is it like that ..

Any thoughts?

Thanks

**Comment by benlwalker** [comment]
Can you post your entire configuration file that you pass to the target and the output of lsblk on the target system?

You have your target set up to expose devices AIO0 and AIO1 as namespaces in your subsystems. You say that the rest of your configuration file is the same as the example in etc/spdk/nvmf.conf.in. In that file, AIO0 and AIO1 are set to /dev/sdb and /dev/sdc - which aren't NVMe devices. They're likely SATA devices on your system, and that probably means that AIO isn't able to actually do asynchronous operations.

**Comment by ack72tdp** [comment]
These are block devices that would look like this .. It has underlying storage system creates these block devices and mounts to the linux system...
[AIO]
   AIO /dev/scinia AIO0
   AIO /dev/scinib AIO1

It's same kind of block devices both spdk and kernel drivers use .. 

For ex:
linux-qgd9:~ # lsblk
NAME MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
scinia 259:4 0 200G 0 disk // used with SPDK
scinib 259:5 0 200G 0 disk // used with SPDK
scinic 259:0 0 304G 0 disk // used with KERNEL
scinid 259:3 0 304G 0 disk // used with KERNEL

All four devices are coming out of same underlying storage system... and they all perform equally when run against block devices directly ...

**Comment by darsto** [comment]
Bug scrub: @ack72tdp could you try running the same fio job against a local kernel block device through libaio?

If it's AIO that's slow, we can't do anything in SPDK to improve performance.

**Comment by ack72tdp** [comment]
It's not the libaio as I see .. in my original post it has both kernel and SPDK results using the same device one producing at IOPS=146k, other producing at IOPS=3.6k for the same block size and workload ....

**Comment by benlwalker** [comment]
Could you run fio on those devices locally, without NVMe over Fabrics? Specifically, on the target system run fio directly against the kernel devices in question. The suspicion is that these devices, since they are not NVMe devices, are not able to actually perform asynchronous I/O from user space. The kernel code path probably can.

**Comment by ack72tdp** [comment]
Running FIO on both devices (kernel/userspace) directly .. gives me about 160K-170K IOPS .. Yes.. they are not NVME devices.. Devices are created by our software by abstracting many SSD devices across various nodes..

**Comment by ack72tdp** [comment]
So in summary
direct device  - 160K IOPS
nvme kernl  - 146k IOPS
nvme userspace -  3.6k IOPS..

Same workload, same block size.. and same test ...

**Comment by benlwalker** [comment]
To further narrow down the problem, if you run the SPDK NVMe-oF target with a malloc bdev, do you get good performance? I'm trying to tease out exactly which layer in SPDK is the root cause.

**Comment by benlwalker** [comment]
Not enough information to make forward progress here. Please re-open the issue if you'd like to continue the debug.

**Comment by ccoderr** [comment]
Hi all
I also encountered the same problem in my environment.
At first I used spdk iscsi, I found that the write performance is normal, but the read performance is very low.Then I tried to use perf to test, the same read performance is very low.But the read performance is normal on the nvme devices created using kernel drivers.
The nvme I am using is intel p4600, my spdk version is the main line latest, config file is default. I am using centos 7.6 ,kernel version is 4.18.

Here is the write performance. You can see that there are 300,000 iops.
[root@nas-mmqqwo7q6v ~]# perf -q 32 -o 4096 -w randwrite -t 120 -c 0x8 -r 'trtype:PCIe traddr:0000:01:01.0'
Starting SPDK v19.04-pre / DPDK 18.11.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x8 --log-level=lib.eal:6 --base-virtaddr=0x200000000000 --file-prefix=spdk_pid4683 ]
PMD: net_mlx4: cannot load glue library: libmlx4.so.1: cannot open shared object file: No such file or directory
PMD: net_mlx4: cannot initialize PMD due to missing run-time dependency on rdma-core libraries (libibverbs, libmlx4)
net_mlx5: cannot load glue library: libmlx5.so.1: cannot open shared object file: No such file or directory
net_mlx5: cannot initialize PMD due to missing run-time dependency on rdma-core libraries (libibverbs, libmlx5)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
EAL:   Invalid NUMA socket, default to 0
EAL: Error: Invalid memory
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
Initializing NVMe Controllers
Attaching to NVMe Controller at 0000:01:01.0
Attached to NVMe Controller at 0000:01:01.0 [8086:0a54]
Associating INTEL SSDPEDKE020T7  (PHLE843200BB2P0IGN  ) with lcore 3
Initialization complete. Launching workers.
Starting thread on core 3
========================================================
                                                                                            Latency(us)
Device Information                                     :       IOPS       MB/s    Average        min        max
INTEL SSDPEDKE020T7  (PHLE843200BB2P0IGN  ) from core 3:  355950.66    1390.43      89.84       4.25    5531.41
========================================================
Total                                                  :  355950.66    1390.43      89.84       4.25    5531.41


Here is the read performance. You can see that there are only 70,000 iops.
[root@nas-mmqqwo7q6v ~]# perf -q 32 -o 4096 -w randread -t 120 -c 0x8 -r 'trtype:PCIe traddr:0000:01:01.0'
Starting SPDK v19.04-pre / DPDK 18.11.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x8 --log-level=lib.eal:6 --base-virtaddr=0x200000000000 --file-prefix=spdk_pid4921 ]
PMD: net_mlx4: cannot load glue library: libmlx4.so.1: cannot open shared object file: No such file or directory
PMD: net_mlx4: cannot initialize PMD due to missing run-time dependency on rdma-core libraries (libibverbs, libmlx4)
net_mlx5: cannot load glue library: libmlx5.so.1: cannot open shared object file: No such file or directory
net_mlx5: cannot initialize PMD due to missing run-time dependency on rdma-core libraries (libibverbs, libmlx5)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
EAL:   Invalid NUMA socket, default to 0
EAL: Error: Invalid memory
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
Initializing NVMe Controllers
Attaching to NVMe Controller at 0000:01:01.0
Attached to NVMe Controller at 0000:01:01.0 [8086:0a54]
Associating INTEL SSDPEDKE020T7  (PHLE843200BB2P0IGN  ) with lcore 3
Initialization complete. Launching workers.
Starting thread on core 3
========================================================
                                                                                            Latency(us)
Device Information                                     :       IOPS       MB/s    Average        min        max
INTEL SSDPEDKE020T7  (PHLE843200BB2P0IGN  ) from core 3:   78135.61     305.22     409.48      16.50    6423.37
========================================================
Total                                                  :   78135.61     305.22     409.48      16.50    6423.37

Here is the fio read performance using kernel drivers
[root@nas-mmqqwo7q6v ~]# fio -filename=/dev/nvme0n1  -iodepth=32 -numjobs=4 -thread -rw=randread -bs=4k -ioengine=libaio -group_reporting -name=mytest -randrepeat=0 -time_based -runtime=120 -direct=1 -fsync=0 -size=20g
mytest: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=32
...
fio-3.1
Starting 4 threads
Jobs: 4 (f=4): [r(4)][100.0%][r=1575MiB/s,w=0KiB/s][r=403k,w=0 IOPS][eta 00m:00s]
mytest: (groupid=0, jobs=4): err= 0: pid=6128: Wed Sep 18 15:00:28 2019
   read: IOPS=398k, BW=1556MiB/s (1631MB/s)(182GiB/120001msec)
    slat (usec): min=2, max=5057, avg= 4.29, stdev= 2.55
    clat (usec): min=26, max=9260, avg=313.22, stdev=166.52
     lat (usec): min=30, max=9264, avg=318.34, stdev=166.53
    clat percentiles (usec):
     |  1.00th=[  120],  5.00th=[  174], 10.00th=[  202], 20.00th=[  231],
     | 30.00th=[  249], 40.00th=[  265], 50.00th=[  281], 60.00th=[  302],
     | 70.00th=[  326], 80.00th=[  367], 90.00th=[  449], 95.00th=[  537],
     | 99.00th=[  816], 99.50th=[  988], 99.90th=[ 2114], 99.95th=[ 3425],
     | 99.99th=[ 4883]
   bw (  KiB/s): min=354968, max=408016, per=25.00%, avg=398212.00, stdev=11996.36, samples=956
   iops        : min=88742, max=102004, avg=99553.00, stdev=2999.09, samples=956
  lat (usec)   : 50=0.01%, 100=0.40%, 250=30.08%, 500=62.91%, 750=5.23%
  lat (usec)   : 1000=0.90%
  lat (msec)   : 2=0.37%, 4=0.08%, 10=0.03%
  cpu          : usr=33.97%, sys=64.92%, ctx=335562, majf=0, minf=133
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=100.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.1%, 64=0.0%, >=64=0.0%
     issued rwt: total=47789118,0,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=32

Run status group 0 (all jobs):
   READ: bw=1556MiB/s (1631MB/s), 1556MiB/s-1556MiB/s (1631MB/s-1631MB/s), io=182GiB (196GB), run=120001-120001msec

Disk stats (read/write):
  nvme0n1: ios=47748105/0, merge=0/0, ticks=286358/0, in_queue=9014391, util=100.00%

I tried using trace point to track down the problem.I found that the read command has a much longer delay than the write command.
Here is read
 3:   8292.832 c01 ISCSI_READ_DONE          size:     48                         
 3:   8292.917 c01 ISCSI_READ_PDU                        opc:   1                id:    p80              
 3:   8293.311 c01 ISCSI_TASK_QUEUE         size:   4096 pdu:   0x200015939f00   id:    t80              
 3:   8293.431 d00 SCSI_TASK_START          size:   4096                         id:    t80              time:  0.120            
 3:   8293.916 b00 BDEV_IO_START                         type:  1                id:    i80              
 3:   8295.103 c00 ISCSI_TASK_EXECUTED                                           id:    p80              time:  2.185            
 3:   8298.176 c01 ISCSI_READ_DONE          size:     48                         
 3:   8298.287 c01 ISCSI_READ_PDU                        opc:   1                id:    p81              
 3:   8298.615 c01 ISCSI_TASK_QUEUE         size:   4096 pdu:   0x200015938d80   id:    t81              
 3:   8298.702 d00 SCSI_TASK_START          size:   4096                         id:    t81              time:  0.087            
 3:   8298.951 b00 BDEV_IO_START                         type:  1                id:    i81              
 3:   8300.265 c00 ISCSI_TASK_EXECUTED                                           id:    p81              time:  1.977            
 3:   8359.383 b00 BDEV_IO_DONE                                                  id:    i51              time:  2607.049         
 3:   8359.679 d00 SCSI_TASK_DONE                                                id:    t51              time:  2607.947         
 3:   8359.771 c01 ISCSI_TASK_DONE                                               id:    t51              time:  2608.039         
 3:   8360.493 c01 ISCSI_WRITE_START        size:   4144 iovec: 2                
 3:   8364.927 c01 ISCSI_WRITE_DONE         size:   4144                         
 3:   8365.543 c00 ISCSI_PDU_COMPLETED                                           id:    p51              time:  2614.192         
 3:   8416.154 b00 BDEV_IO_DONE                                                  id:    i52              time:  2578.774         
 3:   8416.357 d00 SCSI_TASK_DONE                                                id:    t52              time:  2579.452         
 3:   8416.451 c01 ISCSI_TASK_DONE                                               id:    t52              time:  2579.547         
 3:   8417.078 c01 ISCSI_WRITE_START        size:   4144 iovec: 2                
 3:   8419.076 c01 ISCSI_WRITE_DONE         size:   4144                         
 3:   8419.621 c00 ISCSI_PDU_COMPLETED                                           id:    p52              time:  2583.046         
 3:   8453.538 c01 ISCSI_READ_DONE          size:     48                         

Here is write

3:  93553.492 d00 SCSI_TASK_START          size:   4096                         id:    t176             time:  0.244            
 3:  93553.812 b00 BDEV_IO_START                         type:  2                id:    i176             
 3:  93554.758 c00 ISCSI_TASK_EXECUTED                                           id:    p176             time:  1.898            
 3:  93555.938 c01 ISCSI_READ_DONE          size:     48                         
 3:  93557.898 c01 ISCSI_READ_DONE          size:   4096                         
 3:  93558.008 c01 ISCSI_READ_PDU           size:   4096 opc:   1                id:    p177             
 3:  93558.367 c01 ISCSI_TASK_QUEUE         size:   4096 pdu:   0x20001593a980   id:    t177             
 3:  93558.617 d00 SCSI_TASK_START          size:   4096                         id:    t177             time:  0.238            
 3:  93558.844 b00 BDEV_IO_START                         type:  2                id:    i177             
 3:  93559.672 c00 ISCSI_TASK_EXECUTED                                           id:    p177             time:  1.664            
 3:  93560.828 c01 ISCSI_READ_DONE          size:     48                         
 3:  93563.367 c01 ISCSI_READ_DONE          size:   4096                         
 3:  93563.453 c01 ISCSI_READ_PDU           size:   4096 opc:   1                id:    p178             
 3:  93563.805 c01 ISCSI_TASK_QUEUE         size:   4096 pdu:   0x20001593b5c0   id:    t178             
 3:  93563.914 d00 SCSI_TASK_START          size:   4096                         id:    t178             time:  0.111            
 3:  93564.281 b00 BDEV_IO_START                         type:  2                id:    i178             
 3:  93565.242 c00 ISCSI_TASK_EXECUTED                                           id:    p178             time:  1.786            
 3:  93566.898 b00 BDEV_IO_DONE                                                  id:    i155             time:  401.098          
 3:  93567.188 d00 SCSI_TASK_DONE                                                id:    t155             time:  401.864          
 3:  93567.289 c01 ISCSI_TASK_DONE                                               id:    t155             time:  401.966          
 3:  93567.859 c01 ISCSI_WRITE_START        size:     48 iovec: 1                
 3:  93571.836 c01 ISCSI_WRITE_DONE         size:     48                         
 3:  93572.469 c00 ISCSI_PDU_COMPLETED                                           id:    p155             time:  407.479          
 3:  93577.828 b00 BDEV_IO_DONE                                                  id:    i156             time:  406.836          
 3:  93578.117 d00 SCSI_TASK_DONE                                                id:    t156             time:  407.621          
 3:  93578.203 c01 ISCSI_TASK_DONE                                               id:    t156             time:  407.713          
 3:  93578.773 c01 ISCSI_WRITE_START        size:     48 iovec: 1                
 3:  93582.977 c01 ISCSI_WRITE_DONE         size:     48                         
 3:  93583.539 c00 ISCSI_PDU_COMPLETED                                           id:    p156             time:  413.381          
 3:  93589.312 b00 BDEV_IO_DONE                                                  id:    i157             time:  412.919          
 3:  93589.594 d00 SCSI_TASK_DONE                                                id:    t157             time:  413.788          
 3:  93589.688 c01 ISCSI_TASK_DONE                                               id:    t157             time:  413.881          

Thanks

**Comment by benlwalker** [comment]
I believe you are comparing 4 threads doing 32 queue depth each in fio, to 1 thread doing queue depth 32 in SPDK. Try increasing the queue depth in SPDK to 128 to get a fair measurement of the device's performance.

**Comment by ccoderr** [comment]
@benlwalker Thank you. Your answer inspired me.I have solved the problem in my environment.I found that the queue depth used by the kernel driver to create a submission queue is 1024.so after I changed this value DEFAULT_IO_QUEUE_SIZE from 256 to 1024, the same model read performance is normal.
```
--- a/lib/nvme/nvme_internal.h
+++ b/lib/nvme/nvme_internal.h
@@ -136,7 +136,7 @@ extern pid_t g_spdk_nvme_pid;
  *  try to configure, if available.
  */
 #define DEFAULT_MAX_IO_QUEUES          (1024)
-#define DEFAULT_IO_QUEUE_SIZE          (256)
+#define DEFAULT_IO_QUEUE_SIZE          (1024)
 
 #define DEFAULT_ADMIN_QUEUE_REQUESTS   (32)
 #define DEFAULT_IO_QUEUE_REQUESTS      (512)
```
