### ISSUE TITLE
RUN_NIGHTLY switch is off in all NIGHTLY servers

### ISSUE THREAD

**Issue by ChenBo2333** [spdk/spdk#754]
RUN_NIGHTLY switch is off in all NIGHTLY server , so all of the NIGHTLY test didn't run.

## Expected Behavior
RUN_NIGHTLY=1

## Current Behavior
RUN_NIGHTLY=0

## Possible Solution
Set "RUN_NIGHTLY=1" in all NIGHTLY test servers.

## Steps to Reproduce
1. view build log on RBD_autotest server,
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/28583/archive/RBD_autotest/build.log (search "RUN_NIGHTLY=0")

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit b62dca93082b0e3efbb48f183ead1fcda24700f4

**Comment by darsto** [comment]
In the first of the log you've provided I can see:
> Started by upstream project "autotest-per-patch" build number 28583

So it's a per-patch test, not a nightly one. For nightly the log starts with the following line:
> Started by upstream project "autotest-nightly" build number 466

(taken from https://dqtibwqq6s6ux.cloudfront.net/results/autotest-nightly/builds/466/archive/RBD_autotest/build.log )

For nightly tests we just set override RUN_NIGHTLY to 1.

You can see all the nightly test runs here: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-nightly.html

**Comment by wanghailiangx** [comment]
@darsto Your reply is no problem, perhaps ChenBo did not make it clear. 
We can find NIGHTLY test result by two entrances. One is https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-nightly.html,
another is https://review.gerrithub.io/#/c/spdk/spdk/+/393768/. 
The problem lies in the latter. There, SPDK CI Jenkins always shows "autotest-per-patch" log. In actual, it should show "autotest-nightly" log. 
So I suggest reopen the issue, thanks.

**Comment by darsto** [comment]
@wanghailiangx Ohh that's true. I've just talked to @Seth5141 and we will get rid of that patch - we don't use it anyway.
