### ISSUE TITLE
Intermittent json_config.sh test failure

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#789]
https://10.102.17.104:8080/job/Other_systems/job/centos7_autotest/25276/artifact/build.log

This has come up several times.  I recently pushed a patch to get more debugging information, and this log above contains that data.

The failure would always be indicated by this line:  "Config not empty".  The log above now shows that config.

Calling clear_vhost_subsystem
Calling clear_nbd_subsystem
Calling clear_nvmf_subsystem
Calling clear_bdev_subsystem
 04:58:07	# local config_filter=/var/jenkins/workspace/Other_systems/centos7_autotest/spdk/test/json_config/config_filter.py
 04:58:07	# /var/jenkins/workspace/Other_systems/centos7_autotest/spdk/scripts/rpc.py -s /var/tmp/spdk_tgt.sock save_config
 04:58:07	# /var/jenkins/workspace/Other_systems/centos7_autotest/spdk/test/json_config/config_filter.py -method delete_global_parameters
 04:58:07	# /var/jenkins/workspace/Other_systems/centos7_autotest/spdk/test/json_config/config_filter.py -method check_empty
Config not empty
[{'method': 'construct_split_vbdev', 'params': {'split_count': 2, 'base_bdev': 'Nvme0n1', 'split_size_mb': 0}}, {'method': 'construct_nvme_bdev', 'params': {'traddr': '0000:00:09.0', 'name': 'Nvme0', 'trtype': 'PCIe', 'prchk_guard': False, 'prchk_reftag': False}}]
  04:58:08	# on_error_exit json_config_clear 408
  04:58:08	# set -x
  04:58:08	# set +e
  04:58:08	# print_backtrace
  04:58:08	# [[ hxBE =~ e ]]
  04:58:08	# return 0
  04:58:08	# trap - ERR

@tkulasek - I know you didn't originally develop this test, but it looks like you've done some work with it recently.  Could you take a look?

**Comment by jimharris** [comment]
http://10.102.17.206/results/autotest-per-patch/builds/30759/archive/ubuntu17_autotest/build.log

Same failure just hit again.

**Comment by tkulasek** [comment]
@jimharris ok.

**Comment by tomzawadzki** [comment]
And here as well https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/31913/archive/ubuntu17_autotest/failed_test.log

Hard to judge from the log output, but it would seem that clear_bdev_subsystem() didn't fully clean the bdevs.
Originally theres nvme, split into two, where one of those splits is used for creating lvol store with two lvol bdevs. Lvol bdevs were deleted correctly looking at print from left over configuration (only nvme and two splits left).

Couple of notes @tkulasek that might be helpful when narrowing it down.
Was lvol store deleted ?
Doesn't clear_bdev_subsystem() go over bdevs just once, meaning that if some were skipped - they won't be deleted ? If so, probably deleting first unclaimed bdev - until none are left is right way to go.

**Comment by tkulasek** [comment]
@tomzawadzki Is that possible that split as well as nvme is pending deletion, but config is not updated yet, and we should to wait a while?

**Comment by tkulasek** [comment]
I have a problem to reproduce it on my local machine. I've run this test in a loop for a whole night and nothing happen.

**Comment by tomzawadzki** [comment]
This issue is still valid, last failure occurred as recent as last Friday May 31st.
I've seen it occur on Ubuntu17/Centos7/FreeBSD, on different VMs for each one.

<details> 
  <summary>Links to build logs</summary>
  <p>

https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/30108/archive/centos7_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/30142/archive/ubuntu17_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/30358/archive/ubuntu17_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/30381/archive/ubuntu17_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/30655/archive/centos7_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/30657/archive/centos7_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/30721/archive/centos7_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/30759/archive/ubuntu17_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/30805/archive/freebsd_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/31021/archive/ubuntu16_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/31104/archive/ubuntu17_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/31139/archive/centos7_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/31395/archive/ubuntu16_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/31430/archive/ubuntu17_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/31439/archive/freebsd_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/31523/archive/ubuntu17_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/31554/archive/freebsd_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/31743/archive/ubuntu17_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/31784/archive/centos7_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/31819/archive/ubuntu17_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/31913/archive/ubuntu17_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/31983/archive/centos7_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/31989/archive/ubuntu17_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/32059/archive/ubuntu17_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/32068/archive/ubuntu17_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/32073/archive/ubuntu17_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/32121/archive/freebsd_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/32128/archive/centos7_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/32154/archive/centos7_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/32256/archive/freebsd_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/32275/archive/centos7_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/32280/archive/freebsd_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/32299/archive/ubuntu17_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/32328/archive/freebsd_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/32345/archive/freebsd_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/32529/archive/ubuntu17_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/32536/archive/centos7_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/32605/archive/centos7_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/32635/archive/ubuntu17_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/32661/archive/ubuntu17_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/32702/archive/ubuntu17_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/32704/archive/ubuntu17_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/32708/archive/freebsd_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/32759/archive/ubuntu17_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/32775/archive/ubuntu17_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/32834/archive/centos7_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/32929/archive/centos7_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/32976/archive/centos7_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/33034/archive/ubuntu17_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/33102/archive/centos7_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/33104/archive/centos7_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/33107/archive/centos7_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/33220/archive/ubuntu17_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/33240/archive/freebsd_autotest/build.log

</p></details>

**Comment by darsto** [comment]
Bug scrub: The leftover NVMe bdev was used as lvolstore. @tomzawadzki is working on improving the test output.

**Comment by jimharris** [comment]
I'm fairly certain this intermittent failure is because clear_config.py issues the RPCs to delete the split and nvme bdevs, but those RPCs complete immediately - they don't wait for the bdev unregister callback.

In most cases, by time we run the config_filter, the unregistrations have happened, and the configuration is clear.  But not always.

I think for now, just be dumb and add a 2 second delay in the json_config_clear function, after we call clear_config.py.

Longer term, we probably want *all* of the various bdev deletion RPCs (including NVMe controller detach) to not complete until the bdev unregister callback is received.  This will be a lot more work though.  I think fixing up the test is fine for now.

**Comment by tkulasek** [comment]
I was trying with delay here: https://review.gerrithub.io/c/spdk/spdk/+/455668, but I wasn't able to confirm it solves the problem.

**Comment by jimharris** [comment]
I think that patch is the best approach. I’d suggest using a shorter sleep time per loop but run the loop more times so that it waits up to 10 seconds to be safe. And also add a comment explaining why we are doing the sleeping.

It’s ok to merge that without confirmation - we can always reopen the issue if it surfaces again.

**Comment by tkulasek** [comment]
New version of patch is ready.

**Comment by jimharris** [comment]
Thanks @tkulasek!  Code changes look good.  Could you add "Fixes issue #789" to the commit message?

**Comment by jimharris** [comment]
Patch merged so closing.  Let's keep an eye out for this though.
