### ISSUE TITLE
Use IOAT to perform fast copy from memory to Nvme SSD

### ISSUE THREAD

**Issue by amtrek** [spdk/spdk#795]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

I read an article published by intel which use IOAT to perform fast memcpy, we have couple nvme SSD device on dev enviroment, using the nvme perf example, the write speed achieves up to spec (1.8G /s), however, this is not fast enough for us. I am wondering if I can use IOAT to further facilitate copying from memory to NVME, basically I want to use my Nvme device as a large memory buffer, then use spdk_ioat_submit_copy() to store data into SSD buffer. The reason of doing so, is to reduce CPU usage (unbinding from kernel driver), also because we've seen ioat_submit_copy perform more stable than memcpy. 

When I allocate a buffer size using spdk_malloc
for example:
`
(char*)spdk_malloc(chunkBufNums*buffersizeneeded*sizeof(char), sizeof(char), nullptr, SPDK_ENV_SOCKET_ID_ANY, SPDK_MALLOC_DMA);`

How do I know, if this buffer is allocated on my nvme device ?  What is the SOCKET_ID referring to and how do I find out what's the value of Socket_ID for my device ?

Function | Description
-- | -

## Steps to Reproduce

1.
2.
3.
4.

**Comment by changpe1** [comment]
@amtrek NVMe specification defines a feature called Controller Memory Buffer, but not all NVMe devices can support it, you need to check it can support data buffer or not first.  If you have such drives, you can use spdk_nvme_ctrlr_alloc_cmb_io_buffer() API to allocate data buffer, spdk_malloc* related APIs can't be used for that purpose.

**Comment by amtrek** [comment]
@changpe1  thanks for your reply, it helps me understand a bit better. I've now created buffer on my nvme device, but while doing the ioat copy, the spdk_submit_copy never finished. Is the copy operation between source (via malloc) and destination (via spdk_nvme_ctrlr_alloc_cmb_io_buffer()) can not be completed by ioat ?

**Comment by benlwalker** [comment]
@amtrek Can you confirm that you have devices that support Controller Memory Buffer for data transfer? Almost no devices support that, so I'd be surprised if you have one.

If you don't have controller memory buffer, then you can't use IOAT to transfer data to an NVMe device. The NVMe device has its own DMA engine to pull data out of host memory anyway, and the NAND itself isn't exposed as DMA-able memory.

The device can only go so fast - are you sure that 1.8GB/s isn't the maximum speed of the SSD? Also, if you see high CPU usage, remember that SPDK is polling when you run the perf benchmark so the CPU use is always at 100%. That doesn't mean that the core is particularly busy - you can almost certainly interleave other useful work on that core between polling and not reduce the performance at all.

**Comment by amtrek** [comment]
Hi, @benlwalker : Thanks for pointing that out, I am actually not certain that our SSD supports command memory buffer (Intel SSD DC P4500), when I use spdk_nvme_ctrlr_alloc_cmb_io_buffer() to allocate buffer, there's no error thrown. Dumb question, which specification should I look for to see if my device support command memory buffer ? 

For your question, yes, 1.8G/s is max speed in product specification , and write speed is in line using standard File IO & SPDK Nvme perf. Still, this is not enough speed for our application, so we start explore to see if it's possible that spdk can help perform write speed better than specs on paper. We've tried to benchmark from nvme perf which capped write speed at 1.8G/s, and was wondering if copy via IOAT can possibly get speed more than 1.8G/s ?

**Comment by benlwalker** [comment]
The DC P4500 does not support controller memory buffer. It's interesting that spdk_nvme_ctrlr_alloc_cmb_io_buffer() does not fail. That's something that we need to investigate. The code looks like it should fail to me.

You can check if your device supports controller memory buffer by running the SPDK identify tool - `./examples/nvme/identify/identify`. It's also on https://ark.intel.com. 

SPDK in general can't make a device faster than what the spec sheet says. The device speed, especially for sequential operations, is bounded by either the available PCIe bandwidth or by the available NAND channels on the device itself. What SPDK can do is hit that maximum device performance using fewer CPU cycles - often many times fewer total CPU cycles than other mechanisms.

In order to get more performance you can use more SSDs and put them in a pool of some sort (SPDK has a RAID 0 module, for example). A RAID 0 of two SSDs has more or less double the performance of a single SSD, while still behaving like a single SSD in the SPDK bdev layer.

**Comment by amtrek** [comment]
@benlwalker  it looks to us that in order to configure nvme SSD into RAID, the server needs to supports it, and ours does not.  Thank you for your detail answers, I've benefit from the discussion a lot.

**Comment by jimharris** [comment]
Closing this issue.  We can still continue discussion if you have more questions.
