### ISSUE TITLE
NVMeOF tests fail on Fedora 29 (or kernels 5.0+)

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#846]
## Current Behavior
test/nvmf/host/aer.sh fails when calling nvmfcleanup() function.
This is most probably because kernels 5.0+ have nvme-tcp enabled and nvme-tcp uses nvme-fabrics module which we try to unload in cleanup function.

## Steps to Reproduce
1. Run nvmf test suite on test system which has nvme-tcp module enabled and loaded.
```
10:35:22  10:37:15	# trap - SIGINT SIGTERM EXIT
10:35:22  10:37:15	# nvmfcleanup
10:35:22  10:37:15	# sync
10:35:22  10:37:15	# set +e
10:35:22  10:37:15	# for i in {1..20}
10:35:22  10:37:15	# modprobe -v -r nvme-rdma nvme-fabrics
10:35:22 rmmod nvme_rdma
10:35:22 modprobe: FATAL: Module nvme_fabrics is in use.
[...]

```
## Possible Solution
Fix nvmfcleanup() to detect if nvme_tcp module is loaded.
If so, then remove it prior to removing nvme-fabrics in cleanup routine.

## Context (Environment including OS version, SPDK version, etc.)
Fedora 29, 5.1.11-200.fc29.x86_64
SPDK 3d1995c35bdc253a0647b1ab807021dc23384224

**Comment by Seth5141** [comment]
@karlatec When you were running the tests, were you running them against the RDMA transport or the TCP transport?

There is already a loop in the nvmftestcleanup function that attempts to unload nvme_tcp if you are running the tests against  the tcp transport.

~~~
        for i in {1..20}; do
		modprobe -v -r nvme-$TEST_TRANSPORT nvme-fabrics
		if [ $? -eq 0 ]; then
			set -e
			return
		fi
		sleep 1
	done
~~~

Is it possible that you had explicitly modprobed nvme_tcp before starting the tests?

**Comment by karlatec** [comment]
@Seth5141 We hooked up new systems to CI and got these fails, so I'm 99.9% sure that tests were running against RDMA transport layer.

> Is it possible that you had explicitly modprobed nvme_tcp before starting the tests?
I didn't modprobe nvme_tcp. Must be enabled by default.

> There is already a loop in the nvmftestcleanup function that attempts to unload nvme_tcp if you are running the tests against the tcp transport.
Yes, but it doesn't work if you have nvme_tcp loaded as well. Loop will get stuck on modprobe: FATAL: Module nvme_fabrics is in use.

**Comment by Seth5141** [comment]
@karlatec I don't think that nvme_tcp is enabled by default on fedora 29.  I don't have a fed 29 vm available ATM, but I confirmed that on fedora 30 it is not loaded by default.

I think the issue is this: 

we currently run the test/nvmf/host/perf.sh test with both --transport=rdma and --transport=tcp (see nvmf.sh). perf.sh invokes nvmfappstart which calls modprobe nvme-$TEST_TRANSPORT. However at the end of perf.sh, we don't invoke nvmfcleanup which means that when we run aer.sh next, we end up failing to remove it and can't remove nvme-fabrics. I think there needs to be a slight overhaul of these cleanup tests to make them symmetric in all cases.  Maciej made a couple of good points about the general nature of the cleanup functions in comments here(https://review.gerrithub.io/c/spdk/spdk/+/460201) that I think are applicable too.

**Comment by Seth5141** [comment]
I think this series should fix it. https://review.gerrithub.io/c/spdk/spdk/+/460396 It makes sure that we probe and remove the nvme-* modules on every test run using the current infrastructure.
