### ISSUE TITLE
15% performance degradation of iSCSI target by thread poller change

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#854]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

The patch thread: Run all pollers on each spdk_thread_poll call
(https://review.gerrithub.io/c/spdk/spdk/+/440598) caused 15% IOPS degradation for 4KB random read for our iSCSI target application.

One difference of our application from SPDK master is that we have utilized two special timer pollers:
*  1 microsecond timer poller to check I/O completion from backend
*  10 millisecond timer poller to check I/O timeout.

## Expected Behavior
No performance degradation.

## Current Behavior
15% performance degradation.

## Possible Solution
Revert the part of the patch (https://review.gerrithub.io/c/spdk/spdk/+/440598) that degraded IOPS.

## Steps to Reproduce
Run vdbench with 4KB random read.

## Context (Environment including OS version, SPDK version, etc.)
SPDK master branch at which the patch (https://review.gerrithub.io/c/spdk/spdk/+/440598) was merged.

**Comment by optimistyzy** [comment]
This is interesting.

**Comment by benlwalker** [comment]
Some comments I made on Slack regarding this issue:

I suspect that I know what the problem is. There are two types of pollers - ones that run as often as possible (non-timed) and ones that run on a time delay (timed). In the old code, each time through the main reactor loop it would run one non-timed poller (round-robin) and then any expired timed pollers.
Whereas in the new code, each time through the main reactor loop it runs all of the non-timed pollers, then any expired timed pollers

So in your code, you've made the code that reaps completions from the backend a timed poller with a very short delay (1us), and I think what's happening is that the new algorithm is actually running it less often than before because running the whole set of non-timed pollers takes longer than 1 us. You'd actually found a trick to make your poller higher priority effectively, and now that trick doesn't work anymore.

I think the best path forward is to figure out what other pollers are running on that thread and to instead introduce delays for those. Then make your poller that reaps I/O from your backend have 0 delay.

**Comment by shuhei-matsumoto** [comment]
Hi @benlwalker 

Thank you so much for your kind comment.

Your inspection matches our team's experience. 

The comment from our team was that we saw sensitivity of the random IOPS to the timer interval and so we tuned the timer interval according to that experience.

**Comment by shuhei-matsumoto** [comment]
The cause is clear and we have workaround. Close this issue and track further activity on Trello board. https://trello.com/c/soHtrkTj/153-timer-scheduling-improvement-on-the-current-spdk-thread

**Comment by shuhei-matsumoto** [comment]
@benlwalker 

Our communication was not enough.

Our team had thought that we can't set period of poller to zero because SPDK had returned error when they designed.

Our poller to check completion is light if no completion, and we could confirm the issue was fixed without reverting any patch and only with period change (1us to 0).

Regardless of this update, I will work on improvement but the priority became lower as our team.

Thanks,
Shuhei
