### ISSUE TITLE
trace record test on iscsi: failure on inefficient entries number check

### ISSUE THREAD

**Issue by darsto** [spdk/spdk#865]
```
 06:07:10	# echo 'entries numbers from trace record are:' 4096 4096 4096 4096
entries numbers from trace record are: 4096 4096 4096 4096
 06:07:10	# echo 'entries numbers from trace tool are:' 4096 4096 4096 4096
entries numbers from trace tool are: 4096 4096 4096 4096
 06:07:10	# arr_record_num=($record_num)
 06:07:10	# arr_trace_tool_num=($trace_tool_num)
 06:07:10	# len_arr_record_num=4
 06:07:10	# len_arr_trace_tool_num=4
 06:07:10	# '[' 4 -ne 4 ']'
  06:07:10	# seq 0 3
 06:07:10	# for i in $(seq 0 $((len_arr_record_num - 1)))
 06:07:10	# '[' 4096 -le 4096 ']'
 06:07:10	# echo 'trace record test on iscsi: failure on inefficient entries number check'
trace record test on iscsi: failure on inefficient entries number check
```

https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/37960/archive/RBD_autotest/build.log

**Comment by dong-liuliu** [comment]
From the its gerrithub page https://review.gerrithub.io/c/spdk/spdk/+/462043/2 , the patch get veirfied-1 from different test env in each round of test.
So I don't think it is one issue, 

This test is used to check whether trace_record tool works well.
If it works well, entries counted from trace_record tool will be much much larger than 4096.
Two factors may cause the failure:
1. trace_record didn't work, or there is some bug in trace_record
2. iscsi_tgt has some issue to keep processing IO in order to generating enough trace entries.
