### ISSUE TITLE
NVMe/SAS/SATA Storage controllers (Broadcom/Microchip) supported in SPDK?

### ISSUE THREAD

**Issue by rajasekaranmam** [spdk/spdk#895]
Query:
Is/Are NVMe/SAS/SATA Storage controllers (Broadcom/Microchip) supported in SPDK?

Reason:
Looking for an option to check if NVMe/SAS/SATA storage controllers supported in SPDK already.

**Comment by jimharris** [comment]
Hi,

The SPDK NVMe userspace driver will work with any specification-compliant NVMe SSD.

SPDK supports SAS/SATA storage controllers using Linux AIO (or io_uring on newer Linux kernels).  In this case, you would use the Linux kernel driver for your SAS or SATA storage controllers.

Best regards,

-Jim

**Comment by ak-gh** [comment]
On Tue, Aug 6, 2019, 20:47 Jim Harris <notifications@github.com> wrote:

> Hi,
>
> The SPDK NVMe userspace driver will work with any specification-compliant
> NVMe SSD.
>
> SPDK supports SAS/SATA storage controllers using Linux AIO (or io_uring on
> newer Linux kernels).
>
Jim,

sorry for off-top, but still what is the minimum kernel version required
for the SPDK io_uring bdev?

Thanks,
Andrey

**Comment by jimharris** [comment]
5.1

**Comment by ak-gh** [comment]
On Tue, Aug 6, 2019, 21:31 Jim Harris <notifications@github.com> wrote:

> 5.1
>
Thanks.

**Comment by rajasekaranmam** [comment]
Thanks, Jim.

In that case, I believe we can use any storage controller in 5.1 kernels with SPDK 19.07.x environment, which helps to expose only drives connected (JBOD or RAID) behind the storage controller to userspace.

Is there any provision (now in SPDK), to expose the entire storage controller completely to userspace?

**Comment by jimharris** [comment]
There are currently no native userspace SPDK drivers for any SAS or SATA/AHCI controllers.  SPDK only enables SAS/SATA via kernel mode drivers.

**Comment by benlwalker** [comment]
Note that this is an intentional design decision on our part. For SAS and SATA/AHCI, the CPU overhead of the kernel I/O path (especially via libaio and liburing) is low enough relative to the performance of these types of devices that bypassing the kernel isn't worthwhile.

Also, you can use SAS and SATA devices you can use them via SPDK on any kernel that supports libaio, which covers any actively maintained kernel in any distribution you may be using, effectively. You only need 5.1 to use the new io_uring interface via liburing. For SAS and SATA devices, their kernel stacks are not plumbed to take advantage of io_uring anyway.
