### ISSUE TITLE
NVME device insertion/removal?

### ISSUE THREAD

**Issue by cmicalizzi** [spdk/spdk#9]
I don't see anything in the SPDK regarding device removal or insertion.
Is this going to be added at some point?
I know a lot of the current work was done with Add In Cards but how will this work with SFF 8639 devices?
I also see that there are is no validation of register accesses. 
Blindly assuming PCIe accesses are successful can lead to data corruption.
Isn't it a rule that PCIe register accesses should always check the result for -1 (0xffffffff indicates an access failure). 

thank you

chuck

**Comment by bwalker-intel** [comment]
We're actively investigating hot plug support in SPDK's NVMe driver. We just pushed some major API changes around initialization that are a step in this direction. Now instead of calling spdk_nvme_attach on a specific NVMe PCI handle, you call spdk_nvme_probe and pass it two callback functions - probe_cb and attach_cb. The probe_cb is called for each device with the NVMe class code on the PCI bus (that isn't already managed by SPDK's NVMe driver) and you can choose to return true if you'd like to claim the device or false otherwise. For each device where you return true, the SPDK NVMe driver will then claim the device, load, and call attach_cb when it is ready for your use.

This new API helps with hot plug because your software can simply poll spdk_nvme_probe periodically to get new devices (or register it to be called in response to a uio or vfio event). We're still actively working on this portion today. Note also that this new API allows us to do device initialization in parallel behind the scenes, which is another improvement we're actively working on.

As far as checking the values returned from a PCIe read - we'll include this as part of the hot plug work.

We do accept and appreciate patches if you'd like to contribute improvements!

**Comment by cmicalizzi** [comment]
Benjamin,
     Thank you for the response. I appreciate your consideration.
     I've been working with the SPDK for a couple months now.
     Thank you for the invitation to contribute. I will take you up on 
it as I get more comfortable with the code.

chuck

**Comment by selvanhcl** [comment]
Hi , is there any plan to develop nvme over fabrics initiator in spdk. we are planing to contribute in these area.

**Comment by benlwalker** [comment]
This thread is about device hot insertion/removal. Please direct general questions to our mailing list (https://lists.01.org/mailman/listinfo/spdk). We'd love to discuss an NVMf initiator.

(I will delete this comment and yours after 24 hours to keep this thread on topic)

**Comment by dverkamp-intel** [comment]
Hotplug support for the NVMe driver library has been added as of SPDK 16.11 - for an example of how to use the API, see [examples/nvme/hotplug](https://github.com/spdk/spdk/tree/master/examples/nvme/hotplug).

Note that hotplug support has not yet been extended to the higher layers of the SPDK stack; for example, the bdev layer, iSCSI target, etc. do not yet support hotplug.
