### ISSUE TITLE
fio_plugin info

### ISSUE THREAD

**Issue by zlsh007** [spdk/spdk#907]
Hi all
When testing fio_plugin, the printed information contains -c 0x1, but why the first cpu is not used when actually running, but other cpu is used, thanks；
![image](https://user-images.githubusercontent.com/15990748/62870681-9bc42d00-bd4c-11e9-92ff-3e07e900f394.png)
![image](https://user-images.githubusercontent.com/15990748/62870720-b1395700-bd4c-11e9-9e0c-9f3c92b5c73b.png)

**Comment by zlsh007** [comment]
I don't know why the first cpu has no usage rate. Does the -c parameter have no effect?

**Comment by jimharris** [comment]
Hi @zlsh007,

The SPDK NVMe fio plugin initializes DPDK via spdk_env_opts_init(), but does not use DPDK threads.  fio creates its own threads, and SPDK runs in the context of those threads.

See spdk_fio_setup() in examples/nvme/fio_plugin/fio_plugin.c for where this initialization occurs.

So DPDK gets initialized with the -c 0x1 mask because we have to pick *some* mask to use when initializing DPDK.  This is just the default when no mask is specified.  After spdk_env_opts_init() returns, that thread will be bound to core 0.  But shortly later SPDK calls spdk_unaffinitize_thread().  This allows that thread to run on any core, and would result in the behavior you are seeing.

If you would like to affinitize workers to threads with the fio_plugin, you can use the cpumask or cpus_allowed parameters.

Regards,

Jim

**Comment by zlsh007** [comment]
Hi@jimharris
Thanks for your answer, is it possible to use multiple queues of nvme devices in multithreaded situations? Each queue commits and completes on the same CPU？

Regards,
Su

**Comment by jimharris** [comment]
Yes!  You can create multiple jobs, each running on a different CPU.  Then in the fio plugin, each of these threads will allocate and use their own NVMe queue pair for each attached NVMe SSD.

**Comment by zlsh007** [comment]
@jimharris Thanks a lot；
