### ISSUE TITLE
iSCSI assert 'ahs_len <= ISCSI_AHS_LEN' when using VPP on CI

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#917]
Assert is triggered during autotest.sh runs on CI during for patches unrelated to iSCSI or VPP:
- https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_39920.html
- https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_40171.html
- https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_40090.html

Issue occurs during ./test/iscsi_tgt/fio/fio.sh with VPP enabled, on step `$fio_py -p iscsi -i 1048576 -d 1024 -t read -r 1 -n 4`. Specifically interesting part is:
``` shell
 11:14:20	# /var/jenkins/workspace/iSCSI_tests/vpp_autotest/spdk/scripts/fio.py -p iscsi -i 1048576 -d 1024 -t read -r 1 -n 4
Device paths:
['/dev/sdb', '/dev/sdc']
job0: (g=0): rw=read, bs=(R) 1024KiB-1024KiB, (W) 1024KiB-1024KiB, (T) 1024KiB-1024KiB, ioengine=libaio, iodepth=1024
...
job1: (g=0): rw=read, bs=(R) 1024KiB-1024KiB, (W) 1024KiB-1024KiB, (T) 1024KiB-1024KiB, ioengine=libaio, iodepth=1024
...
fio-3.3
Starting 8 threads
vpp.c: 418:session_reset_handler: *DEBUG*: Reset session 0xb7d670 (1) handler
vpp.c: 872:spdk_vpp_sock_recv: *DEBUG*: Client 0xb7d670(1) is disconnected.
vpp.c: 300:session_accepted_handler: *DEBUG*: Listeners handle is 6917529023346180096
vpp.c: 174:_spdk_vpp_session_create: *DEBUG*: Creating new session 0xb7d730 (2)
vpp.c: 311:session_accepted_handler: *DEBUG*: Accept session 0xb7d730 (2) on 0xb7d5b0 (0/6917529023346180096)
vpp.c: 817:spdk_vpp_sock_accept: *DEBUG*: Client 0xb7d730(2) accepted.
iscsi_tgt: iscsi.c:446: spdk_iscsi_read_pdu: Assertion `ahs_len <= ISCSI_AHS_LEN' failed.
```

On successful runs, the session reset does not occur.

**Comment by jimharris** [comment]
The ahs_len assert must be a by-product of the session reset.  None of the initiators we test with send any AHS data - so if this assert is hitting it must be due to reading invalid data off the TCP stream.

Session reset could indicate that the initiator dropped the connection because it detected something bad.  And if we look at the 39920 dmesg.log, we see this:

[437155.641194] sd 11:0:0:0: [sdb] Attached SCSI disk
[437155.646956] sd 11:0:0:1: [sdc] Attached SCSI disk
[437163.496326]  connection310:0: iscsi_tcp: datalen 13608722 > 262144
[437163.496339]  connection310:0: detected conn error (1006)
[437286.924404]  session310: session recovery timed out after 120 secs
[437286.924431] sd 11:0:0:1: rejecting I/O to offline device
[437286.924436] print_req_error: 4 callbacks suppressed
[437286.924439] print_req_error: I/O error, dev sdc, sector 22528 flags 0
[437286.924476] sd 11:0:0:1: rejecting I/O to offline device
[437286.924479] print_req_error: I/O error, dev sdc, sector 26624 flags 0
[437286.924503] sd 11:0:0:1: rejecting I/O to offline device
[437286.924506] print_req_error: I/O error, dev sdc, sector 30720 flags 0
[437286.924529] sd 11:0:0:1: rejecting I/O to offline device

Since this is failing with very large reads, my suspicion is that something in the VPP code isn't handling partial writes correctly.

**Comment by jimharris** [comment]
Slightly different failing signature but fairly certain this is related to the same issue:

https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_40529.html

**Comment by shuhei-matsumoto** [comment]
Another log

https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/41185/archive/vpp_autotest/build.log

**Comment by Seth5141** [comment]
Another log from fio

https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_42124.html

**Comment by jimharris** [comment]
Bug scrub: Closing this issue - hasn't been seen in over 5 months and we we aren't actively debugging issues only seen with VPP.
