### ISSUE TITLE
Getting poor performance with the blobstore

### ISSUE THREAD

**Issue by stevelandiss** [spdk/spdk#919]
I created an fio_plugin engine backend based on the bdev/fio_plugin sample code and I am getting very low performance.  For comparison, against the same NVMe backend device. bdev is able to get around 80k IOPS, but when I go through the BLOB layer, it drops to 300.

My code is available here: https://github.com/stevelandiss/spdk/tree/master/examples/blob/fio_plugin

## Expected Behavior
I would expect IOPS numbers to be close to the bdev numbers

## Current Behavior
The IOPS when going through the BLOB store drops to a very low range (~300 IOPS)

## Possible Solution
N/A

## Steps to Reproduce
1. Clone my source repo at https://github.com/stevelandiss/spdk/tree/master/examples/blob/fio_plugin
2. Follow the instructions in the README.md available at the above repository.  It requires that you have the SPDK repo available

## Context (Environment including OS version, SPDK version, etc.)
Host information
```
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

NVMe information: Intel NVMe
FIO version: fio-3.3

**Comment by tomzawadzki** [comment]
Hi @stevelandiss 
Briefly looking at the linked repo, it seems that you are creating blobstore on top of AIO bdev - not NVMe bdev. AIO performance depends on which device its based on and adds overhead by itself.

I'd suggest using Logical volumes, which is bdev module built on top of blobstore. See documentation here: https://spdk.io/doc/logical_volumes.html

To use it with spdk/examples/bdev/fio_plugin, _no changes are required._
Small note, fio_plugin does not accept RPC. Best way is to set up lvols on NVMe device is to use any other SPDK app like, app/spdk_tgt. Metadata for blobstore/lvolstore is persistent on the device and fio_plugin will detect it on startup, loading up previously created blobs/lvols.

**Comment by stevelandiss** [comment]
Hi @tomzawadzki thank you for your reply.  I did in fact write an fio plugin using logical volumes as well and get the same results as the blob store.  Note that... I do not know how to initialize the LVS (logical volume store) with a an NVMe bdev... perhaps that is where I can use some help.  Below is my fio plugin for logical volumes... if you could help me with the proper way to initialize my LVS in the `spdk_fio_bdev_open` function in the code below, that could point me in the right direction...  Again thank you for your help...

```

**Comment by tomzawadzki** [comment]
Please note that its not change of using blobstore to lvolstore that you would see the improvement in performance, its **changing from AIO bdev to NVMe bdev**.
The NVMe bdev itself has to be present and attached to the application, so bdev.conf.in from linked repo needs to have NVMe section. For help on creating this section see spdk/scripts/gen_nvme.sh. Then using bdev API [spdk_bdev_get_by_name()] get reference to NVMe bdev, which can be used in blobstore/lvolstore initialization.

**Is there a reason why the fio_plugin is modified ?**
What is currently in SPDK repo supports the above scenario of running FIO on lvol bdevs. Along with plethora of other configuration options already available for lvols via RPC. Steps to run I/O on lvol bdev using fio_plugin are:
1) Start spdk/app/spdk_tgt
2) Attach NVMe bdev to the target via [RPC](https://spdk.io/doc/jsonrpc.html#rpc_construct_nvme_bdev)
3) Configure lvols on the NVMe bdev via [RPC](https://spdk.io/doc/jsonrpc.html#jsonrpc_components_lvol)
4) Close spdk_tgt
5) Run spdk/examples/bdev/fio_plugin and provide NVMe bdev in config [see gen_nvme.sh]

There is no step 6, since the lvol store will load up exactly as set up before closing spdk_tgt (metadata is persistent on device). For details on logical volumes, please see [here](https://spdk.io/doc/logical_volumes.html).

**Comment by stevelandiss** [comment]
@tomzawadzki Thank you... I get it now.  Just two questions... when I run gen_nvme.sh, it generates this:
```

**Comment by tomzawadzki** [comment]
There are couple things to unfold here. 
- The output from gen_nvme.sh provides all necessary info for SPDK application to create bdev from NVMe device (transport type, transport address and **name** that will be used for the NVMe bdev).
- You've created lvol store on top of that NVMe bdev, and some lvol bdevs in that lvol store. This will result in new bdevs being present.

In general **all bdevs** have two properties that are used to identify them - `name` and `alias`.
`get_bdevs` RPC or `spdk_bdev_get_by_name()` bdev API return certain bdev using those two fields. All bdevs are **required** to have `name` that is unique among all SPDK bdevs at time of creation. Aliases are **optional** for bdev modules to add, but have to be unique as well.
With that in mind lvol bdev module design uses `uuid` (that is persisted in metadata too) as bdev `name` and use provide _lvol name_ as `alias`. User can refer to certain lvol bdev by either one.
This was chosen because lvols are automatically loaded when device containing them is attached. If _lvol names_ conflict during this operation they are not added as alias, but lvol bdev is still loaded and can be referred to by its bdev `name` (which is an uuid generated at creation time).

Getting back to pointing fio_plugin to the lvol bdev (or any other bdev). **Use bdev `name` or `alias` in fio configuration as _filename_ parameter.** In this case its either `e210d28d-ed47-4775-8406-7afc47ea17f9` (lvol bdev name) or `lvs_name/lvol_name` (lvol bdev alias).

The above can be found in [bdev](https://spdk.io/doc/bdev.html), [lvol ](https://spdk.io/doc/logical_volumes.html) and [RPC ](https://spdk.io/doc/jsonrpc.html)documentation - admittedly it is bit spread out.

Those kind of questions are perfect for Slack, so please feel free to join the SPDK community there too. There is always someone online, so responses will be much more immediate :)
https://spdk.io/community/

**Comment by stevelandiss** [comment]
@tomzawadzki thank you for your explanation... I will close this issue
