### ISSUE TITLE
Configuring status raid bdevs with SPDK

### ISSUE THREAD

**Issue by liang2yan** [spdk/spdk#921]
## Expected Behavior
No configuring status RAID BDEV.

## Current Behavior

    ./rpc.py construct_raid_bdev -n StoragePool1 -r 0 -z 64  -b "NVMe3n1"   -->This command will cause the issue. It will report error message, but a "Configuring" status raid is built.
  

## Possible Solution
  It seems with above steps, we can't recover previous settings after system reboot. But the steps work with old version SPDK v18.04. How should we do if we want to recover the setting after the system reboot?
## Steps to Reproduce
```
./setup.sh
    ./app/nvmf_tgt/nvmf_tgt -i 1 &
    ./rpc.py nvmf_create_transport -t RDMA -u 8192 -p 4 -c 0
    ./rpc.py construct_nvme_bdev -b NVMe1 -t PCIe -a 0000:08:00.0
    ./rpc.py construct_nvme_bdev -b NVMe2 -t PCIe -a 0000:0d:00.0
    ./rpc.py construct_nvme_bdev -b NVMe3 -t PCIe -a 0000:12:00.0
    ./rpc.py construct_nvme_bdev -b NVMe4 -t PCIe -a 0000:17:00.0
    ####Create raid with SSD drive
    ./rpc.py construct_raid_bdev -n StoragePool1 -r 0 -z 64  -b "NVMe3n1"
    ###Create volume store
    ./rpc.py construct_lvol_store StoragePool1 StoragePool1store
    ###Create volume on the volume store
    ./scripts/rpc.py construct_lvol_bdev -l StoragePool1store "1" 10240
    Then reboot the system, and after the system rebooted, run below command:
    ./setup.sh
    ./app/nvmf_tgt/nvmf_tgt -i 1 &
    ./rpc.py nvmf_create_transport -t RDMA -u 8192 -p 4 -c 0
    ./rpc.py construct_nvme_bdev -b NVMe1 -t PCIe -a 0000:08:00.0
    ./rpc.py construct_nvme_bdev -b NVMe2 -t PCIe -a 0000:0d:00.0
    ./rpc.py construct_nvme_bdev -b NVMe3 -t PCIe -a 0000:12:00.0
    ./rpc.py construct_nvme_bdev -b NVMe4 -t PCIe -a 0000:17:00.0
    ### Recover the RAID
    ./rpc.py construct_raid_bdev -n StoragePool1 -r 0 -z 64  -b "NVMe3n1"   
```

## Context (Environment including OS version, SPDK version, etc.)
spdk version: 19.04.1

**Comment by liang2yan** [comment]
Current comment:
Hi Neil,
    
 I started looking into this and can easily reproduce.  Question though, why are you using a single disk RAID0? Or are you meaning to create a RAID0 out of all of the nvme devices in which case when you create the raid you need to pass in a list of all of the devices.  The thinking is that this would work with other than a single disk RAID0 (which has no real value in anything except test). 
    
Thx
Paul
-------------------------------
After reboot, could you try construct_raid_bdev *before* construct_nvme_bdev?

Doing construct_raid_bdev first will cause the RAID module to claim NVMe3n1 once it appears without giving other modules (such as logical volumes) a chance to claim it.  Then after the RAID module registers the StoragePool1 bdev, the logical volume module will see the blobstore/lvolstore metadata on StoragePool1 and claim it.

Building on what Paul said, single disk RAID0 is the only case where switching the order would be needed.  For a multiple disk RAID0, lvol would see the metadata on the first member disk, but then would see the size of the member disk didn't match the size of the blobstore and wouldn't claim it.  That would give you a chance to construct_raid_bdev.  Once the RAID volume was registered, lvol would confirm the size reported in the lvol metadata matched the size of the RAID volume itself.

-Jim
-----------------------------------------
FYI switching the order worked for me...
-Paul

**Comment by shibingxun** [comment]
Hi Paul, Jim, Liang,

Thanks for your help. Below is my update and response:
1.	I tried the same steps with 2 SSD as a RAID bdev, the issue is not there. Just as you point out, it happens only with 1 SSD as a RAID bdev.
2.	The reason why we have 1 SSD as a RAID:
Yes, we understand that creating a RAID with 1 SSD has meaningless. We are using SPDK build up the NVMe-oF model. In our design, the first step is to create a storagepool with large size, and secondly create volume on top of the storagepool, then NVMf target endpoint with the volume. If one SSD is large enough, it can be taken as a storagepool, SPDK may support create partition and build nvmf target with the partition. But we want to use the same logic in the backend with 1 SSD or 2 SSD, or 3 SSD...  As SPDK supports to create RAID bdev with 1 SSD, so no matter how many SSDs are chosen to create a storagepool, we are making the selected SSDs as RAID bdev. This will make simple logic in the design. Do you think this make sense?
3.	>>>>After reboot, could you try construct_raid_bdev *before* construct_nvme_bdev?
Sorry, I can understand how this happen. “construct_raid_bdev” command requires “-b” parameter input, which means the block device name should be given.  Without excuting “construct_nvme_bdev”, how could we get the bdev? Before this command, “get_bdevs” shows nothing.. That means, “construct_raid_bdev”  needs "construct_nvme_bdev" create bdev first..

Thanks.
Neil

**Comment by shibingxun** [comment]
Hi Paul, Jim, Liang,

Thanks for your help. Below is my update and response:
1.	I tried the same steps with 2 SSD as a RAID bdev, the issue is not there. Just as you point out, it happens only with 1 SSD as a RAID bdev.
2.	The reason why we have 1 SSD as a RAID:
Yes, we understand that creating a RAID with 1 SSD has meaningless. We are using SPDK build up the NVMe-oF model. In our design, the first step is to create a storagepool with large size, and secondly create volume on top of the storagepool, then NVMf target endpoint with the volume. If one SSD is large enough, it can be taken as a storagepool, SPDK may support create partition and build nvmf target with the partition. But we want to use the same logic in the backend with 1 SSD or 2 SSD, or 3 SSD...  As SPDK supports to create RAID bdev with 1 SSD, so no matter how many SSDs are chosen to create a storagepool, we are making the selected SSDs as RAID bdev. This will make simple logic in the design. Do you think this make sense?
3.	>>>>After reboot, could you try construct_raid_bdev *before* construct_nvme_bdev? <<

Sorry, I can understand how this happen. “construct_raid_bdev” command requires “-b” parameter input, which means the block device name should be given.  Without excuting “construct_nvme_bdev”, how could we get the bdev? Before this command, “get_bdevs” shows nothing.That means “construct_raid_bdev” needs “construct_nvme_bdev” create bdev first.

Thanks.
Neil

**Comment by shibingxun** [comment]
Hi Paul, Jim, Liang,

Thanks for your help. Below is my update and response:
1.	I tried the same steps with 2 SSD as a RAID bdev, the issue is not there. Just as you point out, it happens only with 1 SSD as a RAID bdev.
2.	The reason why we have 1 SSD as a RAID:
Yes, we understand that creating a RAID with 1 SSD has meaningless. We are using SPDK build up the NVMe-oF model. In our design, the first step is to create a storagepool with large size, and secondly create volume on top of the storagepool, then NVMf target endpoint with the volume. If one SSD is large enough, it can be taken as a storagepool, SPDK may support create partition and build nvmf target with the partition. But we want to use the same logic in the backend with 1 SSD or 2 SSD, or 3 SSD...  As SPDK supports to create RAID bdev with 1 SSD, so no matter how many SSDs are chosen to create a storagepool, we are making the selected SSDs as RAID bdev. This will make simple logic in the design. Do you think this make sense?
3.	>>>>After reboot, could you try construct_raid_bdev *before* construct_nvme_bdev? <<<<

Sorry, I can’t understand how this happen. “construct_raid_bdev” command requires “-b” parameter input, which means the block device name should be given.  Without excuting “construct_nvme_bdev”, how could we get the bdev? Before this command, “get_bdevs” shows nothing.That means “construct_raid_bdev” needs “construct_nvme_bdev” create bdev first.

Thanks.
Neil

**Comment by tomzawadzki** [comment]
Hi Neil,

> Sorry, I can’t understand how this happen. “construct_raid_bdev” command requires “-b” parameter input, which means the block device name should be given. Without excuting “construct_nvme_bdev”, how could we get the bdev? Before this command, “get_bdevs” shows nothing.That means “construct_raid_bdev” needs “construct_nvme_bdev” create bdev first.

Raid bdevs do not require the underlying bdevs to be present at creation time. `construct_raid_bdev` RPC can be issued on non-existent _bdev names_. When bdevs with those names appear at later time, they will immediately be claimed by the bdev module.

Until all bdevs underlying the raid bdev are present, no I/O is possible with raid bdev and `get_bdevs` do not list raid bdev. There is separate RPC to show all raid bdevs in offline state - `get_raid_bdevs`.

This behaviour is described [here](https://spdk.io/doc/bdev.html#bdev_ug_raid).

**Comment by peluse** [comment]
Hi Neil,

Wrt reversing the order it works because RAID was written with an examine_config entry point defined because it does not use metadata data on disk, lvol was written with an examine_disk entry point.  When you call the RAID RPC and it can’t find the bdev it just remembers the name so when its examine function is called (when the nvme shows up) it will grab it. Below the snippet from bdev.c that shows why RAID goes first in this case.

Can you confirm this works on your end?

Thx
Paul

              /*
              * Modules with examine callbacks must be initialized first, so they are
              *  ready to handle examine callbacks from later modules that will
              *  register physical bdevs.
              */
              if (bdev_module->examine_config != NULL || bdev_module->examine_disk != NULL) {
                             TAILQ_INSERT_HEAD(&g_bdev_mgr.bdev_modules, bdev_module, internal.tailq);
              } else {
                             TAILQ_INSERT_TAIL(&g_bdev_mgr.bdev_modules, bdev_module, internal.tailq);
              }

**Comment by peluse** [comment]
Using either >1 disk in the RAID or creating the RAID bdev before the NVME bdevs will make this work.  The single disk case is special in that the size of the vol and disk are the same so unless the RAID is created first, lvol will read the metadata and grab it which puts things in a very bad state

**Comment by peluse** [comment]
Hmmm, hate to question my own answer but Jim the snippet I pasted below would put RAID and lvol in the same category tight? So what is guaranteeing that the RAID examine will happen before the lvol in this case?

Thx
Paul

From: Luse, Paul E
Sent: Wednesday, August 21, 2019 6:18 AM
To: 'spdk/spdk' <reply@reply.github.com>; spdk/spdk <spdk@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: RE: [spdk/spdk] Configuring status raid bdevs with SPDK (#921)

Hi Neil,

Wrt reversing the order it works because RAID was written with an examine_config entry point defined because it does not use metadata data on disk, lvol was written with an examine_disk entry point.  When you call the RAID RPC and it can’t find the bdev it just remembers the name so when its examine function is called (when the nvme shows up) it will grab it. Below the snippet from bdev.c that shows why RAID goes first in this case.

Can you confirm this works on your end?

Thx
Paul

              /*
              * Modules with examine callbacks must be initialized first, so they are
              *  ready to handle examine callbacks from later modules that will
              *  register physical bdevs.
              */
              if (bdev_module->examine_config != NULL || bdev_module->examine_disk != NULL) {
                             TAILQ_INSERT_HEAD(&g_bdev_mgr.bdev_modules, bdev_module, internal.tailq);
              } else {
                             TAILQ_INSERT_TAIL(&g_bdev_mgr.bdev_modules, bdev_module, internal.tailq);
              }

**Comment by jimharris** [comment]
bdev_raid.c implements the examine_config function pointer, while vbdev_lvol.c implements the examine_disk function pointer.  spdk_bdev_start() in bdev.c will call all of the examine_config function pointers first.  If it's not claimed by any of them, it will proceed with calling the examine_disk function pointers.

**Comment by shibingxun** [comment]
Hi Tomasz,
Thanks. Now I understand how it works , and I tried "construct_raid_bdev" with a non-created bdev name, it can be success. The RAID bdev status is "configuring", and after the nvme bdev created, the RAID bdev status will change to "online".

Hi Paul, Jim,
Thank you so much. Change the command sequence really works with 1 SSD. Now we can make some update in our flow, then the solutin will be OK with any nubmer SSDs.

Neil
