### ISSUE TITLE
QEMU memory registration failure with PMEM

### ISSUE THREAD

**Issue by vermavis** [spdk/spdk#930]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

QEMU is registering this pmem memory region with the SPDK process, but SPDK only knows how to register ‘regular’ huge page memory. This is making guest VM to not boot. 

## Expected Behavior

It would be good for SPDK process to register pmem memory region, that would allow the VM to boot with pmem and also run SPDK vhost-scsi process to underlying I/O device.

## Current Behavior

Failed memory registration with SPDK vhost.

## Steps to Reproduce

1. Configure pmem device in fsdax mode, and write a raw file with XFS fs on a pmem directory with given size (SIZE) "SIZE" being the size of pmem device the guest should see.
2. Run QEMU with pmem device, provide the pmem file as a source for QEMU to map pmem device onto the guest.
3. Command line:
qemu-system-x86_64 --enable-kvm -machine pc,nvdimm -m 40G,slots=1,maxmem=280G \
-cpu host -smp 14 -nographic \
-vnc 10.34.119.34:1 \
-drive file=/home/centos7.0_5.qcow2,if=none,id=disk \
-device ide-hd,drive=disk,bootindex=0 \
-object memory-backend-file,id=mem1,share=on,pmem=on,mem-path=/mnt/pmem0/pmem1.img,size=240G \
-object memory-backend-file,id=mem,size=1G,mem-path=/dev/hugepages,share=on \
-device nvdimm,id=nvdimm1,memdev=mem1 \
-chardev socket,id=spdk_vhost_scsi0,path=/home/vermavis/spdk/vhost.0 \
-device vhost-user-scsi-pci,id=scsi0,chardev=spdk_vhost_scsi0,num_queues=14 \ 
4. Using RPC to create a remote NVMe-oF TCP bdev and add it as vhost scsi lun to be able to use it as a vhost-scsi device from within the guest
./scripts/rpc.py construct_nvme_bdev -b Nvmf0 -t tcp -f ipv4 -a 192.168.25.2 -s 4421 -n testnqn0
./scripts/rpc.py construct_vhost_scsi_controller vhost.0
./scripts/rpc.py add_vhost_scsi_lun vhost.0 0 Nvmf0n1

## Context (Environment including OS version, SPDK version, etc.)

Running it on Fedora 29, 
with SPDK commit: 0ce883cef0e, 
QEMU :v4.0.094 (v4.1.0-rc4)
[vhost_log.txt](https://github.com/spdk/spdk/files/3543095/vhost_log.txt)

**Comment by vermavis** [comment]
SPDK tgt process logs when running QEMU with /dev/hugepages vs. PMEM (/dev/dax). 
Ran with spdk_build_eal_cmdline  --log-level=lib.eal:8

[log_hugepages.txt](https://github.com/spdk/spdk/files/3561121/log_hugepages.txt)
[log_pmem_devdax.txt](https://github.com/spdk/spdk/files/3561122/log_pmem_devdax.txt)

**Comment by darsto** [comment]
SPDK translates only 2MB-aligned virtual addresses and assumes:
`2MB_aligned_vaddr + offset == vtophys(2MB_aligned_vaddr) + offset`

This is not true for memory that's not physically contiguous in sub-2MB granularity.

If the VM doesn't boot, the above could be a reason. In such case, SPDK ends up writing to `vtophys(2MB_aligned_vaddr) + offset`, which is different from `vtophys(2MB_aligned_vaddr + offset)`. So instead of writing to the region the VM expects us to, we end up writing to something completely different and possibly corrupt the VM.

I'm not sure how pmem works so I still have to verify this.

**Comment by peluse** [comment]
@changpe1 @darsto I'm in the same geo as @vermavis so I'm going to jump in and help out on this one...

**Comment by peluse** [comment]
quick update: awaiting access to PMEM system but int he meantime:
* From the docs it seems clear that a PMEM name space system physical address is contiguous but I'll get on pmem IRC and confirm
* I can use qemu with emulated pmem on my dev system and reproduce the same behaviors that Vishal describes wrt hugepages, pmem alone (boots) and pmem w/scsi vhost (hangs
* Note using vhost-blk still hangs but gets further
* The hang is in SeaBios, not quite sure how to debug form the SPDK side yet (not much to go on, we're just sitting there waiting for work) but I can add prints to SeaBios, rebuild and use w/qemu.  Can't src level debug but I'll start adding some prints to see if I can find the hang and maybe that will be enough to find out what we're doing on the SPDK side (or PMDK or wherever)

**Comment by peluse** [comment]
@vermavis can you try adding both "-object memory-backend-file" options at the same time? That made it work for me and Jim and I can kinda see why but how the -m option is related to the backend-file options isn't totally clear yet.  Either way please give it a shot.

**Comment by peluse** [comment]
BTW the reason this works is because the virtio queues are being mapped into the hugepage mem object, not the pmem.  So you should have pmem available in the VM but SPDK isn't using it.  Here's what my VM looks like with hugepages, pmem and spdk vhost iscsi target:

peluse@q2:~$ lsblk --output "NAME,KNAME,MODEL,HCTL,SIZE,VENDOR,SUBSYSTEMS"
NAME   KNAME MODEL            HCTL        SIZE VENDOR   SUBSYSTEMS
fd0    fd0                                  4K          block:platform
loop0  loop0                               89M          block
loop1  loop1                             88.5M          block
sda    sda   QEMU HARDDISK    1:0:0:0      20G ATA      block:scsi:pci
├─sda1 sda1                                 1M          block:scsi:pci
└─sda2 sda2                                20G          block:scsi:pci
sdb    sdb   Malloc disk      2:0:0:0      64M INTEL    block:scsi:virtio:pci
pmem0  pmem0                                4G          block:nd:acpi

**Comment by vermavis** [comment]
OK- that makes sense.
I will give it a shot and let you know if it works or not.

**Comment by peluse** [comment]
just out of curiosity, what exactly are you trying to uses pmem for in this configuration/test?

**Comment by vermavis** [comment]
By adding  2nd "-object memory-backend-file" it works just fine like Paul indicated. 

Here is the corrected qemu command line that I used:
qemu-system-x86_64 --enable-kvm -machine pc,nvdimm -m 4G,slots=1,maxmem=8G \
-cpu host -smp 14 -nographic \
-vnc 10.34.119.34:1 \
-drive file=/home/centos7.0_5.qcow2,if=none,id=disk \
-device ide-hd,drive=disk,bootindex=0 \
-object memory-backend-file,id=mem0,size=4G,mem-path=/dev/hugepages,share=on \
-numa node,memdev=mem0 \
-object memory-backend-file,id=mem1,share=on,pmem=on,mem-path=/dev/dax1.0,size=4G,align=2M \
-device nvdimm,id=nvdimm1,memdev=mem1 \
-chardev socket,id=spdk_vhost_scsi0,path=/home/vermavis/spdk/vhost.0 \
-device vhost-user-scsi-pci,id=scsi0,chardev=spdk_vhost_scsi0,num_queues=14 \
-net nic,model=virtio,macaddr=$(cat /sys/class/net/macvtap10/address) \
-net tap,fd=3 3<>/dev/tap$(cat /sys/class/net/macvtap10/ifindex) &

On the VM I can see: pmem0 device of size 4G, vhost-scsi device of whatever size it was and 4G Memory being allocated as expected.

Thanks for debugging this Paul!

**Comment by peluse** [comment]
Heh, didn't fix anything actually but thanks @jimharris for wondering why we weren't including the hugepage backing object :)
