### ISSUE TITLE
intermittent failure for test/bdev/blockdev.sh with AIO backend in autotest 

### ISSUE THREAD

**Issue by changpe1** [spdk/spdk#935]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

intermittent failure for test/bdev/blockdev.sh with AIO backend in autotest 

## Current Behavior

sha1: verify failed at file AIO0 offset 7667712, length 196608
       Expected CRC: 29a28934f6847e5f1d0ff0ab8ba2636acafc5e00
       Received CRC: 22e2b81042435120cef21af6473281328c75434b
fio: pid=9185, err=84/file:io_u.c:2108, func=io_u_queued_complete, error=Invalid or incomplete multibyte or wide character

## Steps to Reproduce
intermittent failure with nightly tests

## Context (Environment including OS version, SPDK version, etc.)

07:03:48	# /usr/src/fio/fio --ioengine=spdk_bdev --iodepth=128 --bs=192k --runtime=100 /var/jenkins/workspace/Other_systems/ubuntu18_autotest/spdk/test/bdev/bdev.fio --spdk_conf=./test/bdev/bdev.conf --spdk_mem=0
job_Malloc0: (g=0): rw=randwrite, bs=(R) 192KiB-192KiB, (W) 192KiB-192KiB, (T) 192KiB-192KiB, ioengine=spdk_bdev, iodepth=128
job_Malloc1p0: (g=0): rw=randwrite, bs=(R) 192KiB-192KiB, (W) 192KiB-192KiB, (T) 192KiB-192KiB, ioengine=spdk_bdev, iodepth=128
job_Malloc1p1: (g=0): rw=randwrite, bs=(R) 192KiB-192KiB, (W) 192KiB-192KiB, (T) 192KiB-192KiB, ioengine=spdk_bdev, iodepth=128
job_Malloc2p0: (g=0): rw=randwrite, bs=(R) 192KiB-192KiB, (W) 192KiB-192KiB, (T) 192KiB-192KiB, ioengine=spdk_bdev, iodepth=128
job_Malloc2p1: (g=0): rw=randwrite, bs=(R) 192KiB-192KiB, (W) 192KiB-192KiB, (T) 192KiB-192KiB, ioengine=spdk_bdev, iodepth=128
job_Malloc2p2: (g=0): rw=randwrite, bs=(R) 192KiB-192KiB, (W) 192KiB-192KiB, (T) 192KiB-192KiB, ioengine=spdk_bdev, iodepth=128
job_Malloc2p3: (g=0): rw=randwrite, bs=(R) 192KiB-192KiB, (W) 192KiB-192KiB, (T) 192KiB-192KiB, ioengine=spdk_bdev, iodepth=128
job_Malloc2p4: (g=0): rw=randwrite, bs=(R) 192KiB-192KiB, (W) 192KiB-192KiB, (T) 192KiB-192KiB, ioengine=spdk_bdev, iodepth=128
job_Malloc2p5: (g=0): rw=randwrite, bs=(R) 192KiB-192KiB, (W) 192KiB-192KiB, (T) 192KiB-192KiB, ioengine=spdk_bdev, iodepth=128
job_Malloc2p6: (g=0): rw=randwrite, bs=(R) 192KiB-192KiB, (W) 192KiB-192KiB, (T) 192KiB-192KiB, ioengine=spdk_bdev, iodepth=128
job_Malloc2p7: (g=0): rw=randwrite, bs=(R) 192KiB-192KiB, (W) 192KiB-192KiB, (T) 192KiB-192KiB, ioengine=spdk_bdev, iodepth=128
job_TestPT: (g=0): rw=randwrite, bs=(R) 192KiB-192KiB, (W) 192KiB-192KiB, (T) 192KiB-192KiB, ioengine=spdk_bdev, iodepth=128
job_raid0: (g=0): rw=randwrite, bs=(R) 192KiB-192KiB, (W) 192KiB-192KiB, (T) 192KiB-192KiB, ioengine=spdk_bdev, iodepth=128
job_crypto_ram: (g=0): rw=randwrite, bs=(R) 192KiB-192KiB, (W) 192KiB-192KiB, (T) 192KiB-192KiB, ioengine=spdk_bdev, iodepth=128
job_crypto_ram2: (g=0): rw=randwrite, bs=(R) 192KiB-192KiB, (W) 192KiB-192KiB, (T) 192KiB-192KiB, ioengine=spdk_bdev, iodepth=128
job_AIO0: (g=0): rw=randwrite, bs=(R) 192KiB-192KiB, (W) 192KiB-192KiB, (T) 192KiB-192KiB, ioengine=spdk_bdev, iodepth=128
job_Nvme0n1p1: (g=0): rw=randwrite, bs=(R) 192KiB-192KiB, (W) 192KiB-192KiB, (T) 192KiB-192KiB, ioengine=spdk_bdev, iodepth=128
job_Nvme0n1p2: (g=0): rw=randwrite, bs=(R) 192KiB-192KiB, (W) 192KiB-192KiB, (T) 192KiB-192KiB, ioengine=spdk_bdev, iodepth=128
fio-3.3
Starting 18 threads
Starting SPDK v19.10-pre / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: fio --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid9166 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
cryptodev_aesni_mb_create() line 1304: IPSec Multi-buffer library version used: 0.52.0

vbdev_crypto.c:1372:vbdev_crypto_init: *NOTICE*: WARNING: You are storing your key in a plain text file!!
vbdev_crypto.c:1372:vbdev_crypto_init: *NOTICE*: WARNING: You are storing your key in a plain text file!!
vbdev_passthru.c: 505:vbdev_passthru_init: *NOTICE*: conf parse matched: Malloc3
vbdev_passthru.c: 601:vbdev_passthru_register: *NOTICE*: Match on Malloc3
vbdev_passthru.c: 644:vbdev_passthru_register: *NOTICE*: io_device created at: 0x0x614000011e40
vbdev_passthru.c: 656:vbdev_passthru_register: *NOTICE*: bdev opened
vbdev_passthru.c: 668:vbdev_passthru_register: *NOTICE*: bdev claimed
vbdev_passthru.c: 681:vbdev_passthru_register: *NOTICE*: pt_bdev registered
vbdev_passthru.c: 682:vbdev_passthru_register: *NOTICE*: created pt_bdev for: TestPT
sha1: verify failed at file AIO0 offset 7667712, length 196608
       Expected CRC: 29a28934f6847e5f1d0ff0ab8ba2636acafc5e00
       Received CRC: 22e2b81042435120cef21af6473281328c75434b
fio: pid=9185, err=84/file:io_u.c:2108, func=io_u_queued_complete, error=Invalid or incomplete multibyte or wide character

**Comment by changpe1** [comment]
We will use the following configuration for this AIO backend:

# Create a file to be used as an AIO backend
dd if=/dev/zero of=/tmp/aiofile bs=2048 count=5000

[AIO]
  AIO /tmp/aiofile AIO0 2048

I will try to reproduce in my local environment first.

**Comment by ChenBo2333** [comment]
This failure : https://10.102.17.104:8080/job/Other_systems/job/ubuntu18_autotest/9579/artifact/build.log
and similar nightly failure : 
https://10.102.17.104:8080/job/Other_systems/job/centos7_autotest/35056/artifact/build.log

**Comment by Comphix** [comment]
This issue is still existing at Oct. 10 nightly testing

https://dqtibwqq6s6ux.cloudfront.net/results/autotest-nightly-failing/builds/539/archive/ubuntu18_autotest_nightly/build.log

**Comment by Comphix** [comment]
With same configuration, 128K IO size looks like not able to hit the error. The current error is from 192K IO size. Is it due to some split? overlap?

**Comment by Comphix** [comment]
IO is split into 64K for the write

**Comment by optimistyzy** [comment]
@Comphix A flush I/O request should be sent then kick the flush (SPDK_BDEV_IO_TYPE_FLUSH) and trigger bdev_aio_flush function, and we will use fsync to sync the data. What's block size configured for this aio block device?

**Comment by Comphix** [comment]
Kicked off a 120 minutes long run with same configuration (and applied the O_SYNC change), this issue is not seen. So seems like some data flush related with the AIO bdev.  I know it's not proper to add this new flag when opening the AIO device to impact the performance. It is more reasonable to ask the upper application to call the flush API to make the consistency. In this case, how shall we handle this issue? Change to the IO size from 192K to a smaller one?

**Comment by changpe1** [comment]
Right, AIO backend has two split conditions, the IO boundary and IO size, so there are at least 3 children IOs for each 192KiB request from FIO.  Does FIO send any requests with overlapped LBA ?

**Comment by benlwalker** [comment]
I believe doing random writes with a verify backlog just won't work. What happens is fio does 1024 random writes, then does 1024 reads to verify the data. But if any of those 1024 initial writes overlapped, the read verification will fail.

I think the "serialize_overlap=1" option will fix this. Have you tried that?

**Comment by Comphix** [comment]
@benlwalker , thanks for the suggestion. Let me have a try on this.

**Comment by Comphix** [comment]
Besides above new parameter, will also need to add "verify_backlog=1024" another parameter. Otherwise, it will show below message:

fio: verification read phase will never start because write phase uses all of runtime
job1: (g=0): rw=randwrite, bs=(R) 192KiB-192KiB, (W) 192KiB-192KiB, (T) 192KiB-192KiB, ioengine=spdk_bdev, iodepth=128

**Comment by Comphix** [comment]
Raise the patch https://review.gerrithub.io/c/spdk/spdk/+/471428

**Comment by Comphix** [comment]
Thanks Jim on your comment.

Just tried with the NVMe bdev together with AIO, Malloc bdev and without the "norandommap=1" setting, the issue is there.

fio --ioengine=./fio_plugin --iodepth=128 --bs=192k --runtime=100 ./config.fio --spdk_conf=./bdev.conf --spdk_mem=0
job1: (g=0): rw=randwrite, bs=(R) 192KiB-192KiB, (W) 192KiB-192KiB, (T) 192KiB-192KiB, ioengine=spdk_bdev, iodepth=128
job2: (g=0): rw=randwrite, bs=(R) 192KiB-192KiB, (W) 192KiB-192KiB, (T) 192KiB-192KiB, ioengine=spdk_bdev, iodepth=128
job3: (g=0): rw=randwrite, bs=(R) 192KiB-192KiB, (W) 192KiB-192KiB, (T) 192KiB-192KiB, ioengine=spdk_bdev, iodepth=128
fio-3.3
Starting 3 threads
Starting SPDK v19.10-pre / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: fio --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid11837 ]
EAL: No available hugepages reported in hugepages-1048576kB
sha1: verify failed at file AIO0 offset 9830400, length 196608776 IOPS][eta 01m:24s]
       Expected CRC: 56de80ea66a602b21f04bf9d362d30d1c1cf8648
       Received CRC: 311e2f060a4951b8e6f2a603def668c83fcb8bfb

FIO setting:

[global]
thread=1
group_reporting=0
direct=1
do_verify=1
verify=sha1
verify_backlog=1024
time_based=1
ramp_time=0
#serialize_overlap=1
#norandommap=1
rw=randwrite

This looks like majorly due to the AIO flush handling especially after IO is split into small sizes (here we use 192K IO size and will split into 3 64K sub IOs).

**Comment by Comphix** [comment]
Looking at the issue https://github.com/spdk/spdk/issues/948, it is also seen on NVMe SSD

**Comment by Comphix** [comment]
#948 seems like different with 4K IO on multiple namespace NVMe SSD
