### ISSUE TITLE
is spdk_put_io_channel thread safe?

### ISSUE THREAD

**Issue by yupeng0921** [spdk/spdk#950]
From the code of spdk_put_io_channel, I suppose this function could be called on multiple threads, because it would operate two reference counters and send the actual operation to the thread which the channel belongs to. But I don't think the operations of the reference counters are thread save. Below is the source code:

void
spdk_put_io_channel(struct spdk_io_channel *ch)
{
    SPDK_DEBUGLOG(SPDK_LOG_THREAD,
              "Putting io_channel %p for io_device %s (%p) on thread %s refcnt %u\n",
              ch, ch->dev->name, ch->dev->io_device, ch->thread->name, ch->ref);

    ch->ref--;

    if (ch->ref == 0) {
        ch->destroy_ref++;
        spdk_thread_send_msg(ch->thread, _spdk_put_io_channel, ch);
    }
}

The type of ch->ref and ch->destroy_ref are uint32_t, they are not atomic variables, so ch->ref-- and ch->destroy_ref++ are not atomic operations. If multiple threads operate on the same channel, the values of ch->ref and ch->destroy_ref might be incorrect. Depends on the explain of below article, some inc/dec operations might be lost:
https://en.cppreference.com/w/c/language/atomic

I think we should either use atomic variables for the ch->ref and ch->destroy_ref or protect them by a lock. If I misunderstand anything, please let me know.

**Comment by jimharris** [comment]
Hi @yupeng0921,

Multiple threads must not try to operate on the same channel.  Each thread should get its own channel.

-Jim

**Comment by yupeng0921** [comment]
Hi @jimharris 
If each thread should operate on its own channel, why spdk_put_io_channel calls spdk_thread_send_msg? Why not let spdk_put_io_channel call _spdk_put_io_channel directly?

**Comment by jimharris** [comment]
Oh, good question.  We may need some better comments in the code to make this more clear.

We call spdk_thread_send_msg to allow the stack to unwind before the resources are freed.  Here is a situation:

1) Application gets I/O channel for some device (for example, NVMe bdev)
2) Application issues an I/O
3) Poller for device detects completion, and calls the application's callback
4) In context of application's callback, the application puts the I/O channel since all I/O have been completed (maybe the application is getting ready to exit)
5) Application callback returns to the device poller.  Device poller references the I/O channel again to check for another completion before returning.

If we delete the I/O channel immediately, step #5 causes a use-after-free error.  So we defer deletion of the I/O channel until after the stack unwinds.
