### ISSUE TITLE
spdk_zmalloc failed

### ISSUE THREAD

**Issue by yongseokoh** [spdk/spdk#97]
I was trying to evaluate my own NVMe SSD with perf tool executed with block size set to 64KB (e.g., perf -q 1 -s 65536 -w read -t 5). Unfortunately, the test has been failed with the spdk_zmalloc failed. Before this test, 1GB hugepages was allocated. Could let me know how to resolve this issue?

**Comment by optimistyzy** [comment]
Any error info of spdk_zmalloc failed?

**Comment by yongseokoh** [comment]
The error msg was spdk_zmalloc failed. I didn't see any reason why malloc was failed. Do I have to turn on the DEBUG option to identify detailed info?

**Comment by optimistyzy** [comment]
Not needed.  You can use the following code: perf -q 1 -s 65536 -w read -t 5 -d 1024.  It means that you use 1024 memory instead of 512. From the code, the default mem is 512, you need to rewrite this valud with "-d ".  Also in our current example code, it statically allocates 8192 tasks,  and if your io size is 64KB, the malloc size will be 512M, and there will be other memory used. If you did not use -d, the total huge memory used is 512, so it is not enough. (See line 1182 "-m 512", for the default value used)

**Comment by yongseokoh** [comment]
Thanks. However, the perf tool is still not working for 128KB requests (e.g., ./perf -q 128 -s 131072 -w read -t 5 -d 512).

**Comment by dverkamp-intel** [comment]
With -s 131072, perf will try to allocate 8192 (number of tasks) * 128 KB = 1 GB of buffers, so you will need to increase the -d parameter to be larger than that (plus the other memory allocations that perf and the NVMe library need).  e.g. `perf -q 128 -s 131072 -w read -t 5 -d 1500`

We have some work underway to dynamically size the number of tasks based on the requested queue size and number of namespaces, which would reduce the total necessary DPDK memory for cases where that product is less than 8192 concurrent tasks.

**Comment by yongseokoh** [comment]
This issue has been closed as the number of huge pages increased more than 1.5GB with -d option. Thanks.

**Comment by dverkamp-intel** [comment]
Thanks for testing.  The total amount of memory required for the nvme/perf tool should be reduced for most workloads after commit 11f4362130a0fa38a722e9c508642da1cb409376.
