### ISSUE TITLE
Mount issue with nbd+malloc on ARM64

### ISSUE THREAD

**Issue by habeanf** [spdk/spdk#972]
## Expected Behavior
On ARM64:
```
$ sudo ./rpc.py bdev_malloc_create -b test 128 4096
...
$ sudo ./rpc.py nbd_start_disk test /dev/nbd0
...
$ sudo mkfs.ext3 /dev/nbd0
...
$ sudo mount /dev/nbd0 /nbddisk0
<no error..>
$ touch /nbddisk0/somefile
<no error..>
```
## Current Behavior
```
$ sudo ./rpc.py bdev_malloc_create -b test 128 4096
...
$ sudo ./rpc.py nbd_start_disk test /dev/nbd0
...
$ sudo mkfs.ext3 /dev/nbd0
...
$ sudo mount /dev/nbd0 /nbddisk0
mount: /nbddisk0: wrong fs type, bad option, bad superblock on /dev/nbd0, missing codepage or helper program, or other error.
```
In spdk log:
```
nbd.c: 538: nbd_submit_bdev_io: *ERROR*: nbd io failed in nbd_queue_io, rc=-22
```
## Context (Environment including OS version, SPDK version, etc.)
Hardware: ARM64 (nvidia jetson)
SPDK commit (master HEAD as of issue submit) de1f019edf309de1fa66cac45a8adea21ed89e96 
OS: Ubuntu 18.04

**Comment by tomzawadzki** [comment]
[Bug scrub] @AlekseyMarchuk will take a look at this.

**Comment by AlekseyMarchuk** [comment]
Hi,

I was not able to reproduce this issue on ARM with SPDK version de1f019. I used the following commands:
```
#configure & build
$ git log --pretty=oneline -1
de1f019edf309de1fa66cac45a8adea21ed89e96 nvme/perf: remove unused variable.
$ ./configure --prefix=$PWD/install_arm_gh_issue --disable-tests --enable-debug && make -j install

#run spdk_tgt
$ ./install_arm_gh_issue/bin/spdk_tgt -m 0x2

#run commands to reproduce
$ ./scripts/rpc.py bdev_malloc_create -b test 128 4096
test
$ ./scripts/rpc.py nbd_start_disk test /dev/nbd0
/dev/nbd0
$  mkfs.ext3 /dev/nbd0
mke2fs 1.42.9 (28-Dec-2013)
Discarding device blocks: done
Filesystem label=
OS type: Linux
Block size=4096 (log=2)
Fragment size=4096 (log=2)
Stride=0 blocks, Stripe width=0 blocks
32768 inodes, 32768 blocks
1638 blocks (5.00%) reserved for the super user
First data block=0
Maximum filesystem blocks=33554432
1 block group
32768 blocks per group, 32768 fragments per group
32768 inodes per group

Allocating group tables: done
Writing inode tables: done
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: done

$ mkdir /nbddisk0
$ mount /dev/nbd0 /nbddisk0
$ echo "1" > /nbddisk0/test
$ cat /nbddisk0/test
1
```

I also tried to reproduce the issue on x86 and received an error:
```
$ sudo mount /dev/nbd0 /nbddisk0
mount: wrong fs type, bad option, bad superblock on /dev/nbd0,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.

#SPDK log
nbd.c: 538:nbd_submit_bdev_io: *ERROR*: nbd io failed in nbd_queue_io, rc=-22.
```

ARM setup:
```
$ uname -r
4.20.17-mlnx.1.g0e46f18
$ cat /etc/*-release
CentOS Linux release 7.5.1804 (AltArch)
CentOS7.5-4.20-MLNX_OFED_LINUX-4.6-3.5.8.0.2-aarch64
...
```

I didn't have NBD kernel module on x86, so I compiled it from sources of my kernel version . x86 setup:
```
$ uname -r
3.10.0-862.el7.x86_64
$ cat /etc/*-release
CentOS Linux release 7.5.1804 (Core)
NAME="CentOS Linux"
```

It looks like the problem is not related to SPDK, it is related to NBD module version

**Comment by habeanf** [comment]
@AlekseyMarchuk Perhaps you could verify on a 5.x kernel .. maybe there's an incompatibility with an nbd change in a recent kernel version?

**Comment by AlekseyMarchuk** [comment]
@habeanf unfortunately I don't have 5.x kernel to check incompatibility. I checked it on Ubuntu 18.04 on x86 machine, it was not reproduced.
I added several logs and when mount command is issued, SPDK receives NBD_CMD_READ request with length 1024 bytes. Such request is rejected by bdev layer since it requires buffer size to be divisible by block size. If to change mallock bdev block size to 512 bytes then mount works fine
```
$ ./rpc.py bdev_malloc_create -b test 128 512
```

I'll try to look into NBD module next week to compare working and non-working versions

**Comment by jimharris** [comment]
SPDK CI is running lots of NBD tests with 5.x kernels on x86.  @habeanf - can you also try this on your ARM platform with an older kernel - similar to the one that @AlekseyMarchuk tested with?

**Comment by habeanf** [comment]
@jimharris Unfortunately that's the one thing I'm not sure I can do on the ARM system. The OS image appears to be a customized ubuntu 18.04 by nvidia. I'm not sure critical drivers will work.

**Comment by habeanf** [comment]
I'm not sure if this is the place to ask, but if I understand spdk/dpdk architecture correctly, it requires pinning memory pages for direct I/O on the device side (the iommu stuff [as mentioned here](https://spdk.io/doc/memory.html)). Does the code that sets up this pinning work the same for ARM? Is there any documentation on this?

**Comment by AlekseyMarchuk** [comment]
@habeanf I'm not very familiar with DPDK, probably you can ask someone in slack channel.

Since we have a problem with incorrect size received by SPDK from NBD, I checked the NBD source code and found out that SDPK configures NBD with appropriate block size and number of blocks. NBD applies these values to block device upon startup (when SPDK calls ioctl NBD_DO_IT)
But NBD module receives the incorrect size from blk request via blk_mq. I added several debug prints to NBD module:

These lines appeared after `nbd_start_disk` RPC command:
```
[585787.922278] nbd: registered device at major 43
[585904.008350] NBD_SET_BLKSIZE blksize 4096, nbd->bytesize 0
[585904.008761] NBD_SET_SIZE_BLOCKS blksize 4096, nbd->bytesize 134217728
```
These lines appeared after `mount` command:
```
[586024.523898] send request size 16384
[586024.524179] send request size 24576
[586024.524459] send request size 40960
[586024.524750] send request size 36864
[586024.525218] send request size 57344
[586024.525498] send request size 65536
[586024.526010] send request size 61440
[586024.526588] send request size 4096
[586024.531111] send request size 1024
[586024.531462] block nbd0: Other side returned error (5)
[586024.531871] blk_update_request: I/O error, dev nbd0, sector 2
[586024.532327] EXT4-fs (nbd0): unable to read superblock

```
For unknown reason NBD sends 1024 bytes IO command which is rejected by SPDK.
It seems to be a compatibility issue of NBD version. I think this issue is not related to SPDK and further investigation will take a lot of effort. Could you try another OS or NBD module version?

**Comment by jimharris** [comment]
@habeanf - can you retry your test but with malloc block size 512 instead of 4096?  Maybe nbd has a bug with non-512 byte block sizes.

**Comment by AlekseyMarchuk** [comment]
I tried 512 block size, it worked. As I understood, NBD gets invalid block size via blk_mq from another module, so maybe the root cause not in NBD

**Comment by jimharris** [comment]
Can you try passing -b 4096 to mkfs.ext3?

**Comment by AlekseyMarchuk** [comment]
Unfortunately it doesn't work on my side. `mksf.ext3` reports the correct block size even without `-b 4096`, however `mount` triggers IO request with 1024 bytes length

**Comment by jimharris** [comment]
Thanks @AlekseyMarchuk.  How were you able to finally reproduce this issue?  Was it 5.0+ kernel on ARM?

Could one of you try one more thing for me.  Could you try mkfs.ext4 instead of mkfs.ext3?

Thanks,

-Jim

**Comment by AlekseyMarchuk** [comment]
@jimharris I reproduced it on x86 running CentOS 7.5.1804 with rather old kernel 3.10.0-862
I tried mkfs.ext4, it doesn't work too
