### ISSUE TITLE
NVMeOF kernel host support fast memory registration, if SPDK host support it too?

### ISSUE THREAD

**Issue by gwnet** [spdk/spdk#974]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

Hello intel experts.

NVMeOF kernel host support fast memory registration. but looks like SPDK host does not support this. if we use SPDK host to connect kernel target, what is the risk? can you intel do some analysis for this?

	/*
	 * This device supports the IB "base memory management extension",
	 * which includes support for fast registrations (IB_WR_REG_MR,
	 * IB_WR_LOCAL_INV and IB_WR_SEND_WITH_INV verbs).  This flag should
	 * also be set by any iWarp device which must support FRs to comply
	 * to the iWarp verbs spec.  iWarp devices also support the
	 * IB_WR_RDMA_READ_WITH_INV verb for RDMA READs that invalidate the
	 * stag.
	 */

## Steps to Reproduce

1.
2.
3.
4.

**Comment by optimistyzy** [comment]
@Seth5141

**Comment by AlekseyMarchuk** [comment]
Hi,
Kernel NVMEoF target checks SGL type field and if this field contains `NVME_SGL_FMT_INVALIDATE` bit then kernel sends a response with IB_WR_SEND_WITH_INV opcode and provides actual rkey to be invalidated. If there is no NVME_SGL_FMT_INVALIDATE bit then kernel target uses regular IB_WR_SEND opcode.
Kernel NVMEoF host always sets NVME_SGL_FMT_INVALIDATE bit for requests of type `NVME_KEY_SGL_FMT_DATA_DESC` (`SPDK_NVME_SGL_TYPE_KEYED_DATA_BLOCK` in SPDK). When kernel host receives a response, it checks `wc->wc_flags`, if it contains `IB_WC_WITH_INVALIDATE` that means that the invalidation was done by target, otherwise the host performs local invalidation by posting WR with IB_WR_LOCAL_INV opcode.
So invalidation in kernel target depends on the type of received SGL. SPDK host doesn't set INVALIDATE flag and doesn't use this feature thus kernel target won't make attempts to invalide rkey.
I don't see any interoperability issues here

**Comment by gwnet** [comment]
thank you so much @AlekseyMarchuk. I understand the invalid rkey part now.
I also have some other confusions.
NVMeOF kernel use the FAST memeory registration. it will use one WR to register memory. so kernel host allocate large Send queue. with factor=3.
from NVMeOF kernel host implementation, I see we set QP max_send_wr as 3 times of current NVME queue size. so if SPDK host has compatibility issue here to work with Kernel Target?

SPDK host does not use the Fast memory registration as kernel implementation did. may I know why there is no risk?

memset(&init_attr, 0, sizeof(init_attr));
init_attr.event_handler = nvme_rdma_qp_event;
/* +1 for drain */
init_attr.cap.max_send_wr = factor * queue->queue_size + 1;  factor = 3
/* +1 for drain */
init_attr.cap.max_recv_wr = queue->queue_size + 1;
init_attr.cap.max_recv_sge = 1;
init_attr.cap.max_send_sge = 1 + NVME_RDMA_MAX_INLINE_SEGMENTS;
init_attr.sq_sig_type = IB_SIGNAL_REQ_WR;
init_attr.qp_type = IB_QPT_RC;
init_attr.send_cq = queue->ib_cq;
init_attr.recv_cq = queue->ib_cq;

ret = rdma_create_qp(queue->cm_id, dev->pd, &init_attr);

queue->qp = queue->cm_id->qp;
return ret;

**Comment by AlekseyMarchuk** [comment]
As you said, kernel NVMEoF host uses fast memory registration, so to process 1 request it sends 3 work requests - IB_WR_REG_MR, IB_WR_SEND and IB_WR_LOCAL_INV. Thus it multiplies send queue and receive queue sizes by 3. But these parameters are local for particular qpair. Host and target negotiate queue size during connection establishment. Host sends its queue depth in private data of rdma_conn_param structure.
SPDK host code snippet:
```
nvme_rdma_connect(struct nvme_rdma_qpair *rqpair) {
	...
	request_data.qid = rqpair->qpair.id;
	request_data.hrqsize = rqpair->num_entries; //set by app
	request_data.hsqsize = rqpair->num_entries - 1;

	param.private_data = &request_data;
	ret = rdma_connect(rqpair->cm_id, &param);
```
Kernel target reads qdepth received in private data and responses with the same value.
```
//triggered by RDMA_CM_EVENT_CONNECT_REQUEST
static int
nvmet_rdma_parse_cm_connect_req(struct rdma_conn_param *conn,
				struct nvmet_rdma_queue *queue) 
	queue->recv_queue_size = le16_to_cpu(req->hsqsize) + 1;
	queue->send_queue_size = le16_to_cpu(req->hrqsize);

//ack the connection request
nvmet_rdma_cm_accept
	priv.crqsize = cpu_to_le16(queue->recv_queue_size);
```

When kernel target acks the connection SPDK initiator receives RDMA_CM_EVENT_ESTABLISHED event and checks reported queue depth
```
case RDMA_CM_EVENT_ESTABLISHED:
	rqpair->num_entries = spdk_min(rqpair->num_entries, accept_data->crqsize);
``` 

Kernel host works like SPDK except that it doesn't check crqsize value in kernel's response:
```
nvme_rdma_route_resolved(...)
	if (priv.qid == 0) {
		priv.hrqsize = cpu_to_le16(NVME_AQ_DEPTH); //32
		priv.hsqsize = cpu_to_le16(NVME_AQ_DEPTH - 1); //31
	} else {
		priv.hrqsize = cpu_to_le16(queue->queue_size);
		priv.hsqsize = cpu_to_le16(queue->ctrl->ctrl.sqsize);
```

**Comment by benlwalker** [comment]
I think this question has been sufficiently answered here, so I'm closing the issue. The high level summary is:

1) fast memory registration is a kernel-only feature, so SPDK can't use it directly.
2) SPDK does have the correct handling regarding INVALIDATE so that it interoperates with kernel initiators that are using fast memory registration.
